### ISSUE TITLE
Not able to login to rainloop webmail

### ISSUE THREAD

**Issue by Sabirali450** [RainLoop/rainloop-webmail#1003]
Hi i am new at RainLoop, i have created few websites and i dont like the default web mails which are by default provided by cpanel. I have decided to use rainloop, but before making it live i wanted to check on localhost first. So what i did is :- 

1. Installed WAMP on my windows OS
2. Pasted the RainLoop folder in C:\wamp\www\rainloop
3. Open Internet Explorer
4. Typed the address i.e. localhost\rainloop
5. It shows a login screen i typed the login id as **admin** and password as **123456**
and it shows an error as authentication failed 
![image](https://cloud.githubusercontent.com/assets/17014422/14732836/e42d1a18-087b-11e6-8d29-38391fbfd06c.png)

This is only what i did. Now please help to configure this and troubleshoot the problem.

Thanks in advance.

**Comment by ervee** [comment]
Add /?/Admin to the URL.

**Comment by Sabirali450** [comment]
Thank you sooooo much. I am really very happy, my problem is now solved it works. 
Thank you again @ervee
