### ISSUE TITLE
I can't sign a message with GPG

### ISSUE THREAD

**Issue by r0uzic** [RainLoop/rainloop-webmail#1007]
Hi

Today I upgrade rainloop to the recent version and now I cant sign with my gpg key, error message attached.

![instantanea77](https://cloud.githubusercontent.com/assets/634801/14801432/737078b2-0b49-11e6-9824-6629b7b6300d.png)

**Comment by mioux** [comment]
Are you using a password protected key ? I had to remove the password of my private key in order to use it...

**Comment by RainLoop** [comment]
It was an interface bug (invisible password input) and this bug already fixed in the repository. This fix will be available in the new release version.

**Comment by r0uzic** [comment]
Thanks! That was fast <3

**Comment by imamo** [comment]
@RainLoop when we can expect new release?

**Comment by RainLoop** [comment]
@imamo this week

**Comment by mioux** [comment]
Tested with community edition, it works.

Thanks ;)

**Comment by RainLoop** [comment]
Fixed
