### ISSUE TITLE
Support caching with Redis

### ISSUE THREAD

**Issue by nioc** [RainLoop/rainloop-webmail#1009]
Hello, I see that Rainloop handles files, memcache and APC caching.
Is it an option to support [Redis](http://redis.io/) caching?

**Comment by RainLoop** [comment]
Please, try the last version.
But, I'm not sure that everything is working as it should.

**Comment by nioc** [comment]
Thanks, I will try it next week and give you my feedback.

**Comment by nioc** [comment]
Hello, it seems to work but I still have some data in APC :
- `config:<something like an uid>:time`
- `config:<something like an uid>:data` with the configuration array datas

I set this configuration in `/data/_data_/_default_/configs/application.ini`:
````
fast_cache_driver = "redis"
fast_cache_redis_host = "unix:/var/run/redis/redis.sock"
````

**Comment by RainLoop** [comment]
Well, yes, rainloop uses apc cache for configuration caching if apc supported.

**Comment by nioc** [comment]
Understood but what if redis is set as caching system: why using APC only for these 2 datas?
Are you sure this is not an omission? :smile

**Comment by RainLoop** [comment]
I cannot cache this data inside redis, because redis configurations contain inside this data :).

**Comment by nioc** [comment]
Hehe I understand :laughing:
So I close the issue.
Thanks.
