### ISSUE TITLE
Easy access to "starred" messages

### ISSUE THREAD

**Issue by th23x** [RainLoop/rainloop-webmail#1013]
Hi there,

great job with the webmail app :-)

Small, but potentially powerful improvement idea would be an easy access to the starred mails. Currently you need to click "search", "marked", "search" to get these (most) important messages.

Can we get a quick access to them?

Eg. via a "folder" below the "Inbox" - see screenshot attached...
![improvement](https://cloud.githubusercontent.com/assets/13735303/14879223/3e8dab70-0d28-11e6-8e24-55624cbc5987.jpg)

Thanks for consideration!

Kind regards
Thorsten

**Comment by extremeshok** [comment]
+1 excellent idea

**Comment by th23x** [comment]
Played a bit around...that's how it could look like!?

![idea-wide](https://cloud.githubusercontent.com/assets/13735303/14883093/82e5aab6-0d3c-11e6-9b82-022ae82f53f2.jpg)

**Comment by th23x** [comment]
With the modification directly taken up on the #1014 topic I added, this one is absolete...
