### ISSUE TITLE
Improve GUI - mark most important element / button clearly

### ISSUE THREAD

**Issue by th23x** [RainLoop/rainloop-webmail#1014]
Really love the simplicity this webmailer has... ;-)

Smaller suggestion for improvement in the GUI to enhance user experience: Would it be possible to make the most important element clearly stick out?

Examples - on the main screen, the button "write new mail" for me is the most important one:

![idea-wide](https://cloud.githubusercontent.com/assets/13735303/14883172/ecbf1148-0d3c-11e6-9207-6e5048464a27.jpg)

Same logic also applies to "narrow" sidebar:

![idea-narrow](https://cloud.githubusercontent.com/assets/13735303/14883177/f3246b0a-0d3c-11e6-9e29-7af80cf4f753.jpg)

And for any popup dialog, eg here sending the new mail:

![idea-popup](https://cloud.githubusercontent.com/assets/13735303/14883192/11d56a9a-0d3d-11e6-80ce-67a8aa565283.jpg)

Thanks for consideration!

Kind regards
Thorsten

**Comment by th23x** [comment]
Especially in the last example it's to me counter-intuitive, that (only) the "Delete" button sticks out by being marked in red...

**Comment by RainLoop** [comment]
![x1](https://cloud.githubusercontent.com/assets/5530092/14903021/02468e96-0da7-11e6-9070-ac02dcec1ea5.gif)

**Comment by extremeshok** [comment]
Thank you

**Comment by extremeshok** [comment]
Can we have and quick filter icon for "has:attachment" ?

Can you also add the flagged (star) to the subfolders ?

**Comment by th23x** [comment]
@RainLoop Wow - that was a quick reaction, thanks!

@extremeshok I would be careful not to overload the GUI - one strength of RainLoop right now is it's sleak UI...thus comparing how often I search for "starred" vs "has attachment", I am fine with having the later behind another click in the search field.

(just my 2 cents)

**Comment by pietroalbini** [comment]
Hey @RainLoop!

I'm having some problems translating "New message" in italian, because its translation is "Nuovo messaggio", but transifex requires less than 12 chars. Should I use "New"/"Nuovo" as in the short version, or can you lift that limit?

Pietro.

**Comment by RainLoop** [comment]
> Can we have and quick filter icon for "has:attachment" ?
> Can you also add the flagged (star) to the subfolders ?

I totally agree with @th23x 

@pietroalbini 
This is a temporary necessity. I yet do not know exactly how to do it better.

**Comment by pietroalbini** [comment]
@RainLoop so, should I just use the italian translation of "new" instead of "new message"? I would prefer not to have differences between languages, but it's your project :)

**Comment by RainLoop** [comment]
@extremeshok 

![image](https://cloud.githubusercontent.com/assets/5530092/14925523/8b8b4918-0e50-11e6-85ff-60952f0c82ad.png)

For me it doesn't look good.

**Comment by extremeshok** [comment]
You realize one can hide all the icons and only show them when the mouse hovers over each menu item

So they will only appear for the current folder the mouse has highlighted
