### ISSUE TITLE
Unable to login with CRAM-MD5 over TLS

### ISSUE THREAD

**Issue by nailyk-fr** [RainLoop/rainloop-webmail#1016]
My webserver and my dovecot are on two separate debian. 
Dovecot only allow CRAM-MD5 login. 

> disable_plaintext_auth = yes
> auth_mechanisms = **CRAM-MD5**

On the admin rainloop admin panel connection test is successful. When login-in on the user panel it fail every time. 
The dovecot report: 

> Apr 30 14:38:24 imap-login: Info: Disconnected (tried to use unsupported auth mechanism): user=<>, **method=PLAIN**, rip=xxxx:xxxx:4ad5:2600:1::205, lip=xxxx:xxxx:4ad5:2600:1::201, TLS, session=<EkcVCbMxPAAqAoQ0StUmAAABAAAAAAIF>

The rainloop log report: 

> [12:34:25.761][47dd8f22] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=**CRAM-MD5**] Dovecot ready.
> [12:34:25.767][47dd8f22] IMAP[SECURE]: > TAG1 **LOGIN** "<my full mail>" "********"
> [12:34:25.767][47dd8f22] IMAP[DATA]: < TAG1 NO [ALERT] Unsupported authentication mechanism.  
> [12:34:25.769][47dd8f22] IMAP[WARNING]: exception 'MailSo\Imap\Exceptions\NegativeResponseException' with message 'MailSo-Imap-Exceptions-NegativeResponseExc
eption (ImapClient.php ~ 1844)' in /var/sites/rain.nailyk.fr/rainloop/v/1.9.4.415/app/libraries/MailSo/Imap/ImapClient.php:1844 

When I enable plain in dovecot everything is going fine so I suppose the TLS configuration is ok. 
I also try to set: 

> data/_data_/_default_/configs/application.ini:use_imap_auth_cram_md5 = On

in the lab section

Did I miss something? 
Thank for your time. 

P.S.: [full rainloop log](https://paste.debian.net/448053/)

**Comment by RainLoop** [comment]
> Did I miss something? 

No, RainLoop does not support CRAM-MD5 authentication (not ready yet :( ).

If you give me test email account, I will try to finish this functionality.

**Comment by nailyk-fr** [comment]
> If you give me test email account, I will try to finish this functionality.

Sure! How can I contact you privately to send you the credentials?

**Comment by RainLoop** [comment]
support@rainloop.net

**Comment by nailyk-fr** [comment]
Seems there is ameliorations in 1.10.0.107. 
But every time password fail:
> imap-login: Info: Disconnected (auth failed, 1 attempts in 2 secs): user=<nailyk@______.fr>, method=CRAM-MD5, rip=xxxx:xxxx:4ad5:2600:1::205, lip=xxxx:xxxx:4ad5:2600:1::201, TLS, session=<vbRhceszZAAqAoQ0StUmAAABAAAAAAIF>

and rainloop log: 

> --- FlushLogCache: WriteOnErrorOnly
> [18:41:34.210][a6759238] INFO[DATA]: [DATE:28.05.16][RL:1.10.0.107][PHP:5.6.20-0+deb8u1][IP:2a02:8434:4ad5:2600:feaa:14ff:fecf:2113][PID:11987][Apache][apach
e2handler]
> [18:41:34.210][a6759238] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,sslv3,tls,tlsv1.0,tlsv1.1,tlsv1.2]
> [18:41:34.210][a6759238] REQUEST[NOTE]: [POST] https://rain.nailyk.fr/?/Ajax/&q[]=/0/
> [18:41:34.211][a6759238] AJAX[NOTE]: Action: DoLogin
> [18:41:34.211][a6759238] POST[DATA]: {"Email":"nailyk@______.fr","Login":"","Password":"*******","Language":"","AdditionalCode":"","AdditionalCodeSignMe":"0"
,"SignMe":"0","Action":"Login","XToken":"c470173__________________32ed848"}
> [18:41:34.213][a6759238] IMAP[NOTE]: Start connection to "ssl://kelen.nailyk.fr:993"
> [18:41:34.391][a6759238] IMAP[NOTE]: Connected (success)
> [18:41:34.432][a6759238] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=CRAM-MD5] Dovecot ready.

> [18:41:34.439][a6759238] IMAP[DATA]: > TAG1 AUTHENTICATE CRAM-MD5

> [18:41:34.440][a6759238] IMAP[DATA]: < + PDY5OTA4_______________________________LRUxFTj4=

> [18:41:34.440][a6759238] INFO[DATA]: tiket: <6990833279516772.1464461344@KELEN>
> [18:41:34.442][a6759238] IMAP[SECURE]: > *******

> [18:41:35.972][a6759238] IMAP[DATA]: < TAG1 NO [AUTHENTICATIONFAILED] Authentication failed.

> --- FlushLogCache: Trigger

Are changes needed in the rainloop configuration or something else i miss? 
Are you still able to access the dovecot?

**Comment by RainLoop** [comment]
Available in the last version.

**Comment by nailyk-fr** [comment]
Confirmed working in 1.10.1.127. (dovecot imaps authentication and postfix smtps tested)
Thanks a lot!
