### ISSUE TITLE
Keep sidebar toggle button in same place - UI / UX enhancement

### ISSUE THREAD

**Issue by th23x** [RainLoop/rainloop-webmail#1017]
Again a minor suggestion regarding user experience / user interface:

Currently the button to toggle on/off the sidebar changes place upon changing sidebar being hidden (first image) and enabled (second image)

![today-folder-no-sidebar](https://cloud.githubusercontent.com/assets/13735303/14938387/d9306ac8-0f21-11e6-8930-f4065461178d.JPG)
![today-folder-sidebar](https://cloud.githubusercontent.com/assets/13735303/14938386/d92e356e-0f21-11e6-81b6-321b893cb0af.JPG)

As a user I would expect to switch between sidebar on and off, when I click on the same place again, but instead I open the "create folder" dialog when I click again... Thus I would recommend to position the toggle button first also when the sidebar is enabled (see following image).

![suggestion-folder-sidebar](https://cloud.githubusercontent.com/assets/13735303/14938391/e09ec7c8-0f21-11e6-867e-c5c06f09150a.JPG)

Thanks for consideration :-)

**Comment by RainLoop** [comment]
@th23x 

![_1](https://cloud.githubusercontent.com/assets/5530092/14938435/013d4ea0-0f2c-11e6-8c4c-c4a73815b59b.gif)

**Comment by th23x** [comment]
Yes, that's what I meant - you're really quick and very responsive, top job!
