### ISSUE TITLE
Keep filter removal panel in visible area - GUI / UX enhancement

### ISSUE THREAD

**Issue by th23x** [RainLoop/rainloop-webmail#1018]
Yet another observation / idea on the UX front...

When executing a search / setting a filter on the message list, the (only) option to remove it again is the "x" button next to "Search results for..."
![search-executed](https://cloud.githubusercontent.com/assets/13735303/14941522/4bcf7128-0f9f-11e6-9666-6838754a6aef.JPG)

But when scrolling down the search result list, this button get out of the visible area - so users need to scroll up again before being able to remove the filter.
![search-executed-scrolled](https://cloud.githubusercontent.com/assets/13735303/14941523/4be9b22c-0f9f-11e6-9407-9256aebc3621.JPG)

My suggestion would be to either
* move the "Search results for..." block to the static area with the input field above or
* add the "x" button into the input field

**Comment by mat-m** [comment]
+1

Same applies to the "display external images" in mail view

**Comment by RainLoop** [comment]
![_2](https://cloud.githubusercontent.com/assets/5530092/14941719/aa50f3de-0fae-11e6-93ab-d720c29995e5.gif)

**Comment by ervee** [comment]
How can you enter the search menu/popup that was under the arrow now?

**Comment by RainLoop** [comment]
@ervee It was a mobile version (beta). It is not ready yet.

**Comment by ervee** [comment]
Ah okay. For the desktop version at least I would keep the drop-down arrow to access the menu, introduce the X to clear the current search and get rid of the "search results for" bar altogether.
