### ISSUE TITLE
Google Integration Problems

### ISSUE THREAD

**Issue by CarrotCruncher** [RainLoop/rainloop-webmail#1019]
Hi. I'm having problems integrating my new RainLoop installation with my Google account.

1. Google Drive

I've tried to follow the instructions at [http://www.rainloop.net/docs/social/](http://www.rainloop.net/docs/social/), but I'm getting the following error:

```
401. That’s an error.

Error: invalid_client

Application: Remote Access

You can email the developer of this application at: {USER}@gmail.com

no registered origin
Request Details

    proxy=oauth2relay735528997
    immediate=false
    scope=https://www.googleapis.com/auth/drive.readonly
    origin=https://{WEBSITE URL}
    response_type=token
    redirect_uri=postmessage
    state=514915575|0.3642876979
    client_id={CLIENT ID}
    include_granted_scopes=true
    jsh=m;/_/scs/apps-static/_/js/k=oz.gapi.en_GB.qhpGPHcDIh8.O/m=__features__/am=AQ/rt=j/d=1/rs=AGLTcCOk9nrUkMAXiAsDZhMbjfv4K4bsCQ

That’s all we know.
```

The doco doesn't appear to mention which APIs to enable, I'm assuming I just enable "Google Drive API" for the project, with all the default options.

Also, I can't see any mention of an "API key" which the admin panel states is "Required for Google Drive File Picker". I have created a key and added this to the configuration.

2. Google Contacts

[#293](https://github.com/RainLoop/rainloop-webmail/issues/293) suggests that Google Contacts syncing was implemented some time ago. The only contact syncing option I can find is for CardDAV and [#446](https://github.com/RainLoop/rainloop-webmail/issues/446) suggests that RainLoop doesn't support the Google CardDAV server.

I'm sure both these options are just me being stupid so it would be very much appreciated if anyone could advise on what I'm doing wrong. Cheers.

**Comment by zikeji** [comment]
Can't answer your question on Google Contacts, but for the Google Drive File Picker here's what I did.

Go to the Google Cloud Console, and then the API Manager page. It should look something like this, but the keys listed depend on what you've added.

![Image 1](http://i.imgur.com/En0KKkU.png)

Now click "Create credentials" and select "API Key".

![Image 2](http://i.imgur.com/AIjwiws.png)

Click "Browser Key"

![Image 3](http://i.imgur.com/grTIv1K.png)

Now put in the URL of your RainLoop installation, like so:
`https://your.domain.com/*`

![Image 4](http://i.imgur.com/HjtvUNg.png)

Name it whatever you feel like naming it.

**Comment by CarrotCruncher** [comment]
Dear Caleb B,

The email sent to mail@carrotcruncher.tk with subject
"Re: [RainLoop/rainloop-webmail] Google Integration Problems (#1019)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to mail@carrotcruncher.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by CarrotCruncher** [comment]
Thanks for the response. I've set up both a Browser API key and a Web application OAuth 2.0 client ID, but to no avail.

The URL of the website is:
https://webmail.{mydomain}

I've tried having "Accept requests from these HTTP referrers" set to:
{null}
*.{mydomain}/*
http://webmail.{mydomain}/*
https://webmail.{mydomain}/*
but none of them work.

In the admin panel I have:
Enable Google Integration : checked
Authorization : unchecked
Google Drive Integration (Compose view) : checked
Google Viewer Integration (Preview for Microsoft Word, Excel and PowerPoint files) : checked

**Comment by zikeji** [comment]
I assume when you say `https://webmail.{mydomain}/*` `{mydomain}` includes your TLD (.com, .net, etc).

What error are you getting from Google now?

**Comment by CarrotCruncher** [comment]
I've got Google Drive working now. "no registered origin" was the clue. For the "Web application OAuth 2.0 client ID" I had to add:
https://webmail.{mydomain}
under " Authorized JavaScript origins". Thanks for your help.

**Comment by CarrotCruncher** [comment]
Dear RainLoop Team,

The email sent to mail@carrotcruncher.tk with subject
"Re: [RainLoop/rainloop-webmail] Google Integration Problems (#1019)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to mail@carrotcruncher.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
