### ISSUE TITLE
SSO possible?

### ISSUE THREAD

**Issue by MattB-MA** [RainLoop/rainloop-webmail#1020]
Is SSO possible with RainLoop? I've been doing my best to trace through the code and invoke whatever classes and functions I can find, but I keep hitting a wall. Is there some API for SSO or oAuth other than social networks?

**Comment by RainLoop** [comment]
https://github.com/RainLoop/rainloop-webmail/wiki/SSO-example

**Comment by TranslationsCloud** [comment]
@RainLoop That is not really clear... what do we need to pass as info?
What is returned? Wherer do we need to put that code?

**Comment by sddwt** [comment]
> https://github.com/RainLoop/rainloop-webmail/wiki/SSO-example

Hi, 
We do not usually storage user's password directly, can I pass md5  hashed pwd?
