### ISSUE TITLE
ECC support for OpenPGP.js

### ISSUE THREAD

**Issue by HLFH** [RainLoop/rainloop-webmail#1023]
Hi,

RainLoop implements PGP support with OpenPGP.js. But for now, OpenPGP.js does not support ECC for  [Curve Ed25519](https://github.com/openpgpjs/openpgpjs/issues/428) and [Curves P-256, P-384, P-521](https://github.com/openpgpjs/openpgpjs/issues/427). It seems that [Google End-to-End extension](https://github.com/google/end-to-end/wiki/Build-instructions) [will also soon support the Curve Ed25519](https://github.com/google/end-to-end/issues/319).

So, it's just a reminder. When OpenPGP.js will support Ed25519 used by GPG, it will be great to use the last OpenPGP.js for RainLoop.

**Comment by RainLoop** [comment]
ok

**Comment by RainLoop** [comment]
Could you please open a new issue when OpenPGP will support Ed25519?

**Comment by HLFH** [comment]
@RainLoop Reçu 5 sur 5.

**Comment by HLFH** [comment]
@RainLoop It seems that [it is fixed on kbpgp](https://github.com/keybase/keybase-issues/issues/1738). Shouldn't we migrate from OpenPGP.js to [kbpgp.js](https://github.com/keybase/kbpgp) on RainLoop?
