### ISSUE TITLE
i18n - FOLDER_LIST/BUTTON_NEW_MESSAGE missing in de_DE ?

### ISSUE THREAD

**Issue by graebermedien** [RainLoop/rainloop-webmail#1029]
Could You Please check this?!
I Think the following is missing in de_DE Translation:

    BUTTON_NEW_MESSAGE: "Neue Nachricht"

The Button is displayed in EN, cant translated?!
Please Fix and add German Translation!

**Comment by RainLoop** [comment]
Fixed in the last version.
