### ISSUE TITLE
SSO supported in any way?

### ISSUE THREAD

**Issue by gollenia** [RainLoop/rainloop-webmail#103]
Hi, and thanks for this excellent piece of software. I would like to include it into my other webservices, so single sign on would be a great feature. Is there an easy way to integrate that? Maybe one could use a redis- or sqlite database to check for sessions?
- thomas

**Comment by scith** [comment]
Sorry for reopening the issue. The technique you suggest is working great, but would it be possible to log in via SSO *without* redirecting using header?
With a function or something?

I would like to add the SSO automatic login directly in the index page.

Thanks

**Comment by mehrdaad** [comment]
@scith can you give me a hint where should this code be stored?  it doesn't provide any info.

**Comment by scith** [comment]
@mehtdaad anywhere you like on the same webaerver
