### ISSUE TITLE
Unneeded saved drafts

### ISSUE THREAD

**Issue by anoxi** [RainLoop/rainloop-webmail#1030]
I wrote a mail with my gmail account in rainloop for around 10min and sent it, later I saw like 8 drafts in my Gmail app for that conversation. It looks like rainloop saved those drafts and didn't clean them up.

**Comment by RainLoop** [comment]
> and didn't clean them up.

RainLoop did it, but yes, Gmail draft folder works weird (like and other system folders).
To fix it, I have created my own Draft folder and setup it like draft in the RainLoop client.
