### ISSUE TITLE
settings / contacts gone after upgrade

### ISSUE THREAD

**Issue by cyrilmestrom** [RainLoop/rainloop-webmail#1032]
Hi, I did an automatic upgrade a few moments ago but all my clients lost their contacts and settings.
There was no warning or other messages. What can I do?
Thank you.

**Comment by liassic** [comment]
Recently upgraded to v1.10.0.103.
I confirm that Contacts have vanished. No menu item. New email To: doesn't have previously used email addresses available.
This is a real problem for me.
Hope you can sort this out soon. Thanks

**Comment by liassic** [comment]
@cyrilmestrom - were you using SQLite for your contacts storage? If I go into Admin it looks like SQLite is no longer supported. Only MySQL. A bit of a pain if it's been deprecated without notice...

**Comment by cyrilmestrom** [comment]
@liassic No I was using MySql. Managed to get the contacts back by querying a backup of the database and inserting them in the new db.

**Comment by liassic** [comment]
I fixed mine by installing MySql and reloading contacts.
Not sure why SQLite is showing as not supported, but I'm up and running.
