### ISSUE TITLE
Replied & Forwarded messages are stored in INBOX not in SEND folder

### ISSUE THREAD

**Issue by denispolom** [RainLoop/rainloop-webmail#1034]
Hello 

replied & forwarded messages are stored in INBOX folder not in SEND folder. Version 1.10.0.103.

**Comment by RainLoop** [comment]
Have you enabled "Place replies in the folder of the message being replied to" checkbox?

![image](https://cloud.githubusercontent.com/assets/5530092/15333027/9d8c16aa-1c70-11e6-9067-d665be1882ab.png)
