### ISSUE TITLE
AJAX-XHR call error, cannot compose new EMail

### ISSUE THREAD

**Issue by Dravion** [RainLoop/rainloop-webmail#1036]
Hi there,
Some user is trying to run Rainloop on a Windows Server with XAMP (Apache2, hMailserver (IMAP4v1/POP3)+PHP5 and experiencing strange results. He can login and read mails but
cannot compose new mails. The following Screenshots shows there is an XHR calling bug maybe this is the reason. PS: I cannot find any Windows Install instructions on your Website, even if i  use google, i will allways redirected to the Linux install instructions.

Here the screenshot:
http://postimg.org/image/46fo2tngh/full/

**Comment by RainLoop** [comment]
Are there errors in web server logs?
