### ISSUE TITLE
Aononymous user refused (Radicale + Rainloop)

### ISSUE THREAD

**Issue by jkaberg** [RainLoop/rainloop-webmail#1037]
When trying to auth with Radicale, it seems Rainloop is trying to use an anonymous user (?)

```
2016-05-22 13:21:03,809 - INFO: PROPFIND request at /radicale/.well-known/carddav received
2016-05-22 13:21:03,811 - INFO: Anonymous user refused
2016-05-22 13:21:03,813 - INFO: PROPFIND request at /radicale/.well-known/carddav received
```

Settings in Rainloop,
![image](https://cloud.githubusercontent.com/assets/613363/15453718/791673de-2020-11e6-8c75-f4bdb83fa3d5.png)

Nginx properly rewrites .well-known/carddav to radicale/.well-known/carddav, tested and working with Thunderbird

**Comment by RainLoop** [comment]
RainLoop uses auth information for /.well-known requests.
Try to check RainLoop logs for more information.

**Comment by jkaberg** [comment]
Nevermind this. If anyone stumbles upon this issue, the solution is to use URL like so

```https://domain.tld/radicale/<full username>/AddressBook.vcf/```

Sorry about takeing your time @RainLoop
