### ISSUE TITLE
Highlight selected folder - with text color / not only background

### ISSUE THREAD

**Issue by th23x** [RainLoop/rainloop-webmail#1038]
Some of the preset colors/ images for the background can be quite dark - same for user selectable backgrounds.

If this it the case, it can be very hard to determine the selected folder, as it is currently only highlighted by adding a darker bar below the folder name.

Would like to propose the below change to highlight it additionally by making the name orange - providing a good contrast to the darkened bar below:

![highlight-selected-folder-color](https://cloud.githubusercontent.com/assets/13735303/15468114/ed0f104e-2114-11e6-82f3-79b81f2da44a.JPG)

`  .thm-folders .e-link.selectable.selected,
  .thm-folders .e-link.selectable:hover {
    color: orange !important;
  }`

Thanks for considering :-)

**Comment by RainLoop** [comment]
Well, for dark backgrounds more effectively to use another bar style (from Dark Shine theme for example)

![image](https://cloud.githubusercontent.com/assets/5530092/15479328/549115c4-2128-11e6-8b5a-1233467eded4.png)

**Comment by th23x** [comment]
Oh, indeed a good idea - didn't play around the themes anymore after uploading my own background...sorry!
