### ISSUE TITLE
Dynamically change language

### ISSUE THREAD

**Issue by akirapix** [RainLoop/rainloop-webmail#1040]
Hello,
is there a way to set language 'externally', for example passing a variable in url parameters?
I basically wrapped rainloop in a page and i'd like to set language per user
Thanks

**Comment by RainLoop** [comment]
Fast answer in No.

But, you may do it by using SSO functionality

```php
<?php

// Enable RainLoop Api and include index file 
$_ENV['RAINLOOP_INCLUDE_AS_API'] = true;
include '/var/www/rainloop/index.php';

$ssoHash = \RainLoop\Api::GetUserSsoHash('user@yourdomain.com', 'super-password', array(
    'Language' => 'ru_RU'
));

// redirect to webmail sso url
\header('Location: http://yourdomain.com/rainloop/?sso&hash='.$ssoHash);

```

Unfortunately. it doesn't work right now (additional language parameter), but it will be fixed in the next version.

**Comment by RainLoop** [comment]
This code should work in the last version.
