### ISSUE TITLE
SIEVE filters: Support regex extension

### ISSUE THREAD

**Issue by neuhaus** [RainLoop/rainloop-webmail#1043]
Currently the SIEVE filters frontend does not support the creation of regex filters.

Both the very old Avelsieve plugin for Squirrelmail and Roundcube already support regex filters.

The current specification for the filters themselves is at https://tools.ietf.org/html/draft-ietf-sieve-regex-01

There are several Sieve implementations that support this extensions, including Cyrus Sieve and Piegeonhole for Dovecot.

Rationale:

> In some cases, it is desirable to have a string matching mechanism
    which is more powerful than a simple exact match, a substring match
    or a glob-style wildcard match.  The regular expression matching
    mechanism defined in this draft should allow users to isolate just
    about any string or address in a message header or envelope.

**Comment by RainLoop** [comment]
Available in the last version.

**Comment by zeigerpuppy** [comment]
It may be good to have some help for the user here, 
for instance when "regex" is selected, some common expressions could be shown in a dropdown.

eg: "match all", "match excluding"
