### ISSUE TITLE
Suggestion: OpenPGP: Allow the user to select a decryption key if decryption fails

### ISSUE THREAD

**Issue by sbrl** [RainLoop/rainloop-webmail#1047]
Currently I get a few emails to an alias of mine that isn't included in my PGP key. I can't decrypt this messages automatically because rainloop isn't smart enough to ask me which key to use for decryption when it can't find a key to decrypt the message with.

**Comment by esroyo** [comment]
In the end, it may pay off to add that address to the PGP key rather than selecting it each time. Anyway, sounds like a reasonable feature to have.

**Comment by RainLoop** [comment]
@sbrl which version do you use?

**Comment by sbrl** [comment]
@RainLoop I tried it on 1.9, and now that I've updated to 1.10 it asks me which key I want to use as I thought it should. Thanks anyway!
