### ISSUE TITLE
Fails to Load. ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by atulbhats** [RainLoop/rainloop-webmail#1048]
I have rainloop installed on my server and since two days, it is unable to open. 

The Error displayed is :
_e.atulbhats.com redirected you too many times.
ERR_TOO_MANY_REDIRECTS_

I had updated Rainloop around last week to 1.10.0.107 
The _error_log_ and _error_log.txt_ are both empty. 

I cannot even access the admin panel with ?admin as it gives the same error.

**Comment by RainLoop** [comment]
It looks like web server configuration error.

```
Connection:Keep-Alive
Content-Length:206
Content-Type:text/html; charset=iso-8859-1
Date:Mon, 30 May 2016 12:16:59 GMT
Keep-Alive:timeout=3, max=8
Location:http://e.atulbhats.com
Server:Apache Phusion_Passenger/4.0.10 mod_bwlimited/1.4 mod_fcgid/2.3.9

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://e.atulbhats.com">here</a>.</p>
</body></html>
```

This is not a RainLoop response.
