### ISSUE TITLE
Domains list in admin panel - show more than 99 domains

### ISSUE THREAD

**Issue by TomoZG** [RainLoop/rainloop-webmail#1055]
Hi,

when I enter domains list in admin panel, it shows only 99 domains.
There are more than a 100 domains currently on my server and I can't access and set them up.
Can you please fix this? Maybe add some kind of pagination/search/filter?

Thanks in advance,
Tomislav

**Comment by RainLoop** [comment]
Additional configuration option is available in the last version.

```ini
[labs]
domain_list_limit = 99
```
