### ISSUE TITLE
Only one contact email address in "To:" Field

### ISSUE THREAD

**Issue by Hoellenwesen** [RainLoop/rainloop-webmail#1058]
Hi,

i'm using rainloop with the owncloud contact app and not with the local rainloop contact feature. Most of my contacts have more than one email address but rainloop only shows one of them in the "To:" field so i can't choose one of the other addresses. Please fix this, so that i can choose another email address when i am typing a name in the "To:"-field. Thanks.

**Comment by RainLoop** [comment]
Well, it is an ownCloud bug.

https://github.com/owncloud/core/blob/master/apps/dav/lib/CardDAV/AddressBookImpl.php#L216

Fast fix:

```php
foreach ($vCard->children as $property) {
	if (isset($result[$property->name]) && 'EMAIL' === strtoupper($property->name)) {
		if (!is_array($result[$property->name])) {
			$result[$property->name] = array($result[$property->name]);
		}
		$result[$property->name][] = $property->getValue();
	} else {
		$result[$property->name] = $property->getValue();
	}
}
```

**Comment by Hoellenwesen** [comment]
Hi,

thanks for the fix, now it's working. Hope they fix this bug in next owncloud release.

**Comment by ervee** [comment]
Did one of you file a bug for this at Owncloud? If not, it will probably not be fixed :)
