### ISSUE TITLE
login failures not logged after upgrade

### ISSUE THREAD

**Issue by purejava** [RainLoop/rainloop-webmail#1062]
Hi,

I just upgraded my rainloop installation (standard) via the admin panel from v1.10.1.123 to v1.10.1.127.
Due to the changes to fail2ban logging mentioned in the changelog, I tested it right away and noticed that no log with the date of today is created any more in the fail2ban directory. This used to work before.

To verify this, I installed rainloop into a fresh AWS VM and noticed that fail2ban logging is working there just as designed.

The only difference to my installation I could figure out is that with a fresh install of the latest rainloop the directory layout has changed: `rainloop/data/_data_` does not have the hash code at the end any more.

I enabled rainloop logging on my first installation but as far as I can see the failure of writing the fail2ban logfile is not reflected in this log.

Kind regards,

My installation (shortened)
```
root@xxx:/var/www/rainloop# tree -d
.
├── data
│   └── _data_08868f52a9e464d9d554b7c725384afd
│       └── _default_
│           ├── configs
│           ├── domains
│           ├── logs
│           │   └── fail2ban
│           ├── plugins
└── rainloop
    └── v
        └── 1.10.1.127
```

AWS VM fresh installation (shortened)
```
root@ip-172-31-12-8:/var/www/rainloop# tree -d
.
├── data
│   └── _data_
│       └── _default_
│           ├── configs
│           ├── domains
│           ├── logs
│           │   └── fail2ban
│           ├── plugins
└── rainloop
    └── v
        └── 1.10.1.127
```

rainloop log failed athentication
[failed_auth_no_fail2banlog.txt](https://github.com/RainLoop/rainloop-webmail/files/308735/failed_auth_no_fail2banlog.txt)

**Comment by purejava** [comment]
Well, I made a fresh installation of rainloop on my system.
The fail2ban logfile does not get created any more, so finally I don't know if there is something wrong with my system.

For this, I am closing this issue now.

**Comment by purejava** [comment]
One more note: I enabled and enforced 2FA with Google Authenticator and now the fail2ban logfile gets written.

**Comment by mojili** [comment]
check the SElinux.
