### ISSUE TITLE
"Print" and "View in separate window" blank screen

### ISSUE THREAD

**Issue by ej52** [RainLoop/rainloop-webmail#1070]
Just updated to 1.10.1.127 and there seems to be a issue with "Print" and "View in separate window", it only shows a blank screen. Below is screenshot of console in new window.

<img width="1270" alt="screen shot 2016-06-15 at 9 24 01 am" src="https://cloud.githubusercontent.com/assets/6298706/16071311/f3447fc6-32da-11e6-9ff9-1b1467b10080.png">

**Comment by RainLoop** [comment]
Thanks.
Yes, fix will be available in the next version.

**Comment by maxtoor** [comment]
app.js line 652
from
`script.innerHTML = 'if(window&&window.opener&&window.opener[\'' + func + ']\'){window.opener[\'' + func + '\']();window.opener[\'' + func + '\']=null}';`
to
`script.innerHTML = 'if(window&&window.opener&&window.opener[\'' + func + '\']){window.opener[\'' + func + '\']();window.opener[\'' + func + '\']=null}';`

:)

**Comment by RainLoop** [comment]
https://github.com/RainLoop/rainloop-webmail/commit/a1d829c697c76c7fb39ed33dd5adc01c59f389bd

**Comment by maxtoor** [comment]
Thanks.

**Comment by RainLoop** [comment]
Fixed.
