### ISSUE TITLE
How to always print mail details ?

### ISSUE THREAD

**Issue by Pofilo** [RainLoop/rainloop-webmail#1072]
Hi !

I just installed RainLoop today and it is really amazing ! :+1: 
Though, I miss one (simple) functionnality, how can I always print the details of the mails ? (like in the photo but without pressing the button each time)

![detail_who](https://cloud.githubusercontent.com/assets/7527594/16131589/386c209c-340f-11e6-99fe-c1ba6e0e9446.png)

I have some redirections to my main mail address and I don't see the "TO" line immediatly :/

If you have a solution (changing something in the parameter or in the code) to allow me to see that, it would be astonishing ! :)

Thanks !

**Comment by RainLoop** [comment]
![image](https://cloud.githubusercontent.com/assets/5530092/16166089/bcd709e6-34f0-11e6-83ae-32191cc467fc.png)
