### ISSUE TITLE
Add SPAM button on mobile view

### ISSUE THREAD

**Issue by nioc** [RainLoop/rainloop-webmail#1073]
Hello, I love your mobile view but if you can add the spam button in the main screen (on the messages list, before opening a message) it should be useful: we don't have to open the mail to mark it as a spam  :sunglasses:

**Comment by RainLoop** [comment]
![mch](https://cloud.githubusercontent.com/assets/5530092/16161570/e8265602-34d6-11e6-83e5-4c129cbbeb3b.gif)

**Comment by nioc** [comment]
On nexus 5 or xperia X with Chrome :
![tmp_23513-screenshot_20160617-210416 01327725058](https://cloud.githubusercontent.com/assets/5225411/16162811/f78d4246-34d5-11e6-92de-6cd7bffb459e.png)

**Comment by RainLoop** [comment]
:smile: I've added this functionality right now. It will be available in the next version.

**Comment by nioc** [comment]
You rocks!

**Comment by nioc** [comment]
It is ok in the release 1.10.2.140. Thanks :smile:
