### ISSUE TITLE
Javascript error on create/delete folder

### ISSUE THREAD

**Issue by Ornitier** [RainLoop/rainloop-webmail#1079]
Hi all,

One of my user report to me a bug on creating / deleting folders from parameters.

If the ajax process is ok there is a in error on the callback.
The error in console (same on create and delete) :
app.js?community:4 - Uncaught TypeError: ee.a.abort(...).fastResolve(...).then(...).catch(...).fin is not a function

I'm using Rainloop 1.10.1.127 Community Edition (latest version at the moment) and Chrome (51).

Hope it help.
Thank you for your work ! :+1:

**Comment by RainLoop** [comment]
Thanks!

**Comment by RainLoop** [comment]
Fixed.
