### ISSUE TITLE
Draft delete confirmation when editing it

### ISSUE THREAD

**Issue by Ornitier** [RainLoop/rainloop-webmail#1081]
Hi,

I found yesterday that there is no confirmation on deleting a draft when you are editing it.
As buttons "Save" and "Delete" are close and if you take in consideration that a deleted draft don't go in trash and can not recover it, mistakes can cost a lot of time x)

Hope it help other users too.

**Comment by phsc** [comment]
@RainLoop 
According to the changelog, this should have been resolved with Rainloop [1.10.2](http://www.rainloop.net/changelog/).
Therefore, this issue probably can be closed?

**Comment by Ornitier** [comment]
I update Rainloop this morning to 1.10.2.x, it's in. Perfect ! :+1:
