### ISSUE TITLE
Issue setting up own domain

### ISSUE THREAD

**Issue by Xpydite** [RainLoop/rainloop-webmail#1087]
I recently installed rainloop to a subdomain of my website, and I'm trying to add my own domain. How do I find my imap and smtp servers with available ports?

**Comment by lje** [comment]
This is not a RainLoop issue. If you set up the mail server yourself, you should know host name/port. If you didn't, ask the one who provides the mail server. The settings are exactly the same as in any other mail client (like Thunderbird).
