### ISSUE TITLE
HTML Signature

### ISSUE THREAD

**Issue by Setsuneh** [RainLoop/rainloop-webmail#1088]
Hi,

Is it possible to add directly a signature with HTML code? Because for the moment, you must add the text without..

Thanks

**Comment by RainLoop** [comment]
If I understand you correctly, you may enable a source button in the html editor.

`./data/.../application.ini`

```ini
[labs]
allow_html_editor_source_button = Off
```

**Comment by Setsuneh** [comment]
No, I want to have a visual signature with html (links & images for exemple). 
The html editor is already enabled, and I can't.

**Comment by Setsuneh** [comment]
Tested with 

`[labs]
allow_html_editor_source_button = On`

It works. Closed.

**Comment by lionelh74** [comment]
Hi Setsuneh, 

I am trying to add a signature with html & images, my code is ready to paste but I can't figure out how to do !
Could you explain a little what you've done in July to make it work ? 

Many thanks in advance for your help.

**Comment by charles4201** [comment]
It's the configuration of Rainloop web application on Server, if it's owned by you, then you need to do as @RainLoop said, find ./data/.../application.ini, and modify OFF to ON like "[labs] allow_html_editor_source_button = On".
So if it's not you who installed the web application, you can not add html signature without changing the configuration.
