### ISSUE TITLE
Interference mobile version/FastCGI cache

### ISSUE THREAD

**Issue by Arnaud31500** [RainLoop/rainloop-webmail#1089]
Hi,

My website is running on a nginx server. Today, I've decided to set up some cache parameters in my conf files. Here they are : 
```
        fastcgi_buffers 64 4K;
        fastcgi_cache nginxcache;
        fastcgi_cache_key $host$request_uri;
        fastcgi_cache_valid any 1h;
        fastcgi_cache_use_stale off;
```

When these parameters are on, Rainloop automatically loads the mobile version ! It's impossible to get back to the normal version by clicking on the link above the index page.
When these parameters are off, Rainloop works perfectly and the detection of my screen size works well.

Do you have any idea of how this could be fixed ?
Thanks !

Arnaud

**Comment by extremeshok** [comment]
You can try

fastcgi_cache_key $http_cookie$request_method$host$request_uri;

There is very little benefit to using a cache on such dynamic content.

Rather cache static objects and imap.

__________________________________.    https://eXtremeSHOK.com     .__________________________________

**Comment by Arnaud31500** [comment]
Thanks for your help !
I've noticed that there was some problem on Joomla too with this cache config. It's now turned off...

Thanks again !
