### ISSUE TITLE
Unable to forward emails with attachments

### ISSUE THREAD

**Issue by azidhaka** [RainLoop/rainloop-webmail#1091]
Hi!

Updating to RainLoop 1.10.2.140 today and stumbled upon a very serious problem (also happens on clean install).

My users are unable to forward any mails, containing attachments, The button, which shows the number of attachments contains a spinner, which never stops spinning (see the attached image) and when trying to send, they get the error "Not all attachments have been uploaded yet".

![attachments](https://cloud.githubusercontent.com/assets/19774790/16555345/d97fbcde-41dc-11e6-8370-5de97d7390ca.png)

**Comment by RainLoop** [comment]
Thanks, fixed in the latest version.
