### ISSUE TITLE
Login screen not working on safari on iOS iPad And iPhone 

### ISSUE THREAD

**Issue by conradhagemans** [RainLoop/rainloop-webmail#1092]
I can get the login screen on safari on iOS devices.
I get the background but not the login fields.

If I switch to Chrome on iOS everything works fine.

**Comment by conradhagemans** [comment]
Update. Just figured out that this happens when in private mode. Non private mode works.
Excuse.

**Comment by stueja** [comment]
Thank you very much for the clarification (private mode). I use private mode _exclusively_ on my iPhone. I would love to see Rainloop working in private mode, too.

**Comment by RainLoop** [comment]
Fixed.

**Comment by stueja** [comment]
Thank you for fixing. Works like a charm in private mode now. :+1:
