### ISSUE TITLE
Search input height issue

### ISSUE THREAD

**Issue by Rudloff** [RainLoop/rainloop-webmail#1093]
Hello,

There is a small issue with the search input:
![prudloff animafac net_-_boite_mail_-_animamail_-_2016-07-06_14 23 01](https://cloud.githubusercontent.com/assets/840125/16617655/3dc0d3be-4385-11e6-9c3c-a2430bcc4511.png)

I can reproduce with the latest master and with v1.10.2.141. It happens at lease with Firefox and Chrome.

**Comment by RainLoop** [comment]
Thanks.
Yes, I know about this problem. 
This will be fixed in the next version.

**Comment by RainLoop** [comment]
Fixed.
