### ISSUE TITLE
The web page hangs when trying to import a OpenPGP Public/Private key

### ISSUE THREAD

**Issue by Victorsueca** [RainLoop/rainloop-webmail#1098]
When I try to import a OpenPGP Public or Private key the web page hangs and becomes unresponsive, after allowing several minutes of waiting the page is still unresponsive and can't succesfully import a key. Signing/Encrypting/Decrypting and generating keys seems to work as well as the keys that where succesfully imported in previous versions.

**Comment by DamienR** [comment]
Can confirm I'm having the same issue, no errors in logs to be found, browsers (IE, edge, chrome) hang.

**Comment by RainLoop** [comment]
Fixed.
