### ISSUE TITLE
Run Sieve Filters for existing emails

### ISSUE THREAD

**Issue by marbetschar** [RainLoop/rainloop-webmail#1099]
I've just installed RainLoop Community v1.10.2.141 and configured Filters. They are working absolutely great and I LOVE THEM!

But since I've lived a long time without filters and my inbox is somehow cluttered; is it possible to execute the filters for already existing mails? Not only for new ones?

This would be awesome to clean up my inbox instantly!

**Comment by marbetschar** [comment]
PS: Just a little "Execute" Icon for every filter here would already do it :)

![bildschirmfoto 2016-07-10 um 14 54 26](https://cloud.githubusercontent.com/assets/392542/16713623/4e8125d8-46ae-11e6-8dda-52ebcca30a6d.png)

**Comment by marbetschar** [comment]
Any thoughts on this?

**Comment by ervee** [comment]
That's not possible with Sieve filters. They filter incoming email only. You can use search and multi select to move existing messages.

**Comment by marbetschar** [comment]
Sad to hear that :(

It would be awesome to test filters directly from the management interface.

**Comment by JustusW** [comment]
Sieve now offers the script sieve-filter: https://mebsd.com/configure-freebsd-servers/dovecot-pigeonhole-sieve-filter-refilter-delivered-email.html

**Comment by rudolfschmidt** [comment]
> Sieve now offers the script sieve-filter: https://mebsd.com/configure-freebsd-servers/dovecot-pigeonhole-sieve-filter-refilter-delivered-email.html

the link is dead, any other resource available?
