### ISSUE TITLE
set_time_limit() doesn't work

### ISSUE THREAD

**Issue by think-nice-things** [RainLoop/rainloop-webmail#1103]
Hi,

viewing attachment (e.g. pdf) and images does not work here.
When viewing attachments I get an error message like

set_time_limit(): Cannot set max execution time limit due to system policy in /path/to/rainloop/v/1.10.2.141/app/libraries/MailSo/Base/Utils.php on line 1296 Warning: Cannot modify header information - headers already sent by ...

Everything works fine if I simpliy **remove line 1296 in Utils.php**

```php
\set_time_limit($iTimeToAdd);
```

php safe mode is off as far as I can see and phpinfo doesn't show that set_time_limit was disabled. OTOH I'm not _really_ sure that it has something to do with my hoster's php configuration.

Anyway the check for the existence of set_time_limit in Utils.php doesn't seem to detect that there's a problem with set_time_limit().

```php
$bValidateAction = !$bSafeMode && \MailSo\Base\Utils::FunctionExistsAndEnabled('set_time_limit');
```

**My questions:**

1. **are there any disadvantages when removing or commenting out the line with set_time_limit()?**
2. **could the check for set_time_limit made more robust such that it detects correctly if set_time_limit() can be used or not?**

**Comment by RainLoop** [comment]
Try this:
```php
$iResetTimer = \time();
if (!@\set_time_limit($iTimeToAdd))
{
    $bValidateAction = false;
}
```

**Comment by think-nice-things** [comment]
thanks, seems to work perfectly.

**Comment by RainLoop** [comment]
Good

**Comment by RainLoop** [comment]
Fixed.
