### ISSUE TITLE
Delete icon does not fit on mobile

### ISSUE THREAD

**Issue by Rudloff** [RainLoop/rainloop-webmail#1106]
Hello,

On my phone, the delete icon does not fit in the new message view:
![screenshot_2016-07-14-23-50-56](https://cloud.githubusercontent.com/assets/840125/16857086/0c2da292-4a1e-11e6-82b9-484b4f82ff61.png)

**Comment by RainLoop** [comment]
Thanks!

**Comment by RainLoop** [comment]
Fixed.

**Comment by Rudloff** [comment]
Are you sure this is fixed? I can still reproduce.

**Comment by RainLoop** [comment]
Have you updated your version?

![image](https://cloud.githubusercontent.com/assets/5530092/16968709/3a5ec930-4e19-11e6-94b4-c31eee6dbfc2.png)

**Comment by Rudloff** [comment]
Turns out I add to increment fast_cache_index, sorry.
