### ISSUE TITLE
some emails from contacts are missed

### ISSUE THREAD

**Issue by riegercloud** [RainLoop/rainloop-webmail#1124]
We appreciate your rainloop app but currently it doesn't work as expected on nextcloud.
Rainloop is running on both releases, nextcloud 9.053 and nextcloud 10 beta. 
**The Issue:**
If a contact consists of more than one emailadress only one emailadress will appear in rainloop.

**Rainloop (only one emailadress appears):**

![001](https://cloud.githubusercontent.com/assets/20593693/17138271/c5005eac-533f-11e6-8bfe-de025968c7b5.jpg)

**nextcloud-contacts (2 emailadresses appears):**

![02](https://cloud.githubusercontent.com/assets/20593693/17138178/330d3092-533f-11e6-87a4-f9ca704b34a6.JPG)

Is this a known issue or a bug?

**Comment by AMDG2** [comment]
Hello,

I can't get Rainloop to work on Nextcloud. How did you manage to get it work ?

**Comment by riegercloud** [comment]
Sorry, i missed your question.
First enable "Enable experimental apps" in the left corner
Then you are able to install Rainloop (currently 4.27) directly within nextclouds-app menue.

**Comment by riegercloud** [comment]
Issue can be closed ... with the new release it works as expected
