### ISSUE TITLE
possibility to configure more than 100 mails in list

### ISSUE THREAD

**Issue by derStephan** [RainLoop/rainloop-webmail#1135]
Hi,

currently, there is a limitation to a maximum of 100 eMails in a list. Is it possible to raise this limit to - let's say 1000? I have an inbox with round about 2000 mails and I would like to see more of them on a glimpse. 

I can imagine, that the limit of 100 is due to performance but on decent servers with enough bandwith to the client, this may not be a problem. 

Can you raise the limit?

Thank you in advance.

**Comment by dows** [comment]
Try the option **messages_per_page** at /www/tools/rainloop/data/_data_[...]/_default_/configs/application.ini

**Comment by derStephan** [comment]
I already tried this but with no effect. Even if I change MPP within the json-file

/data/_data_/_default_/storage/cfg/.../settings

there is no change but a reset to 20.

**Comment by HLFH** [comment]
@derStephan Go here. https://github.com/RainLoop/rainloop-webmail/blob/master/dev/Common/Consts.js

export const MESSAGES_PER_PAGE = 20;

export const MESSAGES_PER_PAGE_VALUES = [10, 20, 30, 50, 100];

Add 1000 to MESSAGES_PER_PAGE_VALUES and say to us if that works.

**Comment by derStephan** [comment]
I changed /rainloop/v/1.10.5.192/static/js/min/app.min.js in line 3 column 11.201

from ``o=[10,20,30,50,100]``
to ``o=[10,20,30,50,100,1000]``

with no effect whatsoever.

**Comment by jtackaberry** [comment]
After updating the minified javascript (and shift-reloading on your browser to flush cache), you'll also need to update line 5001 of rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php to include the additional value so it passes through server-side data sanity check:

```
       $this->setSettingsFromParams($oSettings, 'MPP', 'int', function ($iValue) {
            return (int) (\in_array($iValue, array(10, 20, 30, 50, 100, 150, 200, 300, 1000)) ? $iValue : 20);
        });
```

**Comment by derStephan** [comment]
Thank you, this resulted in some kind of progress :-)

I could now select 1000 from the user's settings. After setting this, the "message list is not available". When I set it back to 100 messages, then it works again.

**Comment by RainLoop** [comment]
@derStephan 
More messages require more memory usage. So maybe 1000 messages is a lot for your php configuration.

**Comment by derStephan** [comment]
I see. My memory limit is set to 256M. 

I changed everything to 300 now and that works. But I have to admit that it is by far slower than roundcube with 300 mails. Why is that?
