### ISSUE TITLE
Special char in sender's name is displayed incorrectly

### ISSUE THREAD

**Issue by derStephan** [RainLoop/rainloop-webmail#1139]
Hi, 

in current version 1.10.2.145 there is a problem showing special chars in the sender's name in the message list. 

The sender's name in the following example is "Lands' End".

![special_char_name_messagelist](https://cloud.githubusercontent.com/assets/7764931/17428330/dd3c11a0-5ae7-11e6-82a2-7209c7260fe9.PNG)

This only applies to the message list. In the real message it is shown correctly:

![special_char_correct_in_messageview](https://cloud.githubusercontent.com/assets/7764931/17428482/0bb7378e-5ae9-11e6-8da3-d9be9f4388f8.PNG)

Other special chars like umlauts or "ß" are shown correctly as well.

**Comment by RainLoop** [comment]
Thanks.

Yes, I know about this problem, this fix will be available in the next release and already available in the [beta](https://github.com/RainLoop/rainloop-webmail/releases/tag/v1.10.3.150-beta.1) version.

**Comment by derStephan** [comment]
fixed in version 1.10.3.
Thanks!
