### ISSUE TITLE
File is too big

### ISSUE THREAD

**Issue by spongemon** [RainLoop/rainloop-webmail#114]
Hi,

When I'm trying to attach a file, it shows an error of 'File is too big' although it's only 72 KB. I think it has something to do with the filename because when I'm trying to upload the same file with shorter filename it works. Could there be a way where it accepts any filename no matter how long it may be?

Thanks,

**Comment by mohsenhq** [comment]
In your php.ini file change the value of  **"upload_max_filesize"**

**Comment by mschilli87** [comment]
> In your php.ini file change the value of **"upload_max_filesize"**

Just for future reference: Note that `post_max_size` must be set to an even larger value (in the same file).
