### ISSUE TITLE
Strange error when upgrading to 1.10.3

### ISSUE THREAD

**Issue by ConorIA** [RainLoop/rainloop-webmail#1146]
I am running Rainloop community edition v 1.10.2 mostly without issue. (The only strange thing is that when using the HTML editor, every new line gets terminated with strange characters `Б─▀`. I include that detail here because I suspect it is related to the rest of this issue. 

When I upgrade to 1.10.3.150, Rainloop does not load, saying that an error has occured and to please reload the page. The web browser console returns some noisy error message complaining about a regular expression error: 

![screenshot from 2016-08-14 14-48-33](https://cloud.githubusercontent.com/assets/870746/17651157/d60042b4-622e-11e6-9411-9fffa4009f86.png)

This same error persists when I try using 1.10.3.151

![screenshot from 2016-08-14 14-47-00](https://cloud.githubusercontent.com/assets/870746/17651158/e3a8d41c-622e-11e6-9e37-2abec504f9c4.png)

The files identified in both errors is `rainloop/v/*/static/js/min/admin.js?community:5` and `rainloop/v/*/static/js/min/app.js?community:8`. 

I am happy to try and debug this. It seems that characters are being parsed incorrectly?

I should mention I am running Manjaro Linux. 
nginx 1.10.1-1
php 7.0.9-1
php-fpm 7.0.9-1

**Comment by RainLoop** [comment]
Could you me a link with your installation?

**Comment by ConorIA** [comment]
Ok. I just sent an email to support@rainloop.net referencing this bug.

**Comment by RainLoop** [comment]
Thanks. Now I see the problem.

Your server returns js files with "koi8-r" charset. 
It causes this problem.

```
Content-Type:application/javascript; charset=koi8-r
```

But I will try to fix it on my side.

**Comment by ConorIA** [comment]
Thanks. Commenting out that line in my nginx.conf resolved the problem. To be honest, I'm not even sure why it was in there. I probably copied it form some web tutorial. I had actually tried to disable that option yesterday, but having forgotten to clear my browser cache, it didn't work! Everything is smooth now. Thanks.
