### ISSUE TITLE
Authentication failed When login in to Gmail

### ISSUE THREAD

**Issue by maks112v** [RainLoop/rainloop-webmail#1150]
![untitled](https://cloud.githubusercontent.com/assets/11082252/17779215/d9977d62-6534-11e6-8568-b6ecf893cc7a.jpg) I installed both the community version and standard version and both give me problems login into Gmail. **_Please Help._**

**Comment by ericmoon** [comment]
What do your logs say?

Enable logging in the config file : /data/_data_/_default_/configs/application.ini

```
[logs]
; Enable logging
enable = Off
```

then try to connect and post the log.

**Comment by mcprotector** [comment]
Google see the mail server as new gadget with other location than yours now, and blocking connection for security purposes. Add your mail server to accepted gadgets.
