### ISSUE TITLE
App can't be installed because the version in info.xml is not the same as the version reported from the app store

### ISSUE THREAD

**Issue by jadesoturi** [RainLoop/rainloop-webmail#1155]
Hi.

Installed owncloud on shared hosting - lastest stable release(9.1). Downloaded the rainloop from the app store - extracted, but when I try to enable I get this: 

> App can't be installed because the version in info.xml is not the same as the version reported from the app store

I have tried to change the version in xml from 4.23 to 4.22(thats what is says in the store) and in the VERSION file in ../rainloop/VERSION and ../rainloop/appinfo/VERSION but still no go.. there is also a version file in the ../rainloop/app/data directory, but it says 1.10.3.151

How to fix this?

**Comment by RainLoop** [comment]
Thanks,
I have fixed version in the the app store.

**Comment by jadesoturi** [comment]
Thank you - that solved the problem :) :+1:
