### ISSUE TITLE
Any plans for Nextcloud compatibility?

### ISSUE THREAD

**Issue by leak** [RainLoop/rainloop-webmail#1160]
https://nextcloud.com/

**Comment by Gurkengewuerz** [comment]
At the moment you can use the owncloud version but should a maximum-version tag (#1169)

**Comment by laurentdinclaux** [comment]
The owncloud plugin is fully compatible.

**Comment by bardo** [comment]
Given that the plugin is in the Nextcloud app store since last month, can this issue be closed?
https://apps.nextcloud.com/apps/rainloop

**Comment by leak** [comment]
Of course.
