### ISSUE TITLE
[feature suggestion] message count in imap folders

### ISSUE THREAD

**Issue by naox** [RainLoop/rainloop-webmail#1164]
After upgrading rainloop recently I found out that it stoped showing number of new messages in imap folders if I don't click on every one individualy. I'm guessing that is feature to make rainloop faster in inbox, however this functionality was very usefull and I think option to enable/disable it should be in mailbox preferences (for mailbox user to decide) - how about option to enable it per every imap folder (right next to the "eye" icon (visible))

**Comment by RainLoop** [comment]
It's already supported.

How many folders do you have?

![image](https://cloud.githubusercontent.com/assets/5530092/18203521/2b18ad0e-7120-11e6-8fb0-f7c5e1eae34d.png)

**Comment by naox** [comment]
I got more that 100 imap folders (maybe 20 visible) and I don't see that option

![aaa](https://cloud.githubusercontent.com/assets/341081/18203590/2e0b68e2-7118-11e6-86b1-08ff9e82401d.png)

Rainloop version: 1.10.3.151 comunity

**Comment by naox** [comment]
sorry. I see it now. Icon is barely visible. Close issue.

**Comment by RainLoop** [comment]
ok
