### ISSUE TITLE
IDN Domains in Rainloop

### ISSUE THREAD

**Issue by ZeroEnna** [RainLoop/rainloop-webmail#1175]
Hey there,

I have a feature request for on of the next Versions of Rainloop.

Since a few years, new Domains are allowed containing UTF-8 Characters. For us Germans, it means that "Umlaute" are allowed (ä,ö,ü,ß). 

What I would like Rainloop to do, is to show the "IDN" domain instead of the "punycode" one. I think that this is only a display issue, and I'm pretty sure this could be fixed within the next 6 to 12 months.

Shown address: ich@xn--sascha-schrder-5pb.de
"Real" address:  ich@sascha-schröder.de

I guess, other users (using cyrillic or even asian characters) will also appreciate that.

Thank you very much in advance.

Kind Regards

Zero

**Comment by szepeviktor** [comment]
@RainLoop @ZeroEnna Please close this one.
