### ISSUE TITLE
change password not showing

### ISSUE THREAD

**Issue by spongemon** [RainLoop/rainloop-webmail#118]
Hi,

I have install cpanel plugin and got it activated already but it's not showing on the user's front-end. What could be the problem?

Thanks.

**Comment by craftynetsmith** [comment]
Hi spongemon, were you able to get the cpanel plugin working? Would appreciate it if you can share how you set it up. Thanks.

**Comment by spongemon** [comment]
Hi cratynetsmith,

Yes I was able to set i up.
1. Go the the admin panel of your rainloop installation. (http://yourrainloopinstall.com/?admin)
2. On the 'Packages' tab, find the "Change password (cPanel)" row and click the download button at the very right side.
3. Go now on the 'Plugins' tab and tick the checkmark for the cpanel change password.
4. THIS IS THE IMPORTANT PART. Still at the Plugins tab, click the word itself 'cpanel-change-password'. A pop-up will appear and will prompt you to enter your cpanel host access. Ask your hosting if you're not sure what to enter.
5, Click Save.

Hope this works on you!

**Comment by craftynetsmith** [comment]
Hi spongemon, thanks very much. Yep I got to that part. I'm pretty familiar with whm. Just wanted to verify the values you have on your setup:

cPanel Host: ip address of cpanel or host
cPanel Port: 2087

cPanel User: Is this root or the cpanel user assigned to the domain?
cPanel Password: password of root or password of account assigned to domain?

Did you make any adjustments to cPanel or it just worked right off the box? When I attempt to change the password from the user end, it prompts that I can't change the password.

Really appreciate you taking time to help :-)

**Comment by spongemon** [comment]
Hi,

On my setup, 
cPanel Host: hostname - (host.domain.com)
cPanel Port: 2087
cPanel user: account name in cpanel - (somedomain)
cPanel Password: account password of cpanel - (1234567890)

You're not going to use the root password for anything. It should work right off the box. I have been using it on 3 different hosting and no problems so far. Been using for for years.

I suggest that you login first to your cpanel to manually reset the password. Then attempt to reset the password again using rainloop. If the button below (can't remember specifically) turned green, then the password is already changed in the first attempt. If red, otherwise. 

Most likely it's successful in the first attempt. The buttons would be your indicator if so. There's really no text notification if the password was indeed changed. That was what I was requested as a feature. Not sure if the Rainloop guys have it already.

Hope yours work!

**Comment by craftynetsmith** [comment]
Hi spongemon, got it to work. You were right, not the root whm access but the cpanel access on port 2083. For the benefit of others here's how I got mine working:

cPanel host: domain name
cPanel port: 2083
SSL enabled
cPanel user: cpanel user
cPanel pass: cpanel pass

Thanks again.

**Comment by indexbrasil** [comment]
Does anyone have the plugin updated to work with all domains in my WHM account?

I've tried everything I can think of and nothing works.
