### ISSUE TITLE
Branding, premium and license missing after 1.10.4.179 update

### ISSUE THREAD

**Issue by azidhaka** [RainLoop/rainloop-webmail#1180]
Hi,

Today i updated my (premium) installation of RainLoop to 1.10.4.179 (from the About page) and the branding section is reverted to the free version, the About page no longer shows any Premium information, Update or Changes buttons. I've disabled caching, changed the caching key with no luck.
![rainloop](https://cloud.githubusercontent.com/assets/19774790/18699123/dd6f0ce4-7fd7-11e6-844c-5edb506d3240.png)
![no_premium](https://cloud.githubusercontent.com/assets/19774790/18699127/e2379a16-7fd7-11e6-8e80-f988dbd867e5.png)
![no_branding](https://cloud.githubusercontent.com/assets/19774790/18699130/e5519c24-7fd7-11e6-9f3f-76948be85531.png)

**Comment by RainLoop** [comment]
I'm sorry, it was a repository error (You have installed community version).
You may update your version from site and everything should work correctly.

**Comment by azidhaka** [comment]
That did it, thank you. I am also experiencing the problems in #1181 and #1182 , can you please take a look at them. I am downgrading to 1.10.3.151 temporary. Thank you!

**Comment by RainLoop** [comment]
Fixed.

**Comment by nardeljipa** [comment]
I bought the premium and I don't know how to do it

to get premium ... I already sent an email but they don't answer ...

someone help me please.... 

============================================================================

Comprei a premium e nao sei como fazer 

para ficar premium... Ja mandei e-mail mas nao respondem...

alguem me ajuda por favor....
