### ISSUE TITLE
No Update button in Admin Panel

### ISSUE THREAD

**Issue by purejava** [RainLoop/rainloop-webmail#1181]
Hi!

I always use the update button in the admin panel section About to update the App (standard edition).
The App is installed on a root server.
This morning I updated to 179 and saw, that there is a follow up (180) right away.

But since 179 there is no update button any more.

Thanks.
Cheers,
Ralph

**Comment by azidhaka** [comment]
Hi,

The Login button is missing here too:

![rainloop](https://cloud.githubusercontent.com/assets/19774790/18706572/423bc8ec-7ffb-11e6-839b-c2f13696461f.png)

**Comment by purejava** [comment]
The arrow to the right > worked for me to log in.

**Comment by purejava** [comment]
Never mind. I will install Rainloop again and hopefully the issue will be gone.

**Comment by RainLoop** [comment]
@purejava 
Yes, it was an error in the 179 version.

**Comment by purejava** [comment]
Thanks for that info!
