### ISSUE TITLE
Unable to forward mails with attachments (regression?) in 1.10.4.180

### ISSUE THREAD

**Issue by azidhaka** [RainLoop/rainloop-webmail#1182]
Hi,

The problem reported and fixed in issue #1091 returned in 1.10.4.180. Mails with attachments cannot be forwarded or replied to: Not all attachments have been uploaded yet!

![attachments](https://cloud.githubusercontent.com/assets/19774790/18706422/a0dfa914-7ffa-11e6-96aa-58efdc9f8532.png)

**Comment by RainLoop** [comment]
Fixen in [v1.10.4.181](https://github.com/RainLoop/rainloop-webmail/releases/tag/v1.10.4.181)
Thanks for reporting this problem!
