### ISSUE TITLE
Opening admin on mobile redirects to mobile version

### ISSUE THREAD

**Issue by ervee** [RainLoop/rainloop-webmail#1189]
Hi, 

When I enter the admin URL on my mobile, I get redirected back to the (normal) mobile interface.

**Comment by ervee** [comment]
Ps I use IceCatMobile 38.8.0. A Firefox mobile clone

**Comment by RainLoop** [comment]
Yes, unfortunately rainloop does not support a mobile view for admin panel.

**Comment by ervee** [comment]
Okay, when I use "Request Desktop Site" it does work.
