### ISSUE TITLE
Paste with HTML tags fails

### ISSUE THREAD

**Issue by stenrose** [RainLoop/rainloop-webmail#1193]
Since 1.10.4.181, released 2016-09-21, it's not possible to paste from clipboard, if paste contains a line break (`br`) or HTML tag (such as `<a>` tag), to the New message text area.

When pasting some text with a line break with Chromium web browser I get this in the console panel:

> Uncaught TypeError: Cannot read property 'br' of undefined

Reverted to 1.10.3.151.

**Comment by azidhaka** [comment]
I can confirm that.

**Comment by RainLoop** [comment]
Thanks.
Fixed in the [last](https://github.com/RainLoop/rainloop-webmail/releases/tag/v1.10.4.183) version.
