### ISSUE TITLE
Admin Login form not showing

### ISSUE THREAD

**Issue by malthaher** [RainLoop/rainloop-webmail#1227]
**RainLoop standard edition V1.10.4.183, chrome, windows 10:**

I uploaded the files to the server and tried to open admin panel, but when page open coming with gray background and login 
![untitled](https://cloud.githubusercontent.com/assets/17782409/19586221/e1e040b8-975b-11e6-98f1-0681fc16eb35.png)
from not showing.

**Steps to reproduce the problem:**

**Logs or screenshots:**

**Comment by megadr01d** [comment]
On my end, Safari 10, OS X 10.11.6, your admin page shows up just fine. Since both Chrome and Safari use the same WebKit engine, try to clear the browser cache, test with another browser (just in case) or download the latest Rainloop version and upload to your server manually.

**Comment by malthaher** [comment]
The problem was ioncube disabled on my server.
Now problem solved.

Thank you...
