### ISSUE TITLE
"Domain is not allowed!"

### ISSUE THREAD

**Issue by MasterLykos** [RainLoop/rainloop-webmail#1230]
Hey.

I've got a problem with the RainLoop-Webmail.

Version: 1.10.4.183 (Community Version)
Browser: Mozilla Firefox
OS: Windows 10

What's the problem? 

I've set up the settings of the "domains" section at the admincontrolpanel 
but it doesn't work. I think that I wrote the right imap and smtp from my hoster.

Can you help me? I tried it also with the normal version of RainLoop so I don't know 
how to fix this problem...

----------------------------------------------------------------------------------------------------------

Here is the setting from the ACP...

![ec22f6b3dfca4396a4cbb51a4955849f](https://cloud.githubusercontent.com/assets/23002349/19621538/4836e072-9894-11e6-910f-c0b6a46d2ea5.png)
-> http://prnt.sc/cxldf7 (When it doesn't work.)

----------------------------------------------------------------------------------------------------------

...and here is the Error when i try to log in.

![8672cfcb697445fea8963dad8c86078d](https://cloud.githubusercontent.com/assets/23002349/19621543/64eb121a-9894-11e6-82a2-c937e5404945.png)
-> http://prnt.sc/cxll3m (When it doesn't work.)

----------------------------------------------------------------------------------------------------------

I hope you can help me! Thanks!

<-> Adrian <->

**Comment by RainLoop** [comment]
Try to remove "web." prefix in the domain name.

![111](https://cloud.githubusercontent.com/assets/5530092/19621864/5bf8298a-98a4-11e6-9ed9-6020951c6263.png)

**Comment by MasterLykos** [comment]
@RainLoop I tried it but it doesn't work. :/ There is still the same error.

<-> Adrian <->

**Comment by RainLoop** [comment]
Ohh sorry.

It should be like your an email address domain. So, "web.mypph.de" => "kuntner.me"

**Comment by JuddyT** [comment]
I have the same issue, IMAP settings confirmed working and test also passes

**Comment by MasterLykos** [comment]
@RainLoop But "web.mypph.de" is the nameserver of my hoster. (https://myprepaidhost.de/kunden-bereich/?ccce=knowledgebase&action=displayarticle&id=10)

**Comment by RainLoop** [comment]
I am talking about domain name. Your IMAP and SMTP server configurations are correct.

So:

**Domain name**: kuntner.me
**IMAP server**: web.mypph.de
**SMTP server**: web.mypph.de

**Comment by MasterLykos** [comment]
It works! I'm logged in now. Thanks! :)
