### ISSUE TITLE
Suggestion:  Add <CC> and <BCC> placeholder to message recipient

### ISSUE THREAD

**Issue by megadr01d** [RainLoop/rainloop-webmail#1242]
**Sent Folder View**

When an email is sent **To** `contact1@mail.com` and `contact2@mail.com`

```
contact1@mail.com, contact2@mail.com        a few seconds ago
subject
```

When an email is sent **To** `contact1@mail.com` and **CC**  to `contact2@mail.com`

```
contact1@mail.com                           a few seconds ago
subject
```

When an email is sent **BCC** to `contact1@mail.com` and  to `contact2@mail.com`

```
                                            a few seconds ago
subject
```

The first example is OK, in the last 2 examples, it's just a cosmetic issue, really, but would it make sense to set it like:

```
<CC> / <Multiple Recipients> / <BCC> / <...>     a few seconds ago
subject
```

just so it doesn't look too weird?
Or is this decision based on the "hidden" characteristic attribute of the BCC field? In this case, feel free to close.

**Comment by megadr01d** [comment]
Actually, example 2 could also benefit from some clue that it had another email address CC'd to, instead of being hidden.
What about placeholders for CC and BCC in the Sent folder, like this:

CC

```
contact1@mail.com, <CC>                           a few seconds ago
subject
```

BCC

```
<BCC>                                             a few seconds ago
subject
```

Edited original post accordingly.

**Comment by HLFH** [comment]
@RainLoop Could it be fixed?
