### ISSUE TITLE
Login by Specified username and password

### ISSUE THREAD

**Issue by 286897655** [RainLoop/rainloop-webmail#1250]
Hello. I'm not a web developer.
if i want to use Rainloop login by specified username and password,how can i do it....
such as use http://192.168.1.1/rainloop/?Email=test@test.com&Password=123456&Action=Login
and then login into mailclient.

thanks very much.
:)

**Comment by ervee** [comment]
Using a password in a URL is extremely bad practice. The only liable way to do this would be without password (and then enter it) or use the SSO API somehow.

**Comment by 286897655** [comment]
thanks very much. ~~~

**Comment by 286897655** [comment]
thanks again i use the sso api.very easy

**Comment by brcontainer** [comment]
Can you get an example of using the API to authenticate? I searched the site and did not find it.

**Comment by 286897655** [comment]
@brcontainer ,do you got it? [https://github.com/RainLoop/rainloop-webmail/wiki/SSO-example](url)here is a example.

**Comment by brcontainer** [comment]
@286897655 work fine! :)
