### ISSUE TITLE
Signature not added when reply to email

### ISSUE THREAD

**Issue by conradhagemans** [RainLoop/rainloop-webmail#1261]
**RainLoop version, browser, OS:**
1.10.5.192, Firefox, OSX
**Expected behavior and actual behavior:**
When reply to an email the signature should be added to the new email.
At settings you can choose to add infront of the quoted text.

But it's never added when reply to.
It does work for a new email.

**Steps to reproduce the problem:**
Make sure you have a signature set for your account
Click on reply to email. 

Look if signature is shown?
**Logs or screenshots:**

**Comment by madpsy** [comment]
After a conversaion is initiated my preference is to *not* attach a signature on reply, given the recipient is well aware of who you are at that stage.

**Comment by conradhagemans** [comment]
I don't agree. A lot of email is generated. 
And what is the reason then to have the option on the settings screen of the user : "Insert this signature before quoted text in replies". So madpsy you can choose to show the signature or not.

**Comment by madpsy** [comment]
I just checked that option (didn't realise it existed) and on my install of 1.10.5.192 it works expected.

![test](https://cloud.githubusercontent.com/assets/13963858/20305390/448ff156-ab2d-11e6-9c15-935849d2f2bc.png)

**Comment by conradhagemans** [comment]
I did some checking.
I found the error.

I have 3 accounts. Only the first 2 have a signature.
The third one not. This one is not the default. Stil Rainloop is using this account for the signature.

We can close this issue I guess.

**Comment by megadr01d** [comment]
> We can close this issue I guess.

Please do.

**Comment by conradhagemans** [comment]
Yes. This issue can be closed.
