### ISSUE TITLE
Can't get message list (standard edition v1.10.5.192)

### ISSUE THREAD

**Issue by gomesnz** [RainLoop/rainloop-webmail#1280]
**RainLoop version = v1.10.5.192, browser = Vivaldi , OS: Linux Mint 17.2

**Expected behavior and actual behavior:**
Was experiencing "can't get message list" error when opening my Inbox in earlier version. Upgraded now to v1.10.5.182. Still have the problem. Mailbox size is around 60 emails. Other folders with 300-400 emails displays just fine.

**Steps to reproduce the problem:**
In my settings if I increase the emails per page above 10, I get the error. Also if I have show threads on (feature I like). Currently I am only showing 10 emails per page. Some pages have the error, others are good. 
I don't think its an IMAP problem as my phone has no issue displaying messages. Tested in Firefox, also has the error. I run my own dovecot/postfix server.

**Logs or screenshots:**
What logs would be helpful and how to turn on logging for rainloop.

Many thanks for any help. Love the app, just tired of opensource bugs.....

Darrin

**Comment by gomesnz** [comment]
Further to above. I have followed "Can't get message list for large mailbox #267" and set:

- imap_message_list_hide_deleted_messages  = Off
- imap_message_list_count_limit_trigger = 10000
- imap_message_list_date_filter = 12

No change.

**Comment by gomesnz** [comment]
Fixed the issue, found a rouge message in my CUR folder. This was causing the error.

**Comment by hegyre** [comment]
For those which are still struggling with that (like me), we've just removed all of the dovecot files on the mailbox folder in order to fix that.
