### ISSUE TITLE
Email received empty when sending as HTML

### ISSUE THREAD

**Issue by minaonlyone** [RainLoop/rainloop-webmail#1281]
**RainLoop version : 1.10.5.192, browser chrome, Rainloop running on centos  **

message received empty when sending as html 
when i send email using plain text i see the text normally.

Mime-Version: 1.0
Date: Wed, 07 Dec 2016 18:44:29 +0000
Content-Type: multipart/alternative; boundary="--=_RainLoop_586_914385420.1481136269"
Message-ID: <7ecdc98cf87243541e7d6633ca439d6b@domain.com>
X-Mailer: RainLoop/1.10.5.192
From: mina@domain.com
Subject: asd
To: xxx@xxxx.com

----=_RainLoop_586_914385420.1481136269
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable

----=_RainLoop_586_914385420.1481136269
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html><html><head><meta http-equiv=3D"Content-Type" content=3D"tex=
t/html; charset=3Dutf-8" /></head><body></body></html>

----=_RainLoop_586_914385420.1481136269--

**Comment by minaonlyone** [comment]
When downgraded to "1.10.4.183" i can see message content what is the problem? so i can fix it in the latest version please thanks @RainLoop

**Comment by uchqunbek** [comment]
I have same problem. How to downgrade?

**Comment by RainLoop** [comment]
PHP version?

**Comment by minaonlyone** [comment]
Updated PHP to 5.4.45 it is working good now.
