### ISSUE TITLE
Cannot modify header information

### ISSUE THREAD

**Issue by Loki3000** [RainLoop/rainloop-webmail#1284]
**RainLoop version, browser, OS:**
1.10.5.192 as a nextcloud plugin. Ubuntu 16.04

**Logs or screenshots:**
Found in log file many similar records:
`
Cannot modify header information - headers already sent by (output started at /path_to_nextcloud/apps/rainloop/app/rainloop/v/1.10.5.192/app/libraries/Imagine/Gd/Image.php:580) at /path_to_nextcloud/apps/rainloop/app/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php#8661
`

**Comment by djhargrove** [comment]
having the same issue cant access my emails was working fine yesterday, no changes made

**Comment by insound** [comment]
+1 Have a same issue. php-fpm 5.6

**Comment by alphamat** [comment]
same problem also here / NC 11
PHP 7.02 - error at every usage of rainloop mail plugin 

`Cannot modify header information - headers already sent by (output started at /htdocs/apps/rainloop/app/rainloop/v/1.10.4.183/app/libraries/Imagine/Gd/Image.php:580) at /htdocs/apps/rainloop/app/rainloop/v/1.10.4.183/app/libraries/RainLoop/Actions.php#8665`

this error is horrible flooding the logs - at NC10 was no problem

**Comment by gediminaskv** [comment]
Same problem on CentOS 6, PHP-FPM 7.0.15

**Comment by pierre-alain-b** [comment]
v4.28 of the plugin for nextcloud is out with Rainloop v1.11.0.230, can you tell us if this bug is still applicable?

**Comment by Loki3000** [comment]
Yes. Bug is still here:
```
"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/nextcloud\/apps\/rainloop\/app\/rainloop\/v\/1.11.0.203\/app\/libraries\/Imagine\/Gd\/Image.php:580) at \/var\/www\/nextcloud\/apps\/rainloop\/app\/rainloop\/v\/1.11.0.203\/app\/libraries\/RainLoop\/Actions.php#8671"
"url":"\/apps\/rainloop\/app\/?\/Raw\/&q[]=\/_dPLM-3BypMN-XxxUfSCQFCvfkHEAFPymndf7qz5nYFOcMtox61JvscUz2HLayhWpBJeqf5pPlgiu8YioOrjBdq08i-BKFjpfnaX6FcYj0EjpybP8lkoF8Rq5mqi-FKSpiBuRVlKr4EF36TyyDNhN-mLZsyc0r7HPXZ6umlXs-w0kefJRyrR1cJhfbxTCCEhjuc5jCPqhHk5f4L-q8Tl0D6W8btQsbhI5rXVutVZdLt20Y14216UKOGGQ2ykGlMYHrgqB_vwwLAawbn-ZaTvBVVV3D-agEshId2WPJwsx8NmZFU5bEBUb3Z9QGeY\/View\/&q[]=\/rlUN7kKWz-aG04RizK0jhZ8I8UxRdKjLH0QGI25OfhF31Iw_rQs2E5eAO1g7rRYS-k_z8FprBZ0g7iMLf5HZeX4nEtUfk1h5fv_cM2YIhzLVkz_22hJFw6pRqxvGntloVuY92oXidoftjR69vryatGdt-wK3O6yPwUIduatP7bVPwgNgx74gcnX30buIkD6FUsq0vHJ6PoqWw14wYkeMegoHox6slWQIbNHHLT6cIrFKzsCF_2FoVQm8YfWzjhbfc_cWdtG7i0eMJcoHogv-AUa94KOAbym-uxjbHfzzv6xeu4vgPGMnVQogEKOzsYmUu45km8wAoDzdklTeUEkaxwefmys"
```

**Comment by pierre-alain-b** [comment]
I cannot replicate the behavior in a fresh install of Nextcloud (11.0.2) with Rainloop 11.0.230 freshly installed...
Can you?

**Comment by Loki3000** [comment]
On fresh install same error.
I can provide one of email messages that becomes error if it helps.

**Comment by pierre-alain-b** [comment]
Ah the error is only triggered with some messages, not all?

**Comment by Loki3000** [comment]
Yes messages with attached images as I see.

**Comment by pierre-alain-b** [comment]
Ok now I can replicate this behavior. it is not really blocking except that it is flooding the logs. And this seems to appear only when the image is displayed the first time, do you agree?

**Comment by pierre-alain-b** [comment]
The log line appears when Rainloop "lazy loads" the image in the body of the mail.

**Comment by pierre-alain-b** [comment]
I may have found the culprit: I commented those 5 lines
```
						\header('Content-Type: '.$sContentTypeOut);
						\header('Content-Disposition: '.($bDownload ? 'attachment' : 'inline').'; '.
							\trim(\MailSo\Base\Utils::EncodeHeaderUtf8AttributeValue('filename', $sFileNameOut)), true);
						\header('Accept-Ranges: bytes');
						\header('Content-Transfer-Encoding: binary');
```
in rainloop/app/rainloop/v/1.11.0.203/app/libraries/RainLoop/Actions.php.

And I do not have the error message... Also, Rainloop seems to work without issue. Would you give it a try as well on your side?

**Comment by pierre-alain-b** [comment]
Even better, I encapsulated the call to headers() as below:
```
                                                if (!headers_sent()) {
                                                        \header('Content-Type: '.$sContentTypeOut);
                                                        \header('Content-Disposition: '.($bDownload ? 'attachment' : 'inline').'; '.
                                                        \trim(\MailSo\Base\Utils::EncodeHeaderUtf8AttributeValue('filename', $sFileNam$

                                                        \header('Accept-Ranges: bytes');
                                                        \header('Content-Transfer-Encoding: binary');
                                                }
```
and the error message is gone.

**Comment by Loki3000** [comment]
Yes. Now error is gone.

**Comment by pierre-alain-b** [comment]
@Loki3000, I've pushed a pull request, hoping this can be added to master if it makes sense. Can you close the issue maybe?
PAB
