### ISSUE TITLE
Add button

### ISSUE THREAD

**Issue by Agustors** [RainLoop/rainloop-webmail#1288]
Is it possible to add a button in this view right next to the "More" button?
A button with some functionality for example block the email you are currently viewing?
![freshpaint-4-2016 12 16-04 18 15](https://cloud.githubusercontent.com/assets/9448863/21269719/c363208e-c3ab-11e6-8273-13ce92604541.png)

**Comment by megadr01d** [comment]
What do you mean by "block"? There's already a "Spam" button to mark the current mail as spam.

**Comment by megadr01d** [comment]
Orphaned issue. Please close.
