### ISSUE TITLE
Create Debian Package

### ISSUE THREAD

**Issue by Techwolfy** [RainLoop/rainloop-webmail#1290]
Are there currently any plans to create a Debian package for RainLoop? Currently, it can only be installed by downloading a .zip file and running a few commands, which doesn't fit nicely into my Ansible deployment scripts. Additionally, updates can only be done manually via this method.

I've looked into creating a Debian package, and it seems to be fairly simple; I was able to convert the Community edition ZIP download into a package in a few hours (having never done it before).

I'm not sure how to submit this as a pull request, as it's version-dependent and the git repo doesn't appear to be versioned. I can create a script to repackage the .zip file if you'd like, and I'll submit a pull request for the repo version once I finish figuring out dependencies.

**Comment by Techwolfy** [comment]
Here's the script I wrote to build the package from the .zip file (currently ignores dependencies):

    #Build RainLoop Debian Package
    
    #Working directory
    mkdir rainloop-deb-build
    cd rainloop-deb-build
    
    #Get zip download
    wget https://www.rainloop.net/repository/webmail/rainloop-community-latest.zip;
    unzip rainloop-community-latest.zip;
    find . -type d -exec chmod 755 {} \;
    find . -type f -exec chmod 644 {} \;
    
    #Set up package directory
    VERSION=$(cat data/VERSION);
    DIR="rainloop_$VERSION-0";
    mkdir -m 0755 -p $DIR;
    mkdir -m 0755 -p $DIR/usr;
    mkdir -m 0755 -p $DIR/usr/share;
    mkdir -m 0755 -p $DIR/var;
    mkdir -m 0755 -p $DIR/var/lib;
    
    #Move files into package directory
    mv rainloop/v/$VERSION $DIR/usr/share/rainloop;
    rmdir -p rainloop/v;
    mv data $DIR/var/lib/rainloop;
    rm $DIR/usr/share/rainloop/index.php $DIR/usr/share/rainloop/index.php.root;
    mv index.php $DIR/usr/share/rainloop/index.php;
    
    #Set up Debian packaging tools
    cd $DIR;
    mkdir -m 0755 DEBIAN;
    
    #Create Debian packging control file
    echo "Package: rainloop" > DEBIAN/control;
    echo "Version: $VERSION" >> DEBIAN/control;
    cat >> DEBIAN/control <<-EOF
    	Section: web
    	Priority: optional
    	Architecture: all
    	Depends:
    	Maintainer: Rainloop <support@rainloop.net>
    	Installed-Size: 20330
    	Description: Rainloop Webmail
    	 A modern PHP webmail client.
    EOF
    
    #Build Debian package
    cd ..;
    dpkg-deb -b $DIR;

Settings and user data are stored in `/var/lib/rainloop`, and application files are stored in `/usr/share/rainloop` so they can be symlinked to the desired web-accessible directory. Note that tabs vs. spaces are important in the `DEBIAN/control` section (tabs will be truncated, spaces won't and will cause issues outside of the description block).

**Comment by zeigerpuppy** [comment]
looks interesting, have you tried how it handles upgrades?

**Comment by Techwolfy** [comment]
It should work automatically thanks to the way Debian handles packages. However, this sort of script isn't the way packages are meant to be built, so it might be necessary to uninstall the old one first.

**Comment by Techwolfy** [comment]
This script had a few issues (most notably a few missing redirects that caused Rainloop to not work at all), so I've polished it up a bit and submitted a pull request for the new version.

Here's a patch to make the new script standalone, like the previous one (save as `makedeb.patch`, then apply with `patch makedeb.sh makedeb.patch`):

```
5,9d4
< #Build rainloop
< gulp build;
< cd build/dist/releases/webmail;
< cd $(ls -t);  #Most recent build folder
<
14,15c9,11
< #Prepare zip file
< unzip ../rainloop-community-latest.zip;
---
> #Get zip download
> wget https://www.rainloop.net/repository/webmail/rainloop-community-latest.zip;
> unzip rainloop-community-latest.zip;
```

**Comment by allo-** [comment]
@Techwolfy If you can make it into a Makefile, it's almost a debian package like it's meant.
You can create with a source package (like the zip) and ``dh_make`` a template for a package, where you need to implement the ``debian/rules`` Makefile, which installs to ``debian/target/usr/bin`` and similiar paths. Updating the package with a new version is often then just building with a new source file and adding a changelog entry (which works as version indicator) for the new version.
All details here: https://www.debian.org/doc/manuals/maint-guide/

But before creating complicated debian makefiles yourself, look at ``cdbs``, which has templates for many things: https://build-common.alioth.debian.org/cdbs-doc.html

**Comment by camlafit** [comment]
Hi

To generate a package from zip , it's possible to use also [fpm project](https://github.com/jordansissel/fpm)
Packaging complexity is hide by its process. Looks great to generate a "latest" package
