### ISSUE TITLE
Recent OS update causes SSL to fail

### ISSUE THREAD

**Issue by andrewschott** [RainLoop/rainloop-webmail#1299]
I recently updated the server that Rainloop's install is on, which is separate from my mailserver.   Since then I am unable to get a pass on the domain validation for any of my domains or Google's.  Curious if anyone could help nudge me in the correct direction.  This is starting to get annoying :D  Spent the last day first reinstalling openssl packages, then combing thru data from a manual openssl connect commands and not seeing what the issue may be.

Inside Rainloop for both the IMAP and SMTP domain test I recieve the following to errors:

stream_socket_client(): unable to connect to ssl://my.fqdn:993 (Connection timed out)
stream_socket_client(): unable to connect to ssl://my.fqdn:587 (Connection timed out)

I am only having issues with this host, as my mail clients locally have no issue, and a straggler install of Roundcube can connect, so its not the mail server but this machine.

Any help would be appreciated.

**RainLoop version, browser, OS:**
CentOS 7 (on a vps)

**Expected behavior and actual behavior:**
SSL client actually working properly

**Steps to reproduce the problem:**
Try to login, validate domain

**Logs or screenshots:**
Ask for something in particular and I can provide it.

**Comment by zeigerpuppy** [comment]
To connect via SSL you need to make sure that the server running rainloop can properly handshake with your mail server.  Sometimes you may need to regenerate your local SSL certs.  The best place to check for the error is in the mail server logs, it should tell you there why SSL negotiation failed.
If your mailserver is on the same subnet as rainloop then it's probably not even necessary to use SSL between the two.

**Comment by andrewschott** [comment]
The handshake indeed does occur but takes some time, causing this and a few other clients to fail.  Its not the mail server but the host that has RainLoop installed.
