### ISSUE TITLE
System folders selection

### ISSUE THREAD

**Issue by Med-All** [RainLoop/rainloop-webmail#1303]
Where are stored system folders selected for Sent, Draft and Trash? Or is there any way to automate that process and bind them right away to created by Dovecot same folders?

Thanks

**Comment by ervee** [comment]
When a user logs in for the first time, RainLoop reads and sets the system folders if you specify them in Dovecot. There is actually an RFC for that somewhere. If you want it I'll show you an example config of Dovecot.

**Comment by ervee** [comment]
This is what I have in my local Dovecot config file. Don't copy-past without knowing what you do, read the manuals and adapt it to your needs.

```
namespace inbox {
  inbox = yes
  location =
  prefix =
  mailbox mail-trash {
    auto = create
    special_use = \Trash
  }
  mailbox saved-drafts {
    special_use = \Drafts
  }
  mailbox saved-messages {
    special_use = \Archive
  }
  mailbox sent-mail {
    auto = create
    special_use = \Sent
  }
  mailbox spam-mail {
    auto = create
    special_use = \Junk
  }
}
```

**Comment by Med-All** [comment]
I have similar config on mine but Rainloop still prompt to bind "local" folders to "system folders".  What I found Rainloop is storing those binding in a config file per account but that config file is not created after log in but when you prompt for those changes and I need to automate/default that part.

**Comment by ervee** [comment]
Hmm, to my best knowledge last time I tried this did work for me. I'll test it later on again.

**Comment by Med-All** [comment]
Yes, please but test it on a bran new mailbox - other way issue is not effecting.

**Comment by ervee** [comment]
Hi. I just logged in into RainLoop with a newly created account and after login and doing nothing else but login, this settings file whas created:
```
# cat ./storage/cfg/te/test@example.com/settings_local 
{"SentFolder":"sent-mail","DraftFolder":"saved-drafts","SpamFolder":"spam-mail","TrashFolder":"mail-trash","ArchiveFolder":"saved-messages","NullFolder":"NullFolder"}
```
Note: These empty mail folder files did already exist in the user mail folder on storage because they are included in my new-user skeleton folder (/etc/skel).

When I login with a new user when these files do not exist I get this:
```
# cat ./storage/cfg/te/test@example.com/settings_local
{"SentFolder":"sent-mail","DraftFolder":"","SpamFolder":"spam-mail","TrashFolder":"mail-trash","ArchiveFolder":"","NullFolder":"NullFolder"}
```

Note: No DraftFolder and no ArchiveFolder. This is because "auto = create" is not set for these folders in the Dovecot config.

So for me it really works as I would expect. I never get any prompt for setting folders in RainLoop.

**Comment by Med-All** [comment]
Interesting - on mine system that file is created but looks like 

`{"SentFolder":"","DraftFolder":"","TrashFolder":"","NullFolder":"NullFolder"}`

then when the users creates new email is prompted to bind folders to those "system folders" and after that procedure I'm getting the same looking file as yours.

**Comment by ervee** [comment]
Could it be a setting in application.ini ? I have for example this setting:
```
use_imap_list_subscribe = On
```

**Comment by Med-All** [comment]
Strange - I have that option set to 'On'.

Anyway I have coded to get all handled when user was logged in for the first time.

**Comment by samuelpetrosyan** [comment]
autocreate_system_folders must be on
