### ISSUE TITLE
"Can't send message" - however send is successful.

### ISSUE THREAD

**Issue by adamlove86** [RainLoop/rainloop-webmail#1305]
**RainLoop version, browser, OS:**
Nextcloud 11 with Rainloop 4.27.
**Expected behavior and actual behavior:**
Expected - press send and window closes
Actual - press send and receive "can't send message" error. However despite the error, the email is sent okay.
**Steps to reproduce the problem:**
Write email, press send.
**Logs or screenshots:**
![screen shot 2017-01-09 at 11 53 54](https://cloud.githubusercontent.com/assets/20361489/21755122/55b68dcc-d662-11e6-88a9-9d8f7e7df4cd.png)

**Comment by ervee** [comment]
Hi, please enable logging in application.ini and include logfiles with the bug report. Thank you.

**Comment by pierre-alain-b** [comment]
v4.28 of the plugin for Nextcloud is out, maybe you can try again and tell us?

**Comment by adamlove86** [comment]
Hi there,
I've since moved from Nextcloud Snap to the normal Nextcloud, and it works fine. I imagine it may have had something to do with a lot of the Snap config files being read-only.
