### ISSUE TITLE
[feature] Custom color in hex for editor

### ISSUE THREAD

**Issue by HLFH** [RainLoop/rainloop-webmail#1307]
Hi,

I would like to be able to use a custom color in hex within editor for the color features, and for example with this one: #1d486c

![custom-color](https://cloud.githubusercontent.com/assets/2359059/21772292/80a60c54-d682-11e6-9c1c-da9f57431138.png)

Is that possible? Can you add this feature? Can I help?

Thanks,

**Comment by ervee** [comment]
As far as I know the only way to do it right now is to enable allow_html_editor_source_button in the application.ini
```
allow_html_editor_source_button = On
```
And the when you type a text, color the text you want in a color you you recognize like red (#ff0000), then press the <P>Sourcecode button. Search for red (#ff0000) and change to #1d486c.

![image](https://cloud.githubusercontent.com/assets/4435930/21783479/c18ded74-d6b7-11e6-9a69-a7f45d1b4201.png)

**Comment by HLFH** [comment]
@ervee Thank you for the workaround!! 

The source code related to the `<p>` source code button does not seem to be optimized with Chrome (v. 55.0.2883.87 on Windows 10 x64): my CPU is in high load and I have to wait like one minute to do just one click (I have only 12 opened tabs). It works easily with Firefox by the way. So that's still great to do what I need.

Still, I believe adding a custom color in hex within the editor would be great: imagine you are a marketer and that you don't know code, love to add email signatures, with some branded text with the right branded color, I'm not sure that these kind of people would love to use the `<p>` source code button.

So maybe I'm keeping this issue open in case someone wants to do a PR related to this issue.

What do you think of the [`colorpicker` project](https://github.com/evoluteur/colorpicker)? 
Couldn't we integrate it? 
At least, we have something similar to the classic RainLoop color editor and WITH the hex color code feature.
![68747470733a2f2f7261772e6769746875622e636f6d2f65766f6c75746575722f636f6c6f727069636b65722f6d61737465722f73637265656e73686f74312e706e67](https://cloud.githubusercontent.com/assets/2359059/21791110/971f4ff8-d6d8-11e6-99b8-f562d6bd597b.png)

**Comment by ervee** [comment]
AFAIK RainLoop uses CKEditor for this. And from their website it looks like the latest version does what you need:

![capture](https://cloud.githubusercontent.com/assets/4435930/21801618/b1655c50-d722-11e6-9537-2958046183c3.JPG)

So I _think_ if @RainLoop updates CKEditor, we'll be fine.

**Comment by HLFH** [comment]
@ervee You're right. Thank you! @RainLoop

**Comment by HLFH** [comment]
@RainLoop Hi. Does this commit https://github.com/RainLoop/rainloop-webmail/commit/f383380d5912a67f64c255b7db364b6962abb511 solve this issue?

**Comment by ervee** [comment]
It updates CKEditor to 4.6.2 so I think so. I'm sure it is tested and when it's working we'll see a new RainLoop release!

**Comment by HLFH** [comment]
Thanks @ervee @RainLoop
