### ISSUE TITLE
Compose replies as plaintext

### ISSUE THREAD

**Issue by allo-** [RainLoop/rainloop-webmail#1323]
When i choose plaintext as default for new mails, rainloop still chooses html for replies (to html mails). This can be toggled, but i think it would be useful to default to the setting for new mails.

**Comment by RainLoop** [comment]
Try to use Plaintext (forced):

![image](https://cloud.githubusercontent.com/assets/5530092/22295260/5c64ee94-e327-11e6-901b-15ee7334f709.png)

**Comment by allo-** [comment]
Okay, this works.
