### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by HLFH** [RainLoop/rainloop-webmail#1331]
Hi,

@RainLoop Could you please make a release of rainloop-webmail?
Since the previous release, there are a lot of interesting commits, so I would like to use the most recent release based on master. Could you do it?

Thanks,

**Comment by ad-m** [comment]
What do you mean https://github.com/RainLoop/rainloop-webmail/compare/v1.10.5.192...master ? There is no new features, only a small bug fixes.

**Comment by HLFH** [comment]
@ad-m https://github.com/RainLoop/rainloop-webmail/issues/1307

https://github.com/RainLoop/rainloop-webmail/commit/f383380d5912a67f64c255b7db364b6962abb511

I wanted to try the updated CKEditor because I need the updated one.
And I prefer a release for that.

**Comment by megadr01d** [comment]
It's already on v1.11.2. You have plenty of releases already. Close this issue, shall we?

**Comment by HLFH** [comment]
@megadr01d <3 Yes.
