### ISSUE TITLE
Add filter possibility on Rainloop for Nextcloud

### ISSUE THREAD

**Issue by jybeeL** [RainLoop/rainloop-webmail#1337]
**RainLoop version, browser, OS:**
RainLoop 1.10.4.183 on Nextcloud

Is it possible to add a new function to rainloop?
for example , i want to filter my mail by sender and automatically move this or these mails to a folder already existing or a new folder.

Thx :)

**Comment by ad-m** [comment]
Hmm... My rainloop standalone provide filters feature.

**Comment by jybeeL** [comment]
I forgot to configure "Sieve" in the admin control panel. 

I see now filter menu in the user panel.
