### ISSUE TITLE
Does RainLoop Webmail need his own DAV server? 

### ISSUE THREAD

**Issue by RainLoop** [RainLoop/rainloop-webmail#138]
Poll

**Comment by adynis** [comment]
Hi,
I would also like to be able to sync contacts with google.
Thanks.

**Comment by gadjou** [comment]
I'm probably a dummy, but I use rainloop 1.9.1.335 andI cannot find an option to configure my carddav server under "contact" like in the above screenshot. I only have a "Allow contacts sync (with external CardDAV server)" checkbox. and other option to configure an sql Storage (PDO). And I wasn't able to find any documentation on this.

**Comment by ervee** [comment]
Are you using the Owncloud version?

**Comment by gadjou** [comment]
I´m definitly a dummy: I was stuck looking at the admin settings, not the user settings. It make sence. Solved now.

**Comment by ervee** [comment]
Happens to the best!

**Comment by COLORLINK** [comment]
for local companys.. they use internal server.. is there away to sync contacts from admin area. and so it reach every one whos logging to rainloop .?

**Comment by mpietruschka** [comment]
I'd like to see a general setting in the adminarea, too.

**Comment by mpietruschka** [comment]
@COLORLINK I've opened a new issue for this #974
