### ISSUE TITLE
Removing message that was not marked

### ISSUE THREAD

**Issue by arturbonnett** [RainLoop/rainloop-webmail#1388]
Hello! 

**RainLoop version, browser, OS:** Rainloop 1.11.0.203, Chrome, Ubuntu

**Expected behavior and actual behavior:**  **Steps to reproduce the problem:**
When you select some messages using the keyboard (Shift + up / down) and delete them, it's also deleting the message in focus (the current selected message), instead of deleting only those that are checked.

**Logs or screenshots:**
On INBOX:
![screenshot--2017-04-01-23-42-23](https://cloud.githubusercontent.com/assets/7110872/24584041/b6997f96-1735-11e7-9fc3-534e1c52c696.png)
Now on TRASH after press Del:
![screenshot--2017-04-01-23-42-56](https://cloud.githubusercontent.com/assets/7110872/24584043/bf8a33a2-1735-11e7-9c85-4b5ddae6a528.png)

Best Regards

**Comment by RainLoop** [comment]
Thanks
