### ISSUE TITLE
Missing "Download all attachments as ZIP"

### ISSUE THREAD

**Issue by tilkov** [RainLoop/rainloop-webmail#1403]
Rainloop 1.11.0.203, Ubuntu 16.04.2 Server

Hi, i somehow lost the "Download all attachments as ZIP" functionality in my (premium) RainLoop installation. 
I upgraded the server from Ubuntu 14.04 to 16.04 and at the same time Rainloop to 1.11.0.203 and lost it. 

Can you please remind me, is it application.ini setting or separate module?

**Comment by RainLoop** [comment]
RainLoop uses php zip extension to do this stuff.
Perhaps you updated php and the zip extension disappeared after that.

**Comment by tilkov** [comment]
That was it, php7.0-zip was not installed. 
Thank you!
