### ISSUE TITLE
Rainloop has no Code of Conduct

### ISSUE THREAD

**Issue by mikehenrty** [RainLoop/rainloop-webmail#1412]
At this point, CoCs are considered best practices for open source communities, and all the [cool kids are doing it](https://github.com/blog/2039-adopting-the-open-code-of-conduct).

In a recent Github issue, I saw people treating others in a way that made me feel angry and sad. I found myself blaming Rainloop, when really it was just a couple of people with dubious connections to the project.

https://github.com/RainLoop/rainloop-webmail/issues/1408

And while a Code of Conduct doesn't prevent people from treating each other badly on Github, it does empower nicer people to speak up by pointing to CoC violations, and it allows a framework for dealing with such problems.

By contrast, allowing people to mistreat others will deprive a community of richness and diversity, and can effect the health of an open source project in profound ways down the road. So let's fix this bug!

**Comment by ervee** [comment]
While I think this is a good idea, I can't resist to comment on you saying "a couple of people with dubious connections to the project" as I'm probably one of two you are referring to. 

Although I never coded anything on RainLoop, have no connections to the dev. etc., I do consider myself a good participant of the project even when the author never asked for it. I've done my share of translations, brought actual issues to light and helped (or at least tried to help) some people who had problems. Most of which were never RainLoop issues anyway. 

But using the issue tracker to pitch yourself or your company didn't do it for me. If I overreacted then I'm sorry for that. But the storm of criticism by all those people I've never seen on the RainLoop project made it feel even more a hoax to me. 

I get the idea that the developer of this piece of software is better at coding than politics, policies or CoCs... So if you could help him with any of this I'm sure he'd appreciate it.

**Comment by mikehenrty** [comment]
Hi @ervee. Thanks for you comment, and explanation of the situation. If more people voice support support a CoC, I would love to help out by suggesting one we could fork for this project (there are a few [I personally like](https://opensource.org/codeofconduct)), and I could even submit a PR for adding it.

**Comment by tachyons** [comment]
I think you close this issue now, See the tagged PR

**Comment by mikehenrty** [comment]
@tachyons 👍
