### ISSUE TITLE
Uploaded files to shared hosting; set permission; but Rainloop doesn't work

### ISSUE THREAD

**Issue by lntn** [RainLoop/rainloop-webmail#1419]
**RainLoop version, browser, OS:**
1.11.0.203
Chrome
Windows 10

**Expected behavior and actual behavior:**
Login page or admin page to load up
Not loaded properly: http://mail.next-gen.vn/

**Steps to reproduce the problem:**
Just visit: http://mail.next-gen.vn/

**Logs or screenshots:**
![image](https://cloud.githubusercontent.com/assets/11488899/25722197/7792db36-313d-11e7-9222-60cb60fce563.png)
![image](https://cloud.githubusercontent.com/assets/11488899/25722232/998d6684-313d-11e7-9b7c-2571a89a7c2c.png)

**Comment by ervee** [comment]
Hi,

From the HTTP headers I can't really find anything wrong, with the exception of the presence of a ```Via:"1.1 W0213, 1.1 W0203"``` header. Is your Webserver behind a Proxy or Load balancer? Perhaps it is there where it goes wrong. Just guessing...

**Comment by ervee** [comment]
Also when I look at the page source. After all these weird characters does come the correct RainLoop HTML content.

**Comment by lntn** [comment]
@ervee No proxy or load balancer that I know of. The share hosting has been working fine for me for years. It's now on PHP 5.6 (the issue is still there when I switch to PHP 5.4).

May I know if there is any PHP extension that should be on or off?

**Comment by lntn** [comment]
Decided to use another hosting server, hence the links above won't work.
