### ISSUE TITLE
Attachment download not working

### ISSUE THREAD

**Issue by 749** [RainLoop/rainloop-webmail#1428]
**RainLoop version, browser, OS:**
Rainloop: 1.11.0.203
Chrome Browser: 58.0.3029.110 (64-bit)
Windows 8.1 all updates till 16.05.2017

**Expected behavior and actual behavior:**
Download should have the correct name. but actually is called "Download".
Also it fails due to network error. but if I restart the download manually it suddenly works..

**Steps to reproduce the problem:**
Try to download any attachment.

**Further information about the problem**

I have found that the header x-frame-options:DENY is blocking an iframe which should download the correct file.

I have also tried to setup my webserver to send a header of "x-frame-options: SAMEORIGIN" however this seems to get overriden somewhere (I am using nginx and dovecot as imap server)

I also found that there is an ini setting in the application.ini which i set to SAMEORIGIN however this only results in the headers containing two instances of "x-frame-options:" one with "SAMEORIGIN" and another after it with "DENY" I cannot for the life of me figure out where the second entry is comming from, it certainly is not in the nginx settings.

**Logs or screenshots:**
the javascript console outputs the following:
`
Refused to display 'https://{Website}.de/?/Raw/&q[]=/_lxELoTQqffdsCOXj3HoVZPnvkhG0F70zO1g…w-4FI1-0ZlkIvb91hOPQLjL9UMagQ_StB9FoeFdyXHQl9EOWLrIbojXJRPEkbmJGhGY405Rup8' in a frame because it set multiple 'X-Frame-Options' headers with conflicting values ('SAMEORIGIN, DENY'). Falling back to 'deny'.`

**Comment by 749** [comment]
Upon further investigation, the additional `x-frame-options: deny` seems to be added after php has run. I have absolutely no idea how this is possible.
Oh FIY in FF the download of attachments works just fine.

**Comment by RainLoop** [comment]
RainLup does not do anything special with the x-frame-option header if you did not change the [security] x_frame_options_header setting.

**Comment by 749** [comment]
Hmm then I am at a total loss, even if i set the security setting to GOFORIT it still outputs the header *twice* once with GOFORIT and once with DENY.. And DENY wins the race in chrome.
Any Ideas where the second x-frame-options could come from? I configured nginx with the following line:
`add_header X-Frame-Options SAMEORIGIN;`
and it works on all the other sites I have on the server, just the rainloop site keeps sending the DENY which seems to override everything.

**Comment by 749** [comment]
I have found it, I used the following command to search through the nginx settings:
```grep -ri "X-Frame-Options" /etc/nginx```
