### ISSUE TITLE
message-ID in header exposes domain

### ISSUE THREAD

**Issue by derStephan** [RainLoop/rainloop-webmail#1432]
When I send an eMail via SMTP, the domain of the rainloop installation is exposed to the receiver in the eMail headers:

```
Mime-Version: 1.0
Date: Thu, 18 May 2017 08:56:40 +0000
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable
X-Mailer: RainLoop/1.11.0.203
Message-ID: <a7602bac614e8f8345cfa3d472882338@my-domain.com>
```

I do not think, that anybody out there should see this. Especially when it is impossible to prevent new users to log in using their credentials for gmail.com or outlook.com. 

My suggestion is to change this domain to the eMailaddresses'. 

So instead of 
``a7602bac614e8f8345cfa3d472882338@my-domain.com``
 it should be 
``a7602bac614e8f8345cfa3d472882338@gmail.com``
for a gmail.com-address or
``a7602bac614e8f8345cfa3d472882338@outlook.com``
for a outlook-address

Otherwise, I could be held responsible for abuse that any foreign user may do with my installation.

**Comment by RainLoop** [comment]
Thanks! Fix will be available in the next release.

**Comment by derStephan** [comment]
wow, that was quick. Thank you very much. Is there a planned time point for the next release?

**Comment by RainLoop** [comment]
Next week I think.

**Comment by derStephan** [comment]
Thanks for all of your work. It is really appreciated.
