### ISSUE TITLE
[DEV] Message body - how to obtain content?

### ISSUE THREAD

**Issue by Med-All** [RainLoop/rainloop-webmail#1434]
Is there any other way to get a message body rather than data bind for `initDom: messagesBodiesDom`? In that case when I will display message body prior any other data bind is not going to work.

Thanks

**Comment by RainLoop** [comment]
RainLoop uses a special way to display the body of the message to improve performance.

You may see the main logic of this process here:
https://github.com/RainLoop/rainloop-webmail/blob/master/dev/Stores/User/Message.js#L555

This is something like a cache, its necessary to avoid repeated dom renders of messages in different situations.

**Comment by Med-All** [comment]
OK, so how does the message body is populated for "View in separate window". I'm trying to display a message body "preview" in a modal window but as I have mentioned previously binding it back is not working as renders message body only once.

**Comment by RainLoop** [comment]
Here is "View in separate window" code logic:
https://github.com/RainLoop/rainloop-webmail/blob/master/dev/Model/Message.js#L638

**Comment by Med-All** [comment]
OK, so it looks like I need to access `message` object (oMessage) but can I get a message body itself from `MessageViewMailBoxUserView()`?

**Comment by RainLoop** [comment]
try this:
```js
console.log(this.message());
```

**Comment by Med-All** [comment]
Yup, I have tried this before but `body` in a `MessageModel` comes as a null. Maybe I'm calling it in wrong code spot - just after all KO observables are assigned like `this.viewSubject(oMessage.subject());` etc. of `MessageViewMailBoxUserView()`

**Comment by RainLoop** [comment]
Ok, let's see how it works:

https://github.com/RainLoop/rainloop-webmail/blob/master/dev/Stores/User/Message.js#L729

```js
selectMessageByFolderAndUid(sFolder, sUid) { // here you click message in message list
	if (sFolder && sUid)
	{
		// here RainLoop populates message with information from message list (subject, date & so on, body does not received yet)
		this.message(this.staticMessage.populateByMessageListItem(null));
		this.message().folderFullNameRaw = sFolder;
		this.message().uid = sUid;

		this.populateMessageBody(this.message()); // next step (function below)
	}
	else
	{
		this.message(null);
	}
}

populateMessageBody(oMessage) {
	if (oMessage)
	{
		// here RainLoop asks server to get full message information (with body) and handles response by onMessageResponse function
		// next step (function below)
		if (Remote.message(this.onMessageResponse, oMessage.folderFullNameRaw, oMessage.uid))
		{
			this.messageCurrentLoading(true);
		}
	}
}

// oData = message json with body
onMessageResponse(sResult, oData, bCached) {

	this.hideMessageBodies();

	this.messageCurrentLoading(false);

	if (StorageResultType.Success === sResult && oData && oData.Result)
	{
		// here is RainLoop do all things with message body and DOM
		this.setMessage(oData, bCached);
	}
	else if (StorageResultType.Unload === sResult)
	{
		this.message(null);
		this.messageError('');
	}
	else if (StorageResultType.Abort !== sResult)
	{
		this.message(null);
		this.messageError((oData && oData.ErrorCode ?
			getNotification(oData.ErrorCode) : getNotification(Notification.UnknownError)));
	}
}
```

**Comment by Med-All** [comment]
Well, I have got stuck somehow. I was able to get message body but it happens outside of `MessageViewMailBoxUserView()` where I have added my modal to apply bindings. I must to have missed something.

**Comment by Med-All** [comment]
I'm at the stage where I have create a command to open a popup from `MessageViewMailBoxUserView()`

`			this.myCommand = Utils.createCommand(this, function() {
			    kn.showScreenPopup(__webpack_require__(/*! View/Popup/MyPopUp */ 170});`

and I'm able to open a popup.

Then how I can get data from a "current message"? I have tried to load it as a parameter

`			this.myCommand = Utils.createCommand(this, function() {
			    kn.showScreenPopup(__webpack_require__(/*! View/Popup/MyPopUp */ 170},MessageStore.message());`

or accessing it directly from `View/Popup/MyPopUp` by loading `MessageStore = __webpack_require__(/*! Stores/User/Message */ 30)` but both ways were not successful. 

Any tips on that?

**Comment by Med-All** [comment]
Got it to work on my own.
