### ISSUE TITLE
CC field is not displyed

### ISSUE THREAD

**Issue by namezk** [RainLoop/rainloop-webmail#1435]
**RainLoop version: 1.11.0.203
**Browser: Firefox and Chrome
**OS: Mac OS

**Expected behavior:
The CC: field should be displayed below the TO: field

**Actual behavior:
The CC: field is not displayed below the TO: field.
This is true for list view and message view.

The only way for me to see the addresses in the CC field is to Reply All, at that point, they are populated properly.

Thank you.

**Comment by RainLoop** [comment]
![x1](https://cloud.githubusercontent.com/assets/5530092/26461056/5fbb2944-4184-11e7-8ee9-9be14f79509a.gif)

**Comment by namezk** [comment]
Thank you for the quick reply, and for the screencast!
I understand your decision behind hiding that info under the i button, it makes the interface cleaner; but I think the CC field should be visible by default. The other fields can/should be hidden, but the CC field is elemental in email communication.
Is there a way to change this?

Thank you for your work, I'm a big fan of RainLoop.

**Comment by RainLoop** [comment]
> Is there a way to change this?

Yes

![image](https://cloud.githubusercontent.com/assets/5530092/26465475/045e0750-4194-11e7-8748-b37853412477.png)

**Comment by namezk** [comment]
Awesome, but how? :)

**Comment by RainLoop** [comment]
Wait for the next release

**Comment by namezk** [comment]
Thank you!

**Comment by nasmacs** [comment]
Please note that when you print the email, the CC field doen't not appear as well.
Everybody may be likely to have to provide evidence with the apparent recipients on a prited email.

Regards, Maxime
