### ISSUE TITLE
when answering, contact names are crippled

### ISSUE THREAD

**Issue by derStephan** [RainLoop/rainloop-webmail#1447]
**RainLoop version**

1.11.1

**Expected behavior and actual behavior:**

Whenever there is a comma in an address, only the last part of the information is kept when replying or forwarding it. 

Assume, I get a message from ``"Schmidt, Heinrich" <mail@domain.com>`` and I reply to it. 

expected: To-address is ``"Schmidt, Heinrich" <mail@domain.com>`` 

actual: To-address is ``"Heinrich" <mail@domain.com>`` 

This did not happen in the previous version of rainloop.

**Comment by louis-eyond** [comment]
I've noticed this as well, with names that have a suffix like Eddie Blake, DDS.  The reply name is just "DDS".

RainLoop 1.11.1

**Comment by derStephan** [comment]
Problem is still present in current version 1.11.3
