### ISSUE TITLE
Add more Keyboard Shortcuts / Document existing Shortcuts

### ISSUE THREAD

**Issue by sushinger** [RainLoop/rainloop-webmail#1462]
**RainLoop version, browser, OS:**
1.11.1, Chrome Version 59.0.3071.115 (Official Build) (64-Bit), Mac OS 10.11.6

**Expected behavior and actual behavior:**

Some **more functions** should be enabled by Keyboard-Shortcuts, such as

- Delete Message
- Reply to All
- Archive Message
- Add Email-Address of Sender or Recipient to Address Book
- etc.

**Steps to reproduce the problem:**

At the moment I have only found out about these shortcuts **working**:

- Reply to Message Sender: "**r**"
- Forward Message: "**f**"
- Close New Message Window: "**esc**"

_Just for the record: The navigation via **arrow-keys** is very well deployed and enables to navigate the Webmail interface by using the keyboard instead of the mouse or trackpad. Depending on which "panel" is currently selected you will find the arrow-keys to work like this:_

If the left panel / **mailbox-list** is currently selected:
-- use "**Up**" or "**Down**" to scroll the mailboxes up or down
-- use "**Right**" to select the messages-list

If the middle panel / **messages-list** is currently selected:
-- use "**Up**" or "**Down**" to scroll the message-list up or down
-- use "**Left**" to select the mailbox-list
-- use "**Right**" to select the message

If the right panel / **message** is currently selected:
-- use "**Up**" or "**Down**" to scroll the message-content up or down
-- use "**Left**" to select the messages-list

**FEATURE REQUEST**
1. Please add more keyboard shortcuts to use with Rainloop Webmail Interface
2. Please provide a complete list of existing shortcuts and their functions to the Documentation (I can also do this, if you want. However: it would be useful :) )

**Comment by RainLoop** [comment]
![image](https://user-images.githubusercontent.com/5530092/27960533-509c789c-6334-11e7-8694-4cf616ac5775.png)

![image](https://user-images.githubusercontent.com/5530092/27960549-5ebf05a2-6334-11e7-8beb-a1903a7a932e.png)

**Comment by sushinger** [comment]
Oh, thank you!
