### ISSUE TITLE
Gmail and Yahoo and Microsoft says Rainloop is a "Less secure app"

### ISSUE THREAD

**Issue by szepeviktor** [RainLoop/rainloop-webmail#1465]
Hello!

To be honest I am not a Gmail user
but during testing a Rainloop installation I've tried to log in to my Gmail account.

```
Google just blocked someone from signing 
into your Google Account szepe.viktor@gmail.com from an app that may put your account at risk. 
> Less secure appSaturday, July 8, 2017 4:32 PM (Finland Time)
> Finland*
```

What is the technical cause of this? The `AUTH` type?
Google's IMAP capabilities are
```
* CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH

```
Log shows `AUTHENTICATE PLAIN` 
See also https://developers.google.com/gmail/imap/xoauth2-protocol
and https://stackoverflow.com/a/30021510

I've tried `imap_use_auth_plain = Off` but no success. Had to Enabled Less secure apps https://myaccount.google.com/lesssecureapps

Please advise.

**Comment by szepeviktor** [comment]
Yahoo says the same: https://help.yahoo.com/kb/account/SLN27791.html

**Comment by szepeviktor** [comment]
Microsoft sent me a notification also. (@hotmail.com)

**Comment by szepeviktor** [comment]
@RainLoop Do you have plans to implement OAuth?

Duplicate of  #906

**Comment by AaronADev** [comment]
Was there ever any resolution to this issue?

**Comment by elhananjair** [comment]
> Was there ever any resolution to this issue?

@AaronADev turn on "Allow less secure apps" in gmail setting, but in general it would be better if rainloop could be one of secured apps and recognized by mail providers.
