### ISSUE TITLE
Date of imported emails

### ISSUE THREAD

**Issue by firvudastz** [RainLoop/rainloop-webmail#1466]
Hi,

I am a recent user of Rainloop installed as an app on my Nextcloud 12.0 server (Rainloop app is 5.0.0).

I imported emails (MBOX format) from my previous email account, I did it through the Roundcube interface of my email client, as I did not find the option on Rainloop. When Rainloop synchronized, these emails appeared as just received, i.e. the date of each of them was "9th of July, 00:30 am". While in Roundcube, the original date is properly used.
Do you know what I can do to get the right date for each email in Rainloop ?

Thanks in advance,

**Comment by louis-eyond** [comment]
In your application.ini, try changing date_from_headers = Off to On.  This will display the date from the header of the eml in your message list; however, it won't correct the sort order in the folder, as that is based on the IMAP creation date...  This is a typical pain with IMAP moving messages between Mailboxes, where the date written to the IMAP server database is going to be the new creation date that is being made when you are doing the move/copy via the IMAP client.

**Comment by firvudastz** [comment]
Thank you!

**Comment by firvudastz** [comment]
Excuse me, can you tell me where is the application.ini file in the case of Rainloop installed as an app on Nextcloud? I searched it in Filezilla but until now did not find it.

**Comment by akmet** [comment]
It's inside the Nextcloud Data Folder.
There go to rainloop-storage/_data_/_default_/config
