### ISSUE TITLE
Unable to upload attachments larger than 512kb

### ISSUE THREAD

**Issue by colinjmatt** [RainLoop/rainloop-webmail#1471]
RainLoop version, browser, OS:
Rainloop Version 1.11.1
Firefox 54.0.1 & IE11 on Windows 7
Firefox 54.0.1 on Arch Linux
Firefox 7.5 on iOS

Expected behavior and actual behavior:
With current settings, attachments up to the size of 500MB should be uploadable, but in reality, only files of around 512KB seem to be permitted. Files greater tha 512KB can be uploaded and sent using other mail clients such as Thunderbird or iOS Mail.

php.ini:
upload_max_filesize = 500M
post_max_size = 550M

application.ini:
attachment_size_limit = 500 (also attempted using a value of zero for unlimited)

Steps to reproduce the problem:
Create new message and attempt to attach a file greater than 512KB

Logs or screenshots:
Nothing in the Apache or Rainloop logs when attempting to attach. This also occurs when trying to attach a file when using a Gmail account through the Rainloop website.

![image](https://user-images.githubusercontent.com/13071027/28362392-2cff9240-6c74-11e7-9e54-c80196c83280.png)

**Comment by akmet** [comment]
I'm using Chromium under Debian Stretch and I am able to upload all files correctly.
When logging on to the Admin Panel you can see your php.ini Settings. Are there stated the right values?
Do you maybe have a special log for php errors somewhere?

**Comment by colinjmatt** [comment]
Admin Panel:
![screen shot 2017-07-19 at 19 10 12](https://user-images.githubusercontent.com/13071027/28382493-33cf85d4-6cb6-11e7-93bd-87b1e8226264.png)

No special log in any other location for PHP. All my logs are kept in /var/log so that I don't have to go hunting for them.

**Comment by colinjmatt** [comment]
OK, so after trawling through every config file I could think of, I looked at my sites-enabled folder in /etc/apache2. I spotted that I had LimitRequestBody set to 512KB. Removing this has resolved the issue completely.
