### ISSUE TITLE
cursor positioning in new messages with signature

### ISSUE THREAD

**Issue by fsantiago07044** [RainLoop/rainloop-webmail#1481]
**RainLoop version, browser, OS:** current (1.11.1) / chrome / windows 10

question; when I begin a new message, my signature appears correctly but my cursor is always at the very bottom of the window and i need to move it up above my signature. any way to have the cursor start by default above my signature, but below any quoted text? i have my signature set to be applied after the quoted text, if I'm replying. thanks.

**Comment by megadr01d** [comment]
I'm pretty sure this was working fine before. Now, composing a new message and tabbing through the fields, when the cursor reaches the text area, it's after the signature, and not in the first line as expected.

I guess https://github.com/RainLoop/rainloop-webmail/commit/a72b95a86846faa4691626bc0deb2ead0752c32e fixes it but not sure why cursor placing keeps getting broken...

**Comment by fsantiago07044** [comment]
if i have an existing installation, is it safe to update from git via a clone of the repo? what do i have to keep in mind when doing so if possible? Thanks.

**Comment by megadr01d** [comment]
I think the GH repo is the source code and needs to be built. The safest way to upgrade is through the admin panel.

https://www.rainloop.net/docs/

**Comment by fsantiago07044** [comment]
understood. thanks. if this issue is fixed then i will close this.
