### ISSUE TITLE
Sieve Filter Regex backslash usage - Some docs would help

### ISSUE THREAD

**Issue by ksylvan** [RainLoop/rainloop-webmail#1486]
RainLoop version 1.11.1

Reading this, https://datatracker.ietf.org/doc/html/draft-murchison-sieve-regex-04 I was putting double-backslashes into my Filter rules.

```
From: .*@.*\\.ru
```

When they did not work, I found the actual Rainloop generated scripts and figured out my problem. The frontend was already turning my backslashes into double-backslashes for the generated Sieve scripts.

Some examples of how to input Regex into the Rainloop UI would help in this case.

**Comment by GuzziGuy** [comment]
I'm me-too-ing this - I also found that backslashes get escaped before they get to the sieve script. I can't see any mitigation for this in the source code, so I don't think we are missing any examples/instructions as such.

This does limit regex usefulness a bit, so maybe one to resolve if possible...
