### ISSUE TITLE
Rainloop automatically creates Archive Folder upon first login

### ISSUE THREAD

**Issue by schnappijedi** [RainLoop/rainloop-webmail#1489]
Rainloop is neat. One thing holding back from deploying is that upon first loginin Rainloop automatically creates an "Archive" folder and defaults to using a System archive folder (instead setting the archive system folder to "do not use" for users who do not already have an archive folder) or at least giving some kind of choice in the admin panel.

If deploy Rainloop it will create archive folders for all users which is not desirable.

RainLoop version 1.11.1 on Debian 9.1

**Comment by louis-eyond** [comment]
In your application.ini, try changing autocreate_system_folders = On to Off.

**Comment by schnappijedi** [comment]
Thanks.
