### ISSUE TITLE
Authenticator Reset

### ISSUE THREAD

**Issue by Tobstr02** [RainLoop/rainloop-webmail#1492]
Hello Rainloop Team,
I've Activated the 2Step-Verification on Rainloop-Webmail.

After a while, I reset my phone. So I lost the Google Authenticator's codes.
How can I access my account now?

Rainloop Version: 1.10.5.192
OS: Linux Mint
Browser: Firefox

**Comment by RainLoop** [comment]
Try to remove this file:
`./data/_data_/_default_/storage/cfg/te/test@rainloop.net/two_factor`

Change `te/test@rainloop.net` with your email.
