### ISSUE TITLE
[FEATURE REQUEST] Ctrl+Enter to send email, like in Outlook or Gmail

### ISSUE THREAD

**Issue by jadesoturi** [RainLoop/rainloop-webmail#1499]
**RainLoop version, browser, OS:*5.0.2 on a nextcloud 12, chorme/vivaldi/opera/firefox, arch linux/windows 7/10*

**Expected behavior and actual behavior:* Press Ctrl+Enter when done writing email to send it instead of pressing the send button with the mouse* Actual: nothing happens:/

This would be very useful and timesaving feature. Rainloop is awesome, but this would be like a cherry topping:)

**Comment by ervee** [comment]
This cherry topping can be activated in the application.ini.

**Comment by jadesoturi** [comment]
Awesome! Thank you! The documentation is not so clear as what features do what so not easy to know. But thank you! Closed the issue :)
