### ISSUE TITLE
Default domain in login screen 

### ISSUE THREAD

**Issue by Mageti** [RainLoop/rainloop-webmail#15]
Hello, 
The lazy man in me has a question : 
Rainloop is install on my server (domain : domain1.com). My email is "mageti_AT_domain1.com", but my login is just "mageti" for IMAP and SMTP. I use the "extended" version of the login screen to set the mail, the login and the password. Quite long for me...
The question is : is it possible to set a parameter so that for the default domain, I just have to enter the login (just "mageti") on the normal login screen (email+password), and if rainloop does not detect it to be a valid email address, it autocomplete the email address with the default domain (so "domain1.com") but keeps using the short login to authenticate on the default domain server ?

Hm... Not sure if I explained it well enough. So if I mis-explained,please ask.

**Comment by rvuban** [comment]
Please help me to solve this.

![untitled](https://cloud.githubusercontent.com/assets/12150277/7386819/c1fc20b4-ee79-11e4-8171-7df0af57f381.png)

**Comment by rvuban** [comment]
All the prefixed domains are unusable. What is the problem ?

![gmail](https://cloud.githubusercontent.com/assets/12150277/7386869/57b8693c-ee7a-11e4-8f6c-49fb1023465d.jpg)

**Comment by mhamzas** [comment]
Make sure you've right DNS entries of the hostnames you're using.
Ask your isp to provide you the imap/pop3 and smtp details
