### ISSUE TITLE
Mixed version numbers in nextcloud

### ISSUE THREAD

**Issue by akmet** [RainLoop/rainloop-webmail#1506]
Hey, I just noticed that in the last update the owncloudapp got version 5.0.1.
But 5.0.2 was already available.
With 5.0.1 (new) I get 1.11.2
With 5.0.2 (installed) I have 1.11.1

**Comment by RainLoop** [comment]
Well, nextcloud changes the version himself.
The last version is 5.0.1 (1.11.2) here: https://github.com/RainLoop/rainloop-webmail/releases
