### ISSUE TITLE
application.ini gets overwritten with standard values

### ISSUE THREAD

**Issue by joe-average-user** [RainLoop/rainloop-webmail#1509]
**RainLoop version, browser, OS:**
rainloop 1.11.1
Firefox 55.0.3 on client
openSUSE 42.3 on server

**Expected behavior and actual behavior:**
I installed a new webserver under openSUSE 42.3 and installed rainloop. Logged in as admin and configured language (german, admin and user), enabled contacts, configured mysql and x-originating-ip plugin. Logged in as several users and configured some accounts. in about 6 hours runtime application.ini got overwritten three times. It always lost the mysql setup, the language and the default domain. 
To prevent that I changed the file owner to root. But that's no solution of course.

**Steps to reproduce the problem:**
Well, see above. The only non-standard thing about the installation is that it resides on a glusterfs.

**Logs or screenshots:**
Unfortunately have none.

**Comment by megadr01d** [comment]
Maybe duplicate of https://github.com/RainLoop/rainloop-webmail/issues/1287.

**Comment by joe-average-user** [comment]
I thought about such a problem you try to solve here. If you have two sessions open on your browser you may end up at this point of overwriting.
But there is another possibility: if you have multiple webservers running on the same installation (lets say in a loadbalancing environment) can rainloop handle this correctly, not overwriting things in the data tree used by another session on another webserver?
This could be solved by an autologout of all but the active sessions ...

**Comment by insound** [comment]
I fix that when run php7. When use php5.6 problem come back.

**Comment by joe-average-user** [comment]
I am on php 7.0.7 btw

**Comment by joe-average-user** [comment]
Update: running Rainloop 1.11.3 now and since 3 days the problem did not occure again...

**Comment by megadr01d** [comment]
That's because it was [fixed](https://github.com/RainLoop/rainloop-webmail/commit/f695a1acd2359cc2e94846b828265e9b11fdd402). Please close the issue if it solved your problem.

**Comment by joe-average-user** [comment]
I'd say you are right.

**Comment by zeigerpuppy** [comment]
this still seems to be a problem in 1.12.0
some of the settings fall back to default... including the admin password which is a major issue!
