### ISSUE TITLE
Integration with SpamAssassin

### ISSUE THREAD

**Issue by fearworksmedia** [RainLoop/rainloop-webmail#151]
When I used to use Roundcube (don't worry - I won't be going back to it!!) there was a handy plugin that allowed emails to be marked as spam, and it allowed a command to be run whenever a message was marked as spam so that Spamassassin could learn from it:

"C:\SpamAssassin\sa-learn.exe" --spam %f

where %f was replaced with the path to the message file.

There was also the opposite command in case an email was marked as spam but wasn't spam:

"C:\SpamAssassin\sa-learn.exe" --ham %f

This is a Windows-based command of course, but regardless of the OS, where in the RainLoop code (or how) can I run a command such as this when an email is marked as spam? As I understand it right now, marking an email as spam does nothing apart from moving it quickly to the spam folder - is that right?

I notice the "Not Spam" button has been removed from RainLoop but maybe if this could be implemented then it would be a reason to bring that button back?

Thanks!

**Comment by fgiorlando** [comment]
One mechanism that works well for learning spam is using folders which Spamassassin can scan for spam and ham. 
I think just reconfiguring the system folder for "Spam" should work with this mechanism.
However, it won't work for Ham, would it be possible to change where Ham goes to when marked by the user?

There is a plugin in roundcube that can be configured to place spam in a specific folder and mis-marked spam in a ham folder. (I call the folders "LearnAsSpam" and "LearnAsHam")

The following gives an example for mail organised in maildirs.
Then you can just use cron jobs (once per day is plenty):

### Find spam
```
sa-learn -p ~/.spamassassin/user_prefs --spam /home/vmail///Maildir/.LearnAsSpam/{cur,new} sa-learn -p ~/.spamassassin/user_prefs --ham /home/vmail///Maildir/.LearnAsHam/{cur,new}
```
### Move spam
```
find /home/vmail/ -type d -path "//Maildir/.LearnAsSpam/cur" -exec sh -c '(cd {} && mv ./* ../../.Junk/cur)' ';' find /home/vmail/ -type d -path "//Maildir/.LearnAsSpam/new" -exec sh -c '(cd {} && mv ./* ../../.Junk/new)' ';'
```
### Move ham
```
find /home/vmail/ -type d -path "//Maildir/.LearnAsHam/cur" -exec sh -c '(cd {} && mv ./* ../../.Inbox/cur)' ';' find /home/vmail/ -type d -path "//Maildir/.LearnAsHam/new" -exec sh -c '(cd {} && mv ./* ../../.Inbox/new)' ';' 
```

**Comment by zeigerpuppy** [comment]
I think it should be possible to change the folder to which the "spam" and "not-spam" buttons move mail to.

see: 
- rainloop-webmail/dev/App/User.js
- rainloop-webmail/dev/Stores/User/Folder.js

In User.js, we'd probably need to change the `case FolderType.NotSpam` function, but I think it would also be necessary to define the new folder name (in my case `LearnAsHam`) in `Folder.js`)

**Comment by msimerson** [comment]
For training spam filters, this solution is independent of the spam filter and the webmail app. I use dovecot as my POP/IMAP server and have sieve scripts that train the filters based on common user actions. These scripts detect the actions a user would take if they click on a "Spam" or "Not Spam" button in their MUA or webmail app, so there's practically no human training required.

In my dovecot config I have sieve enabled with these blocks:

````
  # From elsewhere to Junk, train as Spam
  imapsieve_mailbox1_name = Junk
  imapsieve_mailbox1_causes = COPY
  imapsieve_mailbox1_after  = file:/usr/local/lib/dovecot/sieve/report-spam.sieve

  # From elsewhere to Spam, train as Spam
  imapsieve_mailbox2_name = Spam
  imapsieve_mailbox2_causes = COPY
  imapsieve_mailbox2_after  = file:/usr/local/lib/dovecot/sieve/report-spam.sieve

  # From Junk to elsewhere, train as Ham
  imapsieve_mailbox3_name = *
  imapsieve_mailbox3_from = Junk
  imapsieve_mailbox3_causes = COPY
  imapsieve_mailbox3_after  = file:/usr/local/lib/dovecot/sieve/report-ham.sieve

  # From Spam to elsewhere, train as Ham
  imapsieve_mailbox4_name = *
  imapsieve_mailbox4_from = Spam
  imapsieve_mailbox4_causes = COPY
  imapsieve_mailbox4_after  = file:/usr/local/lib/dovecot/sieve/report-ham.sieve

  # From elsewhere to Archive, train as Ham
  imapsieve_mailbox5_name = Archive
  imapsieve_mailbox5_causes = COPY
  imapsieve_mailbox5_after  = file:/usr/local/lib/dovecot/sieve/report-ham.sieve
````

By using the standard folders and standard user actions, there's no need for separate `Learn Ham` and `Learn Spam` folders.

Here's an example of the contents of a sieve script:

````
# cat /usr/local/lib/dovecot/sieve/report-ham.sieve
require ["vnd.dovecot.pipe", "copy", "imapsieve", "environment", "variables"];

if environment :matches "imap.mailbox" "*" {
  set "mailbox" "${1}";
}

if string "${mailbox}" "Trash" {
  stop;
}

if environment :matches "imap.user" "*" {
  set "username" "${1}";
}

pipe :copy "learn-ham-rspamd.sh" [ "${username}" ];
pipe :copy "learn-ham-sa.sh" [ "${username}" ];
````

You'll notice that a single user action trains both rspamd and spamassassin.

Also, for completeness, here are the training scripts:

````
# cat /usr/local/lib/dovecot/sieve/learn-ham-rspamd.sh 
exec /usr/local/bin/curl -s -S -XPOST --data-binary @- http://N.N.N.N:11334/learnham
# cat /usr/local/lib/dovecot/sieve/learn-ham-sa.sh 
exec /data/bin/spamc -d N.N.N.N --learntype=ham -u ${1}
````

**Comment by zeigerpuppy** [comment]
thanks @msimerson, that's a much more elegant solution!
