### ISSUE TITLE
.htaccess in data is not apache 2.4 compatible

### ISSUE THREAD

**Issue by joe-average-user** [RainLoop/rainloop-webmail#1510]
**RainLoop version, browser, OS:**
rainloop 1.11.1
openSUSE 42.3
apache 2.4

**Expected behavior and actual behavior:**
accessing the data dir with browser throws error. 
AFAIK "Deny" does not exist any longer, "Require" Statement is needed.

**Steps to reproduce the problem:**
Just try to load application.ini with complete path in browser.

**Logs or screenshots:**
apache log:
[Thu Sep 21 10:30:31.319032 2017] [core:alert] [pid 31281] [client XXX:YY] /srv/www/rainloop/data/.htaccess: Invalid command 'Deny', perhaps misspelled or defined by a module not included in the server configuration

**Comment by RainLoop** [comment]
Could you check this file: [htaccess.zip](https://github.com/RainLoop/rainloop-webmail/files/1322531/htaccess.zip)

**Comment by joe-average-user** [comment]
Your suggested new htaccess works as expected on apache 2.4.
Thanks for that.

**Comment by joe-average-user** [comment]
Is it possible that your fix does not automatically work if updating, but only on fresh installation?

**Comment by RainLoop** [comment]
> Is it possible that your fix does not automatically work if updating, but only on fresh installation?

Why?

**Comment by joe-average-user** [comment]
Because we tried to solve the problem on a second installation and found out that the .htaccess does not get updated/overwritten even if using the newer version of rainloop. The former .htaccess in the data dir survives.

**Comment by ervee** [comment]
Perhaps RainLoop should not write an htaccess file altogether, but only detect when none is present. Then refuse to load and point to documentation on how to fix is per Apache version.

It would even be better if RainLoop could also detect whether proper ngix equivalent settings are present. But that could be some more work for another time.

**Comment by joe-average-user** [comment]
I don't think so. I think it is pretty ok for rainloop to support the most-used webserver version (e.g. the htaccess file). But I think there seems to be no logic inside to replace the file with a newer version in case of an update...

**Comment by ervee** [comment]
Yes, but I was more thinking of when someone modifies the htaccess file. If it is over written then those changes are lost (of there is no smart way of checking...)

**Comment by RainLoop** [comment]
In fact, I want to remove all these extra files. The user should understand that he must hide the data folder from the web access.

**Comment by joe-average-user** [comment]
Well, the "user" does not understand a lot of things most of the time :-) A little help from the application programmer(s) is therefore often appreciated. I don't think that the htaccess file securing the primary data dir of such a big application should be subject to change by any third party user. There should be no reason for that at all. So I see no valid source for "changes to be overwritten on update".
Iff the user thinks of changes he should probably make them in the apache config file and not fiddle around inside the app. Because the apache config cannot be overwritten by any update at all, so it is the only safe place for such user-intended changes.

**Comment by RainLoop** [comment]
![image](https://user-images.githubusercontent.com/5530092/31047645-ff8a66c8-a616-11e7-8b94-64d0dfceda26.png)

**Comment by joe-average-user** [comment]
I think the warning is ok. Let's leave it here.Thanks.
