### ISSUE TITLE
Wrong language title

### ISSUE THREAD

**Issue by fitzg2** [RainLoop/rainloop-webmail#1511]
**RainLoop version, browser, OS:**
1.10.2.143

**Expected behavior and actual behavior:**
The flag is wrong.

**Steps to reproduce the problem:**
1. Download rainloop
2. Install 
3. Choose language in login screen

**Logs or screenshots:**
![image](https://user-images.githubusercontent.com/17569693/30709751-abf7faa0-9ed9-11e7-96e5-9510b15b0760.png)

**Comment by RainLoop** [comment]
Fixed in the last versions:

![image](https://user-images.githubusercontent.com/5530092/30713670-b6edd9ae-9f18-11e7-9373-2d5954c423b0.png)

**Comment by Darlelet** [comment]
@RainLoop Why leaving the issue opened then? :wink:

**Comment by RainLoop** [comment]
@Darlelet Because it might be the environment error.  But most likely it is not. :)
