### ISSUE TITLE
Entering webmail via link on android homescreen ends up in desktop mode

### ISSUE THREAD

**Issue by joe-average-user** [RainLoop/rainloop-webmail#1514]
**RainLoop version, browser, OS:**
rainloop v1.11.1
Chrome Browser
Android 7.0

**Expected behavior and actual behavior:**
If you enter the webmail interface by Chrome on Android it understands that it is a mobile device and uses mobile setup.
But if you tell Chrome to place the weblink on the androids' homescreen for easy access and enter that afterwards you end up in desktop mode.
This should be pretty easy to reproduce.

**Steps to reproduce the problem:**
s.a.

**Logs or screenshots:**
really not needed, happens every time you do the above...

**Comment by ervee** [comment]
I can't reproduce this. I opened the RainLoop login screen in Chrome (I see "/?/Mobile/" in the URL), added that to the homescreen. When I open that I get the mobile version. The same when I add a logged in session to the homescreen.

**Comment by joe-average-user** [comment]
Please login and try again

**Comment by ervee** [comment]
Logged in, created shortcut, went to homescreen, tapped the shortcut, still the same, it opens the mobile version. I'm on a Sony Xpera Z5c, Android 7.1.1

**Comment by joe-average-user** [comment]
Re-Checked that with 1.11.3 now and the problem is gone. Thank you.
