### ISSUE TITLE
Problem syncing 1300 contacts from CardDAV server

### ISSUE THREAD

**Issue by joe-average-user** [RainLoop/rainloop-webmail#1517]
**RainLoop version, browser, OS:**

rainloop 1.11.1
Firefox
Windows 10

**Expected behavior and actual behavior:**
Setting up CardDAV server, syncing contacts.
Stop after around 1000 contacts with error msg

**Steps to reproduce the problem:**

**Logs or screenshots:**

Is there some hardcoded maximum number of contacts? I did not find anything inside the ini file ...

**Comment by joe-average-user** [comment]
Maybe I should explain the setup a bit more.
I am using Nextcloud as a CardDAV server for the contacts. I imported all contacts there via a vcf file, which worked out well. All contacts are visible in the nextcloud web interface.
Then I tried to setup this nextcloud server as CardDAV server in rainloop. Syncing takes a while and stops with an error message I cannot repeat here (simply forgotten). When looking into the contacts afterwards in rainloop it seems all contact up to a certain beginning character are there. I have not counted them but could well be around 1000. Since all the contacts are working in the cloud I came to the conclusion that there could be an explicit or implicit maximum inside rainloop somewhere.
Has anybody more than 1000 contacts inside rainloop via CardDAV?

**Comment by joe-average-user** [comment]
Update:
In the meantime I am on rainloop 1.11.3 and it seems all contacts are synced. Is there a logfile somewhere where I can look after the CardDAV sync activities of rainloop?

**Comment by RainLoop** [comment]
Perhaps it was just some kind of error, and the contacts were not synchronized all at once. 
RainLoop does not contain any changes about contacts between 1.11.1 and 1.11.3 versions.

> Is there a logfile somewhere 

To enable logging, find `./data/_data_/.../configs/application.ini` configuration file:

```ini
[logs]
enable = On
```
All log files are located in `./data/_data_/.../logs` directory.

**Comment by joe-average-user** [comment]
Thank you for confirmation.
