### ISSUE TITLE
Send Keyboard Shortcut

### ISSUE THREAD

**Issue by Riscue** [RainLoop/rainloop-webmail#1532]
**RainLoop version, browser, OS:**
RainLoop 1.11.3, Chrome 61.0.3163.100 (64 bit), Win 10 (1703)

**Expected behavior and actual behavior:**
It would be nice to have a shortcut for sending a mail. Like Ctrl + Enter default for gmail.

**Steps to reproduce the problem:**

**Logs or screenshots:**

**Comment by megadr01d** [comment]
https://github.com/RainLoop/rainloop-webmail/issues?utf8=%E2%9C%93&q=send%20shortcut

Close issue if fixed.

**Comment by Riscue** [comment]
Thanks mate! Its working now.
But there must be setting in admin panel or could be enabled by default.
