### ISSUE TITLE
How to install owncloud client?

### ISSUE THREAD

**Issue by mehrdaad** [RainLoop/rainloop-webmail#1537]
Apperantly, this project has a dependency on ``OCP`` api.  
I assume that this is a owncloud api but I couldn't find any information how to install it.  
for instance, there is a function as follow:  

    /**
	 * @return bool
	 */
	public static function IsOwnCloudLoggedIn()
	{
		return self::IsOwnCloud() && \class_exists('OCP\User') && \OCP\User::isLoggedIn();
	}
as it's apparent, rainloop checks for a class existence with name ``OCP\User``.  
This class is not existent in rainloop.  
My question is how to install this package? and precisely, what is it?  
Regrards.

**Comment by mehrdaad** [comment]
@RainLoop can guide a bit?

**Comment by davdavf** [comment]
https://marketplace.owncloud.com/apps/rainloop
Is this what you are looking for?...
