### ISSUE TITLE
How to get attachmented files on rainloop

### ISSUE THREAD

**Issue by mehi-shokri** [RainLoop/rainloop-webmail#1540]
**RainLoop version, browser, OS:**
V1.11.1
Chrome 61
Wdindows10
**Expected behavior and actual behavior:**

What I want to do is to get all files which are selected in a message view.  
presumably this action is done in the messageView.js file. 
So there is a function called ``getAttachmentsHashes()`` which it's returned value is in hashes.  
How can I get files from these hashed so I can upload them with an ajax request?

**Comment by Med-All** [comment]
What do you mean by "get all files"? Download all of them at once?

**Comment by mehrdaad** [comment]
nope I mean the actual files, so I can upload asynchronously to another source.

**Comment by Med-All** [comment]
Interesting because I'm looking for something similar. So far I have found you need to fetch attachments from message itself and store temporarily on the server. To do that there are two ways - to create download link and access it or to use `DoMessageUploadAttachments()` to store attachments.  But for now I'm somehow stuck on both. First requires web session/cookie to have it done and for second endpoint is a web part (JavaScript) but I need to get that done on the server part (PHP).

**Comment by mehrdaad** [comment]
Another thing is that downloading selected attachments gives the link which is a zip file, not separate links

**Comment by danishsultan007** [comment]
@Med-All  I have seen your previous issues with rainloop and i think you might be able to help. I am beginner and a intern right now. i am trying to integrate a calendar in which i want it to intercommunicate between rainloop and the calendar app to create a event automatically once i receive a mail with .ics or .iCal(just like google calendar). I am not able to find out how the attachments in rainloop are being handled. Any help for where to look will be highly appreciated.

i am looking inside attachment.php inside /app/libraries/MailSo/Mail/Attachment.php and mailclient.php
![selection_002](https://user-images.githubusercontent.com/19188658/52404309-bba13c80-2aee-11e9-9964-dcd7fff833f8.png)
![selection_003](https://user-images.githubusercontent.com/19188658/52404310-bc39d300-2aee-11e9-8055-2ad55fce7bb9.jpg)

**Comment by danishsultan007** [comment]
@mehi-shokri  were you able to to find out how attachments are being handled?

**Comment by mehi-shokri** [comment]
@danishsultan007 Nope.
