### ISSUE TITLE
imapproxy support

### ISSUE THREAD

**Issue by rogeriobastos** [RainLoop/rainloop-webmail#155]
Hi,

Does rainloop support imapproxy? It's a nice daemon to improve imap speed!

**Comment by hostingrajamani** [comment]
hello,

We are also looking forward to configure imapproxy. Is there any documentation to configure imapproxy with rainloop ?

**Comment by ervee** [comment]
You don't need that. Use the Imapproxy documentation to set it up on the same server as RainLoop is running on. Then configure RainLoop to connect IMAP to localhost (no SSL).

**Comment by hostingrajamani** [comment]
I have got a reply within few minutes, Its great. 
Even commercial software takes days to reply. 

Thank you, will try. If any issues, will get back

**Comment by hostingrajamani** [comment]
finally configured imap proxy based on the README file and also had some problem, Googled and found a solution. Except this Error.

CentOs 7
tail -f /var/log/messages
Jul 24 09:05:33 localhost in.imapproxyd: main(): Using default configuration file '/etc/imapproxy.conf'.
Jul 24 09:05:33 localhost in.imapproxyd: SetConfigOptions(): parse error reading config file at line 269.  Exiting.

Solved the problem by removing the empty lines at the bottom of the config file.
