### ISSUE TITLE
Sieve rules from other clients are not displayed

### ISSUE THREAD

**Issue by allo-** [RainLoop/rainloop-webmail#1559]
With Rainloop 1.10.3.151, sieve rules from other clients (i.e. old rules from roundcube) are not displayed in the web interface. They still exist on the server and can be seen from roundcube.

**Comment by ervee** [comment]
It's a know issue.
#428
https://github.com/RainLoop/rainloop-webmail/issues/419#issuecomment-76936594
https://github.com/RainLoop/rainloop-webmail/issues/1061#issuecomment-228442045
#1137
