### ISSUE TITLE
RainLoop Webmail mailbox autorefresh

### ISSUE THREAD

**Issue by janarzz** [RainLoop/rainloop-webmail#1571]
Hei,
can i enable RainLoop Webmail message autorefresh ?
I use:
Latest version of RainLoop Webmail
Ubuntu server 16.04.3

**Comment by ervee** [comment]
What do you mean? RainLoop will fetch new messages every x-minutes (1 minute I believe) and if there is new mail it will update the messages list and show a pop-up (if configured/supported by browser).

**Comment by janarzz** [comment]
Hey,
sorry..my bad :) Autorefresh really works :)

**Comment by ervee** [comment]
No problem, please close the issue if it can be closed.
