### ISSUE TITLE
Memcached / APCu

### ISSUE THREAD

**Issue by tilkov** [RainLoop/rainloop-webmail#1576]
RainLoop version 1.11.3 on Ubuntu 16.04 with nginx, php7 and php7-fpm

Hi,
I've tried changing caching from 'files' to 'APC' and then to 'memcached', but neither APC nor memcached show any data being stored in them, zero items

With APC, php-apcu 5.1.3 was installed and enabled, monitored with apc.php file from https://raw.githubusercontent.com/krakjoe/apcu/master/apc.php

With memcached, memcached 1.4.25 and php-memcached 2.2.0 were installed and monitored with "stats" in telnet connection to memcached.

Settings:

[cache]
enable = On
index = "v36" (+1 on every cache setting change)
fast_cache_driver = "memcache"
fast_cache_index = "v36" (+1 on every cache setting change)
http = On
http_expires = 3600

[labs]
cache_system_data = On
fast_cache_memcache_host = "127.0.0.1"
fast_cache_memcache_port = 11211

Am i doing anything wrong?

**Comment by ervee** [comment]
I'm running Debian Jessie with nginx and php5-apcu and for me it is working fine.
```
[cache]
enable = On
index = "RLv1"
fast_cache_driver = "APC"
fast_cache_index = "v1"
http = On
http_expires = 3600
server_uids = On
```
apc.php shows a lot of hits and in the user cache entries I see stuff related to RainLoop. In my nginx I see no specific configuration for apc. This is the php related config I have in nginx:
```
upstream php-handler {
        server 127.0.0.1:9000;
        #server unix:/var/run/php5-fpm.sock;
}

server {
[...snip...]
        location ~ ^/rainloop/.*\.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_keep_conn on;
                fastcgi_pass php-handler;
        }
[...snip...]
}
```
snippets/fastcgi-php.conf:
```
fastcgi_split_path_info ^(.+\.php)(/.+)$;
try_files $fastcgi_script_name =404;
set $path_info $fastcgi_path_info;
fastcgi_param PATH_INFO $path_info;
fastcgi_index index.php;
include fastcgi.conf;
```
fastcgi.conf:
```
fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
fastcgi_param  QUERY_STRING       $query_string;
fastcgi_param  REQUEST_METHOD     $request_method;
fastcgi_param  CONTENT_TYPE       $content_type;
fastcgi_param  CONTENT_LENGTH     $content_length;

fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
fastcgi_param  REQUEST_URI        $request_uri;
fastcgi_param  DOCUMENT_URI       $document_uri;
fastcgi_param  DOCUMENT_ROOT      $document_root;
fastcgi_param  SERVER_PROTOCOL    $server_protocol;
fastcgi_param  HTTPS              $https if_not_empty;

fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_PORT        $server_port;
fastcgi_param  SERVER_NAME        $server_name;

# PHP only, required if PHP was built with --enable-force-cgi-redirect
fastcgi_param  REDIRECT_STATUS    200;
```

**Comment by tilkov** [comment]
The difference seems to be that you are using PHP5 whereas i am using PHP7.

**Comment by ervee** [comment]
Yes. I am planning to update to the latest Debian soon. If that's PHP7 then I'll know if this works for me or not. Perhaps something changes for PHP7 that breaks this, I don't know.

**Comment by Alphix** [comment]
I've encountered the same issue.

I'm not a PHP guru, but the switch statement in [https://github.com/RainLoop/rainloop-webmail/blame/master/rainloop/v/0.0.0/app/libraries/RainLoop/Actions.php](url) on line 989 seems wonky (I'm guessing it's the result of a sloppy conversion from if-else logic into switch logic).

I manually edited the file and changed the `switch(true)` to `switch($sDriver)` and then cleaned up the weird case conditionals. Opened Rainloop in a browser and then checked the apc stats. There are now entries in the cache.

(Also note that if you're using debian you need php-apcu-bc as well as php-apcu since Rainloop only uses the old API)

**Comment by Alphix** [comment]
Actually, it might be enough to just install php-acpu-bc....it seems that PHP allows for some pretty wonky switch syntax :confused:

**Comment by ervee** [comment]
I have migrated to a new server with PHP7 and php-apcu-bc and it looks like it is working when I checkwith apc.php.

**Comment by Alphix** [comment]
Yeah, I just tested it with a pristine `Actions.php` and with `php-apcu-bc` installed and it works so my pull request #1633 isn't necessary (though I still think it's a nice cleanup) and I guess this issue can be closed if @tilkov can confirm that installing `php-acpu-bc` fixes it for him.

I might do a separate PR for adding native APCU support though so the extra package isn't necessary.

**Comment by tilkov** [comment]
Sorry about the late reply.

Yes, APC is working after installing php-apcu-bc as described here: https://gist.github.com/philbot9/1e895303a37a1c18717e90eb7067df73

Thank you very much.
