### ISSUE TITLE
ownCloud Rainloop App: Login with email account error "Domain not allowed"

### ISSUE THREAD

**Issue by plastikschnitzer** [RainLoop/rainloop-webmail#1577]
**RainLoop version, browser, OS:**

ownCloud Rainloop App Version 5.0.5

**Expected behavior and actual behavior:**

Login with email account not working, "Domain not allowed"

I tested several email domains from different server providers (Hostnet, Strato) and I always get the error message "Domain not allowed", only gmail is working as expected.

**Comment by zeigerpuppy** [comment]
You need to log in to the rainloop management interface (from extra settings in nextcloud admin).
domains can be enabled there.

**Comment by plastikschnitzer** [comment]
Ah thank you! I saw the manual here now: https://github.com/pierre-alain-b/rainloop-nextcloud

Issue can be closed.
