### ISSUE TITLE
Trigger CardDAV sync without user interraction

### ISSUE THREAD

**Issue by tilkov** [RainLoop/rainloop-webmail#1589]
Hi!

Is there a way to trigger CardDAV sync externally? cURL/wget, something like that? My users can't be bothered to sync manually :(

Regards,
Todor Todorov

**Comment by ervee** [comment]
It is syncing automatically. You can do it manually only if you need to force a sync.

**Comment by tilkov** [comment]
Perfect! I did not know that.
