### ISSUE TITLE
Not working on localhost

### ISSUE THREAD

**Issue by ghost** [RainLoop/rainloop-webmail#16]
Just trying out RainLoop on my localhost system. Upon first run it complained about Curl, which I installed via terminal as root. Now all I get is a blank screen, and looking at the source view, nothing is being output to the browser. I'm wondering if RL doesn't work via localhost.

BTW, running Ubuntu Saucy, PHP, Apache.

**Comment by rvuban** [comment]
I have installed and configured Rainloop on my web server. But the user login page is not showing at all ! What can I do now ?
