### ISSUE TITLE
"invalid token" and "File is too big"

### ISSUE THREAD

**Issue by greg0r** [RainLoop/rainloop-webmail#1624]
Hey great devs,

First of all Thank you so much for this beautiful peace of software. I really like it. But unfortunately I have an issue right now which makes it unpossible to use.

**RainLoop version, browser, OS:**
Rainloop: 1.11.3
Browser: Firefox 57, Chrome 52
Client OS: Ubuntu 16.04
Server OS: Ubuntu 16.04

**Expected behavior and actual behavior:**
Sending Mails with text that exceeds i.e. some hundred characters I will get a "Invalid Token" when pushing Send. Also when trying to upload even a small file with i.e. 35KB I will get a "File is too big" error. The values in php.ini are correct as the admin panel in rainloop says
PHP: upload_max_filesize = 1024MB; post_max_size = 1024MB

**Steps to reproduce the problem:**
see above
**Logs or screenshots:**
```
[17:18:25.121][de1c02fb] INFO[DATA]: [DATE:19.01.18][OFFSET:-00][RL:1.11.3][PHP:7.0.22-0ubuntu0.16.04.1][IP:88.130.49.252][PID:5261][nginx/1.12.2][fpm-fcgi]
[17:18:25.121][de1c02fb] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql,pgsql][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[17:18:25.121][de1c02fb] REQUEST[NOTE]: [POST] https://domain.tld/?/Upload/&q[]=/_fbdTF3hvqkzXupNmzl-jABIzxo5xdKgBrHbjySPooQv80L0ncnSdFNS_wwffSl5Ol4NAqYiajvr6npvu271tpha6iTgoHl4RUApbdHha_OM3U38
8rGVMSkdWLOk5PkKWzKOyhNfTbBB-4-jjJpNd71fmgp-KCdrMp2SvosKPCWcT97tmAZWbk6ccytO4Mp4tYgfVEWbWx_NMI1D8qezOUHNNJUBvUX8_N7aH4qUPeWAel1GTI8uVx1aIFkPPYJQ0PMa0Rf6zjDbaYle45zXZGHG81TQQOIl_HFfEm7PjOHUQZIrYFXk_b2gCdt9r43FadQx
5VXk-N-clt1EMaX2-8UBz61FZCfDVoFosFTcYYCIywHorVkpSLTCdgsiV4hTFU8AsNWaMWTM/
[17:18:25.122][de1c02fb] UPLOAD[DATA]: {"Action":"Upload","Result":{"ErrorCode":1,"Error":"File is too big"}}
[17:18:25.122][de1c02fb] INFO[MEMORY]: Memory peak usage: 2MB
[17:18:25.122][de1c02fb] INFO[TIME]: Time delta: 0.013617992401123

```

**Comment by greg0r** [comment]
I did some additional testings and in turned out that files with the size of 682Bytes are fine but files with the size of 683Bytes fail. That is weird, right? On the other hand I guess the solution might be easy. I just can't find it.

**Comment by ervee** [comment]
Do you have client_max_body_size set correctly in your nginx site config?

**Comment by greg0r** [comment]
I put the following into the server section after you pointed me to this setting:
 ```
 client_max_body_size 100M;
  fastcgi_buffers 64 4K;
```
But still, I get the same error after restarting nginx.

**Comment by ervee** [comment]
Can you please post the complete ngix site config?

**Comment by greg0r** [comment]
nginx server configuration
```
server {
  listen 80;
  listen [::]:80;
  server_name domain.tld www.domain.tld
  return 301 https://$server_name$request_uri;
}

server {
  listen      443 ssl;
  listen      [::]:443 ssl;
  server_name domain.tld;
  root        /var/www/rainloop;

  ssl_certificate     /etc/letsencrypt/live/domain.tld/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/domain.tld/privkey.pem;
  include             /etc/letsencrypt/options-ssl-nginx.conf;
  ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

  access_log  /var/log/nginx/domain.tld_access.log;
  error_log   /var/log/nginx/wdomain.tld_error.log;

  index       index.php;

  client_max_body_size 100M;
  fastcgi_buffers 64 4K;

  location / {
     try_files $uri $uri/ /index.php?$query_string;
  }

  location ~ \.php$ {
      fastcgi_index index.php;
      fastcgi_split_path_info ^(.+\.php)(.*)$;
      fastcgi_keep_conn on;
      include /etc/nginx/fastcgi_params;
      fastcgi_pass  unix:/run/php/php7.0-fpm.sock;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  }

  location ~ /\.ht {
      deny all;
  }

  location ^~ /data {
     deny all;
  }
}
```

**Comment by ervee** [comment]
Repeat the client_max_body_size in the php location stanza and reload nginx and you will probably be fine.

**Comment by greg0r** [comment]
Thank you so much for your help @ervee, but unfortunately it is still not working. Is there a possibility to check wether or not this setting is active?

**Comment by ervee** [comment]
I think your best bet at this moment it to add the word debug just after your error log path, so
```
error_log   /var/log/nginx/wdomain.tld_error.log debug;
```
Then reload nginx, replicate the issue and check for clues in the error log. It will also show you which location was chosen so perhaps you find issues there.

Also, do you have any other sites configured in the sites-enabled folder? Perhaps you are hitting another site config as the one posted above does not have the "default" option at the listen stanza.

**Comment by greg0r** [comment]
**Ok I found it.** 
As always it is the person in front of the display. I put MB in php.ini as the unit. Which shows no error, not even in the phpinfo nor in the admin panel of rainloop. But if I change it from 1024MB to 1024M it finally works. I am so sorry to steal your time, but sometimes you try everything, knowing that it has to be a setup error but you can't find it. Thanks

**Comment by ervee** [comment]
No problem, glad you found it.
