### ISSUE TITLE
Redirect to another site when logging out

### ISSUE THREAD

**Issue by EntornoJT** [RainLoop/rainloop-webmail#1630]
Hello,

On my educational website, I have a Rainloop Webmail link (_domain.edu/webmail_) that takes us directly to the page where the user can log in and when we finish the session, returns to the login. How can we log out and redirect to another web address (_return to the educational website_)?

**Redirect to another website at the end of the session.**

**Comment by djdill** [comment]
@EntornoJT

This is already in the application however is in the experimental part, your settings will get over written if you edit the ?admin page and save:

Edit this file 
rainloop/data/_data_/_default_/configs/application.ini

Find the line custom_logout_link = ""
then add your website: custom_logout_link = "http://www.google.com"
   
If it doesn't apply you might need to clear your rainloop cache

delete this folder
 rainloop/data/_data_/_default_/cache

If this solves your problem please go ahead and close this case

**Comment by EntornoJT** [comment]
@djdill 

Thanks for answering and collaborating.

In my case, it was not necessary to clear the cache. We managed to solve the problem thanks to your help and now everything is going well.
