### ISSUE TITLE
Email not exist, can't send

### ISSUE THREAD

**Issue by ECWeb** [RainLoop/rainloop-webmail#1637]
**RainLoop version, browser, OS:**
1.11.3, Chrome, Windows

**Expected behavior and actual behavior:**
Should display error for non existent local email address.
Shows "Can't Send" only

**Steps to reproduce the problem:**
New Message
Type any non existent local mail address on To field.
Click send

**Comment by ervee** [comment]
RainLoop has no knowledge of local addresses. If I remember correctly you can set an option in application.ini to show a more verbose error though.

**Comment by ECWeb** [comment]
Found the cause of problem... but im sure that rainloop must have the capability to identify rcpt rejected address rather than "Can't send" only...

Fix:
added in main.cf in postfix
smtpd_reject_unlisted_recipient = no

will force to send emails to non existent address and postmaster will reply undelivered if mail doesnt exist..

**Comment by ervee** [comment]
If your mailserver accepts email from the Internet then this is really bad practice. Spammers will flood your server with spam (with the source address spoofed) and some poor people around the world would be flooded with NDR's.

**Comment by ECWeb** [comment]
yep.. its a really bad practice but we have appliance firewall and rspamd to block potential spammers for now.. im looking forward for rainloop to dig deep in local mail addresses(provided the correct settings).

**Comment by markkuit** [comment]
> If I remember correctly you can set an option in application.ini to show a more verbose error though.

@ervee I couldn't find such option - logging is enabled, but only written to file rather than having a more verbose output in the webmail interface. Could you point me in the right direction? I feel like this would be needed 'cause, when trying to send an email to a remote non-existing address, the "can't send" error message feels quite unhelpful.
