### ISSUE TITLE
Where ist the application.ini?

### ISSUE THREAD

**Issue by BoBBer446** [RainLoop/rainloop-webmail#1653]
hey there, im looking for the application.ini

here in desc i see 
https://www.rainloop.net/docs/configuration/

that the application.ini should be here:
`/var/www/rainloop/data/_data_/_default_/configs/application.ini`

but i downloaded the lastes.zip and there is no file like these. On my installation i cant find this file too because she isnt there.

i want to change the default password after installation with sed but how i can change it without file?

**Comment by ervee** [comment]
Did you at least login once in the amin panel? Perhaps it gets created on first use.

**Comment by BoBBer446** [comment]
ah okay now i see your constructor creates the ini file. thats not good for me. So i have to copy the file and give the installation script the file to edit 

thank you for response! :)

**Comment by ervee** [comment]
Hi, I'm not the developer of RainLoop, but you are welcome anyway! :)

**Comment by BoBBer446** [comment]
if you want to set custom (better random) username and password you can use my function:
https://github.com/shoujii/NeXt-Server/blob/master/script/rainloop.sh#L30

Install Rainloop
Make the config via pseudo touch the url maybe curl
Now you can replace "admin" and "12345" with your custom string or / and copy your custom application.ini

It is recommend that NO - Never any Script set passwords like 12345...do not. But im not the owner...
