### ISSUE TITLE
recapchta code not working

### ISSUE THREAD

**Issue by johanpeters** [RainLoop/rainloop-webmail#1683]
**RainLoop version, browser, OS:**
v1.11.3
**Expected behavior and actual behavior:**
Expected: after installation and configuration of the recapchta plugin. at login i have a working recapchta check.

Actual: after installation and configuration correct recapchta keys the frontend gives a error. sitecode.  
dutch: FOUT voor site-eigenaar: ongeldige sitesleutel
english: Error for site owner: invalide sitekey
if i us the key with a other recapchta plugin (joomla website) the code is okay.
**Steps to reproduce the problem:**

**Logs or screenshots:**
![fireshot capture 064 - rainloop webmail - https___itics nl_rainloop_](https://user-images.githubusercontent.com/1411354/39375007-19672baa-4a4d-11e8-9938-2fb72ef60f6f.png)

**Comment by johanpeters** [comment]
issue was fixed...

**Comment by Alwiz79** [comment]
@johanpeters I am currently facing the same issue.
Can you explain how the issue was fixed?
was it really a bug, or wrong usage of yours? Because then I assume I'm doing it the same wrong way :-)
