### ISSUE TITLE
Login form does not load in IE on RainLoop ver 1.12.0

### ISSUE THREAD

**Issue by RinTinCan** [RainLoop/rainloop-webmail#1692]
**RainLoop version, browser, OS:**  RainLoop 1.12.0; IE 11.1029.15063.0, 11.0.9600.17801 under both Windows 10 and Windows 7.

**Expected behavior and actual behavior:**  expect login form to display on page load; with RainLoop 1.12.0, login form fails to display in IE.  This is new behaviour for 1.12.0; login form loaded as expected in RainLoop 1.11.3.

**Steps to reproduce the problem:**  open IE 11 to RainLoop 1.12.0 installation

**Notes:**
* Login form loads for Firefox on the same installation where IE fails
* No problems with IE in previous release 1.11.3

**Logs or screenshots:**
![screenshot-2252](https://user-images.githubusercontent.com/6860356/40108189-23ca361a-58f2-11e8-8ccf-767b06668b6e.png)

**Comment by DonPIZI** [comment]
Hi, I've installed rainloop thru nextcloud apps and I have the same problem. I don't know where I must edit these files :/

**Comment by kuriot** [comment]
I get "An error occurred. Please refresh the page and try again" message on Internet Explorer 11.0.9600.19078. And I don't see any errors in logs. It works on any browser and platform except IE. I know the best solution but anyway I'd like to make it work in IE.

**Comment by RainLoop** [comment]
Should be fixed in the last release 1.12.1.
