### ISSUE TITLE
The following PHP extensions are not available in your PHP configuration

### ISSUE THREAD

**Issue by Ezerbeth** [RainLoop/rainloop-webmail#1717]
**RainLoop version, browser, OS:**
Latest github, Firefox 60.0.1 (64bit), FreeBSD 11.1

**Expected behavior and actual behavior:**
Expected: Not sure, first time I try to install this
Actual behavior:
> [302] The following PHP extensions are not available in your PHP configuration!
>     cURL
>     iconv
>     json
>     dom
>     Zlib

But the modules are all available and working fine using other software:
```
# php -i | egrep --color=auto -i "curl support|iconv support|json support|dom/xml|zlib support"
cURL support => enabled
DOM/XML => enabled
DOM/XML API Version => 20031129
iconv support => enabled
json support => enabled
ZLib Support => enabled
```

Only 1 version of PHP is installed.

**Steps to reproduce the problem:**
Clone, access using browser.

**Logs or screenshots:**
None

**Comment by solkmaaker** [comment]
You are showing browser error and CLI php output.
CLI php and apache php module (or php-fpm) configurations may be different.
Create phpinfo() page and see there, if modules in question are enabled or not.

**Comment by appledeej** [comment]
I'm having the same problem, how may i fix this?

**Comment by Ezerbeth** [comment]
In my case, it was misconfigured / broken PHP installation. I reinstalled it and it solved the issue.
