### ISSUE TITLE
is version compliant with php7.2 being developed?

### ISSUE THREAD

**Issue by johnwayne4d** [RainLoop/rainloop-webmail#1727]
**RainLoop version, browser, OS:**
latest version
**Expected behavior and actual behavior:**
is version compliant with php7.2 being developed?
**Steps to reproduce the problem:**
limited published info on continued development
**Logs or screenshots:**

**Comment by Sm0ke0ut** [comment]
I'm running Rainloop (v1.12.0) with PHP 7.2.5 without any problems. So it seems to be compatible, did you ran into any issues?
