### ISSUE TITLE
GPG Enhancement

### ISSUE THREAD

**Issue by rsertelon** [RainLoop/rainloop-webmail#175]
Hi,

I've finally had the chance to upgrade Rainloop, and first, I would like to thank you for adding GPG support, this is just awesome (plus 2 step verification...)

I was wondering if it could be possible to have openpgp encryption/signing by default if the recipients have keys imported in Rainloop.

It would be nice for people like me who always want to encrypt and sign their emails whenever their recipients will be able to use that information.

Thanks again for this project, it's really awesome :)

**Comment by 0xE02B7** [comment]
nice close tho
