### ISSUE TITLE
favicon not displaying when using https

### ISSUE THREAD

**Issue by jvimolch** [RainLoop/rainloop-webmail#1752]
**RainLoop version, browser, OS:**
1.12.0, All browsers, Windows 10

**Expected behavior and actual behavior:**
Favicon should be displayed in browser tab, displays correctly when using non-SSL http but not when using Https

**Steps to reproduce the problem:**
Change URL to https

**Logs or screenshots:**

**Comment by MrChenaho** [comment]
In your application.ini you should set force HTTPS to true. 
public_html/data/_data_/_default_/configs/application.ini

Default: force_https = Off
Try: force_https = On

Please let us know if this works!

**Comment by jvimolch** [comment]
Unfortunately that did not fix the issue.  I can also view the icon using a direct https URL.

**Comment by MrChenaho** [comment]
Okay, and when you visit your site using HTTPS, does it show the green HTTPS or a GRAY/RED HTTPS? It may be because the script is trying to load a non secure image. If you use Google a chrome, press CTRL + J and attempt to load your site using HTTPS. Do you want to share your URL?

**Comment by jvimolch** [comment]
It does display a green https.

Here is my site... www.vimolchalao.com/mail

**Comment by jvimolch** [comment]
Ah ha!  That was the problem.  The URL had http instead of https in the admin panel.  Thanks for the help.

**Comment by MrChenaho** [comment]
We all make those kinds of mistakes, glad it's all sorted now :) 💯
