### ISSUE TITLE
[Q] Pass parameters on showScreenPopup

### ISSUE THREAD

**Issue by Med-All** [RainLoop/rainloop-webmail#1756]
I'm trying to pass parameters from one viewmodel to another as

`kn.showScreenPopup(__webpack_require__(/*! View/Popup/MyPopup */ 172),[sTest]);`

and then to get it append on `onBeforeShow` but then code will go over

`Object[sMethodName].apply(oObject, Utils.isArray(aParameters) ? aParameters : []);`

and I don't see `sTest` appended to `oObject`

What am I doing wrong?

**Comment by Med-All** [comment]
Never mind - figured on my own.

**Comment by LTIOfficial** [comment]
Consider sharing here what you've worked out, so that others who may be in a similar situation and find this issue in a web search can make use of your example.    ;)

**Comment by Med-All** [comment]
Well, it came up that `aParamteres` will be appended to the `oObject` in case of `onBeforeShow` or `onShow` methods but it will be appended as exact name of declared parameter in the array.

In my case it was something like code below to get parameter appended properly in `MyPopup` viewmodel:

```
MyPopupView.prototype.onBeforeShow = function(sTest)
{
  var sMyTest = sTest;
}
```
