### ISSUE TITLE
Is it possible to have rainloop on one server (cPanel), and my actual mail service on another host?

### ISSUE THREAD

**Issue by Katylar** [RainLoop/rainloop-webmail#1775]
And if yes, how do I go about it?

**RainLoop 1.12.1**

Also, I'm having a "chown: invalid user: `www-data:www-data'" whenever I try that step.

I'm using a cPanel Shared-Hosting from HawkHost.

**Comment by Katylar** [comment]
Found it.

**Comment by yodog** [comment]
it would be of great help to the rest of us if you could post details about your discovery
