### ISSUE TITLE
Cannot Send Email, only receive "Can't send message".

### ISSUE THREAD

**Issue by ArchangelXv1** [RainLoop/rainloop-webmail#1789]
**RainLoop 1.12.0, Chrome, Win10/Mac High Sierra:**

We recently started using Rainloop for our email. Sometimes we cannot send email. They hit send and it doesn’t function…just pops up a message in red saying “Can’t send message”.

I’ve attached the logfile. Thank you.

[log-2018-10-17.txt](https://github.com/RainLoop/rainloop-webmail/files/2489100/log-2018-10-17.txt)

**Comment by ArchangelXv1** [comment]
Hallo?

**Comment by ervee** [comment]
The only thing I see in the logs is this:
```
[19:55:51.887][095d85b6] INFO[NOTICE]: exception 'RainLoop\Exceptions\ClientException' with message 'UnknownError[999]' in /home/paradise/public_html/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/ServiceActions.php:185
Stack trace:
#0 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
#1 /home/paradise/public_html/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
#2 /home/paradise/public_html/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#3 /home/paradise/public_html/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#4 /home/paradise/public_html/rainloop/rainloop/v/1.12.0/app/handle.php(94): RainLoop\Service::Handle()
#5 /home/paradise/public_html/rainloop/rainloop/v/1.12.0/include.php(228): include('/home/paradise/...')
#6 /home/paradise/public_html/rainloop/index.php(13): include('/home/paradise/...')
#7 {main}
[19:55:51.887][095d85b6] AJAX[DATA]: {"Action":"Unknown","Result":false,"ErrorCode":999,"ErrorMessage":"","ErrorMessageAdditional":"","Time":76}
[19:55:51.903][095d85b6] INFO[MEMORY]: Memory peak usage: 5.5MB
[19:55:51.903][095d85b6] INFO[TIME]: Time delta: 0.088840007782
```
No SMTP error so I think this is either a Webserver issue or you hit some kind of bug in RainLoop code. I'm no code developer so I can't comment on the code.

What is your OS, Webserver brand, version and config? And are there any errors in the Webserver log?

**Comment by ArchangelXv1** [comment]
Hey there! Thanks for responding. I believe we figured it out. I went digging on the GitHub support section and found someone who mentioned mod security.  We have a pretty strong setup, so I asked our server admin to take a look and apparently this resolved it. They opened it up for Rainloop and we haven’t had any issues yet. Thank you!

 

- Mike K.

**Comment by AuspeXeu** [comment]
@ArchangelXv1 can you close this issue since it's resolved :)

**Comment by ArchangelXv1** [comment]
Oh yes, didn't realize this was the one on the public forum! My bad!  Thank you!
