### ISSUE TITLE
Threaded view option is missing

### ISSUE THREAD

**Issue by bisherbas** [RainLoop/rainloop-webmail#1797]
**RainLoop version, browser, OS:**
1.12.1, Chrome, Windows 10

**Expected behavior and actual behavior:**
N/A

**Steps to reproduce the problem:**
N/A

**Logs or screenshots:**
N/A

I am sorry to post this question to here but I couldn't find any other place to ask.

Does RainLoop provide an option to view threaded messages like in Gmail? I cannot seem to find it if there is one. I'd like to group all messages belonging a given thread so that the messages list is not cluttered with separate lines.

**Comment by bisherbas** [comment]
Anybody? How can I enable threaded view?

**Comment by bisherbas** [comment]
It is Gmail IMAP. Shouldn't it support?

Use threads is missing in the Gener settings.

mail_use_threads = On in application.ini

**Comment by megadr01d** [comment]
OK, the dev confirms Gmail doesn't support IMAP threading. It uses its own threading implementation only in the web UI.

https://github.com/RainLoop/rainloop-webmail/issues/907#issuecomment-162604941
https://github.com/RainLoop/rainloop-webmail/issues/46#issuecomment-31737792
https://github.com/RainLoop/rainloop-webmail/issues/46#issuecomment-31739919

**Comment by lhorace** [comment]
Hello there,

New to Rainloop here, planning to experiment with Rainloop in conjunction with Roundcube. Surprisingly, most clients I've used, irregardless of E-Mail provider, had support for threaded messages. I was particularly interested in this issue. Sadly, after looking over linked comments, for a modern WebMail client, apparently this feature has a dependency on the IMAP server supporting IMAP Threading. I would have to look over Dovecot documentation to determine if such support exists.
