### ISSUE TITLE
RainLoop cannot be used with IMAP/SMTP account that isn't either mail address or local part of it.

### ISSUE THREAD

**Issue by yasuhirokimura** [RainLoop/rainloop-webmail#1815]
RainLoop assumes that IMAP/SMTP account name is either mail address or local part of it. But IMAP/SMTP specifications don't provide such restriction between account name and mail address. And actually there are mail service providers that acount name is different from mail address and its local part. And RainLoop cannot be used with such mail services.

**Comment by deMattin** [comment]
It can be used and I'm actually doing it ...
You have to use the plugin "custom-login-mapping" and there you are able to assign a mail-address to a login-name (mail@address.com:AccountName)

**Comment by yasuhirokimura** [comment]
Hi,

I tried `custom-login-mapping` plugin and it's just what I'm looking for.
Thank you for information.
