### ISSUE TITLE
Mails are sorted randomly in the message list (IMAP SORT)

### ISSUE THREAD

**Issue by hostingnuggets** [RainLoop/rainloop-webmail#1817]
**RainLoop version, browser, OS:**
RainLoop: v1.12.1
Browser: Firefox 60.4.0esr
OS: Debian 9.6

**Expected behavior and actual behavior:**
Mails are not sorted correctly by date in the list of messages. The order looks pretty much random. The mails should be correctly sorted by date with the newest at the top of the list and the oldest at the bottom of the list.

**Steps to reproduce the problem:**
Simply login and check any folders, all mails will seem to be sorted randomly.

**Logs or screenshots:**
`[19:42:51.031][e761b74c] IMAP[DATA]: > TAG7 UID SORT (REVERSE ARRIVAL) US-ASCII UNDELETED\r\n`

Now I managed to fix the sorting order by changing the IMAP SORT criteria from `REVERSE ARRIVAL` to `REVERSE DATE` on  line 1867 in the `app/libraries/MailSo/Mail/MailClient.php` file as such:

```
$this->oImapClient->MessageSimpleSort(array('REVERSE DATE'), $sSearchCriterias, true) :
```

and it works... So I was wondering why is this code using `REVERSE ARRIVAL` and not `REVERSE DATE` instead?

My IMAP server is running Dovecot 2.2.36.

**Comment by droop91** [comment]
I had the same problem with outlook.com IMAP server and you solution solved it.
thanks a lot

**Comment by hostingnuggets** [comment]
@droop91 you're welcome, glad my fix could help. I hope this can also be fixed in the next release of RainLoop.

**Comment by alhimik45** [comment]
So, what about fix?

**Comment by 532910** [comment]
Just installed, and have the same issue. It's totally unusable due to this issue!

**Comment by paulcalabro** [comment]
Weird, I don't see this behavior with Gmail. Though, if I move a message from one folder to another, the message floats to the top...even if it's older than messages below it.

**Comment by paulcalabro** [comment]
I think the sort behavior should mirror that of the thread algorithms described here:

"Internet Message Access Protocol - SORT and THREAD Extensions"
https://tools.ietf.org/html/rfc5256.html      

Threading defaults to sorting by _date_.

> ARRIVAL
>          Internal date and time of the message.  This differs from the
>          ON criteria in SEARCH, which uses just the internal date.
> ...
>       DATE
>          Sent date and time, as described in section 2.2.

In addition, the time sensitiveness of an email is mostly a function of the _arrival_ time not the _internal_ date and time of a message.

>   (4) Sort the messages under the root (top-level siblings only)
>              by sent date as described in section 2.2.  In the case of a
>              dummy message, sort its children by sent date and then use
>              the first child for the top-level sort.
