### ISSUE TITLE
Any plans to update app in owncloud marketplace to support latest 10.1 version?

### ISSUE THREAD

**Issue by motorious1** [RainLoop/rainloop-webmail#1836]
Updated to latest release of owncloud (10.1.0) and had to disable the rainloop app.  Just curious if there is plans to update to support the latest release of owncloud or if there is a known workaround to "trick" it into believing it is 10.0.10...

Rainloop 5.1.0

sudo -u www-data php occ app:enable rainloop

```
In app.php line 1178:
                                                                                                        
  App "RainLoop" cannot be installed because the following dependencies are not fulfilled: ownCloud 10.0 or lower is required.                                                                              

```                                                                                                        

``
TIA

**Comment by plastikschnitzer** [comment]
You can install the app by changing the max-version located in /rainloop/appinfo/info.xml to 10.1 instead of 10.0. 
Then upload the app to your ownCloud app directory, enable the app and happy mailing! So far no problems detected on my side.

**Comment by motorious1** [comment]
That solved it for me.  I went ahead and updated the info.xml file before performing the upgrade b/c I didn't want to reinstall the app (lazy admin I know) Cheers!
