### ISSUE TITLE
Converged view of different identities/imap accounts

### ISSUE THREAD

**Issue by FleischKarussel** [RainLoop/rainloop-webmail#184]
Hello people,

maybe this is just from my own laziness but I got three different imap accounts (A,B,C) and don't want to switch every now and then between the current view of account A to account B and C to manually check if there have any new mails arrived without my knowledge or any notification.
Is there a possibility to somehow build an optional layer ontop (or something like what AUFS is for filesystems. :) ) to converge the imap inboxes to one big inbox view, they still can be seperated in the background.
I know it sounds easier than it is, but maybe this is possible.

Thank you very much for your current great product!

greetings
FleischKarussel

**Comment by emresaracoglu** [comment]
I think they do not want to do this.. 2014 -> 2018

**Comment by Vincent14** [comment]
There is a duplicate closed here #568 and another more active here #690 I guess it's more useful to talk in the last one, #690
