### ISSUE TITLE
Why there is no new release even beta?

### ISSUE THREAD

**Issue by habnai** [RainLoop/rainloop-webmail#1842]
I want use rainloop as my first webmail it's great project but I see it's freezing no new release no new patch even issue no clear answer from dev team will be future for this project?

**Comment by warnerbryce** [comment]
Last commit 4 of Feb. more than a month, last stable version last year... 
It's not very healthy as a signal, Can the team break this silence ?

**Comment by lhorace** [comment]
You might have better luck getting a standard license ? There isn't much communication from their twitter https://twitter.com/RainLoopTeam or you could reach out to their support team via their E-Mail?

Alternatively, you code fork the repo and maintain it yourself? Doesn't seem they are even accepting any third-party pull-request either. Or even roadmap. Seems sporadic fixes here and there.

**Comment by habnai** [comment]
You have right guys no even simple action from dev team,I think support is only for paid license so good luck for them,for me this project I dead.
