### ISSUE TITLE
Sending emails failed, authentication error

### ISSUE THREAD

**Issue by Windows10User2k19** [RainLoop/rainloop-webmail#1865]
**RainLoop version, browser, OS:**
Rainloop version: 1.12.1
Host OS: Raspbian Stretch (Based on Debian Stretch)
Email software: Postfix and Dovecot
Client OS: Windows 10 Pro 1809 64Bit
Client Browser: Brave (Based on Chromium 73)  
**Expected behavior and actual behavior:**
Expected pressing Send would send the email
Actual:
Trying to send an email results in authentication failed.
**Steps to reproduce the problem:**
Install Rainloop with Postfix and Dovecot using the guide https://samhobbs.co.uk/raspberry-pi-email-server but replacing Squirrelmail for rainloop
**Logs or screenshots:**
![image](https://user-images.githubusercontent.com/47116600/55996336-0423d480-5caf-11e9-8f3f-653e711dcc4d.png)
![image](https://user-images.githubusercontent.com/47116600/55996370-1867d180-5caf-11e9-84ec-028486670c2d.png)

I'm not sure where to look for logs so I haven't posted them here though I'm happy to do so if someone tells me where they are.

**Comment by lhorace** [comment]
Hey there, Rainloop authenticates against your mail servers, so the error is certainly coming from you SMTP server. Did you properly setup authentication for your SMTP mail gateway?

Cheers.

P.S. FYI, if source ip is 127.0.0.1, you could bypass authentication by whitelist it.

**Comment by Windows10User2k19** [comment]
> Hey there, Rainloop authenticates against your mail servers, so the error is certainly coming from you SMTP server. Did you properly setup authentication for your SMTP mail gateway?
> 
> Cheers.
> 
> P.S. FYI, if source ip is 127.0.0.1, you could bypass authentication by whitelist it.

I'm not too sure how to do that as it's my first time using Postfix/Dovecot

**Comment by lhorace** [comment]
I don't mind helping, but why you want this? That way, I'm motivated enough to help

**Comment by SgtBatten** [comment]
Does it pass the test function fully?

My guess (from me with no experience with this stuff) is that your mixed use of short logins is the issue. Would it not be most common for both to be either short or long?

**Comment by Windows10User2k19** [comment]
> Does it pass the test function fully?
> 
> My guess (from me with no experience with this stuff) is that your mixed use of short logins is the issue. Would it not be most common for both to be either short or long?

I can login and receive emails just fine, it's just sending

**Comment by Windows10User2k19** [comment]
> I don't mind helping, but why you want this? That way, I'm motivated enough to help

Sorry about the late reply, I've been busy, I'm mostly doing this as a hobby as I'm a technology nerd and I was to experiment with web/email servers on Linux.

**Comment by lhorace** [comment]
@Windows10User2k19 What does the logs say when you try to send mail from Rainloop? Your postfix logs, e.g. /var/log/mail.log. Use gist.github.com for pastebin. `swaks` is your friend, use it to test you SMTP server authentication.

https://linux.die.net/man/1/swaks

> short logins

My suspicion, you mean `username` vs `username@domain.com`.

**Comment by Windows10User2k19** [comment]
> @Windows10User2k19 What does the logs say when you try to send mail from Rainloop? Your postfix logs, e.g. /var/log/mail.log. Use gist.github.com for pastebin. `swaks` is your friend, use it to test you SMTP server authentication.
> 
> https://linux.die.net/man/1/swaks
> 
> > short logins
> 
> My suspicion, you mean `username` vs `username@domain.com`.

Log file from Postfix:
<script src="https://gist.github.com/Windows10User2k19/b91be39d52a4b6b5218fdcea50b196a1.js"></script>

**Comment by Windows10User2k19** [comment]
> Does it pass the test function fully?
> 
> My guess (from me with no experience with this stuff) is that your mixed use of short logins is the issue. Would it not be most common for both to be either short or long?

I can only login using the long login
(user@domain.com and not just user)

**Comment by lhorace** [comment]
Nothing useful in the logs, have you test authentication with `swaks` against postfix?

**Comment by Windows10User2k19** [comment]
`pi@raspberrypi2:~ $ swaks --to user1@******.com --from user2@******.com --server ******.com
=== Trying ******.com:25...
=== Connected to ******.com.
<-  220 raspberrypi3plus.home ESMTP Postfix (Raspbian)
 -> EHLO raspberrypi2
<-  250-raspberrypi3plus.home
<-  250-PIPELINING
<-  250-SIZE 10240000
<-  250-VRFY
<-  250-ETRN
<-  250-STARTTLS
<-  250-ENHANCEDSTATUSCODES
<-  250-8BITMIME
<-  250-DSN
<-  250 SMTPUTF8
 -> MAIL FROM:<user2@******.com>
<-  250 2.1.0 Ok
 -> RCPT TO:<user1@******.com>
<** 504 5.5.2 <raspberrypi2>: Helo command rejected: need fully-qualified hostname
 -> QUIT
<-  221 2.0.0 Bye
=== Connection closed with remote host.
pi@raspberrypi2:~ $ pi@raspberrypi2:~ $ swaks --to user1@******.com --from user2@******.com --server ******.com
=== Trying ******.com:25...
=== Connected to ******.com.
<-  220 raspberrypi3plus.home ESMTP Postfix (Raspbian)
 -> EHLO raspberrypi2
<-  250-raspberrypi3plus.home
<-  250-PIPELINING
<-  250-SIZE 10240000
<-  250-VRFY
<-  250-ETRN
<-  250-STARTTLS
<-  250-ENHANCEDSTATUSCODES
<-  250-8BITMIME
<-  250-DSN
<-  250 SMTPUTF8
 -> MAIL FROM:<user2@******.com>
<-  250 2.1.0 Ok
 -> RCPT TO:<user1@******.com>
<** 504 5.5.2 <raspberrypi2>: Helo command rejected: need fully-qualified hostname
 -> QUIT
<-  221 2.0.0 Bye
=== Connection closed with remote host.
`

**Comment by Windows10User2k19** [comment]
> Nothing useful in the logs, have you test authentication with `swaks` against postfix?

https://gist.github.com/Windows10User2k19/b26b03a7ec2cc35da1305c837d9d7c3a

**Comment by Windows10User2k19** [comment]
Issue seemed to have been resolved with this:
https://github.com/RainLoop/rainloop-webmail/issues/228#issuecomment-70651045

Issue CLOSED
