### ISSUE TITLE
Rainloop not showing logon screen

### ISSUE THREAD

**Issue by Vista2003** [RainLoop/rainloop-webmail#1913]
**RainLoop version, browser, OS:**
Rainloop 1.13.0
Browser: Brave and Firefox
OS: Client, Windows 10 64Bit Server, Rasbian (Based on Debian 9)
**Expected behavior and actual behavior:**
Expected: Logon to show
Actual behavior: just shows background
**Steps to reproduce the problem:**
Installed NGINX
Installed PHP
Used https://nginxconfig.io/ to generate config for NGINX 
Ran config
Tried to login to Rainloop
**Logs or screenshots:**
![image](https://user-images.githubusercontent.com/55105920/64556094-a87d7600-d336-11e9-8db0-106703743ba5.png)

**Comment by solkmaaker** [comment]
> Used https://nginxconfig.io/ to generate config for NGINX
Might be Content-Security-Policy header problem.
https://github.com/RainLoop/rainloop-webmail/issues/1172
