### ISSUE TITLE
Owncloud contacts and duplicate entries in "Contacts"

### ISSUE THREAD

**Issue by fersingb** [RainLoop/rainloop-webmail#192]
I configured rainloop to sync my contacts with Owncloud and now all my contacts have duplicate entries in "Contacts", some of my contacts even show 3 times.

Everything looks good on Owncloud and on my phone

**Comment by maddylliieeee** [comment]
I had the same, but it showed up that this was caused by malformed OC contacts I had imported from Google into my OC. They somehow had their name twice in OC and therefore were duplicates in RLP.

**Comment by adueck** [comment]
I am having this same issue now with fruux. Is this still being addressed.
