### ISSUE TITLE
PGP - lock icon not appear in incoming emails

### ISSUE THREAD

**Issue by sbrodriguez** [RainLoop/rainloop-webmail#1921]
Hello

I have a problem in incoming emails encrypted by PGP public key.

If I send an email from my domain to a Gmail account encrypted with de Gmail public key I haven't any problem. In Gmail I decrypt the message properly.

But if I send an email from Gmail to my one of my domains, configured in Rainloop, the lock icon doesn't appear in the Rainloop webmail. The email is encrypted with my domain public key.

![image](https://user-images.githubusercontent.com/11030243/65593051-0b564a80-df90-11e9-9b24-ee7cf19f7145.png)

However, if I send an email from one of my domains, configured in Rainloop, to another email from other of my domains, also configured in Rainloop, I haven't any problem:

![image](https://user-images.githubusercontent.com/11030243/65593236-57a18a80-df90-11e9-9fc0-079fac87d78a.png)

Rainloop version 1.13.0 in Debian 9.
The logs are exactly the same in all cases.

What do you thing it could be happend?
Regards!!!!

**Comment by solkmaaker** [comment]
This is not a rainloop issue.
Just because gmail acceps faulty format, it does not mean any other mail client should do so.
https://tools.ietf.org/html/rfc4880#section-6.2
After armor headers, there should be a blank line.
More specifically: "A blank (zero-length, or containing only whitespace) line"
In your case, it is missing.

**Comment by sbrodriguez** [comment]
Ok, solkmaaker.
Thanks for your answer.
I was trying with Thunderbird and Enigmail plugin, and everything works fine, but when I send an email encrypted with attachments I can see the body content but not the attachments.
I will open a new topic with this issue. This one is solved with your answer.

Regards
