### ISSUE TITLE
"Can't save message" displayed for a message with specific characters

### ISSUE THREAD

**Issue by junichim** [RainLoop/rainloop-webmail#1939]
I use Rainloop software on ubuntu 18.04 (on aws ec2).
I encountered a problem when I would save a message.

When I wrote an email message and wanted to save this, so I push "save" button. But this button was turned to red and displayed "Can't save message".

Until now I already could save new messages (, of course I send a these messages).

I checked my message and specified at least 5 characters,
<pre>
> (1)
</pre>
to reproduce this problem.

Please teach me why Rainloop can't save a message with specific characters ?

**RainLoop version, browser, OS:**

Rainloop 1.13.0
Chrome  78.0.3904.87
Windows 10 Pro 1903, 64bit, 

**Expected behavior and actual behavior:**

success to save a message

**Steps to reproduce the problem:**

1. login rainloop
2. push "New message" green button at left-upper corner
3. enter message body "> (1)"
4. push "save" button on a editor dialog
5. this dialog shows "Can't save message"

**Logs or screenshots:**
![rainloop_save_error](https://user-images.githubusercontent.com/11746767/68277343-55b00880-00b2-11ea-9032-b5587ab651f3.png)

**Comment by mold-resistant** [comment]
I can't reproduce, I followed your steps and it saved fine for me.

**Comment by junichim** [comment]
Sorry !
This is my mistake.

Now, I checked this issue and I can't reproduce too.
A while ago, I changed WAF (mod_security2) settings for apache2 on rainloop's server.

For checking WAF influence, when I restore WAF settings and I can reproduce this.

So maybe I guess WAF cause this situation.
Not Rainloop's issue.

I'm very sorry.
