### ISSUE TITLE
Support Outbox folder

### ISSUE THREAD

**Issue by megadr01d** [RainLoop/rainloop-webmail#1941]
Feature request. When trying to send an email locally, and it fails for some reason, Apple Mail has an option to try again later, where it saves the message in the "Outbox" folder.

Then, when launching Mail later on, it sees if there's any pending messages there and, if there's no more SMTP errors, it automatically sends the messages.

If I log in Rainloop later on, instead, that folder is not present, so it can't send the pending messages automatically.

**Comment by Philippe34** [comment]
Hi @megadr01d 
Do you want that Rainloop does the same thing that Mail does when a message can not be sent ?

Or do you want to see the "Outbox" folder with Rainloop ? If this folder is local in Mail, it is normal that Rainloop can no show this folder. Rainloop can only display the folders stored in the imap server.
Rainloop can show/hide folders. So you have the check this in the Settings > Folders

**Comment by megadr01d** [comment]
Thanks for the reply, @Philippe34.

I wanted Rainloop to just see the "Outbox" folder, not implement the same thing that Mail does.

However, you made me realize that the "Outbox" folder might be a local folder created by Mail, so it's normal that it doesn't show up in Rainloop. I thought the "Outbox" folder was a default IMAP folder that was only used when needed.
