### ISSUE TITLE
Auth error when I try to send letter

### ISSUE THREAD

**Issue by TimurC1** [RainLoop/rainloop-webmail#1942]
Hello! I have a problem. I host RainLoop client on CloudLinux server.
All is good, but when I try to send mail error appears: "Auth error".
After that I disabled auth in settings.
I tried to send mail second time, and error appears: "Can't send letter".

**Comment by vickersxu** [comment]
me too

**Comment by TimurC1** [comment]
All is ok at moment, but problem is in mail server. Install only stable mail server.
