### ISSUE TITLE
No signature in mailto links

### ISSUE THREAD

**Issue by c-burrows** [RainLoop/rainloop-webmail#1953]
**RainLoop version, browser, OS:**
Community edition v1.13.0
Client Browser: Firefox 71.0 on Debian 11 (Bullseye)
Host OS: Debian 10 (Buster)

**Expected behavior and actual behavior:**
Expected behaviour:
I expect my signature to be included in the body of the compose new email box when I click on another website's mailto link.

Actual behaviour:
When I click on another website's mailto link, the body of the compose new email box is empty and without my signature.

**Steps to reproduce the problem:**
Configure a signature in Rainloop, click on a mailto link and open it with Rainloop.

**Other information:**
In most countries, including the United Kingdom, it is a legal requirement to include certain information when sending an email on behalf of a company/organisation you work for, such as: company registration number, company registered office address, etc. and email signatures are a necessity for this reason.

**Comment by kaystrobach** [comment]
can totally confirm this - this behaviour is similar to MS Outlook, but totally unexpected for the user
