### ISSUE TITLE
Rainloop 5.2 & Owncloud 10.2 - Class ‘OCP\Config’ not found

### ISSUE THREAD

**Issue by albansch** [RainLoop/rainloop-webmail#1960]
Rainloop 5.2, CentOS 7, Owncloud 10.2

As announced by Owncloud, some deprecated calls have been removed in 10.2.
https://github.com/owncloud/core/pull/34927
Such as the OCP\Config, which worked until Owncloud 10.1.1.

Error log will show the following:
`{“reqId”:“gYAVuoJgNWtHeq00BvnZ”,“level”:3,“time”:“2020-01-05T20:31:43+00:00”,“remoteAddr”:“IP-address”,“user”:“username”,“app”:“index”,“method”:“GET”,“url”:"/index.php",“message”:“Exception: {“Exception”:“Error”,“Message”:“Class ‘OCP\\Config’ not found”,“Code”:0,“Trace”:”#0 \/var\/www\/owncloud\/lib\/private\/legacy\/app.php(239): require_once()\n#1 \/var\/www\/owncloud\/lib\/private\/legacy\/app.php(190): OC_App::requireAppFile(‘rainloop’)\n#2 \/var\/www\/owncloud\/lib\/private\/legacy\/app.php(124): OC_App::loadApp(‘rainloop’)\n#3 \/var\/www\/owncloud\/lib\/base.php(896): OC_App::loadApps()\n#4 \/var\/www\/owncloud\/index.php(54): OC::handleRequest()\n#5 {main}",“File”:"\/var\/www\/owncloud\/apps\/rainloop\/appinfo\/app.php",“Line”:16}"}
{“reqId”:“H110XhypsoT2q3Wnl7fs”,“level”:3,“time”:“2020-01-05T20:31:44+00:00”,“remoteAddr”:“IP-address”,“user”:“username”,“app”:“PHP”,“method”:“GET”,“url”:"/ocs/v2.php/apps/notifications/api/v1/notifications?format=json",“message”:“Error: Class ‘OCP\Config’ not found at /var/www/owncloud/apps/rainloop/appinfo/app.php#16”}`

I can see a way of replacing those calls here (as an example):
https://codecov.io/gh/owncloud/core/pull/34927/diff?src=pr&el=tree#diff-YXBwcy9maWxlc190cmFzaGJpbi9saWIvRXhwaXJhdGlvbi5waHA=

Any plan to implement this update in next version?

**Comment by RaZer0r** [comment]
Yes please.

Aparently owncloud removed the OCP\Config (which has been deprecated since owncloud 8) from their codebase.

**Comment by plastikschnitzer** [comment]
I tried with ownCloud 10.3 and rainloop 5.3, issue still exists. So I guess rainloop is not usable in ownCloud versions higher than 10.1.1, right?
Any idea how to fix this?

**Comment by plastikschnitzer** [comment]
OK I checked again: There is a fix available https://github.com/RainLoop/rainloop-webmail/commit/796183d40d6ac9dfe488c57d8b127720a61d310
I applied the fix and its working with ownCloud 10.3.2! I did not check with 10.4.1 (yet). So hopefully this PR makes it to the next Rainloop app release.

**Comment by albansch** [comment]
> OK I checked again: There is a fix available [796183d](https://github.com/RainLoop/rainloop-webmail/commit/796183d40d6ac9dfe488c57d8b127720a61d310)
> I applied the fix and its working with ownCloud 10.3.2! I did not check with 10.4.1 (yet). So hopefully this PR makes it to the next Rainloop app release.
> 
> EDIT: Its working with ownCloud 10.4.1!

@plastikschnitzer great news, could you please let me know which source you took for the owncloud rainloop app (url)? and then you simply applied the mentioned fix?
As I just tried to download latest version of rainloop-app from git, and use this in the apps folder of owncloud, but it completely broke it on 10.1, had to revert back.

**Comment by plastikschnitzer** [comment]
@albansch sure! I downloaded this release: https://github.com/RainLoop/rainloop-webmail/releases/download/v1.14.0/rainloop-owncloud-app-5.3.0.zip
And I applied https://github.com/RainLoop/rainloop-webmail/commit/796183d40d6ac9dfe488c57d8b127720a61d310 to it. This is the only patch I applied to it, as you can see there are a few more available (https://github.com/RainLoop/rainloop-webmail/compare/v1.14.0...master), but I ignored them all.

As I said, I only tested it on 10.3.2 and 10.4.1, not on older versions, but I will do so soon (maybe in 2 weeks).

I will also test on 10.5.0 as soon as its released (its in beta test at the monent).

As you can see here https://github.com/RainLoop/rainloop-webmail/pull/1987 the fix was already merged to the rainloop master repo, so it will be included in the next Rainloop release.

**Comment by albansch** [comment]
@plastikschnitzer it works all the way from 10.1.1, I have tested. Thx again for sharing this, it's great to have upgraded to 10.4.1 and have rainloop working perfectly.
