### ISSUE TITLE
Can't receive email from others except localhost

### ISSUE THREAD

**Issue by rafalohaki** [RainLoop/rainloop-webmail#1973]
**RainLoop version, browser, OS:**
1.14.0
**Expected behavior and actual behavior:**
I want to receive email from others server.(me sending email from gmail and receive on my server)
When i sent email from root it actually receive email but when i sent email from gmail it show nothing.
**Steps to reproduce the problem:**

**Logs or screenshots:**

**Comment by rafalohaki** [comment]
anyone can help me? its would be pleasant

**Comment by LeoBoudet** [comment]
I's a bit difficult to help you with so few details. The fact that you don't receive emails from outside your server can have multiple reasons and it's likely that Rainloop is not the cause. You can take a look at the ports, firewall, ipv4/ipv6 issues, dns, etc. The most common misconfiguration is in the dns settings. It can also be a problem of port forwarding.

**Comment by rafalohaki** [comment]
i deleted server. close
