### ISSUE TITLE
trouble sending with dismail.de account

### ISSUE THREAD

**Issue by klausmcm** [RainLoop/rainloop-webmail#1990]
**RainLoop version, browser, OS:** 1.12.1 (from debian 10 repo)

**Expected behavior and actual behavior:** Email should be sent through my *dismail.de* account.

**Steps to reproduce the problem:** See below screenshots for domain configuration.

**Logs or screenshots:**

When trying to send an email through my *dismail.de* account

![image](https://user-images.githubusercontent.com/14914359/79076236-67bf5400-7cad-11ea-8c5f-e976095b6970.png)

Domain config in admin account

![image](https://user-images.githubusercontent.com/14914359/79076253-86bde600-7cad-11ea-848a-880b21f1cc3c.png)

Parameters taken from https://dismail.de/info.html

![image](https://user-images.githubusercontent.com/14914359/79076262-9806f280-7cad-11ea-9876-7e9c5829b2d2.png)

**Comment by CountCypher** [comment]
I'm facing the same issue setting up the domain "dismail.de" (using Rainloop CE 1.14.0 on Debian 10). Same error message on the SMTP with STARTTLS settings, by the way:

![Bildschirmfoto von 2020-06-16 13-39-21](https://user-images.githubusercontent.com/54265000/84770204-6b39c900-afd7-11ea-9a8a-a77ada2e9b88.png)

**Comment by CountCypher** [comment]
I've found the issue in my case:
In the Nginx configuration I had the server name defined like this:

`server_name  _;`

This led to an error with the Dismail.de SMTP, as the Rainloop log shows:
```
[15:23:10.684][00ba5260] SMTP[NOTE]: Start connection to "ssl://smtp.dismail.de:2525"
[15:23:11.613][00ba5260] SMTP[NOTE]: Connected (success)
[15:23:11.655][00ba5260] SMTP[DATA]: < 220 dismail.de ESMTP OpenSMTPD\r\n
[15:23:11.655][00ba5260] SMTP[DATA]: > EHLO _\r\n
[15:23:11.664][00ba5260] SMTP[DATA]: < 501 5.5.4 Invalid command arguments: Invalid domain name\r\n
```
Stating the IP instead in the Nginx config solved the issue:

`server_name 192.168.178.28;`

**Comment by klausmcm** [comment]
@CountCypher 

That seems to have solved the issue. Thank you!
