### ISSUE TITLE
Can't connect to server issue

### ISSUE THREAD

**Issue by metalicworker** [RainLoop/rainloop-webmail#20]
I tried to install RainLoop on my webserver, but running into a connection issue...when I submit email login/password, it just says "Can't connect to server."  It's a gmail account, and I verified that gmail domain settings are configured properly in the admin panel.  I also verified that logging in works from the rainloop online demo.  It just doesn't work in my installation.

If it helps, you can test it out here:
https://authma.com/mail/

I left default admin/password and did NOT block directory listing with .htaccess in case that helps to debug the issue.  Let me know if there's anything I can do on my end.

Thanks!

**Comment by teytey** [comment]
I have the same problem if I want to send an e-mail it says "Can't connect to server" but there is no problem with reading my mails. Ports are also open

**Comment by megadr01d** [comment]
@teytey Try STARTTLS:587. One of my third party webmail services claim they support SSL:465 but I can only get a successful SMTP connection on port 587.

**Comment by teytey** [comment]
@megadr01d thank you but it doesn't work. I asked my host (1und1) once again and they said that the SMTP-Server are blocked from the server :(

**Comment by megadr01d** [comment]
Free hosting usually does that, it's just too limited on the resources they provide to users (No SSH, blocked ports, poor PHP module support, etc.). If you're paying for it, consider changing host provider.

**Comment by teytey** [comment]
@megadr01d well 1€ per year for students is ok (normally 7€ p. m.)   they said i can use sendmail instead of SMTP but I don't know how. The only one thread about sendmail is this one: 

https://github.com/RainLoop/rainloop-webmail/issues/209

**Comment by RainLoop** [comment]
![image](https://cloud.githubusercontent.com/assets/5530092/7811817/e9d9c068-03b5-11e5-86a6-ed54dc265a93.png)

**Comment by teytey** [comment]
@RainLoop thank you so much, it works! :+1:

**Comment by RainLoop** [comment]
Great

**Comment by Guideman** [comment]
I have the same problem I can't connect to secure certificate. I have attached the log file if anyone could help please........
[log-2016-04-18.txt](https://github.com/RainLoop/rainloop-webmail/files/223879/log-2016-04-18.txt)

**Comment by turok1997** [comment]
Had the same problem. Restarting of Dovecot helped me.
