### ISSUE TITLE
Question: Sending username/password

### ISSUE THREAD

**Issue by johnlewisdesign** [RainLoop/rainloop-webmail#200]
Hi guys 

Is it possible to send the username and password on the address bar? Reason being I want to try out autologin from my FileMaker Database via a web viewer so I can avoid the login screen.

Any help much appreciated - amazing app, thank you!

**Comment by aamirshakil** [comment]
It's not bypassing the login page. When i generate sso hash and redirect it to my server it is always redirecting me to the login page without bypassing it!
