### ISSUE TITLE
How to add email Accounts >?

### ISSUE THREAD

**Issue by daslicht** [RainLoop/rainloop-webmail#2011]
Hi,
the documentation do not show how to actually add an email account , or where do I find that info please?

**Comment by Philippe34** [comment]
Hi,
You have to go to the admin panel of where Rainloop is hosted, like:
https://webmail.example.com/rainloop/?admin

And you can add a domain in "Domains" by entering the imap and the smtp parameters of you server (host, port, security, sieve ...)
Rainloop acts as a client to the mails server.

This is documented here:
https://www.rainloop.net/docs/configuration/

**Comment by daslicht** [comment]
Yeah I found that documentation, but where to 
* password ?
* add email address ?
?
I only can add domains there ?

**Comment by BayInternetGroup** [comment]
Enable the e-mail domain you want to use along with the necessary imap/smtp configuration in the admin section. Use the imap credentials of a valid  pre-existing e-mail account on the domain you added in the admin section to login at the screen you attached to your post. Hope that helps :)

**Comment by BayInternetGroup** [comment]
You will need to create the user on your mail server. RainLoop is just an e-mail client.

**Comment by daslicht** [comment]
alrerdy treid that , I get anytime that the domain is not allowed

**Comment by daslicht** [comment]
> You will need to create the user on your mail server. RainLoop is just an e-mail client.

yeh I know that , outlook is also a emial client but i need to create a account ... that what i meant

**Comment by daslicht** [comment]
ok I got it now, the input is case sensitive
