### ISSUE TITLE
Rainloop - cannot login as user - authentication failed

### ISSUE THREAD

**Issue by conandoyle318** [RainLoop/rainloop-webmail#2014]
**RainLoop version: latest version 1.14.0 , browser: any browsers, OS: debian 10, x64 bits

**Steps to reproduce the problem:**
Login to webmail.annvashop.com with test user
**Logs or screenshots:**
![Screenshot_20200704-132907_Chrome](https://user-images.githubusercontent.com/67814287/86504338-8e97ad00-bdfa-11ea-88dc-b6ddd9c0441b.jpg)
![Screenshot_20200704-132814_Chrome](https://user-images.githubusercontent.com/67814287/86504339-90fa0700-bdfa-11ea-9691-e5ba38b699d3.jpg)

Any helps would be appreciated. 

Kind regards, 

Thanh

**Comment by BayInternetGroup** [comment]
From you screenshot I assume you are running your RainLoop install on the imap server for annvashop.com and that the user test@annvashop.com has already been created prior to your login attempt. Can you confirm if my assumption is correct? 

I also notice that your are using two different domains. Depending on your configuration RainLoop might consider these different installations as RainLoop does support multiple domains with multiple configurations. Could you try to login from the mail.annvashop.com domain you used to configure the imap settings and see if that resolves the issue.

**Comment by conandoyle318** [comment]
> From your screenshot I assume you are running your RainLoop install on the imap server for annvashop.com and that the user [test@annvashop.com](mailto:test@annvashop.com) has already been created prior to your login attempt. Can you confirm if my assumption is correct?
> 
> I also notice that your are using two different domains. Depending on your configuration RainLoop might consider these different installations as RainLoop does support multiple domains with multiple configurations. Could you try to login from the mail.annvashop.com domain you used to configure the imap settings and see if that resolves the issue.

Thanks very much for your reply.

Yes, I did created test account before and attempted to login but failed. I then created another test account but also failed to login.

I've just change the setting to mail.annvashop.com as you suggested
![Screenshot_20200704-143239_Chrome](https://user-images.githubusercontent.com/67814287/86505064-a293dc80-be03-11ea-8b5c-d577c54aef25.jpg)
But didn't seem to work.

Any other thoughts?
Kind regards, 

Thanh

**Comment by BayInternetGroup** [comment]
> Could you try to login from the mail.annvashop.com

I suggested you try and login from mail.annvashop.com not to change the settings.

**Comment by conandoyle318** [comment]
Hi @BayInternetGroup ,

I just tried again, still failed. 

Sorry about webmail and mail. They are host names.

I can share the mail logs if that helps.

Kind regards, 
Thanh

**Comment by BayInternetGroup** [comment]
The host names will make a difference if you have RainLoop configured for multi domain. 

Since using the same host name/domain name to login as you used to configure did not resolve the issue, I would like to ask if you were able to authenticate against your mail server using the test credentials with another e-mail client. 

Since you have access to your mail logs you may also want to see if there are any failed or passed authentication attempts for the test user coming from localhost, 127.0.0.1 or 45.32.188.60.

I can confirm that your server is responding on port 143 and 25.

**Comment by BayInternetGroup** [comment]
To help debug and save some time I added your imap/smtp configuration to a working RainLoop server I have at https://emailvalet.com/

You can try to log in there with your test credentials if you are unable to login at https://emailvalet.com/ then there is an issue with the login credentials you are using. If you are able to get it to work then we will need to debug your RainLoop installation further.

**Comment by conandoyle318** [comment]
Hi @BayInternetGroup,

Thansk very much for your help. But I cannot login at https://emailvalet.com/ , same error message at my site.

I'm sure the username and password I used is correct as I can send/receive test emails from the server (CLI).

Please see extracted logs below:
`[05:46:07.071][99a128ca] INFO[DATA]: [DATE:04.07.20][OFFSET:-00][RL:1.14.0][PHP:7.4.7][IP:165.225.114.205][PID:582][nginx/1.14.2][fpm-fcgi]
[05:46:07.071][99a128ca] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql,pgsql,sqlite][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3]
[05:46:07.071][99a128ca] REQUEST[NOTE]: [POST] https://mail.annvashop.com/?/Ajax/&q[]=/0/
[05:46:07.071][99a128ca] AJAX[NOTE]: Action: DoLogin
[05:46:07.072][99a128ca] POST[DATA]: {"Email":"test@annvashop.com","Login":"","Password":"*******","Language":"","AdditionalCode":"","AdditionalCodeSignMe":"0","SignMe":"0","Action":"Login","XToken":"e7cbb48a55cd6013b77faf90b1bac331"}
[05:46:07.072][99a128ca] PLUGIN[NOTE]: Hook: filter.login-credentials
[05:46:07.072][99a128ca] IMAP[NOTE]: Start connection to "tcp://127.0.0.1:143"
[05:46:07.074][99a128ca] IMAP[NOTE]: Connected (success)
[05:46:07.090][99a128ca] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN] Dovecot (Debian) ready.\r\n
[05:46:07.090][99a128ca] IMAP[DATA]: > TAG1 AUTHENTICATE PLAIN\r\n
[05:46:07.090][99a128ca] IMAP[DATA]: < + \r\n
[05:46:07.091][99a128ca] IMAP[SECURE]: > *******\r\n
[05:46:11.172][99a128ca] IMAP[DATA]: < TAG1 NO [AUTHENTICATIONFAILED] Authentication failed.\r\n
[05:46:11.173][99a128ca] IMAP[WARNING]: MailSo\Imap\Exceptions\NegativeResponseException: MailSo-Imap-Exceptions-NegativeResponseException (ImapClient.php ~ 1876) in /var/www/rainloop/rainloop/v/1.14.0/app/libraries/MailSo/Imap/ImapClient.php:1876`

Kind regards,
Thanh

**Comment by BayInternetGroup** [comment]
There seems to be an issue with the login credentials you are using. You mentioned that you can log in to your e-mail server from the command line interface. What command are you using to verify your e-mail login credentials from the CLI?

**Comment by conandoyle318** [comment]
Hi @BayInternetGroup,

I used nc localhost 143
`# nc localhost 143
# x1 LOGIN matie user_password
# x2 LIST "" "*"
# x3 SELECT Inbox
# x4 LOGOUT`

See below screenshot

![image](https://user-images.githubusercontent.com/67814287/86510823-abea6c80-be36-11ea-97f4-413a7ea0bbe6.png)

Kind regards,

Thanh

**Comment by BayInternetGroup** [comment]
Ok, that's what I suspected. Try to log in again at https://emailvalet.com/ again. If that works this time then you will need to go to the Admin URL on your installation and do the following:

Click Domains in the left pane then click on annvashop.com in the center pane and enable "Use short login" in both the IMAP and SMTP section then click update. 

That should solve the issue :-).

**Comment by conandoyle318** [comment]
Hi @BayInternetGroup,

Thank you very much. I can now login at https://emailvalet.com 
![Screenshot_20200705-081059_Chrome](https://user-images.githubusercontent.com/67814287/86521686-63af6680-be97-11ea-9bd9-f7a1f0c470fd.jpg)
 And changed settings on mail server, 

![Screenshot_20200705-081401_Chrome](https://user-images.githubusercontent.com/67814287/86521704-9a857c80-be97-11ea-819b-d818e201172b.jpg)
But it still failed

![Screenshot_20200705-081416_Chrome](https://user-images.githubusercontent.com/67814287/86521709-acffb600-be97-11ea-91b8-85730383dba7.jpg)

What else should I check?

Kind regards, 
Thanh

**Comment by BayInternetGroup** [comment]
On the screenshot you provided you have the username as "test". The username should be "test@annvashop.com".  Use the same credentials you tried at https://emailvalet.com when you log into your RainLoop installation.

**Comment by conandoyle318** [comment]
Hi @BayInternetGroup ,

I tried both test and test@annvashop.com, same result,  authentication failed. 
![Screenshot_20200705-111630_Chrome](https://user-images.githubusercontent.com/67814287/86523519-1e982e00-beb1-11ea-97fa-1181340f1164.jpg)

Thanks @BayInternetGroup

**Comment by conandoyle318** [comment]
Hi @BayInternetGroup ,

Finally, I'm in. Thanks very much for your help.

Now trying to send email and got authentication failed. 

![Screenshot_20200705-112102_Chrome](https://user-images.githubusercontent.com/67814287/86523569-c44b9d00-beb1-11ea-8105-418850e3d71d.jpg)

Same result when tried on your server.

Kind regards, 

Thanh

**Comment by BayInternetGroup** [comment]
Try turning off "Use short login" on SMTP section in the settings then click update.

**Comment by conandoyle318** [comment]
Hi @BayInternetGroup ,

Turning off use short login in SMTP didn't help. 

![Screenshot_20200705-125341_Chrome](https://user-images.githubusercontent.com/67814287/86524506-bea88400-bebe-11ea-869b-8c95175069f6.jpg)

Will have a look at logs.

Kind regards, 

Thanh

**Comment by BayInternetGroup** [comment]
Try sending mail from the CLI and post the results when successful. That may give some insight about your mail server's configuration.

**Comment by conandoyle318** [comment]
Hi @BayInternetGroup,
Try to send to gmail, failed via netcat, but worked with @annvashop.com
![image](https://user-images.githubusercontent.com/67814287/86525490-22d14500-becb-11ea-8c25-c89447ea06bc.png)

Email received
![image](https://user-images.githubusercontent.com/67814287/86525496-2a90e980-becb-11ea-8431-664415998b88.png)

Try again on Rainloop, still failed

![image](https://user-images.githubusercontent.com/67814287/86525533-a1c67d80-becb-11ea-8fb7-e4295f6cf6da.png)

Any advices?

Kind regards,

Thanh

**Comment by BayInternetGroup** [comment]
Your Mail Server more than likely requires authentication to send mail for the "annvashop.com" domain. The example you provided is that of an incoming SMTP and a relay connection. Please do an internet search on "smtp authentication with cli example" to create a proper outbound e-mail session. Once you have successfully sent an authenticated message post the steps you took to successfully make it work here so I can take a look at how your server expects it's login string to be configured.

Alternatively could you try to send mail again using https://emailvalet.com and let me know if that works. If not then do the steps above.

**Comment by conandoyle318** [comment]
Hi @BayInternetGroup ,

I've just tried sensing email from emailvalet.com 

![Screenshot_20200705-170149_ADM](https://user-images.githubusercontent.com/67814287/86527352-73ec3380-bee1-11ea-9f2f-721797cdf27c.jpg)

Will do your suggestions and let you know. 

Kind regards,

Thanh

**Comment by BayInternetGroup** [comment]
If you send me your test user login credentials via the contact form at https://bayinternet.com/#contact_area I can do some troubleshooting from this end and hopefully that will cut down on the back and forth messaging on here.

**Comment by conandoyle318** [comment]
Hi @BayInternetGroup ,

Thanks very much for your kind. I've sent the login details via contact form.

Kind regards, 

Thanh

**Comment by BayInternetGroup** [comment]
There are a couple things I found. First the SSL certificate you are using on your SMTP server is not valid. Second you have SMTP authentication disabled as can be seen from the response I got below using port 25 on your server.

AUTH LOGIN
503 5.5.1 Error: authentication not enabled

I believe the default is to have SMTP auth disabled on port 25 and something like port 587 is used with START TLS encryption however this may or may not be the case. In any event you will need to get your e-mail server working properly as the issues you are encountering are not related to RainLoop.

**Comment by conandoyle318** [comment]
Hi @BayInternetGroup,
Thanks for your troubleshooting, I dont know what else I need to check. 
I've made some changes on main.cf and master.cf to get the below
![image](https://user-images.githubusercontent.com/67814287/86547682-1ad1dd80-bf7d-11ea-8027-4e201fe19dee.png)


But still can't send email. Authentication failed.

SSL also passed with IMAP but not SMTP

![image](https://user-images.githubusercontent.com/67814287/86547727-4a80e580-bf7d-11ea-84e2-147cd5705ccf.png)

Can you help to fix SSL certificate? If it's not validthen why it's get passed?

Kind regards,

Thanh

**Comment by conandoyle318** [comment]
Hi All,

I think I fixed the issue with @BayInternetGroup helps.
Install SSL certificate seems to fixed the SMTP issue.

Thanks once again for your help @BayInternetGroup.

Kind regards,

Thanh
