### ISSUE TITLE
Can't tabulate when composing new message

### ISSUE THREAD

**Issue by ultreiac** [RainLoop/rainloop-webmail#2027]
**RainLoop version, browser, OS:**

1.14.0, Firefox & Chromium on Linux, but  possibly it happens on all systems and browsers.
Server is a Debian 10 with Apache and PHP7.3.

**Expected behavior and actual behavior:**

Have the possibility to tabulate.

**Steps to reproduce the problem:**

Create a new message and try to tabulate it. This happens with the tab key on the keyboard and with the virtual buttons, which are disabled.

It also happens in [Rainloop Demo](https://mail.rainloop.net/)

**Logs or screenshots:**

![2020-09-02_12-13](https://user-images.githubusercontent.com/49978873/91969026-d1500580-ed15-11ea-9024-b4c07cc7b55d.png)

**Comment by Philippe34** [comment]
Hi @ultreiac 

This feature seems to be linked to the bulleted list.
First, add a list and then you have the possibility to decrease ou increase the shrinkage.

![retrait-liste](https://user-images.githubusercontent.com/12435553/93088981-ef652080-f69a-11ea-946e-8834584a4690.png)

**Comment by the-djmaze** [comment]
@Philippe34 is correct. This is a CKEditor issue.
There are editors which do not have this issue.
