### ISSUE TITLE
Can't connect to yandex mailbox

### ISSUE THREAD

**Issue by Stezkoy** [RainLoop/rainloop-webmail#2030]
**RainLoop version, browser, OS:**
1.14 

Can't connect to yandex mailbox
Domain add
![Imap](https://mascloud.ru/wp-content/uploads/2020/09/snimok-ekrana-2020-09-11-140024.png)

**Logs:**
https://pastebin.com/raw/btgpjPk7

**Comment by GoodFor-Nothing** [comment]
Hi,
the pastebin logs report "Auth failed" - are you sure username / password are correct ?

**Comment by Stezkoy** [comment]
yea correct
