### ISSUE TITLE
Cannot enter text in email

### ISSUE THREAD

**Issue by mountainman13** [RainLoop/rainloop-webmail#2045]
**RainLoop version, browser, OS:**
Rainloop 1.12.1-2
Ubuntu 20.04.1 LTS
Google Chrome

**Expected behavior and actual behavior:**
This is a new install and I am new to rainloop. I am trying to to compose a new email. I can enter the email address and the subject but I can not enter any body text. There is no cursor in the "body" part of the compose window.

**Steps to reproduce the problem:**
Just compose an email.

**Logs or screenshots:**

**Comment by the-djmaze** [comment]
1.12 is old. Try 1.14

**Comment by mountainman13** [comment]
Upgraded to 1.14.0-2, same problem. Is it possible that this problem is related to my PHP setup? (I am very unfamiliar with PHP).

**Comment by mountainman13** [comment]
Hmm, found a mix of php 7.2 and 7.4 libraries on my system, removed them all, re-installed and it is all working now.
