### ISSUE TITLE
To use forgot_passwork_link ?

### ISSUE THREAD

**Issue by Philippe34** [RainLoop/rainloop-webmail#2046]
**RainLoop version, browser, OS:** 1.14.0

Hi,
In application.ini, we could add on logon screen the possibility of adding a link for the users who have forgotten their password.

```
forgot_password_link_url = ""
registration_link_url = ""
```
How does it work ? It seems that this feature is not really implemented in Rainloop, else we could have the possibility of defining a backup email in a another different domain of Rainloop. On this other address, after having clicking on this Rainloop link, we should receive a message with a link to change the password in Rainloop.

I will understand it like this.

Is someone succeded to do this in application.ini ?

Thanks for your feedback

**Comment by the-djmaze** [comment]
RainLoop manages "change password" through plugins.
But there is no full system for registration/reset.
The links are merely there if you want to setup something like protonmail, fastmail, etc.

**Comment by Philippe34** [comment]
@the-djmaze 
Thanks for you answer. It's clear and it confirms what I was thinking.

Regards
