### ISSUE TITLE
Unable to use UNIX-socket for local mysql connection

### ISSUE THREAD

**Issue by intervisionlord** [RainLoop/rainloop-webmail#2055]
**RainLoop version, browser, OS:**
1.14.0
Firefox 84.0.1
server: Debian 9
client: Windows 10

**Expected behavior and actual behavior:**
Ability to use UNIX-socket local connection for MySQL instead of TCP/IP

**Steps to reproduce the problem:**
Enable support of contacts
Fill all settings for MYSQL
Get `Access denied for user '<username>'@'localhost'` message

**Comment by the-djmaze** [comment]
MariaDB/MySQL should use socket by default when 'localhost' is used.

In MariaDB you can also define system users to use socket only.
For example php runs as systen user 'rainloop' and in MariaDB you have a socket user 'rainloop' then no password is required.

So how is your db configured?

**Comment by intervisionlord** [comment]
My DB configured to use sockets if loclalhost used as target server and other resources works with sockets and localhost without any issues.
When i switch database assigned to rainloop user to allow external connections it works properly, so i am a little confused why so.

**Comment by the-djmaze** [comment]
You are using MariaDB 10.2.29 which is old.
There are also connection restrictions based on /etc/hosts, mysqld.sock being a symlink, etc. etc. etc.

When using 10.3 or 10.4 you can use without -u and -p:

`[~] username@servername > mysql`

See https://mariadb.com/kb/en/authentication-plugin-unix-socket/

So yes, your "Access denied" can be caused by many things.
Try a test script like:

new mysqli('localhost', 'username', 'passwd', 'dbname', 3306, '/var/run/mysqld/mysqld.sock');

**Comment by intervisionlord** [comment]
I have already solve this issue by creating a new user (maybe it was some password issue)/
But i'd like to mention some things
First of all

> You are using MariaDB 10.2.29 which is old.

I don't think that this version can cause some problems. This is last version in debian 9 repos and i trust that it is stable.

> When using 10.3 or 10.4 you can use without -u and -p:

I can't agree with this statement, because until i am using "db per project" model (and not using system users to connect to db because of security reasons) i stiil need to use username and password to connect with database i need (because every single user has it's own db, not all bases for one user).

But anyway, everything works perfect now.
