### ISSUE TITLE
Suggestion: I designed some logos

### ISSUE THREAD

**Issue by bertvandepoel** [RainLoop/rainloop-webmail#2066]
At a student organization I'm a member of, we offer users both Roundcube and Rainloop as webmail clients on our servers. Now currently users are redirected to Roundcube and have to know about Rainloop. We wanted to quickly build a nice landing page with each webmail client's logo, so visitors could pick. Sadly, it seems Rainloop only sort of has a logo. There's a relatively small PNG logo available in the repo (which is also used on the website), but it's not shown on the login page or on the main page. We were actually not able to find the logo used anywhere on the UI while quickly looking around.

The logo seems a bit generic, and also doesn't mention Rainloop. So I ended up making a few logos in Inkscape (as well as some font suggestions). I'm not sure if this project is looking for the kind of logo I created, but we're going to use one on our landing page regardless, so it seemed silly not to also offer them to the project. Obviously I'm willing to grant a license or even transfer the copyright if so desired. Attribution is nice, but even that I don't really need. I mostly think that Rainloop could benefit from a more clear and prominent logo. 

The designs I have are below as a PNG render, but I'm happy to submit specific renders as well as the source SVG (both as an Inkscape and a simplified version). Let me know what you think and how I should continue (e.g. what kind of PR you want or what kind of files you need).

![rainloop](https://user-images.githubusercontent.com/4948317/108005595-67909300-6ff9-11eb-9452-8d5abd554cc7.png)

**Comment by the-djmaze** [comment]
Also see: https://github.com/RainLoop/rainloop-webmail/blob/master/assets/css/images/rainloop-logo.png

**Comment by bertvandepoel** [comment]
@the-djmaze Yeah, that's the logo I mentioned in my text. It's quite unfortunate it's not an SVG and quite generic. That's why I ended up making something different, hopefully it's suitable and something worth considering.

**Comment by the-djmaze** [comment]
@bertvandepoel although your vectors do strenghten rain and loop, i do miss a good fit for certain areas:
* phone shortcut icon
* phone/pc notification area
* favicon

For example i have a black background on KDE, which makes black notification image unseen.
My mobile has a blue background...

How will you make your logo fit those areas?

Current logo is simple but works due to the inside being white.

With that in mind your bottom right vector without name would fit the best 😉

**Comment by bertvandepoel** [comment]
I assume (but do correct me if I'm wrong) the phone shortcut icon and favicon are both originating from these HTML meta tags:
```
<link type="image/png" rel="shortcut icon" href="rainloop/v/1.14.0/static/apple-touch-icon.png?community">
<link type="image/png" rel="apple-touch-icon" href="rainloop/v/1.14.0/static/apple-touch-icon.png?community">
```
It seems that image is actually just the black icon with a transparant background in Rainloop right now. For example in my browser it doesn't really work well when the tab doesn't have focus on the dark background:
![Screenshot at 2021-02-17 23-45-57](https://user-images.githubusercontent.com/4948317/108277840-5c18a580-717a-11eb-96d1-65ae861fa18a.png)
When the tab is selected it's a light background, which looks great. I have to mention though that the GitHub favicon has the same thing happening, so I'm not sure if it's something we should be too concerned about. But a background, either to the shape of the bottom right suggestion, or some kind of background shape on any other, could easily fix that I think, if so desired.

With the phone shortcut icon, do you mean the icon shown when you bookmark the page in your phone browser, or do you mean something different? I don't tend to do email on my phone, so I'm not sure, and I would want to have a vague idea what kind of surroundings and form factor I'm adapting it for.

Finally, for notifications I tested it out locally and asked a friend to test it too. It seems that that icon also doesn't have any background or fill, which makes it fairly hard to see on dark notification bubbles like the ones we have:
![Screenshot at 2021-02-18 00-10-43](https://user-images.githubusercontent.com/4948317/108280147-0e05a100-717e-11eb-8dd6-8c2b7e034574.png)
![qFZxfl](https://user-images.githubusercontent.com/4948317/108280160-12ca5500-717e-11eb-947c-b4d93f8747f4.png)

So while it currently isn't a feature, I do agree it's something that should be considered, so I'm glad you brought it up. Do the favicon, the shortcut and the notification all use the same 64x64 PNG from https://github.com/RainLoop/rainloop-webmail/blob/master/assets/css/images/icom-message-notification.png or do some also use https://github.com/RainLoop/rainloop-webmail/blob/master/assets/css/images/rainloop-logo.png you mentioned?

**Comment by bertvandepoel** [comment]
@the-djmaze I see you thumbs-uped my post but perhaps missed the specific questions I asked. It's of course also possible you don't know the answer, since you're not the main dev of Rainloop. Should I maybe mention someone to get this moving? Once I know whether there's interest from those who have permissions to accept PRs, I'd gladly hear what logo and font has the preference, and then get all the right versions ready for inclusion.

**Comment by the-djmaze** [comment]
@bertvandepoel i'm just a contributor and have a fork.
Thumbs up are just for your good work and testing.

Yes you should make PR and hope the dev accepts them.

**Comment by bertvandepoel** [comment]
I recently started looking into writing a PR. I'm however noticing that the situation is more complex than I anticipated and I therefore wonder which decision I should make and if things should be combined in one big PR or in several smaller ones.

Specifically:
Currently the favicon standard is a huge mess, with Apple, Google and Microsoft all doing their own things. Only some of these are supported by RainLoop right now, and often not correct (only one size general icon and one size apple touch icon are supplied, no favicon .ico, a web manifest is included). Ideally I would like to add several other formats and a .ico.
The problem is that both icons (not for the app icon made for the web manifest) can be overwritten using the favicon URL setting under branding. This already kinda doesn't make sense for how it works right now, but wouldn't work at all for different sizes and formats except if we would add a ton of settings. I therefore wonder whether it wouldn't be best to remove this option
However, I would ideally suggest to add the rainloop logo to the login page like other webmail client such as roundcube does. This does bring up two problems, namely that there should probably be a setting to disable or overwrite that logo specifically. Furthermore there's no way to know whether a theme is "light" or "dark" right now. I can see how light icons were made for dark themes and included in the repo, but they are never used. That's also a bit tricky.

In general I don't know if I should just replace what exists or at least bring RainLoop up-to-date with modern standards. Then there's the questions about both the favicon URL setting and the login page. So I'm really hoping for some guidance here. What should I do and in how many PRs should I split it up (if I have to split it up at all).

**Comment by bertvandepoel** [comment]
@the-djmaze perhaps you can help me with the above? I'm kind of stuck and @RainLoop doesn't tend to respond on issues it seems.

**Comment by the-djmaze** [comment]
Although everything you say sounds correct, i think this is currently wasted time for RainLoop.

Because real dark themes in RainLoop are not possible (yet), and it took me a lot of time to get it "somesort" working in SnappyMail.
Mainly because people who send e-mails screw it up, like: text with color="black" but no background="white".

But, if you remove the text in your designs and just use the blue logo (with black or white shadow), i think it would be fine 90% of time and just keep it that way and push it as PR.

**Comment by bertvandepoel** [comment]
So do I understand it correctly that you agree to add more standards for 1, for 2 you would remove the option, and for 3 you would add a logo to the login page but without text. Did I understand you correctly, @the-djmaze ?

**Comment by bertvandepoel** [comment]
It has become abundantly clear that this project is dead. I'm sad to see it die, but I'm no longer going to periodically check this issue and I guess I will just close it. Too bad I wasted time designing these logos.
