### ISSUE TITLE
An Error occured...

### ISSUE THREAD

**Issue by Threesixty** [RainLoop/rainloop-webmail#21]
Hi, I tried to deploy your application but I can't log in with my personnal IMAP server or with a gmail address. I got this message every time I try, in middle of the page on gray background "An Error occured, please refresh the page and try again." Thank you in advance for your help.

PS: Another problem, when I copy-paste my email address in the field provided for this purpose, it becomes red when I move to the next field. I remove the dash (-) of my address, I pass on the password fields, and again on this field and now it's ok ...

**Comment by saikatharryc** [comment]
an error occurd..!! there is some problem,,i cant understand.. can u help me with this?
