### ISSUE TITLE
Cannot send mails with other identity

### ISSUE THREAD

**Issue by BaumelndesEi** [RainLoop/rainloop-webmail#212]
Hello,

I am forwarding all my old mailboxes to my new one. (test@example.com)
I can send and receive mails via "test@example.com" but now, I would like to send a mail with my created identity "test@gmx.de". SMTP and IMAP settings are made under domains.
I just get the error: "The mail cannot be send", but I expect the site to show an login dialog for the GMX SMTP.
Am I doing something wrong? Or is the login dialog not suported?

Best regard
Philipp

**Comment by RainLoop** [comment]
https://rainloop.uservoice.com/forums/223477-ideas-for-rainloop-webmail/suggestions/6207336-optional-per-identity-smtp-configuration
