### ISSUE TITLE
Rainloop as transparent bridge

### ISSUE THREAD

**Issue by Ciangi** [RainLoop/rainloop-webmail#2125]
Hello,

i have one question.

I have installed rainloop on host with ip 1.2.3.4

Client with ip 5.6.7.8 trying to log in to his mail account (abcd@domain.com) using rainloop. On my mail server i see that ip 1.2.3.4 trying to authenticate using user abcd@domain.com.

How can i configure rainloop that i will see on my mail server that instead of rainloop host IP (1.2.3.4) i will see that client with ip 5.6.7.8 is trying to authenticate ?

Greetings

**Comment by gijoe88** [comment]
Hello,

You cannot, as the request to the mail server is effectively coming from rainloop server, and you cannot fake that.

2 things:
- you can see the client IP in the access logs of the web server (if using apache, those are in /var/logs/apache2)
- you can add a header inside the mails sent by rainloop indicating the client IP via the plugin X-Originating-IP

**Comment by Ciangi** [comment]
Thanks for reply
