### ISSUE TITLE
no table created in the database

### ISSUE THREAD

**Issue by andrex4k** [RainLoop/rainloop-webmail#2137]
RainLoop 1.16, chromium-95.0.4638.69, Ubuntu 18.04.6 LTS, mysql  Ver 15.1, php-fpm7.4, nginx/1.14.0.
DB name rainloopdb; DB user rainloopuser/root

Enable contacts, set db. test is ok (green)
Send test email.
address book is empty.

Log:
`
[14:18:32.834][55045196] AJAX[DATA]: {"Action":"Contacts","Result":false,"ErrorCode":999,"ErrorMessage":"42S02 - SQLSTATE[42S02]: Base table or view not found: 1146 Table 'rainloopdb.rainloop_users' doesn't exist","ErrorMessageAdditional":"","Time":16}
`

```
MariaDB [rainloopdb]> SHOW tables;
+------------------------+
| Tables_in_rainloopdb   |
+------------------------+
| rainloop_ab_contacts   |
| rainloop_ab_properties |
| rainloop_system        |
+------------------------+
```

why this happened I did not understand.... or the installation procedure has been violated.
I think in such a case, you need a clean database dump in the package.

**Comment by Philippe34** [comment]
Hi @andrex4k

I looked the tables in my rainloop DB and you should have the rainloop_users table.

```
MariaDB [rainloop]> describe rainloop_users;
+----------+------------------+------+-----+---------+----------------+
| Field    | Type             | Null | Key | Default | Extra          |
+----------+------------------+------+-----+---------+----------------+
| id_user  | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| rl_email | varchar(128)     | NO   | MUL |         |                |
+----------+------------------+------+-----+---------+----------------+
```

For me, the dump of the DB is:

```
CREATE TABLE `rainloop_users` (
  `id_user` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rl_email` varchar(128) NOT NULL DEFAULT '',
  PRIMARY KEY (`id_user`),
  KEY `rl_email_rainloop_users_index` (`rl_email`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```
If this can help you to create this tables ...

**Comment by andrex4k** [comment]
Thx. yeah, that's the!
