### ISSUE TITLE
call to  http://api.rainloop.net/status/FQDN on login page

### ISSUE THREAD

**Issue by yeupou** [RainLoop/rainloop-webmail#2160]
with rainloop 1.16.0+dfsg-1, there is a timeout on login page

It tries to get 
INFO[DATA]: cUrl: URL: http://api.rainloop.net/status/FQDN
and it fails with timeout.

On the same server, with a different subdomain, there is no issue. What could be the cause?

From what I understand, in include.php there is
define('APP_API_PATH', 'http://api.rainloop.net/');

This is called in 
RainLoop/Providers/Prem.php
I do not understand it's purpose and why it works with another subdomain (both are public with proper SSL certificate

Regards

**Comment by rainloopsay919** [comment]
The issue was explained further in #2161, I suggest closing this one.

**Comment by yeupou** [comment]
Duplicate of #2161
