### ISSUE TITLE
Feature request : Rule to move email to folder

### ISSUE THREAD

**Issue by smck83** [RainLoop/rainloop-webmail#2163]
**RainLoop version, browser, OS:**
Chrome
**Expected behavior and actual behavior:**
As a user I would like to create a rule in Rainloop that looks for text in a header or a subject e.g. [SPAM] and moves it to the Spam folder when rain-loop opens.

**Steps to reproduce the problem:**
Most mail servers will add a header or word to subject of an email. It would be great that when/if Rainloop loads the email it looks for a word in the subject .e.g [SPAM] or in the message header and automatically moves it to 'Spam' folder

**Logs or screenshots:**

**Comment by darthmaul0181** [comment]
This fuctionality already exists in Rainloop. 

Sieve must be available on the mailserver and Rainloop must be configured to work with it.
When done, the "Filters" functionality is available in the settings page.

**Comment by smck83** [comment]
ok thank you. i am using hmailserver and dont believe Sieve is supported.

I have since found a server rule in hmailserver that allows me to look for a header in the e-mail and move it to an IMAP folder.
