### ISSUE TITLE
Which PHP version is necessary for your PHP e-mail client?

### ISSUE THREAD

**Issue by jayjupdhig** [RainLoop/rainloop-webmail#2165]
As the title says - thank you for your feedback.

With kind regards from Switzerland,
Jan

**Comment by jayjupdhig** [comment]
???

**Comment by jayjupdhig** [comment]
Maybe the question is too complex...?

**Comment by kosuodhmwa** [comment]
Another question: https://github.com/RainLoop/rainloop-webmail/issues/2166

**Comment by jayjupdhig** [comment]
The only thing i get after uploading the expanded zip to web server folder www.mydomain.com/rainloop is that: 

![image](https://user-images.githubusercontent.com/42765391/158985213-63750406-3823-4242-9d7a-e4c9ffc35996.png)


**Again:** What PHP version do i need to run Rainloop!?

**Comment by jayjupdhig** [comment]
Maybe somebody knows an open-source alternative to Rainloop!?
-> https://stackoverflow.com/questions/2490818/webmail-client-that-can-open-multiple-email-addresses-at-once-like-a-desktop-cli

**Comment by derStephan** [comment]
>What PHP version do i need to run Rainloop

Running it without any problem on 7.4 but should work with 8.0 as well.

>Maybe somebody knows an open-source alternative to Rainloop!?

https://github.com/the-djmaze/snappymail

This is a fork of rainloop with very active development.

**Comment by kosuodhmwa** [comment]
Thank you very very much for your feedback!! :-)

**Comment by jayjupdhig** [comment]
Now i use snappyMail. Because of that, i close that issue...

**Comment by jayjupdhig** [comment]
Closed!!
