### ISSUE TITLE
Does the free version support multiple e-mail-accounts they coexist "parallel" to each other 

### ISSUE THREAD

**Issue by jayjupdhig** [RainLoop/rainloop-webmail#2166]
Which means there is NOT "main account" which contains some sub-account / identities like GMail does... i mean can i use it as a full IMAP mail client like M$ outlook? (But in the web way... ;-))

Thank you very very much for your feedbacks...

Kind regards, Jan

**Comment by jayjupdhig** [comment]
???

**Comment by jayjupdhig** [comment]
Maybe the question is too complex...?

**Comment by kosuodhmwa** [comment]
Yes, seems so!!

**Comment by kosuodhmwa** [comment]
Another question: https://github.com/RainLoop/rainloop-webmail/issues/2165

**Comment by jayjupdhig** [comment]
Maybe somebody knows an open-source alternative to Rainloop!?
-> https://stackoverflow.com/questions/2490818/webmail-client-that-can-open-multiple-email-addresses-at-once-like-a-desktop-cli

**Comment by derStephan** [comment]
>Does the free version support multiple e-mail-accounts they coexist "parallel" to each other 

yes, absolutely

>i mean can i use it as a full IMAP mail client like M$ outlook?

yes.

>Maybe somebody knows an open-source alternative to Rainloop!?

https://github.com/the-djmaze/snappymail

This is a fork of rainloop with very active development.

**Comment by kosuodhmwa** [comment]
Thank you very very much for your feedback!! :-)

**Comment by jayjupdhig** [comment]
Now i use snappyMail. Because of that, i close that issue...
