### ISSUE TITLE
Force SSL even for images

### ISSUE THREAD

**Issue by nodomain** [RainLoop/rainloop-webmail#220]
Request for enhancement: implement a "proxy" that fetches images via the server and replace all image URLs in emails to HTTPS. This would avoid browser warnings.

**Comment by colinjmatt** [comment]
For anyone wanting an answer to this (like I was) `use_local_proxy_for_external_images = True` works, but it requires the cache of the browser to be cleared for that setting to take effect if the images have already been downloaded.
