### ISSUE TITLE
OpenPGP key unsaved

### ISSUE THREAD

**Issue by jeromeg81** [RainLoop/rainloop-webmail#2204]
Bonjour,
J'ai un petit soucis lors de la génération ou l'importation de clé openPGP dans rainloop.
Une fois que je quitte le webmail, celle-ci est supprimée ! Je dois donc en renouveler une ou réimporter à chaque nouvelle connexion.
Une idée ? 
Merci d'avance pour votre aide !
----
Sorry about my English.
Good morning,
I have a small problem when generating or importing openPGP key into rainloop.
Once I leave the webmail, it is deleted! So I have to renew one or re-import each time I connect.
Any idea?
Thank you in advance for your help!

**Comment by jeromeg81** [comment]
J'ai retrouvé un post sur le même problème. Les clés ne sont pas enregistrées côté serveur mais localement (cookies ?) et donc supprimées à la fermeture du navigateur (pour mon cas).
De plus, Rainloop ne semble pas prendre en charge la dernière norme openPGP !
Dommage, à peine installé, je dois déjà penser à un autre webmail...
-----
I found a post about the same problem. Keys are not stored on the server side but locally (cookies?) and therefore deleted when the browser is closed (in my case).
Also, Rainloop doesn't seem to support the latest openPGP standard!
Too bad, just installed, I already have to think about another webmail. . .

**Comment by the-djmaze** [comment]
You can read more details here: https://github.com/the-djmaze/snappymail/issues/89
