### ISSUE TITLE
Remove the Delete feature in RainLoop

### ISSUE THREAD

**Issue by zainbfaisal** [RainLoop/rainloop-webmail#2230]
**1.17.0**

![image](https://github.com/RainLoop/rainloop-webmail/assets/144497086/fa2d1e2b-b2bc-47cb-9c89-11df85089957)

I would like to Remove the Delete Icon/Feature from RainLoop so no user should be able to delete an Email, how can i do it.

Normally I would just delete it from the index.html but i either can't access or don't know where to find it.

**Comment by michaelbutler** [comment]
Hi @zainbfaisal I'm a freelance web developer and could help customize or fork your RainLoop instance to disable the Delete email feature. Let me know if you're interested.
