### ISSUE TITLE
Enable multiple domains

### ISSUE THREAD

**Issue by heruan** [RainLoop/rainloop-webmail#226]
I have two domains, one for family and one for friends. I'd like to have separate configurations, but all is placed under /data/…/_default_/ no matter what domain I use. How can i enable multiple domain support?

**Comment by Zunedg** [comment]
Hi
I want to activate multiple domains in rainloop, I have a premmium version, I want all the domains to enter the only portal webmail.co.mz, in the admin panel I already added the domains, more when I try to enter the webmail with different accounts of the main domain webmail.co.mz it says this domain is not premiited.
what I need to do?
