### ISSUE TITLE
Authentication failed on sending a mail

### ISSUE THREAD

**Issue by Sndan** [RainLoop/rainloop-webmail#228]
I can login and receiving mails with no problem 
but when I want to send a new message it gives me "Authentication failed"
in the JS console the resposne is error code Json {"Action":"SendMessage","Result":false,"ErrorCode":102,"ErrorMessage":"","Time":56}

if I goes into other webmail like virtualmin I can send mails with no problem ...

thanks,

**Comment by djibux** [comment]
Using php mail() function (beta in 1.7.2.229) is a workaround that issue.

**Comment by djibux** [comment]
The problem seems fixed for me.  Maybe OVH changed its settings or there was a bug and it has been fixed.

**Comment by lucas-sticky** [comment]
Just try with my OVH server, and still get the same error message...

**Comment by Think-It** [comment]
Just try with my OVH server, and still get the same error message...

**Comment by grotesque42** [comment]
It is working for me also. Good news ! @Think-It did you update your rainloop ?

**Comment by Think-It** [comment]
@grotesque42 : Yes, I've v1.8.0.251. Good, no ?

**Comment by RainLoop** [comment]
> Anyone with this issue ?

Yes, I have met a similar problem when using a mail function.

**Comment by grotesque42** [comment]
@Think-It  I have the same version and it works but without the php mail. Here is my configuration which is working well :
![capture](https://cloud.githubusercontent.com/assets/9765129/6153436/d5f0d3da-b224-11e4-8f36-8183eb04a0c3.PNG)

**Comment by peterthecoon** [comment]
Like @grotesque42, no more problem with SMTP in v1.8.0.251 ! Thanks !

**Comment by lucas-sticky** [comment]
@grotesque42 : I'm using my own imap/smtp server.
I have try to set "localhost" or "mydomain.com". The "TEST" button become green each time I try it.

By the way, my config work perfectly with Thundetbird and my email app on Android. =(

**Comment by Think-It** [comment]
@grotesque42 : I'm using my own imap/smtp server.
I have try to set "localhost" or "mydomain.com". The "TEST" button become green each time I try it.

By the way, my config work perfectly with Thundetbird and my email app on Android. =(

**Comment by grotesque42** [comment]
@Think-It  I can't help you, I am using OVH shared server... good luck.

**Comment by SimpleHomeUser** [comment]
Hi,
sorry to come back to it but I have the same problem.
Installed Rainloop on an OVH mutualized web hosting.
I have the message "Authentication failed" randomly:
Next exception 'MailSo\Smtp\Exceptions\LoginBadCredentialsException' with message '555 sorry, too many emails [mail137] (#5.7.1)'
This message is surprising as I don't have a limited number of email allowed and mostly because I don't send a lot of emails (4 or 5 max a day).

**Comment by Think-It** [comment]
There is a real  authentication issue with some server configs (especially on OVH servers).
The Rainloop team should investigate on it.

**Comment by grotesque42** [comment]
Yes... I'm back with the same problem again....(ovh shared hosting, last version of RainLopp, failed authentification).

**Comment by caranchls** [comment]
I have same problem with this logs
SMTP[NOTICE]: exception 'MailSo\Smtp\Exceptions\LoginBadMethodException' with message 'MailSo-Smtp-Exceptions-LoginBadMethodException (SmtpClient.php ~ 264)' in /var/www/webmail/rainloop/v/1.9.3.363/app/libraries/MailSo/Smtp/SmtpClient.php:264

**Comment by lucas-sticky** [comment]
UP ?

**Comment by vtolenti89** [comment]
I am facing the same problem above. Could we reopen the issue?
