### ISSUE TITLE
An unknown file upload error occurred - Rainloop 1.6.8.151

### ISSUE THREAD

**Issue by radmanz** [RainLoop/rainloop-webmail#238]
When uploading files bigger then 150KB, it shows an error of "An unknown file upload error occurred". When uploading any file less then 150KB, it can attach and send the file with no errors.
I've set all permissions as stated on the installation procedure.
I have changed my max post and upload to 2G in the php.ini
Admin output = PHP: upload_max_filesize = 2048M; post_max_size = 2048M  
Happened on all previous versions and the most current version of Rainloop 1.6.8.151

This has been a continuing problem for me and Rainloop the past couple of weeks.
I've just recently formatted my server, hoping that the problem would go away, but it still exists. Please help me solve this problem :)

System Info:
Ubuntu Server 12.04.03
apache2 -v = Server version: Apache/2.2.22 (Ubuntu)
php -v = PHP 5.3.10-1ubuntu3.13 with Suhosin-Patch (cli) (built: Jul  7 2014 18:52:09)

**Comment by jougs** [comment]
Sorry for commenting in a closed issue.

I am observing the exact same problem and there's no mention of the problem in the log file. Changing the server to nginx is not an option for me.

Could you please supply me with further help in debugging this? E.g. what are the things I should look for in the log, or in what PHP file is the error message raised?

Many thanks!

**Comment by dinardwi-s** [comment]
This problem can be resolved by restarting lscpd
by writing the command "service lscpd restart"
