### ISSUE TITLE
Moving Emails between Accounts (Feature)

### ISSUE THREAD

**Issue by al-Iskandar** [RainLoop/rainloop-webmail#242]
If you have different account, you have often the problem that some emails are sent to the wrong account (e.g. you know somebody from business and privately, but he is not able to make a difference between business related and private emails). There it would be to helpfull, if you could move or copy the emails from one account to another.

**Comment by mwaeckerlin** [comment]
This Uservoice instance is no longer available!

Please take up the feature, I need it too.
