### ISSUE TITLE
ownCloud autologin with same user credentials

### ISSUE THREAD

**Issue by marticardus** [RainLoop/rainloop-webmail#248]
In many cases the mail user can be the same as that of ownCloud. 

The plugin for roundcube has some triggers to automatically save user data in the database and not have to put them manually. 

They could do something similar to that of rainloop? 

example: https://github.com/hypery2k/owncloud/blob/master/roundcube/src/main/php/lib/RoundCubeAuthHelper.class.php

**Comment by maderluc** [comment]
i implemented rainloop in a symfony backend and a Dashboard for users! the user need to login to the personal dashboard. if they want to acces the mail area, they need to login again. Is there a way to autologin with a server token ?
