### ISSUE TITLE
postfixadmin-change-password plugin

### ISSUE THREAD

**Issue by sctt** [RainLoop/rainloop-webmail#251]
hello,

in my environment we use postfixadmin to manage mailboxes and domains, i know it is pretty common as a solution.

i wrote a plugin to enable password change with postfixadmin.

i wanted to write a more generic MySQL password changer, but i needed a fast solution due to production deadlines, but i think it can be useful even in this way, for who has postfixadmin and doesn't want to set up raw table and fields configurations.

it currently supports md5crypt, md5, system, mysql_encrypt and cleartext encryption methods, it doesn't support yet authlib and dovecot, i hope ill have time to add them in the future.

here is the tar:
http://speedy.sh/mhNJn/postfixadmin-change-password.tar.gz

**Comment by davi-dns** [comment]
It is possible to use PLAIN-MD5?

**Comment by RainLoop** [comment]
![postfix2](https://cloud.githubusercontent.com/assets/5530092/9413500/c908c41e-483a-11e5-8aa1-95f0f64d40ea.png)

**Comment by imeldesign** [comment]
Hello to everyone,
please can someone help me on postfixadmin-change-password plugin install ?
1 - i download it on https://github.com/RainLoop/rainloop-webmail/tree/master/plugins/postfixadmin-change-password
2 - put it on: /var/www/rainloop/data/_data_/_default_/plugins in a folder called postfixadmin-change-password
3 - Check for the correct permissions and owner

But when i go to the admin page, i can't activate it, i receive an error message: "Invalid plugin package"

My Environment is a Ubuntu Server / Postfix / PostfixAdmin / Dovecot and virtuals users stored in a MySQL database.

Any help would be appreciate. Thanks

**Comment by RainLoop** [comment]
This is strange.

Try this: [postfixadmin-change-password.zip](https://github.com/RainLoop/rainloop-webmail/files/394970/postfixadmin-change-password.zip)

**Comment by imeldesign** [comment]
Hi, 
The zip version is working perfectly. Thanks alot

**Comment by zilon84** [comment]
Ist this plugin already included in the standard version of Rainloop? Cannot find it.

**Comment by Schroeffu** [comment]
Same as zilon84, cannot find it too.

**Comment by Bbertatum** [comment]
Very usefull comment for the directory to unzip into "/var/www/rainloop/data/_data_/default/plugins"
Also the plugin works with postgreSQL with a little patch in ChangePasswordPostfixAdminDriver.php :
Just replace mysql with pgsql, and then in the config 5432 instead of 3306
`218   $sDsn = 'pgsql:host='.$this->sHost.';port='.$this->iPort.';dbname='.$this->sDatabase; `
