### ISSUE TITLE
Can't get message list

### ISSUE THREAD

**Issue by eldide** [RainLoop/rainloop-webmail#253]
Hi - 

I've installed the latest and greatest version. I really want to use this however, when I log in and click on a folder (inbox) that I know has messages I get a red message "Can't get message list". 

I'm using it with Xeams, if anyone else out there is, any help would be gratefully appreciated. 

The following is what's in the log file when I select such a folder:

--- cuted ---

Thanks in advance,
Charles

**Comment by shubhammatta** [comment]
Any solution for above bug??
