### ISSUE TITLE
[202] Data folder permisions error

### ISSUE THREAD

**Issue by MrKeiKun** [RainLoop/rainloop-webmail#262]
**Information:**
Im using rainloop from github src, I installed once before on another server. Worked fine same procedures. Now im running centos7.

I already ran

```
cd /var/www/rainloop
find . -type d -exec chmod 755 {} \;
find . -type f -exec chmod 644 {} \;
```

still not working

```
[root@neko www]# pwd
/var/www
[root@neko www]# ls -lha
total 28K
drwxr-xr-x.  7 root root 4.0K Jul 31 07:12 .
drwxr-xr-x. 21 root root 4.0K Jul 29 12:42 ..
drwxr-xr-x.  2 root root 4.0K Jul 23 10:48 cgi-bin
drwxr-xr-x.  2 root root 4.0K Jun  9 22:32 html
drwxr-xr-x. 10 root root 4.0K Jul 31 07:12 rainloop
```

```
total 92K
drwxr-xr-x. 10 root root 4.0K Jul 31 07:12 .
drwxr-xr-x.  7 root root 4.0K Jul 31 07:12 ..
drwxr-xr-x.  4 root root 4.0K Jul 31 07:12 build
drwxrwxrwx.  2 root root 4.0K Jul 31 07:18 data
drwxr-xr-x. 12 root root 4.0K Jul 31 07:12 dev
drwxr-xr-x.  8 root root 4.0K Jul 31 07:12 .git
-rw-r--r--.  1 root root  126 Jul 31 07:12 .gitignore
-rw-r--r--.  1 root root  19K Jul 31 07:12 gulpfile.js
-rw-r--r--.  1 root root  214 Jul 31 07:12 _include.php
-rw-r--r--.  1 root root  428 Jul 31 07:12 index.php
-rw-r--r--.  1 root root 1.2K Jul 31 07:12 .jshintrc
-rw-r--r--.  1 root root 1.5K Jul 31 07:12 LICENSE
-rw-r--r--.  1 root root   69 Jul 31 07:12 _MULTIPLY
-rw-r--r--.  1 root root 1.2K Jul 31 07:12 package.json
drwxr-xr-x. 20 root root 4.0K Jul 31 07:12 plugins
drwxrwxrwx.  3 root root 4.0K Jul 31 07:12 rainloop
-rw-r--r--.  1 root root  791 Jul 31 07:12 README.md
drwxr-xr-x.  4 root root 4.0K Jul 31 07:12 tests
drwxr-xr-x. 32 root root 4.0K Jul 31 07:12 vendors
```

**Comment by Boycce** [comment]
Same had to change chmod to 777

**Comment by galch99** [comment]
1) is_dir=1
2) is_readable=1
3) is_writable=1
4) mkdir=1
5) file_put_contents=0
6) unlink=0
7) rmdir=1

every thing 777. but not working :(

**Comment by rjapeer** [comment]
Took me a little while to figure out, but the solution is to have SE Linux allow writing data folder by httpd:
You need to change the label on '/your/installation/folder/data'.
In my case this is done by the following two commands (as root user):
```shell
[root@machine rainloop]# cd /var/www/html/rainloop
[root@machine rainloop]# semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/rainloop/data'
[root@machine rainloop]# restorecon -v '/var/www/html/rainloop/data'
```
Note that the complete path to the rainloop data folder must be specified.
You can check the setting using ls -Z:
```shell
[root@machine rainloop]# ls -Z
drwxr-xr-x. apache apache system_u:object_r:httpd_sys_rw_content_t:s0 data
-rw-r--r--. apache apache system_u:object_r:httpd_sys_content_t:s0 index.php
drwxr-xr-x. apache apache system_u:object_r:httpd_sys_content_t:s0 rainloop
```

And with the check.php script from a previous comment the output should be:
```
1) is_dir=1
2) is_readable=1
3) is_writable=1
4) mkdir=1
5) file_put_contents=1
6) unlink=1
7) rmdir=1
```

**Comment by saikatharryc** [comment]
[202] Data folder permissions error [is_writable]. i have SSH console. how do i make this run?

**Comment by aestheticsdata** [comment]
following the doc has worked for me :

http://www.rainloop.net/docs/permissions/

maybe it was the missing : chown -R www-data:www-data .

**Comment by saikatharryc** [comment]
not worked.

**Comment by lutfiarfianto** [comment]
i have

1) is_dir=1
2) is_readable=1
3) is_writable=1
4) mkdir=1
5) file_put_contents=0
6) unlink=0
7) rmdir=1

chmod = 0777

but i dont have ssh access

what should i do?

**Comment by mpatron** [comment]
You should try
```
setsebool httpd_unified true
setsebool httpd_can_network_connect true
yum install policycoreutils-python
cd /var/www/html/rainloop
semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/rainloop/data'
restorecon -v '/var/www/html/rainloop/data'
systemctl restart httpd
```
It is working for me on my centos7+rainloop.

**Comment by parsibox** [comment]
you should desable selinux and reboot your os

**Comment by MoacirSchmidt** [comment]
For Windows + IIS you have to give proper permissions to IUSR also

**Comment by Alirezaies** [comment]
I had the same problem with SELinux off and correct permissions (644 for files and 755 for directories).
I needed to change php-fpm user to the same user as web server (e.g. nginx, www-data, ...)

here is what I changed in `/etc/php-fpm.d/www.conf` in CentOS 7:

    listen.owner = nobody
    listen.group = nobody
    user = nginx
    group = nginx

and then `sudo systemctl restart php-fpm` solved the problem

**Comment by mojili** [comment]
I have the same problem with SELinux. first setenforce 0 and then try if everything is ok, then enable SELinux setenforce 1 and try to find the targets witch SELinux denies them .
Tail -f /var/log/audit/audit.log | grep deny 
then with semanage or other tools set the proper permission.

**Comment by shaahinhs** [comment]
hi , i had the same problem ;

1) is_dir=
2) is_readable=1
3) is_writable=1
4) mkdir=1
5) file_put_contents=1
6) unlink=1
7) rmdir=1
Selinux disable

but :    [202] Data folder permisions error  

os: centos 5.11  / apache 2.2.31

**Comment by mpatron** [comment]
shaahinhs , you should follow https://github.com/pierre-alain-b/rainloop-nextcloud/issues/7

**Comment by Mardiie** [comment]
Might be a dumb addition, but make sure the rainloop folder is owned by www-data.

**Comment by eanon** [comment]
Hello, Just my two cents on a topic that, I guess, still raises issues in a lot of minds all year long (not only about Rainloop). For me, what is said on http://www.rainloop.net/docs/permissions/ is not enough since it takes some assumptions (eg. www-data user) with no strong way to figure-out what to do if your system is not perfectly as described...

So, here is my proposition:
1) cd <root-directory-where-rainloop-installed> (should contain 2 directories: 'rainloop' and 'data')
2) ps aux | grep <name-of-your-webserver> (e.g. nginx)
    => In 1st column you see user running web server (for nginx, consider worker only)
3) chown -R <webserver_user_found_above>:<webserver_user_found_above> rainloop
4) ps aux | grep php => In 1st column you see user running PHP code
5) chown -R <php_user_found_above>:<php_user_found_above> data
6) chmod all directories recursively to 755 (through SSH or using FTP client like FileZilla)
7) chmod all files recursively to 644 (through SSH or using FTP client like FileZilla)
8) Test all is OK with PHP script provided by Rainloop in comment #50786471 above
9) As double-check, go to Rainloop Admin panel and do a change, then logout/login to see if kept.

For example, here an exotic context: in a VPS I just installed yesterday, the user about Nginx was "emps" (related to Webuzo, a control panel from which I installed Nginx) and the one running PHP-FPM was "admin" (this being confirmed looking in the php-fpm.conf managed by Webuzo again). So, my two concerned users were "emps:emps" and "admin:admin".

Hoping it may help...

**Comment by chrboesch** [comment]
For those who use nginx and php-fpm: As of PHP 7.4 php-fpm protects the system by mounting /usr, /boot, and /etc directories read-only. For it to work, the directory /usr/share/webapps/ must be moved to /www/, for example.

**Comment by Obada8** [comment]
You should set the path of the data folder in `open_basedir` 

for example:
`php_admin_value open_basedir "/tmp:$VH_ROOT:/usr/local/lscp/cyberpanel/rainloop"`
