### ISSUE TITLE
rainloop auth: Account is not allowed

### ISSUE THREAD

**Issue by bms8197** [RainLoop/rainloop-webmail#265]
I am running the latest version of rainloop on my CentOS server. I have never experienced any problems with your webmail application. I have multiple domains hosted on the server. I always used rainloop as a webmail client for my main domain. So now from the Admin section of rainloop I have successfully added another domain.

Now I am accessing rainloop and when I try to login with email@domain.tld & password it says: Account is not allowed. The other domain that I was using before is working just fine. I tried to add other domains (all hosted on the same server and unfortunately I get the same error).

Any help is really appreciated!
![rainloop_error](https://cloud.githubusercontent.com/assets/7985374/3784329/fc30ba58-19b6-11e4-8319-1bd6fa46d4bb.PNG)

**Comment by Loris1634** [comment]
Hi,

How did you solve your issue ? I got the same problem here.

Loris

**Comment by RainLoop** [comment]
Have you filled a "White List" field?
Admin Panel / Domains / your-doamin-name.com / White List button

**Comment by Loris1634** [comment]
Worked like a charm, thanks a lot :)

Loris
