### ISSUE TITLE
Address Book

### ISSUE THREAD

**Issue by saji89** [RainLoop/rainloop-webmail#27]
The address book is a very important feature lacking in this application. I have to enter the same mail id every time, I want to mail a person. 
Atleast the email address of people who we have already mailed to, should be stored. 
Before storing an email address, a dialog box can be added, asking whether we want to save that mail address to the list.

**Comment by WhiteFalcon77** [comment]
Hi, it says above - "  When you send a new message RainLoop writes TO field emails to address book (but they are hidden in the contact list). After that these contacts will appear as suggestions when you write new messages. This all works on the latest version of webmail only (1.5.0.530). "

I have Rainloop installed on my domain and I really like it, but the address book feature as described above does not work.  Whenever I begin to type in an address that I have previously sent emails to it does not auto complete.  Any ideas?

Thanks

**Comment by megadr01d** [comment]
@WhiteFalcon77 Enable **Settings > Contacts > Automatically add recipients to your address book**.

**Comment by WhiteFalcon77** [comment]
Thanks megadr01d, but I don't have "Contacts" in my settings menu.  I only have -

General
Accounts
Security
Folders
Themes

**Comment by megadr01d** [comment]
Enable it in the admin panel (add `?admin` to the URL) under **Contacts**.

**Comment by WhiteFalcon77** [comment]
Thanks, I followed your instructions and managed to get 'Contacts' into my 'Settings' menu. 

'Automatically add recipients to your address book.' is enabled but it is having no effect.

When I manually try to add addresses to 'Contacts' it refuses to save them.

Any ideas?

**Comment by megadr01d** [comment]
Did you test the DB (MySQL, SQLite) in the admin panel? Your server needs PDO module support.
Also try to enable logging and post the logs or sendthem to support@rainloop.net.

`./data/_data_/_default_/configs/application.ini`

```
[logs]
enable = On 
```

`./data/_data_/_default_/logs/*`

**Comment by WhiteFalcon77** [comment]
Hi megadr01d, when I tested the MySQL it said -

SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)

When I tested PostgreSQL it said -

SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)

When I tested SQLite it was fine

Couldn't find out how to enable logging.

Cheers.

**Comment by megadr01d** [comment]
> Couldn't find out how to enable logging.

Open `application.ini` and search for `[logs]`. Then you can find them in the `logs` folder (check paths above).
I use SQLite and it works well here.

**Comment by WhiteFalcon77** [comment]
Thanks  megadr01d , I am a complete novice, no coding ability at all, so I just changed it to SQLite and now the Contact/ address book works as it should!  Thanks a lot.

So, I take it SQLite is just a different type of Database?  Would there be any disadvantage to using it?
It warned me not to use it if there were a lot of people accessing the account or something, but it's only me.

Cheers.

**Comment by megadr01d** [comment]
@WhiteFalcon77 No problem.

SQLite is file based, fast and it's recommended for a single user (no multi user support).
MySQL is an old standard but demands more configuration on your server (create user and pass, host and port, tables, etc.).

Meh, [this](https://www.digitalocean.com/community/tutorials/sqlite-vs-mysql-vs-postgresql-a-comparison-of-relational-database-management-systems) website explains it better.

**Comment by WhiteFalcon77** [comment]
Hi, I'm trying to sign into the admin panel but I can't get access.  I am using the same username and password as my email account.  is there something I'm doing wrong?

Cheers

**Comment by ervee** [comment]
> Hi, I'm trying to sign into the admin panel but I can't get access. I am using the same username and password as my email account. is there something I'm doing wrong?
Log in to the admin panel with the admin account. User settings can be changed when logged in as user in the normal webmail interface.

**Comment by WhiteFalcon77** [comment]
I can't get into the admin panel.

It is mydomain.com/webmail/?admin

and my username and password for my email account aren't letting me in.

**Comment by megadr01d** [comment]
@WhiteFalcon77 

If it's the first time you're accessing the admin panel, then

> Default login is "admin", password is "12345".

After you login, you can change the admin login and password (they can be different from your webmail credentials).

[Source](http://www.rainloop.net/docs/configuration/)

**Comment by WhiteFalcon77** [comment]
Thanks, but unfortunately those login details did not work either.

No, it's not the first time I have logged into admin.  I did it ages ago when sorting out the Contacts issue outlined above; there was no difficulty using my usual login.

Strange problem....

**Comment by megadr01d** [comment]
You say

> and my username and password for my email account aren't letting me in

and then

> there was no difficulty using my usual login.

Your email credentials are one thing (they're bound to your email server). Your admin credentials are another.
My guess is that you must have forgotten your admin credentials so I recommend reinstalling the latest version. It takes 5 minutes to set Rainloop's preferences from scratch.

**Comment by WhiteFalcon77** [comment]
Thanks  megadr01d, I'll do that.  Are there spam controls in the Admin section?

**Comment by megadr01d** [comment]
I'm not using Rainloop anymore (or any other selfhosting app since I don't have a domain anymore) but last time I checked there were [Sieve filters](https://github.com/RainLoop/rainloop-webmail/issues/994), if that suits you.

**Comment by WhiteFalcon77** [comment]
Thanks for your help megadr01d, I'll check that out.

**Comment by shmaltz** [comment]
My server (OpenLiteSpeed/CyberPanel) uses MariaDB. Is it possible to use the Address Book with this setup?

**Comment by BayInternet** [comment]
> My server (OpenLiteSpeed/CyberPanel) uses MariaDB. Is it possible to use the Address Book with this setup?

RainLoop supports MySQL so MariaDB should work without issue. See -> https://mariadb.com/kb/en/mariadb-vs-mysql-compatibility/

**Comment by shmaltz** [comment]
Thank you!
