### ISSUE TITLE
Signature trailing whitespace

### ISSUE THREAD

**Issue by ghost** [RainLoop/rainloop-webmail#270]
As far as I know the oficial way of starting a signature is with "-- " (note the trailing space). When composing a new email the trailing whitespace gets removed. 

The signature does get saved properly, though.

**Comment by ChoiZ** [comment]
Hi,

I search how to have a correct signature (with trailing space).
Maybe it can be fine to write this tip in an rainloop page like an FAQ or directly in account preferences page.

Best regards
