### ISSUE TITLE
Error conecting Gmail IMAP

### ISSUE THREAD

**Issue by felipeladislau** [RainLoop/rainloop-webmail#275]
I have a error conecting gmail server, the SMTP conect, but the imap don't
It says "conection timed out"

What do I do?

**Comment by web-ghost** [comment]
I faced same problem and can't connect with gmail imap error: stream_socket_client(): unable to connect to ssl://imap.gmail.com:993 (Network is unreachable)

**Comment by gigantium** [comment]
To solve this, you must re-enable Basic Authentication for Outlook in your Google Account Settings. This can be done via the “<a href="https://www.google.com/settings/security/lesssecureapps">Allow less secure apps</a>” page where you set it to “Enable”.
