### ISSUE TITLE
Reset admin password

### ISSUE THREAD

**Issue by saji89** [RainLoop/rainloop-webmail#28]
How can I reset or set a new password for admin user?

**Comment by ordinaryegi** [comment]
hello
i'd change admin password rainloop at application.ini, but i'm still can't login to admin panel, any solution?

**Comment by RainLoop** [comment]
The password must be hased.
There is only one exception (password = 12345).

Try to set admin_password = "12345" and go to Admin panel to change it to something new.

**Comment by scith** [comment]
Hello, how can I hash the password before inputting it in the *application.ini* file please?
Is it possible to do this via command line? (or changing the password via command line) Or API?

Thanks

**Comment by RainLoop** [comment]
You may use RainLoop PHP API:
```php
$_ENV['RAINLOOP_INCLUDE_AS_API'] = true;
include '<path-to-rainloop-folder>/index.php';

$oConfig = \RainLoop\Api::Config();
$oConfig->SetPassword('pa$$wOrd');
echo $oConfig->Save() ? 'Done' : 'Error';
```

**Comment by scith** [comment]
Thanks it works great! Is this API documented somewhere please?

**Comment by fabricetriboix** [comment]
Hi,

I am in the same situation. I tried modifying application.ini directly, or use the PHP code snippet, in both cases the web page says "authentication failed"...
I found a "logs" directory somewhere under the "data" directory, but it is empty. Apache logs do not tell anything useful...

What is going wrong here?

Thanks a lot for your help!

**Comment by fabricetriboix** [comment]
OK, for those who are have the same problem, please make sure the URL you enter ends with "?admin". Otherwise, logging as admin will fail, even with the correct password.

**Comment by JimmyKater** [comment]
errr...
as i am still a beginner with all of this i can't follow all advices here.
i am running raincloud as an app (5.0.1) in nextcloud (12.0.2). apparently i have installed it sometime earlier, once and set a password there (for admin user) which i completely forgot about.
so now i try to login with admin:12345 (as it ist still set in application.ini) but that doesn't work. "authentification wrong".
what do i need to do to (more or less step by step) to be able to log in... either with default password or with a new (and hashed) one

sorry for asking these newbie questions as for all others it seem to be clear what to do from the hints above :(

**Comment by JimmyKater** [comment]
ha! 
using https://mydomain.tld/index.php/apps/rainloop/app/?admin did the trick!
i manually changed the address directly in my browser and then i could sucessfully enter the standards

**Comment by ubaldus** [comment]
> You may use RainLoop PHP API:
> 
> ```
> <?php
> 
> $_ENV['RAINLOOP_INCLUDE_AS_API'] = true;
> include '<path-to-rainloop-folder>/index.php';
> 
> $oConfig = \RainLoop\Api::Config();
> $oConfig->SetPassword('pa$$wOrd');
> echo $oConfig->Save() ? 'Done' : 'Error';
> 
> ?>
> ```

Hi, I am trying this on a nextcloud installation but it does change the password in the wrong configuration file and using a different salt:

/var/www/nextcloud/apps/rainloop/app/data/_data_/_default_/configs/application.ini 

in place of 

/var/www/nextcloud/data/rainloop-storage/_data_/_default_/configs/application.ini

**Comment by jerome-diver** [comment]
This application really need a FAQ page to explain users how to access admin rainloop page from nextcloud app. Do not deny it because the information changed many times and this definitely show it required a FAQ page to be more serious and respect users time.
Thank you for help users to access the admin page the easy way...

**Comment by manishalankala** [comment]
/var/www/html/rainloop/data/_data_/_default_/configs

**Comment by annaparker** [comment]
Guys, stupid thing, but if you think you entering valid password and doesn't work, remember it won't work on standard login page, you have to login by address: **https://yourdomain.tld/?admin**

**Comment by Weltolk** [comment]
> Guys, stupid thing, but if you think you entering valid password and doesn't work, remember it won't work on standard login page, you have to login by address: **https://yourdomain.tld/?admin**

same

**Comment by andyfw** [comment]
I tried several things in this list, but the one that works is the API code.   Take that code, make a file and put it in a secure place (NOT your WWW directory).  You can run it any time you want to reset the admin password, then log into the web interface and immediately change it to some thing more secure.  Yes, you do need the ?admin on the URL (you can change that in the admin panel if you want) but I would not have been here if it was that simple.  I never could get editing the config file to work, even with 12345.

**Comment by techdash** [comment]
> You can change the settings in the configuration file:
> 
> rainloop/data/_data_xxxx/_default_/configs/application.ini
> 
> [security] admin_login = "admin" admin_password = "12345"

This method worked for me. Just put in 12345 as password and you are all set to login and change admin password asap from the Rainloop admin dashboard.
