### ISSUE TITLE
Store PGP Keys in db

### ISSUE THREAD

**Issue by heubergen** [RainLoop/rainloop-webmail#280]
It would be so nice if you can add a feature to store PGP Keys in the db.

Just optimal, for security reasons.

Edit: I mean of course the public keys.

**Comment by Leryan** [comment]
A warning about security concerns can be a good way to inform users about the risk they take by pushing their key on the server.

Even if most of GPG users are already aware of such concerns…

**Comment by Corna** [comment]
I agree, but the storing of the private keys on the server should be discouraged (but allowed).
News?

**Comment by heubergen** [comment]
Sorry but just with a closing, will the question not answered...

Can the write please make a statement?

**Comment by el-dge** [comment]
Une piste : https://github.com/chtixof/pgpback_ynh
