### ISSUE TITLE
Send only accounts

### ISSUE THREAD

**Issue by bigz94** [RainLoop/rainloop-webmail#287]
Is it possible to have email accounts setup, which are send only? It woul be greate, if it is possible to change the outgoung email adress by just one click wen creating a mail. Since it is pretty easy to setup a forward I think that would be quite comftable to have all mails-addresses in one folder.

**Comment by RainLoop** [comment]
https://rainloop.uservoice.com/forums/223477-ideas-for-rainloop-webmail/suggestions/6207336-optional-per-identity-smtp-configuration
