### ISSUE TITLE
Contacts only from CardDAV Server

### ISSUE THREAD

**Issue by rhwilr** [RainLoop/rainloop-webmail#290]
It would be great if i could configure rainloop so it would only use a CardDAV Server for contacts.
The way it is now the user has to configure the CardDAV sync settings by himself. It would be nice if i could configure the settings for them in the admin menu.
I'm using a DAViCal Server which authenticates against the imap server. So the user logs in with the same login credentials as he uses to login to rainloop. The carddav url is like https://dav.example.com/caldav.php/john@examle.com/addresses/ so as far as I can see it should be possible to configure it generaly for all users.

**Comment by prologic** [comment]
Can we revisit this? I'm using RainLoop too and would like to use an external CardDAV server; radicale in this case.

**Comment by jkaberg** [comment]
I'd also like to see this (beeing able to set default carddav settings for all users in admin panel) 

@RainLoop

**Comment by extremeshok** [comment]
+1

**Comment by Zepmann** [comment]
Agreed. Suggested functionality:

1. For each domain: the option to configure CardDAV settings for all domain accounts. Remote synchronization can be enabled, and a URL for the CardDAV server can be specified. Note that the username can be part of the URL (as is the case with ownCloud), so a placeholder for the username (such as $u or something similar) should be supported.
2. For each domain: the option to make Rainloop use CardDAV exclusively (no local contacts). This ensures good integration between Rainloop and ownCloud.

The only limitation is that a single address book of the ownCloud installation will be available in Rainloop (chosen as part of the CardDAV URL). From a usability perspective, it would be acceptable when the default address book is used. The chosen URL would for OC 9.x be:
`http[s]://hostnameorip[:port]/remote.php/dav/addressbooks/users/$u/default/`

**Comment by jkaberg** [comment]
If you don't specify an addressbook it should fetch all from carddav server (atleast radicale does this). IDK how ownCloud does it.

**Comment by Zepmann** [comment]
@jkaberg Maybe ownCloud does the same. The point is: for this feature request it is not required that RainLoop supports multiple CardDAV address books (for each account).

**Comment by jkaberg** [comment]
@Zepmann would be sure handy if it did.

**Comment by extremeshok** [comment]
> Zepmann commented on May 24 • edited
Agreed. Suggested functionality:

For each domain: the option to configure CardDAV settings for all domain accounts. Remote synchronization can be enabled, and a URL for the CardDAV server can be specified. Note that the username can be part of the URL (as is the case with ownCloud), so a placeholder for the username (such as $u) should be supported.
For each domain: the option to make Rainloop use CardDAV exclusively (no local contacts). This ensures good integration between Rainloop and ownCloud.
As for the username and password, it can be assumed that they are the same as what is used to login. The only limitation is that a single address book of the ownCloud installation will be available in Rainloop (chosen as part of the CardDAV URL). From a usability perspective, it would be acceptable when the default address book is used. The chosen URL would for ownCloud 9.x be:
http[s]://hostnameorip[:port]/remote.php/dav/addressbooks/users/$u/default/

>

**Comment by zeigerpuppy** [comment]
This is really an essential feature.
There should be an option to set a default URL for the CardDAV server.
Radicale can authenticate against IMAP so this would make the whole process relatively automatic (and would also work for CalDAV).
Ideally a new user for a domain should have access to the domain's default CalDAV server the first time the log in, in the same way that sieve is currently configured.

**Comment by infrafast** [comment]
Hello, I am evaluating different webbased mail client option and definitely agree we would need to bind CARDDAV to domain or user account automatically to avoid the user making his own setting. 
BR

**Comment by hoo2** [comment]
Hello. I am using version 1.12 and it seams the CardDav option is already available. I have my own nextcloud server and I thought it would be nice to enable this feature.

The problem is that there is no documentation entry for the URL format required for "Addressbook URL" field. In other words, what part of the nextcloud address should we put in the field? A example in the UI would be nice also.

So what do we put in field?
