### ISSUE TITLE
"domain is not allowed" - cannot login

### ISSUE THREAD

**Issue by ssdnvv** [RainLoop/rainloop-webmail#296]
Hi all,

I just installed and configured rainloop on a synology nas, but cannot get it to work, as I cannot login. Just always got the following message. Neither [user]@mydomain nor [user] + password work.
I searched the web for a hole day now but didn't get any glue on how to do it. Configured everything via https://mydomain:port/rainloop/?admin as mentioned in how-to's.

![unbenannt](https://cloud.githubusercontent.com/assets/8572055/4065931/39436a04-2e1f-11e4-84ab-2c46eb4cdeef.PNG)

Regards,
ssdnvv

**Comment by ssdnvv** [comment]
Hi jedufa,

as rainloop does not fit my needs I recently uninstalled it. Therefore I'm sorry for not being able to help you.

KR

**Comment by jedufa** [comment]
ok thanks. did you manage to get it to work properly? What was your main
issue with it?

**Comment by ssdnvv** [comment]
* I use 3 IMAP-accounts from different email-providers (short: A-C)
* configured my mailserver to collect the emails and save them to my own IMAP-account (short: D)

- It is not possible to send emails using SMTP-servers from providers A-C while logged on to D. In order to send an email with the A(/B/C)-SMTP-server, I have to login with rainloop-Account A(/B/C). [main issue]
- I'm not able to move an email from A to C-D (and vice versa) from within rainloop [smaller issue]

**Comment by boku78** [comment]
Hi, i am very new to rainloop and still just testing.
I do have the same problem as mentioned above. When i try to login to rainloop through owncloud i get "Domain is not allowed", when i login through the "normal" webinterface, i am able to login just fine.
Owncloud and rainloop are runing and both on the same server under the same domain.
I also confidured the domain in rainloop in the admin section.

I do need some advice where i should change or enter the domain.

THX CU Boris

**Comment by Logicbloke** [comment]
Having a similar issue. Domain is in the list of domains but it's not letting me login saying "Domain is not allowed".

**Comment by Logicbloke** [comment]
Apparently I needed to go to /rainloop?admin and login as an admin and add my new domain to the domains menu.

**Comment by cloudsnife** [comment]
why my rainloop authentication failed?
please help

**Comment by tommylux** [comment]
Hi, I'm really struggling to get this to work with my synology nas. @ssdnvv confirmed he got his working with the synology nas - can you confirm what settings you have in mailstation and which parameters you have configured in Rainloop? Thanks.

**Comment by tommylux** [comment]
Got it working:

> Ok, you need to enable "Use short login" setting in your domain configuration.

This worked for me..

**Comment by boku78** [comment]
My fault was that i accessed the wrong admin-Panel. I had two installations of rainloop. One standalone and one in my owncloud. These are indeed different independent installations. If you are you rainloop wihtin owncloud than you have to use / find that admin-Panel to configure the allowed Domains.
In the meantime i have owncloud 9 und aren't using rainloop within oc anymore, I do use rainloop standalone.

**Comment by ElucGeek** [comment]
Hello, I have the same issue as described here. In admin control panel I have added 2 domains:
External hosted email: 
Name: mydomain1.tdl
Serveur: mail.externalprovider.tdl
It works fine

Internal hosted email:
Name: mydomain2.tdl
Server: mydomain2.tdl (I have tried also mail.mydomain2.tdl has it work in regular email client)
Short login enabled

Then I go back to user account, add an account, enter user@mydomain2.tdl + password of the user and it fails like shown above.

For those who solved this, how did you do ?

Also I've found the plugin to bypass SMTP server that is the problem @ssdnvv did have above, you he can use another SMTP server for its self-hosted email.
https://github.com/RainLoop/rainloop-webmail/tree/master/plugins/override-smtp-credentials

Thank you for your help

**Comment by bigkiandi-projects** [comment]
## domain is now allowed

this is working solution that you should try. Please take a look in image below : 

<img src="https://goldentranswisata.com/strorage/rl.png">

So, First step is that you must fill name input as you email domain after @ character. example if your email domain is user@mydomain.com, you should typing @mydomain.com. SEE ON THE RED INFORMATION ON THE RIGHT SIDE.

**Comment by sirio81** [comment]
On debian 10 the admin panel is disabled by default.
To enable it:

```
nano /etc/rainloop/application.ini
allow_admin_panel = On
```
