### ISSUE TITLE
"Can't get message list" if "Use threads" is activated

### ISSUE THREAD

**Issue by JanWelker** [RainLoop/rainloop-webmail#311]
Dear Rainloop Devs,

I am running Raindrop in version 1.6.9.164. If I do activate "Use threads" in the settings my inbox and all containing folders are no longer shown. The following error message appears "Can't get message list". If I disable the feature again everything goes back to normal and my mail is shown. My inbox folder is not very big. It contains less than 50 mails. But some of my sub folders have a couple of ten thousand mails in it.

Regards,
Jan

**Comment by RainLoop** [comment]
Hi, sorry for not replying in time.
This problem is still relevant?

**Comment by JanWelker** [comment]
Looks like this problem is not occurring anymore. I am using 1.7.2.226

**Comment by RainLoop** [comment]
Thanks!

**Comment by jeekajoo** [comment]
Hi,
A folder that have 7053 messages is not displaying ("Can't get message list") if "Use threads" is activated.
Using last version 1.9.4.394

**Comment by jeekajoo** [comment]
Might be worth reopening this, @Rainloop
