### ISSUE TITLE
Remember me option at login screen is not remembered.

### ISSUE THREAD

**Issue by ervee** [RainLoop/rainloop-webmail#315]
Hi!

For some features to work, like mailto links, you have to check the "Remember me" option at the login screen. But every time I logout, the checkbox is blank again. And this makes it easy to forget to check it and then some stuff does not work...

Is this a bug, or a feature request to have this checkbox remember himself? ;-)

**Comment by RainLoop** [comment]
Done

**Comment by ervee** [comment]
Is there a new option like cookie for sign_me_auto? Or do you set a default behavior there and my browser will rember when I tick/untick the checkbox?

**Comment by RainLoop** [comment]
Your browser will rember when you tick/untick the checkbox.

**Comment by ervee** [comment]
Cool, thanks!
