### ISSUE TITLE
Support for Delivery Status Notifications (DSN)

### ISSUE THREAD

**Issue by kupschke** [RainLoop/rainloop-webmail#325]
Hello,

it would be nice to see Delivery Status Notifications (DSN) implemented in Rainloop.

https://en.wikipedia.org/wiki/Delivery_Status_Notification

**Comment by bms8197** [comment]
I agree!

**Comment by erasmuswill** [comment]
+1

**Comment by Rbeuque74** [comment]
:+1:

**Comment by erasmuswill** [comment]
+1

**Comment by ervee** [comment]
RainLoop is not the place to implement DSN's. That's the MTA's job. Not a webmail client's job. You could fake a DSN with Sieve (configurable trough RainLoop) I suppose...

**Comment by kupschke** [comment]
I just need a function for requesting "Delivery Status Notifications" from recipients MTA.
This is a nice feature which is supported for a long time in thunderbird and roundcube.

**Comment by ervee** [comment]
There is already a "request a read receipt"

![read](https://cloud.githubusercontent.com/assets/4435930/6315944/dc742586-ba12-11e4-9882-305b9516fa51.JPG)

So I guess there should indeed also be a "request delivery", like in other mailers such as Outlook.

![requests](https://cloud.githubusercontent.com/assets/4435930/6315957/29977e30-ba13-11e4-851d-14542993252a.JPG)

**Comment by ervee** [comment]
Tested new delivery receipt and it's working for me! Note that not all recipient servers will send a DSN so not getting a DSN will not always mean the message was not delivered.
