### ISSUE TITLE
ownCloud Plugin Enhancement Request: Email Attachments

### ISSUE THREAD

**Issue by kneiser** [RainLoop/rainloop-webmail#326]
It would be nice to have an option to be able to save email document attachments in to ownCloud (WebDav?). A dialog should be displayed asking which folder in the user's ownCloud account to store the attachments (a default location could also be configured in the setup).

**Comment by RainLoop** [comment]
Done.

![bd12f52c-eb6e-11e4-9ddd-896dfecca0b4](https://cloud.githubusercontent.com/assets/5530092/7550636/1e564704-f672-11e4-8e1f-1f0e60b78928.gif)

**Comment by conradhagemans** [comment]
Nice. And the other way around. Insert attachement from owncloud?
