### ISSUE TITLE
top/bottom posting

### ISSUE THREAD

**Issue by ftoledo** [RainLoop/rainloop-webmail#327]
any way to change the top posting behavior?

**Comment by RainLoop** [comment]
Hi, sorry for not replying in time.
Can you please explain your issue in more detail?

**Comment by ervee** [comment]
I think he wants an option to (default) insert new text at the bottom when replying/forwarding email.
https://en.wikipedia.org/wiki/Posting_style#Top-posting
This is mostly done in (sysadmin) mailing lists.

If I reply to such list I just move my signature to the bottom and start my reply just above my signature. A simple manual cut'n'paste...

**Comment by ftoledo** [comment]
when reply the cursor position and signature still on top of quote text. i expected to fall below
![pantallazo](https://cloud.githubusercontent.com/assets/95441/6044390/acd3aa12-ac71-11e4-8ff5-d2c3d2ddc657.png)

**Comment by amdavidson** [comment]
This seems to still be an issue in 1.9.3.365 (w/ Chrome 47.0.2526.80). I think that having a top / bottom posting setting would clear it up.

Right now, when I use the plain text editor and have a signature configured, it gets top posted and my cursor starts at the bottom of the email. This is very unconventional and seems to be a hybrid of top posting / bottom posting.
