### ISSUE TITLE
incorrect thread grouping

### ISSUE THREAD

**Issue by ftoledo** [RainLoop/rainloop-webmail#328]
i have 2 thread with same subject 
but 1st have 1 message with one person and 2nd have 4 messages form other persons
in the list i see as one thread with 5 messages that is incorrect (from my point of view)

i think that i would have to see 2 items in the list (although same subject)
im attach a screenshot
![webmail_thread_error](https://cloud.githubusercontent.com/assets/95441/4367996/535ceae0-42e3-11e4-8f20-16cecf13bf05.png)

**Comment by megadr01d** [comment]
@ftoled There's a new [thread browsing method](https://github.com/RainLoop/rainloop-webmail/issues/523) in the [lates version](https://github.com/RainLoop/rainloop-webmail/issues/479#issuecomment-84430407).

**Comment by ftoledo** [comment]
Good news! I will test asap.
