### ISSUE TITLE
[PGP] priv key w/ multiple User IDs

### ISSUE THREAD

**Issue by cybershaman** [RainLoop/rainloop-webmail#346]
I have an OpenPGP key that works for both my main email accounts as per having one email defined as primary user ID and the other as additional user ID.
For illustration purpose please see my public key here [1].

When importing the private key to Rainloop and trying to sign/encrypt a mail I can only use one of my identities/email addresses and not both. Paradoxically that is only with the email address that is set as additional user ID in my key. The error message is: "No private key found for [identity/email]."

[1] http://pgp.mit.edu:11371/pks/lookup?search=0x58ABCEA2

**Comment by RainLoop** [comment]
#379
