### ISSUE TITLE
SMTP Connection to server not possible

### ISSUE THREAD

**Issue by Numelle** [RainLoop/rainloop-webmail#347]
Hi all,

I have the issue that rainloop does not connect to all necessary SMTP servers. (Installed version is 1.6.9.167) The server I want to connect to is the mailserver for my own domain, hosted by a Third-Party Unit. Hence I do not have access to the Webserver itself. When I provide the address of my SMTP server to rainloop and click "Testconnection" it test for about 5 seconds and then says "Connection Timeout". If I connect this SMTP server with other Webbased sending tools (GMAIL,GMX,...) I perfectly can connect to this SMTP server and also send mails.
The security settings have been checked and compared with the working PHP Webmailers. Additionally I changed the security settings within Rainloop to verify whether there is another Sec. setting necessary but then after "Test Connection" it directly says "Connection Timed out"
According to my test I assume that the server in general is reachable but does not accept the SMTP request via PHP.

This brings me to my questions:
- Are you able to determine the difference between Rainloop and other WebmailClients and Make the same changes to the Rainloop PHP SMTP send script?
- Is this a known behaviour and do you have any information I can provide to my administrator like: "Change this setting and this setting and it works like charme....." ;-)
- According to the Changelog New Version 1.6.10.182 doesn't solve this behaviour, should I install anyway?
- Can I do anything directly for testing and providing you the corresponding information?

Many thanks for your support

Numelle

**Comment by cfbear3** [comment]
i am having the same problem.... but with a block550... how to fix it??? thanks...
