### ISSUE TITLE
Logout Rainloop

### ISSUE THREAD

**Issue by manirathinam** [RainLoop/rainloop-webmail#353]
Hi,

I have integrated rainloop in my website using iframe. in my site having only one login screen. so, when i logout my website at the same time i need to logout rainloop account also. how can i do this. is it possible? Please, help me...

**Comment by afilipecb** [comment]
Hi,

I have the same problem but this solution does not work out. As I am using iframe, I do not see the cookies. What will be another solution?

Thanks...
