### ISSUE TITLE
Conversations

### ISSUE THREAD

**Issue by ebal** [RainLoop/rainloop-webmail#361]
I am not quite sure that this is an issue but here it is:

Lets say that we have a conversation with 10 emails - all unread. 

When clicking on the conversation - rainloop shows me only the last email of the thread.
To review all the emails i have to close the current email, expend the conversation (click on the number of messages on the conversation list) and then click to every email separately. 

Is there a way to navigate through the emails of a thread/conversation, without manually expend the conversation ? 

If not - i would be great (i guess not only for me) with j/k keys to navigate through the emails of a conversation without ever leaving your message view tab.

Thanks in advance.

**Comment by megadr01d** [comment]
@ebal Thread browsing was improved in the [latest](https://github.com/RainLoop/rainloop-webmail/issues/523) version.

**Comment by RainLoop** [comment]
There are two ways for thread browsing:

1) Conversation view (as Gmail)
2) Thread list in a message list.

For rainloop I have chosen the second one:

![c108daac-eb6e-11e4-9478-79fadd922c46](https://cloud.githubusercontent.com/assets/5530092/7525422/fa7e33b6-f511-11e4-9a12-b6218aa1e9d7.gif)
