### ISSUE TITLE
Bugs regarding the new message pop-up

### ISSUE THREAD

**Issue by ervee** [RainLoop/rainloop-webmail#365]
Hi,

I have several issues related to the pop-up notification.

1) When:
* I have RainLoop open
* And an email message open (preview pane disabled)
  * The new message pop-up is never shown.

2) When:
* I have RainLoop open
* And an email message open (preview pane disabled)
* Switch to another Tab (FFv33)
  * (I see the new message pop-up when a new email arrives)
* Click the new message pop-up
  * (FF switches to the RainLoop Tab, still showing the opened email message)
* Then press the delete keyboard key
  * The message is deleted, but not closed. The Esc key does work though.

**Comment by RainLoop** [comment]
Can I close this issue?

**Comment by ervee** [comment]
It's not a big issue and I don't know if it still happens so I'll just close the case.
