### ISSUE TITLE
An error occured, please refresh the page and try again

### ISSUE THREAD

**Issue by NalleBerg** [RainLoop/rainloop-webmail#370]
At login I get "An error occured, please refresh the page and try again" and I can't get any further. I installed by downloading the .zip-file. 
Here is my log entry in my apache-log I get every time I try to log in:

---

[Fri Nov 07 14:58:46 2014] [error] [client 81.167.156.232] PHP Fatal error:  Class 'MailSo\Log\Enumerations\Type' not found in /var/www/webmail/rainloop/v/1.6.11.191/app/src/RainLoop/Providers/ChangePassword.php on line 54, referer: http://webmail.nalle.no/

---

I am running it on another server. Had some problems installing that too, but after tweaking just a little bit in some setting files I got rid of the errors, and that one is working as it' supposed now.

Liking RainLoop sooooo much better than Squirrelmail I' am trying to switch, but I ran into this hurdle that I think I need some help to solve.

**Comment by XavierTolza** [comment]
Hello! First I want to say your project looks amazing and I hope i'll be able to make it work and test it :smiley: 
I have the same problem and i've been looking around for a while on internet now, I haven't seen a solution that worked for me, it looks like it has been adresses several times... Do you now have more knowledge on this issue now?

I'm using PHP7 with ubuntu server 16.04 and nginx server. I followed [this tutorial](https://www.linuxbabe.com/mail-server/install-rainloop-webmail-ubuntu-16-04).
Here is my [phpinfo](https://drive.google.com/file/d/0B-bHYZtkhv0aVWU2T0c1ODhwSXc/view?usp=sharing), and my nginx conf file:
```
server {
   listen 8083;
   server_name planza.ddns.net;

   root /var/www/rainloop;
   index index.php index.html;
	
   access_log /var/log/nginx/rainloop_access.log;
   error_log /var/log/nginx/rainloop_error.log;
   
   location / {
       try_files $uri $uri/ /index.php?$query_string;
   }

   location ~ ^/(.+\.php)$ {
        try_files $uri =404;
        fastcgi_pass unix:/run/php/php7.0-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include /etc/nginx/fastcgi_params;
   }
 
   location ^~ /data {
       deny all;
   }
}
```
Hope you'll be able to help!

**Comment by Luskan777** [comment]
Hello ,

I had the same problem, and the problem was due to a plugin I had installed, the fix was the removal of this plugin, hope it helps
