### ISSUE TITLE
Plugin doesn't work with the latest version

### ISSUE THREAD

**Issue by sandrodz** [RainLoop/rainloop-webmail#373]
I wrote this plugin for 1.6.3.715 version: https://github.com/wearede/rainloop-change-password-plugin-mysql

It displays invalid plugin notice when used on recent versions of rain loop, so what has changed? Plugins shouldn't break out of the blue :S

**Comment by sandrodz** [comment]
Hi, sorry for not replying in time. Your solution was correct, plugin folder name was the culprit. Thanks!

**Comment by RainLoop** [comment]
Ok, thanks!
