### ISSUE TITLE
Write email RTL

### ISSUE THREAD

**Issue by ammoss** [RainLoop/rainloop-webmail#375]
Hello, 
I can't write Arabic / Hebrew.....
how to change the side? (CTRL+SHIFT) don't work for me :(.

**Comment by hadifarnoud** [comment]
despite setting direction to RTL, emails are still sent as LTR. do you have this issue too @ammoss 
<img width="826" alt="screen shot 1395-10-28 at 5 45 47 pm" src="https://cloud.githubusercontent.com/assets/589808/22023766/cb36b042-dcdc-11e6-8b39-26ced5645ae8.png">

**Comment by mahyard** [comment]
@hadifarnoud, I checked now. Every thing works well for me. ( ver.1.12.1 )
![image](https://user-images.githubusercontent.com/21006810/44004776-85ac2d2c-9e7d-11e8-8fc8-2bf09894a96b.png)

**Comment by hadifarnoud** [comment]
@mahyard glad to see new version fixed the issue
