### ISSUE TITLE
CTRL-Enter for sending new email does not work anymore

### ISSUE THREAD

**Issue by ervee** [RainLoop/rainloop-webmail#387]
Hi,

I just updated to the latest version and now CTRL-Enter for sending new email does not work anymore. I also do not see the shortcut in the Help pop-up anymore.

Was this option removed by accident or for some reason? I would like it back if that's okay with you :)

**Comment by szewczyk-it** [comment]
What do you think to add this option as checkbox to the admin panel?

**Comment by BenoitDuffez** [comment]
What do you think about this setting + a timer to allow to [cancel sending](https://rainloop.uservoice.com/forums/223477-ideas-for-rainloop-webmail/suggestions/7686390-undo-sending-mail-within-5-60-seconds)?
