### ISSUE TITLE
2 Step verification & Gmail not working

### ISSUE THREAD

**Issue by Hoekynl** [RainLoop/rainloop-webmail#389]
Hello Rainloop,
I use your webmail and its awesome!
The only problem is : I cant access Gmail, and Outlook via the panel. (cant login)
And the 2 step verification doesnt work. The code just doesnt work for me, it does generate a code in the Google Authenticator app and a different app, but the codes just dont work.

http://s29.postimg.org/5cu58qx47/Error.png

**Comment by TameOfGroans** [comment]
why are /you/ employing 2FA? if you do not encrypt all mail through a Google property can you really have security without privacy? (hint not yes)

**Comment by RainLoop** [comment]
RainLoop uses its own "2 Step verification" protection.

Read https://support.google.com/mail/answer/1173270?hl=en if you want to use gmail account with 2-step verification.

**Comment by RainLoop** [comment]
https://support.google.com/accounts/answer/185833

**Comment by Remrem84** [comment]
Hello,

I just did that procedure. That works the first time. But when I want to connect with my google acocunt the second time I have the "authentication failed" message (I use google authenticator app on my android phone to generate codes).

Can you help me ?

**Comment by mat-m** [comment]
I just created it. 
* You need to use the application password to log into Rainloop
* You should not use authenticator. If you did, you probably are mixing rainloop double auth with google. I don't know what to expect from that.

IMO, first try by login to rainloop using your full mail address and the app password.
