### ISSUE TITLE
RainLoop logs off while loading mailbox

### ISSUE THREAD

**Issue by shade511** [RainLoop/rainloop-webmail#396]
Hi,

I have a issue while loading some of my mailboxes. Most of them works fine (I have 9 mailboxes added so far) but some of them just don't work. They start to load, but at the end of the loading process it just fall back to login screen. 

I checked mailboxes itself, they are working fine in other clients. Also, RainLoop tested the connection, there was no problem on network side. Mailboxes are not significantly bigger than other ones. 

Might it be a issue with number of mailbox I have added?

Thanks.

**Comment by RainLoop** [comment]
The problem should be fixed in current version of RainLoop Webmail.

**Comment by NicolasCARPi** [comment]
I have the same issue with 1.7.2.226. So I tried to git clone the repo. But I get : 
Loading
An Error occurred,
please refresh the page and try again. 

In the logs : 
[10:11:08.285][88a1431c] INFO[DATA]: [DATE:09.01.15][RL:0.0.0][PHP:5.5.9-1ubuntu4.5][IP:2a01::::][PID:7537][nginx/1.4.6][fpm-fcgi]
[10:11:08.286][88a1431c] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,sslv3,tls]
[10:11:08.286][88a1431c] REQUEST[NOTE]: [GET] http://webmail.example.com/
[10:11:08.291][88a1431c] INFO[MEMORY]: Memory peak usage: 768KB
[10:11:08.291][88a1431c] INFO[TIME]: Time delta: 0.011404991149902

**Comment by shade511** [comment]
the most of the issues were fixed by current patch, so it had to be problem with suhosin. (thanks!)

one last mailbox keeps doing it, but it has the most folders. my default android email client creates separate outbox folder for every session (I have no idea why) so I have around 2000 of them in my mailbox. that takes a lot of memory to load and then crashes.

**Comment by RainLoop** [comment]
Can you give me RainLoop webmail logs (again, for account with 2000 folders)?

Thanks!

**Comment by RainLoop** [comment]
@NicolasCARPi 
can you tell me the URL of your installation?

**Comment by NicolasCARPi** [comment]
@RainLoop, no I can't give you an url because I removed it. But I'd be happy to provide you with more info if needed.

**Comment by siramthar** [comment]
Hello, 
I have the same issue, I can log in with an account, but not with a newly created one.
the Rainmail log shows: 
[14:14:08.528][a0a7732f] IMAP[DATA]: < * BYE Internal error occurred. Refer to server log for more information$
[14:14:08.528][a0a7732f] IMAP[ERROR]: Stream Meta: Array
(
[crypto] => Array
(
[protocol] => TLSv1.2
[cipher_name] => ECDHE-RSA-AES128-GCM-SHA256
[cipher_bits] => 128
[cipher_version] => TLSv1.2
)

  [timed_out] => 
[blocked] => 1
[eof] => 1
  [stream_type] => tcp_socket/ssl
[mode] => r+
[unread_bytes] => 0
 [seekable] =>
)
IMAP[ERROR]: MailSo\Net\Exceptions\SocketReadException: MailSo-Net-Exceptions-SocketReadException (NetClient.php ~ 515) in /var/www/rainloop/rainloop/v/1.12.0/app/libraries/MailSo/Net/NetClient.php:515

Does anyone have a clue?
