### ISSUE TITLE
[Enhancement] Always show active mail account in UI

### ISSUE THREAD

**Issue by deMattin** [RainLoop/rainloop-webmail#398]
Hi,
there's one thing, I'm really missing in rainloop in everyday use:

I use many different mail accounts and in the interface I'm not able to see, which account is the actual one, 

I know, that there is a mouse over info on the account selector, but it would be a great thing, if I ALWAYS would be able see which account is the actual one - like an "always active mouse over" at this position.

![rainloop](https://cloud.githubusercontent.com/assets/5565503/5591335/3ab3cace-9156-11e4-956b-7830eab14548.png)

What do you think about this?

**Comment by RainLoop** [comment]
Ok :)

**Comment by deMattin** [comment]
thx :+1:

**Comment by bsm33** [comment]
I subscribe to deMattin's idea!

**Comment by RainLoop** [comment]
Done!

**Comment by bms8197** [comment]
Thanks for adding that... There is an issue with that option though. See issue #412 (I just added it)
