### ISSUE TITLE
Attachment Preview

### ISSUE THREAD

**Issue by quinnwizard** [RainLoop/rainloop-webmail#40]
Loving Rainloop.  I have replaced my Roundcube webmail client permanently.  

One feature that I would really like to see is an attachment preview option.  Especially for .pdf attachments.  Right now, when there is an attachment, I have to download it then open it.

Thanks, and keep up the good work.

**Comment by maderluc** [comment]
hi, i cant preview PDF attachements, i have the newest version installed! is there a manual config i need to set?

**Comment by ervee** [comment]
I'm also interested. When I click the PDF/eye besides the attachment a new tab briefly opens but then I'm presented with a download/save option.

In IE11 I even don't have a preview option at the PDF attachment.

**Comment by maderluc** [comment]
update: it works perfectly on Chrom browser! with Mozilla / Iceweasel it doesn't even opens up a new tab!

**Comment by Med-All** [comment]
Is this was fixed? My Rainloop contains code

```
		if (Globals.bAllowPdfPreview && window.navigator && window.navigator.mimeTypes)
		{
			Globals.bAllowPdfPreview = !!_.find(window.navigator.mimeTypes, function (oType) {
				return oType && 'application/pdf' === oType.type;
			});

            if (!Globals.bAllowPdfPreview)
            {
                Globals.bAllowPdfPreview = (typeof window.navigator.mimeTypes['application/pdf'] !== 'undefined');
            }
		}
```

but only Chrome can preview. Firefox and IE11 are not even displaying "preview" eye icon.
