### ISSUE TITLE
No more mark as unread option in menu

### ISSUE THREAD

**Issue by ervee** [RainLoop/rainloop-webmail#404]
Hi,

I noticed the message options menu has moved from the top to a dropdown menu inside the message header. I don't think it is better, frankly I think it is worse :) But that's my optinion. Nevertheless, I now can't find the option to mark a message as unread.

![capture](https://cloud.githubusercontent.com/assets/4435930/5681138/e983b396-9815-11e4-899e-cc1aecb55685.JPG)

I can still use the "U" hotkey, but still, is this a bug?

Ralf.

**Comment by RainLoop** [comment]
This menu never had this option.

>  I don't think it is better, frankly I think it is worse.

I understand, but it is necessary for bottom preview view and conversations (threads) in future.

**Comment by ervee** [comment]
Crap, you are right :)

![capture](https://cloud.githubusercontent.com/assets/4435930/5719220/bf8f878c-9b16-11e4-8a91-e9d02f716156.JPG)
