### ISSUE TITLE
Email display truncated

### ISSUE THREAD

**Issue by Leryan** [RainLoop/rainloop-webmail#405]
Hi,

I have a florent-cx@live.fr address, and the up-right corner displayed address is truncated to "florent-".

```
<div class="accountPlace" data-bind="text: emailTitle()">florent-cx@live.fr</div>
```

Bogus emailTitle()?

**Comment by Leryan** [comment]
The HTML code:

<div class="accountPlace" data-bind="text: emailTitle()">florent-cx@live.fr</div>

Bogus emailTitle()?

**Comment by RainLoop** [comment]
Thanks! It will be fixed in the next version.
