### ISSUE TITLE
"Authentication failed" after upgrade to v1.7.2.229 while logging into admin panel

### ISSUE THREAD

**Issue by shivamtiwari93** [RainLoop/rainloop-webmail#408]
I just upgraded my Rainloop Mail to v1.7.2.229 using the option in the Admin Panel. After the upgrade I lost access to the admin panel and started receiving "Authrntication Failed" message using the same credentials.

I modified data/.../appliction.ini to the following 

```
; Login and password for web admin panel
admin_login = "admin"
admin_password = "pass123!@#"
```

But when I try to use this combination to login to the admin panel I get the following

![screenshot 2015-01-11 17 29 26](https://cloud.githubusercontent.com/assets/5646131/5695131/93cd833e-99b7-11e4-92d6-3bc13203b6d0.png)

I'm not facing problems with normal email accounts. Only admin panel seems to have a problem. I encountered this only after the upgrade.

Any help would be great. Thanks!

**Comment by RainLoop** [comment]
Sorry for that, but admin password should be hashed (for security reason).
There is only one exception: password 12345 (for backward compatibility).

This means that you need to set "12345" as your password in application.ini.
After that you can change it to your real password through admin panel.

**Comment by shivamtiwari93** [comment]
That totally fixed the issue. Thanks. :+1:

**Comment by cgaulay** [comment]
Hi,

i've got the same problem but in my application.ini, password is already set to "12345".
Login failed all the time.
Have you any idea ? 

Thanks in advance.
Regards
