### ISSUE TITLE
Feature Request: a smart forlder for unread messages

### ISSUE THREAD

**Issue by namezk** [RainLoop/rainloop-webmail#409]
Thank you for all your work on this very useful piece of software.
Outlook has a very handy feature, it allows the user to view all unread messages by selecting a "smart" folder called Unread.
Would it be possible to implement this feature in RL?

Thanks.

**Comment by RainLoop** [comment]
https://rainloop.uservoice.com/forums/223477-ideas-for-rainloop-webmail
