### ISSUE TITLE
Read Receipt

### ISSUE THREAD

**Issue by quinnwizard** [RainLoop/rainloop-webmail#41]
Another feature that I think would be great would be the option to request a read and/or delivery receipt for emails.

Just a suggestion.

Thanks guys.

**Comment by cypriotxx** [comment]
how can we enable this two receipt feature as default for all accounts ?

**Comment by ShamimIslam** [comment]
Read receipts are the worst idea on the planet and an invention of Microsoft.

Imagine this scenario. You have social engineering phishing. You open the email that has a read-receipt enabled. 

Rainloop without any notification sends the notification to the user that the email was opened. Now the attacker knows a real email address.

Let's not do this.
