### ISSUE TITLE
Performance Question

### ISSUE THREAD

**Issue by namezk** [RainLoop/rainloop-webmail#410]
RL is pretty fast already, but I was wondering what else can be done to speed it up besides memcached?
Is there an optimal setup for best possible performance?

**Comment by RainLoop** [comment]
Yes, you can use it to speed up the cache.

```ini
[cache]
; Can be: files, APC, memcache
fast_cache_driver = "files"
```

and
```ini
[labs]
fast_cache_memcache_host = "127.0.0.1"
fast_cache_memcache_port = 11211
fast_cache_memcache_expire = 43200
```

But I prefer to use the APC.
