### ISSUE TITLE
Multiple Domains

### ISSUE THREAD

**Issue by beli3ver** [RainLoop/rainloop-webmail#411]
Hell
I have a Ubuntu Server with postfix and Some domains in virtual mailboxes
Is there a way to handle all the domains
Thx

**Comment by RainLoop** [comment]
Yes, domain name supports wildcard.

![wcdn](https://cloud.githubusercontent.com/assets/5530092/5702257/9521405c-9a68-11e4-8adc-263acd1a4beb.png)
