### ISSUE TITLE
Error displaying full email address in the right side of the screen

### ISSUE THREAD

**Issue by bms8197** [RainLoop/rainloop-webmail#412]
There is an issue with displaying full email address in the top right section of the screen (next to the settings button).

I suppose the problem is with the length of the email address (in my case, the email is: admin@linux-master.ro). If I am using another email account like user@abcd.ro, the email is fully displayed.

Where I am supposed to modify the length of the variable for the email address in order to be able to see the full email address? See print screen attached.

Thanks,
Bogdan
![rainloop_email](https://cloud.githubusercontent.com/assets/7985374/5700059/d1948794-9a3e-11e4-827b-ab7865dd8c62.JPG)

**Comment by deMattin** [comment]
I don't think, the problem depends on the length of the account name because I use longer mail names without any problems.
I suspect the problem in the "-" character in the domain name.

**Comment by bms8197** [comment]
deMattin: actually you are right. I just checked all my email accounts and only those using the "-" character in the domain name are not correctly displayed. Thanks for the tip

**Comment by RainLoop** [comment]
This problem is already fixed in the last release. Try to update your installation.

**Comment by bms8197** [comment]
Ok, thank you!
