### ISSUE TITLE
Username not part of the mail adress

### ISSUE THREAD

**Issue by Vijabei** [RainLoop/rainloop-webmail#413]
Hello,

I am using mail accounts with user names that are not part of the mail address

Example: foo.bar@example.com, login name is "1756582_1-mail"

I tried to use a workaround like using a wild card in the server setting: Domain = 1756582_1*
But in the login it is mandatory to enter a full mail adress. Also the workaround to use a non existing mail address containing the user name in combination of the short login option is not the final solution. It let me logging into the account and fetching the mails, but i cant send any mails with the true mail address.

Is there a solutiuon planned?

**Comment by ervee** [comment]
Can't you use the Plugin "custom-login-mapping" ?
Configure it with
```
foo.bar@example.com:1756582_1-mail
```
Then login using the email adres. I use this and it works perfectly.

**Comment by Vijabei** [comment]
Ah, thx. I did not see this plugin. It is working now.

This has to be done for all users by the admin? Is there a way to enter this by the users themself?

**Comment by RainLoop** [comment]
> This has to be done for all users by the admin? Is there a way to enter this by the users themself?
Unfortunately, no (for security reasons).
