### ISSUE TITLE
Set imap_folder_list_limit from admin interface

### ISSUE THREAD

**Issue by Leryan** [RainLoop/rainloop-webmail#414]
The imap_folder_list_limit is not settable from the web interface.

A friend has 245 folders and the default limit is to 200.

Also, there is no message telling users they have too much folders and all cannot be displayed.

But first, making this parameter available to modification from web interface would be a nice thing.

Thanks

**Comment by Leryan** [comment]
Hi,

Thanks for this, but how can I test this change by cloning from master?

I guess I have to "build" something, like for minifying javascript components, but how do you accomplish that?

Thanks

**Comment by RainLoop** [comment]
> I guess I have to "build" something.

Yes.

```bash
cd /var/www/rainloop/
npm install gulp -g
npm install
gulp
```
