### ISSUE TITLE
Force SSL failed

### ISSUE THREAD

**Issue by heubergen** [RainLoop/rainloop-webmail#416]
I try to force ssl connection and it works with all my application (php, html etc.) but not with that app.
I try to configure it in the apache2 site configuration file:
http://pastebin.com/4UWmpDTv

Edit: It seems like github will not display the hole code, so I had to upload it on a other place:

And also with different .htaccess configurations.

Nothing of it works, when I navigate to http://mail.***.ch, It will not forwarding to https://mail.***.ch
Tried with chromium and webkit based browsers.

Is there any mistake on my site or is this a issue on rainloop?

**Comment by RainLoop** [comment]
Well, this is not a RainLoop configuration.

Try to check the logs or read Apache's online documentation.

**Comment by heubergen** [comment]
It have to be a rainloop issue but I have now no time for discussion.

**Comment by RainLoop** [comment]
Interesting.
