### ISSUE TITLE
HTML Source - Sourcearea Plugin

### ISSUE THREAD

**Issue by mungle** [RainLoop/rainloop-webmail#417]
Hello, when I press the source icon all the text loses his formatting. I would like to keep it and operate on the code to make html changes... is it possible to fix or add an html source button?

I've tried to do it by mysef following the ckeditor docs without any success... :disappointed: hope someone could help...!

**Comment by mungle** [comment]
Found...
in application.ini under [labs] switch to On this option:
allow_html_editor_source_button = On

Yuppi!

**Comment by RainLoop** [comment]
Very well :)
