### ISSUE TITLE
[Question] PGP/MIME?

### ISSUE THREAD

**Issue by Queuecumber** [RainLoop/rainloop-webmail#418]
Are there plans to support PGP/MIME instead of just inline signing (or do you already support it and I missed something)?

**Comment by Rbeuque74** [comment]
:+1:

**Comment by RainLoop** [comment]
We use the openpgp.js library for encryption/sign.
It supports plain text encryption/decryption and signing.

Unfortunately it doesn't work with mail attachments.

**Comment by Queuecumber** [comment]
Right that makes sense, it seems to me you'd need to pass the correct pieces to openpgp.js and constrict the pgp/mime email yourself

**Comment by Krishath** [comment]
+1

**Comment by ruzaq** [comment]
+1

**Comment by Queuecumber** [comment]
So was this closed because you implemented it?

**Comment by nado** [comment]
What he said. Or asked.

**Comment by nilsmelchert** [comment]
Any updates on this?
