### ISSUE TITLE
Who wants to test Sieve Filters?

### ISSUE THREAD

**Issue by RainLoop** [RainLoop/rainloop-webmail#419]
Good news, Everyone!

I finally have finished this functionality.
If you have the opportunity to test the filters, I'll be grateful to you.

link:
http://repository.rainloop.net/v2/webmail/1.7.3/rainloop-1.7.3.243-214b8f8384bb4830fac7e47680b5371d.zip"

screenshots:

![01](https://cloud.githubusercontent.com/assets/5530092/5888907/5828171c-a421-11e4-89ee-e5307b8a3ea8.png)
![02](https://cloud.githubusercontent.com/assets/5530092/5888911/5bb313b4-a421-11e4-81ea-3873560def8e.png)
![03](https://cloud.githubusercontent.com/assets/5530092/5888913/5f087e3c-a421-11e4-8028-df05f48e2344.png)
![05](https://cloud.githubusercontent.com/assets/5530092/5888916/62e22774-a421-11e4-9cae-c6a7ac381a89.png)
![06](https://cloud.githubusercontent.com/assets/5530092/5888917/66e3dcbe-a421-11e4-8751-c19bf3379b6c.png)
![07](https://cloud.githubusercontent.com/assets/5530092/5888918/698c6f94-a421-11e4-96d2-31192510443c.png)

**Comment by ervee** [comment]
Hi, sorry for the delay, but I finally got time to test this. I created a test install with your supplied zip and here are the results:

When I create a Sieve rule, I'm stuck on "These changes need to be saved to the server":
![capture](https://cloud.githubusercontent.com/assets/4435930/5973236/53f5b7d2-a866-11e4-8d34-f4e804ff90a3.JPG)

I created some logs.

When I enter Settings > Filters, I see this in theRainLoop log:
```
[08:55:36.006][215dc864] INFO[DATA]: [DATE:30.01.15][RL:1.7.3.235][PHP:5.4.36-0+deb7u3][IP:212.61.144.165][PID:7542][Apache][apache2handler]
[08:55:36.007][215dc864] INFO[DATA]: [Suhosin:off][APC:on][MB:on][PDO:mysql,pgsql,sqlite][Streams:tcp,udp,unix,udg,ssl,sslv3,tls]
[08:55:36.007][215dc864] REQUEST[NOTE]: [POST] https://#MYFQDN#/rainloop-sieve-test/?/Ajax/&s=/_#IMSENCORINGTHISJUSTINCASE#/
[08:55:36.007][215dc864] AJAX[NOTE]: Action: DoFilters
[08:55:36.008][215dc864] POST[DATA]: {"Action":"Filters","XToken":"#IMSENCORINGTHISJUSTINCASE#"}
[08:55:36.013][215dc864] SIEVE[NOTE]: Start connection to "tcp://localhost:4190"
[08:55:36.014][215dc864] SIEVE[NOTE]: Connected (success)
[08:55:36.034][215dc864] SIEVE[DATA]: < "IMPLEMENTATION" "Dovecot Pigeonhole"\r\n
[08:55:36.034][215dc864] SIEVE[DATA]: < "SIEVE" "fileinto reject envelope encoded-character vacation subaddress comparator-i;ascii-numeric relational regex imap4flags copy include variables body enotify environment mailbox date ihave"\r\n
[08:55:36.034][215dc864] SIEVE[DATA]: < "NOTIFY" "mailto"\r\n
[08:55:36.035][215dc864] SIEVE[DATA]: < "SASL" "PLAIN"\r\n
[08:55:36.035][215dc864] SIEVE[DATA]: < "STARTTLS"\r\n
[08:55:36.035][215dc864] SIEVE[DATA]: < "VERSION" "1.0"\r\n
[08:55:36.035][215dc864] SIEVE[DATA]: < OK "Dovecot ready."\r\n
[08:55:36.037][215dc864] SIEVE[DATA]: > AUTHENTICATE "PLAIN" {24+}\r\n
[08:55:36.037][215dc864] SIEVE[DATA]: > #IMSENCORINGTHISJUSTINCASE#\r\n
[08:55:36.083][215dc864] SIEVE[DATA]: < OK "Logged in."\r\n
[08:55:36.083][215dc864] SIEVE[DATA]: > LISTSCRIPTS\r\n
[08:55:36.083][215dc864] SIEVE[DATA]: < OK "Listscripts completed."\r\n
[08:55:36.084][215dc864] SIEVE[DATA]: > LOGOUT\r\n
[08:55:36.088][215dc864] SIEVE[DATA]: < OK "Logout completed."\r\n
[08:55:36.088][215dc864] SIEVE[NOTE]: Disconnected from "tcp://localhost:4190" (success)
[08:55:36.088][215dc864] AJAX[DATA]: {"Action":"Filters","Result":{"RawIsAllow":true,"RawIsActive":false,"Raw":"","Filters":[],"Capa":["fileinto","reject","envelope","encoded-character","vacation","subaddress","comparator-i;ascii-numeric","relational","regex","imap4flags","copy","include","variables","body","enotify","environment","mai...
[08:55:36.088][215dc864] INFO[MEMORY]: Memory peak usage: 1.25MB
[08:55:36.089][215dc864] INFO[TIME]: Time delta: 0.086724996566772
```
And my syslog says:
```
Jan 30 09:55:36 webandmail dovecot: managesieve-login: Login: user=<#USERNAME#>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=8318, secured, session=<9WSaxNoNHQB/AAAB>
Jan 30 09:55:36 webandmail dovecot: managesieve(#USERNAME#): Disconnected: Logged out bytes=19/70
```
Then I add a filter, click done and end up with the message "These changes need to be saved to the server".

When I press Save, nothing happens and nothing gets logged...

Ralf.

**Comment by RainLoop** [comment]
Thanks!

Can you create some logs then you press Save button?

**Comment by ervee** [comment]
What do you mean? When I press Save, nothing happens and nothing gets logged...

**Comment by RainLoop** [comment]
Any js errors?

**Comment by ervee** [comment]
You mean in Apache logs? I get also nothing in Apache logs when pressing Save.

**Comment by andre-dierker** [comment]
Same here. Not able to save new Filterscripts. Using this testinstallation on Nginx.
Tested in Firefox and Chrome. Nothing appears in any logs

**Comment by RainLoop** [comment]
Hi, sorry for not replying in time.

@ervee No, I mean browser console.

Ok, there is a new version on RainLoop Webmail with a lot of changes and fixes.

link:
http://repository.rainloop.net/v2/webmail/1.7.3/rainloop-1.7.3.236-932d36047cdaa2426e97645f5f212d89.zip

**Comment by andre-dierker** [comment]
Still the same behaviour with the new version.

**Comment by RainLoop** [comment]
Can you give me access credentials for tests?

**Comment by andre-dierker** [comment]
wrote an mail to support@rainloop.net

**Comment by RainLoop** [comment]
@andre-dierker Thank you very much. You really helped.

new version:
http://repository.rainloop.net/v2/webmail/1.7.3/rainloop-1.7.3.237-edae8ff8823f5fbf684fd076c6e9446f.zip

**Comment by andre-dierker** [comment]
Works fine now :)

**Comment by ervee** [comment]
Saving scripts works here too. Saved script also looks okay. I'll try to test as much rule types as possible. If I find anything wrong I'll let you know.

**Comment by RainLoop** [comment]
Ok, thanks!

**Comment by ervee** [comment]
I do already have a little feedback:

1) I think it should me more clear to the user that the rules are processed from top to bottom and when there is a match, processing stops there. Al least, you insert a "stop" in every Sieve filter.

2) The filters are movable. So perhaps tell the user or make it visualy noticable like in most Android movable lists there are sort of a visual handle at the beginning of each movable item.

3) Perhaps an (advanced) option to _not_ stop rule processing after the rule you are creating/editing?

Ralf.

**Comment by RainLoop** [comment]
@ervee  Thanks.

> 1) 2)

Agree.

> 3) Perhaps an (advanced) option to not stop rule processing after the rule you are creating/editing?

I thought about that. But I can not understand the reason why this is necessary.
If only to use it for "Forward to" and "Vacation message" actions.

**Comment by ervee** [comment]
The only thing I can quickly think of is indeed vacation messages. Perhaps:
1) Make "don't stop processing rules" an option when creating a vacation message?
2) Also have the user decide the reply interval (fixed set at 1 day now)

**Comment by RainLoop** [comment]
> The only thing I can quickly think of is indeed vacation messages. Perhaps:
> 1) Make "don't stop processing rules" an option when creating a vacation message?
> 2) Also have the user decide the reply interval (fixed set at 1 day now)

Done.

**Comment by andre-dierker** [comment]
Managesieve running on port 2000 is very outdated, maybe change it to 4190 in sieve configuration?

**Comment by RainLoop** [comment]
Ok

**Comment by RainLoop** [comment]
new version:
http://repository.rainloop.net/v2/webmail/1.7.3/rainloop-1.7.3.241-a2510466f4c3fa9adeea110e005a220d.zip

**Comment by ervee** [comment]
The filters I created with the previous version (filename rainloop.sieve.user.sieve) are now not visible anymore (but still there) and a new file rainloop.user.sieve is created and the symlink .dovecot.sieve is updated to use that new script. I assume this was a deliberate change :)

Also RainLoop does not use an already existing script? I don't realy know how this works though...

All looks good. But I do get a weird problem in this version (and the previous) if I open an email to read. I can't close it (with the X button of ESC). The message just pops back up again!

**Comment by RainLoop** [comment]
>  I assume this was a deliberate change

Yes

> Also RainLoop does not use an already existing script? 
> I don't realy know how this works though...

RainLoop knows how to build script only.

> The message just pops back up again!

**Comment by ervee** [comment]
> I can not reproduce it.
Probably a browser/cookie/whatever. It's a test setup so I don't mind.

**Comment by RainLoop** [comment]
Ok, now I see the problem.
Thanks for reporting!

**Comment by RainLoop** [comment]
a new version: http://repository.rainloop.net/v2/webmail/1.7.3/rainloop-1.7.3.243-214b8f8384bb4830fac7e47680b5371d.zip

**Comment by ervee** [comment]
This version works great so far.

**Comment by andre-dierker** [comment]
Sieve is working fine now. Now there is a related problem in Inbox view. Reloading the message list, doesn't reloading subdirectories too. New mails in folders aren't displayed.

**Comment by RainLoop** [comment]
@ervee Good.

@andre-dierker There is other reloading mechanism for that (automatically).
Reload button is for current folder message list only.

**Comment by arturbonnett** [comment]
Hi Rainloop Team!

I couldn't test this feature yet, but I have one feedback:
Have to remove the Sieve configs of the validation (Test button) when "Allow sieve scripts" is not checked

Nice feature!

**Comment by RainLoop** [comment]
@arturbonnett Thanks for reporting!

**Comment by RainLoop** [comment]
I think it is a last beta version before release (RC1):
http://repository.rainloop.net/v2/webmail/1.8.0/rainloop-1.8.0.244-e1eb4ba4d60756c560ef7a9e4f406746.zip

**Comment by ervee** [comment]
Just tested this version and it looks okay to me.

**Comment by RainLoop** [comment]
I have released a new version (1.8.0)

http://www.rainloop.net/downloads/

Thanks all!

**Comment by ervee** [comment]
Updated my acceptance instance and still looks good :)

**Comment by UrZ4** [comment]
Ahhhhhh I'm so happy to see that sieve filters are in :)
But I did not understand why imap & smtp settings are there and what I have to put ?
My settings:
![sieve1](https://cloud.githubusercontent.com/assets/10866025/6060880/81ded6ca-ad42-11e4-86a6-d7e2b104f8d2.JPG)
My error:
![sieve2](https://cloud.githubusercontent.com/assets/10866025/6060890/9c35b3b8-ad42-11e4-8501-492ca2a80f3a.JPG)

If i try to put 127.0.0.1 : 2000, it says that the server is not accessible.

Thanks a lot

**Comment by RainLoop** [comment]
Why your sieve port is 993?
Did you mail server support sieve scripts?

**Comment by UrZ4** [comment]
That's good question.. I'll try to find the answer... I hope so !
Ty for ur reply

**Comment by extremeshok** [comment]
please allow it to support already existing filters which were created by sogo.

**Comment by AndrewSav** [comment]
Suggestion to add a link on the sieve page to the sieve manual. This is probably the best page that I've seen: https://support.tigertech.net/sieve but also of course the rfc https://www.ietf.org/rfc/rfc3028.txt and http://sieve.info/

**Comment by d3xt3r01** [comment]
So I finally got the time to test the sieve filters and I remember I had some set up .. but I don't see them .. found out that rainloop has its own "commented headers" that don't allow reading the filters I had written myself OR the ones I had created with squirrelmail .. why ?

**Comment by RainLoop** [comment]
> why ?

A quick answer is: "It's too complicated"

**Comment by ervee** [comment]
But when you manage Sieve filters from multiple applications, the problem rises quickly to the surface. When you create rules in RainLoop (and you fail to notice your existing rules don't show in RainLoop) and save them, you wipe out your existing filters...

I don't have this problem because I only use RainLoop to edit Sieve filters, but I can imagine people running IE RoundCube and RainLoop together. Or when migrating from RoundCube to RainLoop, this needs admin intervention.

**Comment by RainLoop** [comment]
> you wipe out your existing filters...

I do not delete them, I created my own script and sets it as default.

I understand that the best decision is to write a complete Sieve scripts parsing library,
but it is very complex and time consuming task.

**Comment by chrisnorris007** [comment]
im getting the message "Cannot connect to Server" when i click on the filters link.

**Comment by chrisnorris007** [comment]
nevermind - left off sieve in dovecot.conf

**Comment by nachopro** [comment]
Works fine! thanks a lots!

**Comment by dineshrabara** [comment]
i try to use with gmail 
but not working 

please check below screen 

1 .

![screenshot-solution_erp sr 2015-12-01 11-57-47](https://cloud.githubusercontent.com/assets/1228130/11493846/d2eeed54-9822-11e5-8858-5b4e4bb0116c.png)

2.

![Uploading screenshot-solution_erp sr 2015-12-01 11-59-05.png…]()

**Comment by AndrewSav** [comment]
@dineshrabara why do you expect this to work? You need a sieve server for sieve to work (duh!)

**Comment by dineshrabara** [comment]
how can i?
please help me

**Comment by AndrewSav** [comment]
@dineshrabara you can't.

**Comment by dineshrabara** [comment]
is this possible to add vacation email script ??

**Comment by AndrewSav** [comment]
@dineshrabara https://github.com/RainLoop/rainloop-webmail/issues/43

**Comment by dineshrabara** [comment]
Thanks

**Comment by fgiorlando** [comment]
working well here, using managesieve on standard port.

**Comment by poulpito** [comment]
Sorry add a new comment :) 
but last year you comment about subfolder refresh : 

> RainLoop commented on 2 Feb 2015
> @ervee Good.
> @andre-dierker There is other reloading mechanism for that (automatically).
> Reload button is for current folder message list only.

is it possible to know how it's working and is there a way to speed up notification for unread message moved in folder ? 

btw  thanks for this fresh webmail :)

**Comment by zdi-software** [comment]
Hello,
Is it possible to enable the "body" condition for the sieve filter?

Thanks.

**Comment by criskolkman** [comment]
Hello,

Sorry to reply on an old/closed subject but I really would like to know this:

I have added the sieve support to create rules, but I would LOVE an option to copy a message to another folder without removing it from the inbox folder.
Is there already an option like this or can this be done?

**Comment by AndrewSav** [comment]
Copy: in theory should work like this: https://tools.ietf.org/html/rfc3894 Did you try it?
Saving them - this best be troubleshoot from server logs. What sieve server are you using?

**Comment by adundovi** [comment]
Is it possible to implement the parsing using existing [projects](http://sieve.info/libraries)? The inability of RainLoop to modify filters created by other programs makes this feature rather incomplete and in some cases even useless. Maybe to add an "Advance" mode in which parsing/interpretation is not needed, just pure editor which would edit all sieve scripts served by the server?

**Comment by AndrewSav** [comment]
@adundovi as far as parsing goes, it does not belong on the mail client such as rainloop. As far as ability to edit sieve scripts, as far as I remember it has been supported from the first release that included sieve support.

**Comment by adundovi** [comment]
Hi @AndrewSav, thank you for your quick reply.

I was referring to [this comment](https://github.com/RainLoop/rainloop-webmail/issues/419#issuecomment-76961263) of @RainLoop above. As I already saw it in practice: RainLoop creates a custom base64 encoded comment inside a sieve script which saves the content of it in RainLoop's recognizable format therefore it doesn't need to parse the sieve language to interpret those rules - reading that comment is enough, if I understand the mechanism correctly (or if I correctly read the code: ``RainLoop/Providers/Filters/SieveStorage.php``). If the other mail client doesn't update the comment in the sieve script created by RainLoop, RainLoop will not display it correctly.

**Comment by adundovi** [comment]
OK, now by reading the code I understand that there is an option for "raw" sieve scripts like I suggest in my first comment. Great! Thus, if one uses the "raw" mode, there is no graphical editing of the scripts, but at least other programs can interfere with those rules. This is fair enough for me.

**Comment by hakkeri** [comment]
Is there some filter limit? After 59 filter I get a ”Invalid token” error, when I try to save filters.

**Comment by fantasio31** [comment]
Same issue for me.

59th filter cannot be saved with "Invalid Token" issue.
Removing one filter and adding a new one works correctly.

**Comment by gusarg81** [comment]
Hi, today I've tested Rainloop filters (or course, installed and configured Sieve with Dovecot first) and works. But I have a problem, which I think is related of Rainloop works: I needed to implement filters most of all cause I need to move emails to folders (since We are leaving Google apps, missing Gmail labels, at least I need to move emails to folders), but does not appears as new emails, only if i navigate to that folder.

There is no way to check for new emails in any folder and not only in the current folder I am browsing?

Thanks in advance.

**Comment by ervee** [comment]
In settings, folders you can toggle a checkmark for that:
![image](https://user-images.githubusercontent.com/4435930/27607467-46a5c5f8-5b84-11e7-933b-c9d405966452.png)

**Comment by gusarg81** [comment]
@ervee: thanks! I didn't saw that.

Cheers.

**Comment by MrEgenius** [comment]
Hello!

Currently I use mail server with postfix+cyrus-imap+roundcubemail.
It work fine and a can manage sieve rules via roundcubemail web console.
I installed rainloop app in nextcloud and see that sieve filters not working.
I can't see my current sieve rules and can't create new rules.

Nextcloud version- 12.0.2
Rainloop app version - 5.0.1

Please. fix this issue.

**Comment by allo-** [comment]
Have you thought about using a good library for parsing the true sieve rules? I understand that this is probably complicated to implement, but there seems to be some library around, which supports sieve + extensions:
https://github.com/ProtonMail/libsieve-php

This would mean no more rules restricted to an own format with a converter to sieve, but being able to implement all possible sieve rules and parse them.
I did not test it myself, but you could give it a try. Would make your life easier in maintaining the sieve-function and our life easier in using every sieve client we can find and still being able to edit the rules in rainloop.

**Comment by ervee** [comment]
±1

**Comment by Ulrar** [comment]
So what's the condition for rainloop to show a script ? I have a "Main" script in use currently which was created from thunderbird, but rainloop doesn't show anything even with the custom script ticked.

**Comment by cauerego** [comment]
this may be obvious to most folks here, but i just want to link more and add redundancy because i had lots of issues to find a link with good documents and examples on how to use sieve script.

imho, this should be a link into rainloop on that very page from op in which there's a list of supported capabilities:

https://tools.ietf.org/html/rfc5228

cheers!

**Comment by gusarg81** [comment]
For me Sieve does not work on Rainloop (and Sieve is running in my server, Ubuntu 18.04).

**Comment by blacklion** [comment]
Any updates?
I still don't see existing sieve script under Rainloop interface.
I'm afraid of adding new filters, as I'm not sure will it override my existing script with lot of filters in it or not.
