### ISSUE TITLE
Extended login page gone?

### ISSUE THREAD

**Issue by yforster** [RainLoop/rainloop-webmail#420]
Hi,

I was using the login page where one needed to specify an email, username and password. Since the last update this page seems to be gone. I can now either log in with the email address (which gets me to the wrong account) our the username (which gets me the wrong default sending adress).

Is there a way to get the old page back, preferably without downgrading? If there is not, to which version will I need to downgrade?

Thanks in advance
Yannick

**Comment by ervee** [comment]
See #206
