### ISSUE TITLE
Creating a DKIM plugin

### ISSUE THREAD

**Issue by SGr33n** [RainLoop/rainloop-webmail#423]
Hi,

I'm just trying to develope a DKIM plugin.

I'm using the following code:

	public function FilterBuildMessage(&$oMessage)
	{	
		if ($oMessage instanceof \MailSo\Mime\Message)
		{

But I'd need to get the email body at this point and I don't know how, since that if i get
$oMessage->Html I get an error sending the email "Impossible to paste".

I get the same error also if i try to include an external php file.

Can somebody help me?

Thanks.

**Comment by RainLoop** [comment]
Do you want sign message with DKIM within PHP?
It's actually a mail server work.

In any case Html property does not exist in the \MailSo\Mime\Message class.

**Comment by SGr33n** [comment]
Yes I'm trying to sign the message with DKIM, because the server where rainloop is running doesn't have DKIM installed.

So, how can I at this point get the message body?

Thanks :)

**Comment by SGr33n** [comment]
I also get the "Impossible to paste message" if i try to define the headers.

E.g.

$to_header = 'To: ' . $oMessage->GetTo();

**Comment by RainLoop** [comment]
Well, It is a low-level object class (@see ./rainloop/v/x.x.x/app/libraries/MailSo/Mime/Message.php). There is no message body as string value.

Message body can be html or plain text.
Sometimes messages can contain multiple text parts simultaneously (For example two html parts and one plain text part).

In this case I want to ask, What is the message body?

**Comment by RainLoop** [comment]
```php
/**
 * @return \MailSo\Mime\EmailCollection
 */
public function GetTo()
```

 \MailSo\Mime\EmailCollection is not a string

**Comment by SGr33n** [comment]
I'm just trying to implement the PHP-DKIM class, the body is a required value, I suppose it's the whole email text.

I also tryied this, to have the message "to header":

			$to = (string) $oMessage->GetTo();
			$to = 'To: ' . $to;

But always the same error :(

Where am I doing wrong?

**Comment by RainLoop** [comment]
```php
$sTo = '';
$oEmailCollection = $oMessage->GetTo();
if ($oEmailCollection && 0 < $oEmailCollection->Count())
{
    $sTo = 'To: '.$oEmailCollection->ToString(true, false);
}
var_dump($sTo);
```

**Comment by SGr33n** [comment]
Thanks!!! :)

**Comment by Corna** [comment]
I'm interested in a DKIM plugin too
What's the current status?
