### ISSUE TITLE
Wrong storage path generated when setting language through login page

### ISSUE THREAD

**Issue by nuxwin** [RainLoop/rainloop-webmail#424]
Hello ;

When setting language through the login page, the generated storage path is wrong ( eg. storage/cfg/_n/nuxwin@domain.tld/settings instead of storage/cfg/nu/nuxwin@domain.tld/settings ). This is due to the fact that the default value for the **$sParentEmail** is **NULL** while the test is made against empty string in the default storage ( generateFileName() method ).

How to reproduce:

With a new account, set the language on login page and then, login on.

To resume here, the default value for the sParentEmail property of the **RainLoop\Model\Account** class should be an empty string instead of NULL.

Rainloop build: 1.7.2.229

**Comment by RainLoop** [comment]
Thanks!
