### ISSUE TITLE
Sieve Mark as read

### ISSUE THREAD

**Issue by stephan13360** [RainLoop/rainloop-webmail#426]
There seems to be an error with the "Mark as seen" option. Is does not work. Looking in the script that is created i see the following line:

addflag "\Seen";

but it should be:

addflag "\ \Seen";      without the space between the \ but github seems to remove one \ if i put two of them after another.

with two backslashes because acording to RFC 5323 (https://tools.ietf.org/html/draft-ietf-sieve-imapflags-05):
0.5. Changes from the revision 02
   1. BugFix: all backslashes must be escaped

**Comment by RainLoop** [comment]
Thanks!

**Comment by NicolasKAROLAK** [comment]
Sorry to ask here, but where do you configure sieve filter ?

**Comment by offspringus** [comment]
NicolasKAROLAK, please see this link
https://github.com/RainLoop/rainloop-webmail/issues/419

**Comment by NicolasKAROLAK** [comment]
Thanks!
5 février 2015 12:02 "offspringus"  a écrit:

	 
	NicolasKAROLAK, please see this link
#419 (https://github.com/RainLoop/rainloop-webmail/issues/419)

**Comment by RainLoop** [comment]
Fixed in the 1.8.1 version.
