### ISSUE TITLE
No TLSv1 for IMAP in Rainloop ?

### ISSUE THREAD

**Issue by nikaro** [RainLoop/rainloop-webmail#429]
Hello,

When I disable SSLv3 in the cipher list of Dovecot, Rainloop can't connect to IMAP server. Here is the log :
`Feb  5 17:41:13 server dovecot: managesieve-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=127.0.1.1, lip=127.0.1.1, TLS handshaking: SSL_accept() failed: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher, session=<JNvT+FkOagB/AAEB>`

**Comment by RainLoop** [comment]
Well.

./rainloop/v/x.x.x/app/libraries/MailSo/Net/NetClient.php
~ 235 line

``` php
$this->sConnectedHost = \in_array(\strtolower(\substr($this->sConnectedHost, 0, 6)), array('ssl://', 'tcp://')) ? \substr($this->sConnectedHost, 6) : $this->sConnectedHost;
$this->sConnectedHost = ($this->bSecure ? 'ssl://' : 'tcp://').$this->sConnectedHost;
```
change to:
``` php
if (!\preg_match('/^[a-z0-9]{2,8}:\/\//i', $this->sConnectedHost))
{
     $this->sConnectedHost = ($this->bSecure ? 'ssl://' : 'tcp://').$this->sConnectedHost;
}
```

After that try to change your IMAP host to:
```
sslv2://imap.domian.com
```

But I'm not sure that it can help.

**Comment by NicolasKAROLAK** [comment]
It doesn't work. I have the same log message, but the "tooltip' show another error message when I use `sslv2://imapserver` :
```
stream_socket_client(): unable to connect to sslv2://imapserver:143 (Unable to find the socket transport &quot;sslv2&quot; - did you forget to enable it when you configured PHP?)
```

I tried `tls://` instead `sslv2://` (since what I want to use is TLS) and it give me this :
```
stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
```

Otherwise, without the 'scheme name' I have :
```
Cannont enable STARTTLS. [Type=3]
```

**Comment by RainLoop** [comment]
```
Cannont enable STARTTLS. [Type=3]
```
Why did you enable STARTTLS ?
What are your IMAP settings?

**Comment by NicolasKAROLAK** [comment]
> Why did you enable STARTTLS ?

Because my IMAP server is configured for STARTTLS.

> What are your IMAP settings?

Server: my.server.tld
Port: 143
Secure: STARTTLS

**Comment by ervee** [comment]
Just a thought. How did you disable SSLv3 in Dovecot? I had a lot of problems when adding !SSLv3 to the ssl_cypher_list. I ended up not using the ssl_cyphetr_list directive but
ssl_protocols = !SSLv2 !SSLv3

Ralf

**Comment by NicolasKAROLAK** [comment]
I use `ssl_cipher_list` with no problem. May be you used spaces instead of semic

**Comment by RainLoop** [comment]
There are some problems with ssl and tls support in PHP < 5.6.
What is your version of php?

**Comment by ervee** [comment]
That's a good possibility. I'm on mobile right now so it's a bit hard (not impossible though ;-)) to check.

**Comment by NicolasKAROLAK** [comment]
I'm on Debian Wheezy, so it's PHP 5.4.

As soon as I can I will test on a server with PHP 5.6 and I will let you know.

Thanks.

**Comment by RainLoop** [comment]
> As soon as I can I will test on a server with PHP 5.6 and I will let you know.

OK, thank you :)

**Comment by RainLoop** [comment]
You can try one more thing.

./rainloop/v/x.x.x/app/libraries/MailSo/Net/NetClient.php
~ 313 line

1) Find the "EnableCrypto" function
```php
public function EnableCrypto($iCryptoType = STREAM_CRYPTO_METHOD_TLS_CLIENT)
```
2) Rewrite it:
```php
	public function EnableCrypto()
	{
		$bError = true;
		if (\is_resource($this->rConnect) &&
			\MailSo\Base\Utils::FunctionExistsAndEnabled('stream_socket_enable_crypto'))
		{
			switch (true)
			{
				case defined('STREAM_CRYPTO_METHOD_ANY_CLIENT') &&
					@\stream_socket_enable_crypto($this->rConnect, true, STREAM_CRYPTO_METHOD_ANY_CLIENT):
				case @\stream_socket_enable_crypto($this->rConnect, true, STREAM_CRYPTO_METHOD_TLS_CLIENT):
				case @\stream_socket_enable_crypto($this->rConnect, true, STREAM_CRYPTO_METHOD_SSLv23_CLIENT):
					$bError = false;
					break;
			}
		}

		if ($bError)
		{
			$this->writeLogException(
				new \MailSo\Net\Exceptions\Exception('Cannot enable STARTTLS.'),
				\MailSo\Log\Enumerations\Type::ERROR, true);
		}
	}
```

**Comment by NicolasKAROLAK** [comment]
It still doesn't work : `Cannot enable STARTTLS.`

**Comment by RainLoop** [comment]
Did you do this https://github.com/RainLoop/rainloop-webmail/issues/429#issuecomment-73111212
modifications?

**Comment by NicolasKAROLAK** [comment]
Yes I did.

**Comment by NicolasKAROLAK** [comment]
Just tested under Ubuntu 14.04, which uses PHP 5.5. And  it works with SSLv3 disabled.

**Comment by Raptormagnum** [comment]
Not works on CentOS 7.1 with php5.6.

Coul'd you repoen ?
