### ISSUE TITLE
Message are not sorted by date

### ISSUE THREAD

**Issue by awikatchikaen** [RainLoop/rainloop-webmail#431]
Hi,

Sometimes, I move my mail from "sent mail" to "inbox" so I have all message from same conversation at the place.
But when I move those mails they appears on top of the inbox .... it's not logical, in a folder when I want mails sorted by date, It's "sent/receive date" and not "creation date"
I have the same problem with my folder "archive", mails are sorted by date wich i move them in and not "receive date"
![temp](https://cloud.githubusercontent.com/assets/552126/6079436/b8fe2048-ae05-11e4-8187-45065fabb8a9.png)

**Comment by RainLoop** [comment]
Does your IMAP server support SORT?

**Comment by awikatchikaen** [comment]
Hi, how can i know ?

**Comment by RainLoop** [comment]
What is your IMAP server?

**Comment by awikatchikaen** [comment]
It's gandi. Support has confirm that they support SORT

**Comment by RainLoop** [comment]
@awikatchikaen 
How many messages in the folder?
