### ISSUE TITLE
Message Templates and Signature

### ISSUE THREAD

**Issue by RainLoop** [RainLoop/rainloop-webmail#433]
I have an idea to refuse the signature setting in favor of the "Message Templates" settings.
Since these things are very similar.

"Message templates" will be more powerful than a signature.

What do you think about this?

**Comment by ervee** [comment]
Hmm, I would like to have a seperate signature from any reply/newmail templates though.

**Comment by RainLoop** [comment]
The main idea is that the templates can be used as signature.
