### ISSUE TITLE
Mails with /Deleted flag are listed in INBOX and other folders

### ISSUE THREAD

**Issue by svdlinden** [RainLoop/rainloop-webmail#434]
RainLoop does not take into account the /Deleted flag set by other clients. Messages with /Deleted flags are shown like any other message. 

Affected version: 1.8.0.

**Comment by hachre** [comment]
Confirmed

**Comment by wiswedel** [comment]
confirmed

**Comment by RainLoop** [comment]
Try the 1.8.1 version.

![deleted](https://cloud.githubusercontent.com/assets/5530092/6215054/344e302a-b60e-11e4-9650-b1c6b83c3de2.png)

**Comment by hachre** [comment]
Sorry I'm not sure if the original poster meant this as well, but I was referring to exactly this strike-through behavior. I'd like those mails not to show up in the INBOX at all, but in Trash (like normal mails there, without strikethrough) instead - if possible

**Comment by RainLoop** [comment]
I understand that.
There are 2 ways to work with deleted messages.
Mark them deleted or moved to a folder (Trash, Bin, ...).

I chose the 2-nd option as a more appropriate.
And I can not hide them, it's a technical limitation since I don't store messages in a database.

**Comment by hachre** [comment]
@RainLoop The code that currently allows for them to make them strike-through, wouldn't that also allow them to hide them completely? If the UI already knows that they are "deleted", I guess it could also simply not render the entire message entry at all? This should be put as an option, though, because some people might wanna see them.

**Comment by RainLoop** [comment]
It's not as easy as it seems.

Let's say I'm going to hide them. 
What should I do if I need to hide 15 messages out of 20 on the first page?
It remains for me to show only 5 messages.

But this is wrong. So I need to request for more than 20 messages per page.
So, how much do I need to request messages from the IMAP server to display the first page? 20, 30, 100 message? And this is only the beginning of problems :)

**Comment by hachre** [comment]
@RainLoop Oh I see! Didn't think of that. Yeah, it wouldn't be very simple to implement then. You'd need this on the server-side and then it will end up like you said, with your own indexing system / database.

**Comment by svdlinden** [comment]
Version 1.8.1 brings a nice improvement, thanks.

I don't see the problem with hiding them. I understand that if you fetch a given number of messages from the IMAP server irrespectively of their flags, and then filter them out, then there is indeed an issue with pagination. But OTOH it is possible to search for undeleted messages in a mailbox with IMAP directly (SEARCH UNDELETED command).

**Comment by RainLoop** [comment]
I repeat :) It's not as easy as it seems.

**Comment by RainLoop** [comment]
Maybe someday I'll understand how to do it well. :)
