### ISSUE TITLE
stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by eallion** [RainLoop/rainloop-webmail#438]
![11](https://cloud.githubusercontent.com/assets/1698841/6095408/6d71e112-af97-11e4-8753-aded25ea516c.png)

i dont know how to fix this error, thank you.

**Comment by ervee** [comment]
Does name resolving _on the Server_ work? Like are there DNS Servers configured etc.

Another thought. Is "extension=php_openssl.dll" enabled in your PHP.INI ?

**Comment by eallion** [comment]
i reinstall my vps os ,and  change to LAMP,it works.

**Comment by luckyrajiv** [comment]
i am having the same issue. Installed Nginx and AJenti V
