### ISSUE TITLE
Play sound for new mails in sieve filters

### ISSUE THREAD

**Issue by skibbipl** [RainLoop/rainloop-webmail#440]
Is it possible to play a sound when new incoming message is for example moved to another folder using sieve filters? Currently sound is played only when message arrives in Inbox folder.

**Comment by ervee** [comment]
RainLoop does not know when Sieve puts a message in another folder than Inbox. So there is no trigger for RainLoop to play a sound.

I don't know what RainLoop's check interval on folders other than Inbox is. Or if it even checks other folders regularly. But I don't think checking every folder on a regular basis is really wanted behavior...

**Comment by skibbipl** [comment]
Yeah, I was afraid that this might not be possible. I thought maybe there is some feedback from server when sieve filter is triggered.

**Comment by ervee** [comment]
Nope, there is not.

Thoug an IMAP client can use IMAP IDLE to notify the Server it is ready to accept notifications of mailbox changes. This has been discussed and is apparently technically difficult to implement for web based email systems so RainLoop does not support this.

**Comment by gusarg81** [comment]
I also stopped to use Rainloop because of this, since We've migrated from Google apps (gmail), and having Tags in all emails was something usefull. Since there is no tags here, I've implemented sieve but is a problem if no notifications being made with this method. There is no way to achieve this in server side?

Thanks.

**Comment by ervee** [comment]
There are loads of 3rd party applications when I Google for "IMAP notification windows" (for Microsoft Windows). But RainLoop does have new mail counters (when enabled on the folder) so I assume it is possible to notify on new email in those folders...

**Comment by gusarg81** [comment]
Right, but I don't use Windows, I use Linux :)

Yes, I know it can notify by that visible counter, but is not enough... I have many folders, one for each client. So would be nice an audible/popup notification like when an Email arrives at INBOX.

**Comment by ervee** [comment]
I understand the need and use of it. Too bad I'm not able to change the code for you. Let's hope someone can!
