### ISSUE TITLE
Thread view / Conversations not available when using gmail imap backend

### ISSUE THREAD

**Issue by cptMikky** [RainLoop/rainloop-webmail#442]
Hi, using latest 1.8 branch I cannot turn on thread view - the option under General just isn't there. Tried enabling it "by default" in app.ini to no avail. Using gmail imap backend. Did I miss something?

**Comment by RainLoop** [comment]
No, everything is correct. gmail imap backend does not support IMAP threading.

**Comment by cptMikky** [comment]
Another reason to leave gmail for good :) Thanks. Perhaps this could be documented in some kind of FAQ?

**Comment by rgarrigue** [comment]
+1 on a bit of doc. Just greying the option under the general panel with a tooltip maybe? Would have saved a couple of hour of search & thinkering.
