### ISSUE TITLE
RainLoop ownCloud App very high CPU load with Chrome

### ISSUE THREAD

**Issue by jelle-e** [RainLoop/rainloop-webmail#445]
When the RainLoop App is loaded/opened in ownCloud(8) and I start composing a new message, CPU load rises significantly. This happens aswel in a Windows7 environment as in Xubuntu. Both using Chrome. Trying with Firefox, this doesn't have the same extreme effect of CPU rising above 100%.

It seems that Chrome is the culprit here. It stalls the system and typing a message becomes almost impossible. Clicking back to the main ownCloud Files section, immediately brings CPU load back to normal.

**Comment by RainLoop** [comment]
Wow, thanks!
This is a very difficult  to detect bug.

**Comment by RainLoop** [comment]
Hi @jelle-e 
You can try a new fixed version (beta) #452
