### ISSUE TITLE
Can't sync with Google CardDav server

### ISSUE THREAD

**Issue by Krishath** [RainLoop/rainloop-webmail#446]
I set the server sync to "google.com", entered my email as user and my email account's password as password but RainLoop says that there were a synchronization error. What can I do?

**Comment by RainLoop** [comment]
Unfortunately, RainLoop does not support google Carddav server.

**Comment by D33D33** [comment]
why ?

**Comment by ervee** [comment]
Because Google does not provide a standard CardDav access.
