### ISSUE TITLE
unkown error on admin login

### ISSUE THREAD

**Issue by unloadco** [RainLoop/rainloop-webmail#448]
Hi, cant login into the admin panel with the default username and pass
it says "Unkown Error"

just have installed it on Ubuntu 14.04 with ISPConfig 3 and mysql and nginx

followed most of steps from [here](https://www.howtoforge.com/installation-and-configuratio-of-rainloop-webmail-client-with-nginx-on-ubuntu-14.04) but still not working. 

any thoughts?
![screenshot 11](https://cloud.githubusercontent.com/assets/10891176/6151405/6d4ddf54-b250-11e4-90c7-6b1ec52f4a3a.png)

**Comment by RainLoop** [comment]
Can you send me (support@rainloop.net) your installation URL?
