### ISSUE TITLE
feature req: download all/multiple attachments

### ISSUE THREAD

**Issue by cptMikky** [RainLoop/rainloop-webmail#449]
Hi,

I'd like to have a functionality where one can download all (or selected) attachments with "a single click" in one ZIP archive. I myself would prefer a tar.{gz,bz2,xz}, 7z or basically anything but a ZIP though since ZIP has problems with unicode fiile names.

thanks for consideration!

**Comment by RainLoop** [comment]
https://rainloop.uservoice.com/forums/223477-ideas-for-rainloop-webmail/suggestions/6291623-download-get-all-attachments-as-zip-file
