### ISSUE TITLE
[BETA] 1.8.1

### ISSUE THREAD

**Issue by RainLoop** [RainLoop/rainloop-webmail#452]
**RainLoop Webmail:**
http://repository.rainloop.net/v2/webmail/1.8.1/rainloop-1.8.1.255-de1f054e82adbcabe615147e85004b43.zip

* New storage provider ( !!! breaking changes / required to recreate your accounts and identities)
* Individual signatures for every Identity
* Fixes and code improvements

**ownCloud package:**
http://repository.rainloop.net/v2/other/owncloud/3.x/rainloop-owncloud-app-3.0-b4f91bc02e7d3f3ba28df0b2f8e29e08.zip 

* built-in RainLoop Webmail (no longer need to install RainLoop Webmail separately.)
* user settings are stored in ownCloud's data folder.
* compose suggestions from ownCloud's contacts (Internal address book is disabled to avoid misunderstandings).
* Small fixes.

**Comment by jelle-e** [comment]
Great, looking good. Configuring now.
I still have the option to select a Storage (PDO) mysql backend for contacts. I guess it doesn't matter what I put in there? I just gets the contact-info from ownCloud? Amazing! :)

Seems so work great. Also the high CPU load on Chrome is fixed entirely. Good job, thanks a lot!

**Comment by RainLoop** [comment]
> I still have the option to select a Storage (PDO) mysql backend for contacts.
Yes, it doesn't matter in ownCloud package.

**Comment by heathen711** [comment]
Works perfectly with owncloud 8, just remember to copy your rainloop data folder to your owncloud data folder so you don't have to rebuild your settings. After my brain go around that one (and I read above) works, auto login works, and according to chrome loads after then before, so bonus!

**Comment by ervee** [comment]
Is there some technical reason why I should not symlink the RainLoop data folder for the OwnCloud instance to the normal RainLoop data folder instance?

**Comment by heathen711** [comment]
I would say the main reason would be if you update rainloop but the owncloud version isn't updated yet then the formatting of the data may have changed this breaking it. 

Side note: why would you need access to the rainloop outside of owncloud? auto login per user is why I use it

**Comment by ervee** [comment]
* Not all my users are using OwnCloud.
* I don't want to force my users to log into OwnCloud when just wanting to check email.
* OwnCloud scales a bit worse on a mobile phone then plain RainLoop
* etc. :)

**Comment by heathen711** [comment]
Makes sense, seeing as how my data folder copied over to the beta without any issues I wouldn't see why it wouldn't work, just make sure you remind yourself to update owncloud rainloop before stand alone rainloop and you shouldn't have issues, so far.

**Comment by RainLoop** [comment]
@ervee 
>I don't want to force my users to log into OwnCloud when just wanting to check email.

You can do it:
<owncloud-url>/index.php/apps/rainloop/app/

**Comment by RainLoop** [comment]
@heathen711 
>Addendum: cannot change email preferences for the auto login
> under the personal settings for owncloud, future update (beta and all) ?

Do you enable "Automatically login with ownCloud user credentials"?

**Comment by heathen711** [comment]
> Do you enable "Automatically login with ownCloud user credentials"?
Yup, forgot about that, now the personal one shows up. Thanks.

**Comment by RainLoop** [comment]
Thanks for testing.
