### ISSUE TITLE
BCC addresses not visible

### ISSUE THREAD

**Issue by jelle-e** [RainLoop/rainloop-webmail#454]
Don't know if it's a feature or a bug ;) but in other email clients I've always had the option to review the contacts I BCC'd to. (Open a sent mail and review the To and BCC list) In RainLoop this isn't possible. Or is this a backend problem of the mailserver / IMAP itself?

**Comment by RainLoop** [comment]
It's a feature :)

In the "Sent" I show exactly what I sent through SMTP and nothing more.
BBC header is not sent to the server (inside message), because I'm not sure that he will cut it correctly.

I certainly can build 2 messages, with and without BBC, but I'm not sure that it's right.

**Comment by jelle-e** [comment]
Okay, I understand. It would be great to be able to review who I've sent mail to. Maybe you can come up with some way some day :) No rush with this one.

**Comment by ervee** [comment]
If I create a message with K-9 mail, put people in BCC, send it, then look at it in the Sent folder. I can see the BCC people.
I (like @jelle-e) would expect to see the BCC people in the message in the Sent folder :)

**Comment by ervee** [comment]
I tested this code with various combinations/with/without To, CC and BCC and it all seems to work. BCC shows in my Sent item. None of the receivers (in To, CC or BCC) can see the adress(es) in BCC like it should. Thank you!

**Comment by jelle-e** [comment]
Strange. I can't see it. It's just the To: field I can see, not the BCC. Not in mailpreview, not in source.
Can you send a screenshot of what you are seeing and where?

**Comment by RainLoop** [comment]
It is not available in regular version yet.

**Comment by jelle-e** [comment]
Ah, sorry. Missed that. Thanks.

**Comment by RainLoop** [comment]
Coming soon :)

**Comment by ervee** [comment]
I was a bit cheeky and patched my Actions.php :)

This is a message from my Sent items:
![toccbcc](https://cloud.githubusercontent.com/assets/4435930/6315988/0797287a-ba14-11e4-945a-7cea2953ee66.jpg)

Ralf.

**Comment by jelle-e** [comment]
Right, thanks. That's what I'd like indeed. Looks good! I'll wait for official release :)

**Comment by arthur7373** [comment]
Is this issue still not resolved?
If so could someone please provide quick fix to manually make corrections, since I need to have it quickly fixed
