### ISSUE TITLE
SecruityProblem with Owncloud 8 and Rainloop

### ISSUE THREAD

**Issue by 8l4ckSh33p** [RainLoop/rainloop-webmail#455]
Example: User "Max" calls his mail through rainloop in the cloud from, looks at her, and then logs off. At the same pc now logs on "Peter". But who has not entered any mail.

If he clicks on email, he can read the mail from Max. So he is then signed with his Rainloop account. Fatal !!!

**Comment by 8l4ckSh33p** [comment]
Confirmed on Windows 7 with newst Firefox an Windows Phone 8.1

**Comment by RainLoop** [comment]
I can't reproduce it.

1) login as user1
2) RainLoop shows user1 mails
3) logout
4) login as user2
5) RainLoop shows user2 mails

> But who has not entered any mail.
> If he clicks on email,

What it means?

**Comment by 8l4ckSh33p** [comment]
Sorry, my english is bad 😆

User2 has no email address in his personal space. He can but read the mail from user1 when he clicks the rainloop app!

**Comment by jelle-e** [comment]
Hmmm, I think I can reproduce.
1) Login ownCloud as User1 (has email account)
2) Click on Email (rainloop app), auto login works.
3) NOT log out of RainLoop, but only out of ownCloud (browser session for rainloop is saved)
4) Login ownCloud as User2
5) Click in Email (rainloop app) and the mail from User1 appears!

**Comment by 8l4ckSh33p** [comment]
Yes jelle-e 😊

**Comment by RainLoop** [comment]
Have you enabled "Automatically login with ownCloud user credentials" option?

**Comment by 8l4ckSh33p** [comment]
No

**Comment by jelle-e** [comment]
I have enabled 'Autologin' in ownCloud admin settings. Tested on Firefox and Chrome.

**Comment by RainLoop** [comment]
It looks like that the ownCloud logout hook does not want to work.
```
OCP\Util::connectHook('OC_User', 'logout', 'OC_RainLoop_Helper', 'logout');
```

Try to ...

```
./apps/rainloop/app/rainloop/v/1.8.1.255/app/libraries/RainLoop/ServiceActions.php (~227)
```

... fix ServiceOwnCloudAuth function

```php
	/**
	 * @return string
	 */
	public function ServiceOwnCloudAuth()
	{
		if (!\RainLoop\Utils::IsOwnCloud() ||
			!isset($_ENV['___rainloop_owncloud_email']) ||
			!isset($_ENV['___rainloop_owncloud_password']) ||
			empty($_ENV['___rainloop_owncloud_email'])
		)
		{
			$this->oActions->SetAuthLogoutToken();
			$this->oActions->Location('./');
			return '';
		}

		$bLogout = true;

		$sEmail = $_ENV['___rainloop_owncloud_email'];
		$sPassword = $_ENV['___rainloop_owncloud_password'];

		try
		{
			$oAccount = $this->oActions->LoginProcess($sEmail, $sPassword);
			$this->oActions->AuthToken($oAccount);

			$bLogout = !($oAccount instanceof \RainLoop\Model\Account);
		}
		catch (\Exception $oException)
		{
			$this->oActions->Logger()->WriteException($oException);
		}

		if ($bLogout)
		{
			$this->oActions->SetAuthLogoutToken();
		}

		$this->oActions->Location('./');
		return '';
	}
```

**Comment by 8l4ckSh33p** [comment]
I have tried it. Runs great!
