### ISSUE TITLE
No multiple identities in plugin for OwnCloud 8

### ISSUE THREAD

**Issue by fracarvic** [RainLoop/rainloop-webmail#456]
I'm testing RainLoop plugin 3.0 for OwnCloud 8 and works wonderful and installation is really simple, but I can't find Identities configuration. In only have "General", "Folders" and "themes" tabs in config.

**Comment by RainLoop** [comment]
Thanks!
Check the 3.1 version.

**Comment by fracarvic** [comment]
Thanks, works like a charm!!!
