### ISSUE TITLE
Accounts disappeared after Update to 1.8.1.258

### ISSUE THREAD

**Issue by tarator** [RainLoop/rainloop-webmail#457]
After the upgrade to version 1.8.1.258 (released 16th Feb. 2015) accounts are deleted or they are not shown anymore (didn't check in database yet).
I updated from the previous released version using the automated update-script.

I used to login with one mailaddress (john.doe@example.com) and there I had multiple e-Mail accounts. After the upgrade only the account for john.doe@example.com is left.
![rainloop_accounts_disappeared](https://cloud.githubusercontent.com/assets/414814/6208695/ebe204d4-b5bc-11e4-8926-f7bcb4e21d80.png)

**Comment by umbertoB67** [comment]
Version 1.8.1.258 it is breaking changes.
You need to recreate your accounts and identities.

**Comment by ervee** [comment]
Just a thought: Is it possible to show the amin a warning before updating when there is a breaking change? It could save you a couple of bug reports and possible emails.

**Comment by skibbipl** [comment]
Also previously I was able to set two accounts with two different skins. Currently setting skin is for the whole instance. Can I set somehow two different skins per account?

**Comment by RainLoop** [comment]
> Also previously I was able to set two accounts with two different skins.
> Currently setting skin is for the whole instance. Can I set somehow different skins per account?

No, most of settings now are per user, not per account.

**Comment by skibbipl** [comment]
> No, most of settings now are per user, not per account.

Can you reconsider adding skin setting as per account? I use several accounts and I used different skin to distinguish between current selected account. Right now I have to check which account I have currently selected.

**Comment by RainLoop** [comment]
> Can you reconsider adding skin setting as per account?

Ok

**Comment by RainLoop** [comment]
> Just a thought: Is it possible to show the amin a warning before updating
> when there is a breaking change? It could save you a couple of bug reports and possible emails.

Yes, it's a great idea.

**Comment by RainLoop** [comment]
> Can you reconsider adding skin setting as per account?

Done, try to update your version.
