### ISSUE TITLE
Setting skin is still for the whole instance

### ISSUE THREAD

**Issue by umbertoB67** [RainLoop/rainloop-webmail#458]
RainLoop 1.8.1.258
Setting skin is still for the whole instance and not per account?

**Comment by RainLoop** [comment]
Try 1.8.1.260 :)

**Comment by umbertoB67** [comment]
In "About" RainLoop  says: RainLoop is up to date (RainLoop 1.8.1.258).
Sorry, where can I see RainLoop version in user interface?

**Comment by RainLoop** [comment]
Wait for a while :)

**Comment by umbertoB67** [comment]
:-))
Where can I see RainLoop version in user interface (not in Admin mode)?

**Comment by RainLoop** [comment]
> Where can I see RainLoop version in user interface

In the page source.

```
<!-- [version:1.8.1.260][time:0.0061][cached:true] ....
```

**Comment by umbertoB67** [comment]
RainLoop 1.8.1.260 installed.
It works very well! Good job, you are awesome!!
Now setting skin is again per account .
For RainLoop's version in user interface, I suggest to put an option ("About...") in the menu

![image](https://cloud.githubusercontent.com/assets/10993001/6216274/b4a7ab6c-b608-11e4-804f-eaa0c404558a.png)

**Comment by RainLoop** [comment]
I do not think that it is important for the end user.
