### ISSUE TITLE
Button overwrites the subject

### ISSUE THREAD

**Issue by umbertoB67** [RainLoop/rainloop-webmail#459]
![image](https://cloud.githubusercontent.com/assets/10993001/6215509/9af1d492-b601-11e4-8361-8bd69c251550.png)

**Comment by RainLoop** [comment]
It is a problem?

**Comment by umbertoB67** [comment]
Not so serious!
It was just a warning.

**Comment by megadr01d** [comment]
I think it looks fugly and the subjetc line should be truncated or, easier, move the reply button a few pixels down.
