### ISSUE TITLE
add a conversation view

### ISSUE THREAD

**Issue by awikatchikaen** [RainLoop/rainloop-webmail#46]
This view (like default gmail) is very useful when following on differents subjects !!

**Comment by giopas** [comment]
I came back to this thread for ask if any change happened on Thread view for Gmail account...

Thanks

**Comment by Razva** [comment]
Any news for 2017?

**Comment by diacritica** [comment]
Any news for April 2017? :)

**Comment by lnalex** [comment]
And for October 2017 ?

**Comment by tadeastadeas** [comment]
and for november 2017? :)

**Comment by prologic** [comment]
Is server-side IMAP support really required for this? Can this not be done client-side as per https://stackoverflow.com/questions/6088914/gmail-imap-how-to-get-conversations-threads-list ? Using X-In-Reply-To header?

**Comment by prologic** [comment]
Can we please reopen this if appropriate @RainLoop ? AFAIK this *can* be done client-side.

**Comment by brousselle** [comment]
+1 more explanations on why this is bound to server side implementation is welcome. 
This is really the feature i have been looking for since ages, and why i am still using gmail.

**Comment by SylwesterZarebski** [comment]
Threaded view is different than conversation view. Conversation view allow to easily view messages from current thread but from all folders, also Sent or Trash.
Ie. from reply You can scroll/go to original message you sent before or opposite.
Check how it is done in Thunderbird Conversations.
