### ISSUE TITLE
Gravatar Images not being fetched

### ISSUE THREAD

**Issue by pyther** [RainLoop/rainloop-webmail#460]
Running verson 1.8.1.260. CentOS 7, php 5.4. Gravatar images are not being fetched. I do not see any php errors. My ./data/_data_*/_default_/logs/ is empty.

Does the client or server fetch the gravatar images? Running Firefox 35.0.1 on the client. Let me know what additional information I can provide.

Thanks

**Comment by RainLoop** [comment]
Strange, try to open the following link

(your-installation-url)/?/Raw/0/Avatar/support%40rainloop.net/

**Comment by pyther** [comment]
Thanks for the quick reply, now everything appears to be working. Probably a problem between chair and keyboard. Sorry for the noise!

**Comment by RainLoop** [comment]
:)
