### ISSUE TITLE
Strange characters in plain text mode

### ISSUE THREAD

**Issue by skibbipl** [RainLoop/rainloop-webmail#462]
I use currently 1.8.1.260 version.
Today I discovered some strange characters when switching message editor from rich text mode to plain text:
![richtext](https://cloud.githubusercontent.com/assets/4746858/6225608/0c44ee6e-b68d-11e4-8b1b-68e6c7e43955.png)
And the same message in plaintext:
![plaintext](https://cloud.githubusercontent.com/assets/4746858/6225610/15f29dee-b68d-11e4-8eb5-c57a22613233.png)
I thought it might be related to some garbage in my identity, but it's empty:
![identity](https://cloud.githubusercontent.com/assets/4746858/6225613/27767b1c-b68d-11e4-8e2d-e83827bdf64f.png)

**Comment by RainLoop** [comment]
No, it is a signature's placeholder.
What is your OS and browser?

**Comment by skibbipl** [comment]
Windows 8.1 x64, Firefox Developer Edition 37.0a2 (2015-02-15). I used the same setup before and I didn't see any characters in plain text mode in earlier versions of RainLoop.

**Comment by RainLoop** [comment]
Thanks.

**Comment by skibbipl** [comment]
I've started seeing again strange characters in latest firefox versions (44 and 45):
![ff](https://cloud.githubusercontent.com/assets/4746858/11270520/f921e614-8ebf-11e5-9a2f-3cc23297e4b2.png)
I use latest RainLoop.
