### ISSUE TITLE
[Suggestion] Display maibox size

### ISSUE THREAD

**Issue by skibbipl** [RainLoop/rainloop-webmail#463]
What I really miss in RainLoop is an information about current mailbox size. I have a VPS server with limited HDD so I would like to know how much size my messages are. Currently there is no option to check that (except opening my mailbox in Thunderbird or checking the maildir used space on the server itself)
Can you think about adding such info somewhere in UI? My mailserver is not enforcing any quotas.

Thanks

**Comment by RainLoop** [comment]
Does your IMAP server support IMAP quota extension?

![quota](https://cloud.githubusercontent.com/assets/5530092/6225949/9bb37c00-b6a1-11e4-9a1d-97ea836377cf.png)

**Comment by skibbipl** [comment]
I use dovecot as a LDA. But I didn't configure any quotas. I guess I have to enable quota to have this information displayed?

**Comment by RainLoop** [comment]
yes

**Comment by iamchathu** [comment]
How about cpanel based mail quotas?

**Comment by RainLoop** [comment]
RainLoop works only with IMAP quotas. Does CPanel support IMAP quotas?

**Comment by luisbarona** [comment]
The actual issue with quotas is Rainloop displays the cPanel Account Quota and not the Mailbox Quota, i can't remember from which version this changed but it used to display the mailbox quota correctly in previous versions.

For example, in my server Rainloop displays a quota use of 31% as shown in the next image:
![image](https://cloud.githubusercontent.com/assets/23487095/21232101/7efabe14-c2b8-11e6-9b6c-b4b79b7e95eb.png)

But it should be displaying the Mailbox quota, which in my case, should be 3% as i have 29mb used of 1gb allowed, this is showed by the roundcube webmail:
![image](https://cloud.githubusercontent.com/assets/23487095/21232029/46d608ae-c2b8-11e6-95ad-ce69c23b5dc2.png)

If this happens for a wrong configuration in the Rainloop app, please let me know so i can fix it in my server, if this is not the case, i'm gladly reporting it in this message.

Thanks.
