### ISSUE TITLE
Impossible to sign in PGP in version 1.8.1.260

### ISSUE THREAD

**Issue by chtixof** [RainLoop/rainloop-webmail#464]
Hello. I was happy with PGP in RainLoop 1.7.2.229. But I upgraded to 1.8.1.260 from the web interface... And it's now impossible to sign in the PGP feature. So I am back to the old version.
FYI: I am using RainLoop from a Yunohost package: https://github.com/polytan02/rainloop_ynh
Thanks for your job!

**Comment by RainLoop** [comment]
Thanks
