### ISSUE TITLE
Mouse right click don't works correctly

### ISSUE THREAD

**Issue by umbertoB67** [RainLoop/rainloop-webmail#466]
While writing a new message, placing the mouse over some text, mouse's right click button does not work correctly and doesn't opens the context menu.
Clicking with right button where there is no text, it successfully opens the context menu.
In this way is impossible to use the online spell correction service or copy some text.
**It happens only if I use HTML format and if I change the text font.**
I'm using Chrome portable ver. 40.0.2214.94.
Best regards.

**Comment by RainLoop** [comment]
Thanks!

**Comment by umbertoB67** [comment]
Fantastic! It works!
