### ISSUE TITLE
[Trigger] Translation update request

### ISSUE THREAD

**Issue by ervee** [RainLoop/rainloop-webmail#467]
Hi,

Sometimes when RainLoop is updated there are strings added to the language files which need translation. To my best knowledge there is no trigger for (regular) translators to update the language files.

Is it perhaps an idea to ask regular translators to subscribe to this bug if they are not already subscribed to the whole repository? Then when you (@RainLoop) put a comment in this bug when there are added strings that need translation, the translators will get a notification of that.

I think this bug can even be closed for that to work, so it won't show as an open bug all the time.

Ralf.

**Comment by RainLoop** [comment]
Ok, let's try to do it.

**Comment by ervee** [comment]
Okay. I have parsed all pull requests and extracted who did updates on which language. I hope this is correct.

Dutch: @wtrdk and @ervee
French: @davbaumgartner and @Rbeuque74 and @sloomy
German: @Teranas
Hungarian: @KardiWeb
Italian: @nicolar and @pietroalbini
Latvian: @eddsstudio
Lithuanian: @daliusm
Norwegian: @filipblaauw
Polish: @james4321 and @skibbipl
Portuguese (Brazilian): @robertol and @arturbonnett
Portuguese (European): @insertc0in
Simplified Chinese: @yutianhot
Spanish: @yasselavila
Turkish: @s4l1h
Ukrainian: @alex-connor

These people will now get a notification if I'm correct.

If you do not want this notification, you can unsubscribe to this via the unsubscribe button on GitHub.

**Comment by RainLoop** [comment]
```ini
[SETTINGS_SECURITY]
LEGEND_SECURITY = "Security"
LABEL_AUTOLOGOUT = "Auto Logout"
AUTOLOGIN_NEVER_OPTION_NAME = "Never"
AUTOLOGIN_MINUTES_OPTION_NAME = "%MINUTES% minute(s)"

[SETTINGS_ACCOUNTS]
DEFAULT_IDENTITY_LABEL = "default"
```

![logout](https://cloud.githubusercontent.com/assets/5530092/6256962/72d41ccc-b7cd-11e4-89cb-e05695ee626a.png)

**Comment by RainLoop** [comment]
```ini
[COMPOSE]
BUTTON_REQUEST_DSN = "Request a delivery receipt"
```
![dsn](https://cloud.githubusercontent.com/assets/5530092/6319409/7a9ee886-bacc-11e4-85cb-ee0fd52e8339.png)

**Comment by robertol** [comment]
Cool

**Comment by RainLoop** [comment]
```ini
[MESSAGE]
BUTTON_THREAD_LIST = "Thread list"
BUTTON_THREAD_PREV = "Previous"
BUTTON_THREAD_NEXT = "Next"
```

**Comment by RainLoop** [comment]
```ini
[SHORTCUTS_HELP]
LABEL_THREAD_NEXT = "Next message in thread"
LABEL_THREAD_PREV = "Previous message in thread"
```

![image](https://cloud.githubusercontent.com/assets/5530092/6689358/b751b014-ccca-11e4-9659-ab33e0703486.png)

**Comment by RainLoop** [comment]
```
[MESSAGE]
BUTTON_THREAD_MORE = "More messages"
```

![image](https://cloud.githubusercontent.com/assets/5530092/6902940/b7b44a08-d71f-11e4-9d60-eb8ad3ed59a9.png)

**Comment by RainLoop** [comment]
```
[MESSAGE_LIST]
BACK_TO_MESSAGE_LIST = "back to message list"
```

```
[SHORTCUTS_HELP]
LABEL_OPEN_THREAD = "Open selected thread"
```

**Comment by RainLoop** [comment]
```ini
[SETTINGS_FOLDERS]
HELP_DELETE_FOLDER = "Delete folder"
HELP_SHOW_HIDE_FOLDER = "Show/hide folder"
HELP_SHOW_HIDE_FOLDER_COUNT = "Show/hide folder message count"
```
![image](https://cloud.githubusercontent.com/assets/5530092/7335040/23e86112-ebae-11e4-92d7-e09290e2d19a.png)

```ini
[MESSAGE]
LINK_DOWNLOAD_AS_ZIP = "Download as zip"
LINK_SAVE_TO_OWNCLOUD = "Save to ownCloud"
LINK_SAVE_TO_DROPBOX = "Save to Dropbox"
```

![image](https://cloud.githubusercontent.com/assets/5530092/7335046/5d658014-ebae-11e4-92e8-160497b19e2d.png)

**Comment by ervee** [comment]
@RainLoop. The rainloop/v/0.0.0/langs/nl.ini is English after your latest commit. Can you revert your change and re-add the new strings so I can translate them?

**Comment by RainLoop** [comment]
@ervee Done. Thanks!

**Comment by RainLoop** [comment]
```ini
[SETTINGS_FOLDERS]
HELP_CHECK_FOR_NEW_MESSAGES = "Check/don't check for new messages"
```

**Comment by skibbipl** [comment]
@RainLoop 
polish translation not updated with new strings

**Comment by RainLoop** [comment]
Sorry, fixed.

**Comment by RainLoop** [comment]
```ini
[POPUPS_FILTER]
SELECT_TYPE_OVER = "Over"
SELECT_TYPE_UNDER = "Under"
```

![image](https://cloud.githubusercontent.com/assets/5530092/7600394/580d8ff4-f913-11e4-85e3-508f6dd8bbd1.png)

**Comment by RainLoop** [comment]
```ini
[SETTINGS_GENERAL]
LABEL_IDENTITY = "Identity"
```
![image](https://cloud.githubusercontent.com/assets/5530092/7672061/897553a0-fced-11e4-9976-329b64c381f1.png)

**Comment by RainLoop** [comment]
![httpsonly](https://cloud.githubusercontent.com/assets/5530092/8513318/73910492-236e-11e5-97e9-650c374a8598.png)

```ini
[SETTINGS_OPEN_PGP]
GENERATE_ONLY_HTTPS = "HTTPS only"
```

**Comment by COLORLINK** [comment]
add me to the language team.
i have already added arabic language.. and sent ya an email about it .

**Comment by davbaumgartner** [comment]
@COLORLINK, you just have to pull-request your file on the repository and they'll merge it.

**Comment by ervee** [comment]
And by commenting on this thread, you just added yourself to the language team ;-)

**Comment by COLORLINK** [comment]
@davbaumgartner  done that.. but it seems they are not there since a while o.e
@ervee tyvm :)

**Comment by RainLoop** [comment]
![VACATION_RECIPIENTS_LABEL](https://cloud.githubusercontent.com/assets/5530092/9123243/fea9a94e-3c96-11e5-83c9-48543c4b7217.png)

```ini
[POPUPS_FILTER]
VACATION_RECIPIENTS_LABEL = "Recipients (comma separated)"
```

![ADD_A_PUBLICK_KEY](https://cloud.githubusercontent.com/assets/5530092/9123289/3aca2a48-3c97-11e5-9887-81d40647283d.png)

```ini
[PGP_NOTIFICATIONS]
ADD_A_PUBLICK_KEY = "Add a public key"
```

**Comment by akrosikam** [comment]
Hi!

I did some corrections and completed the Norwegian translation as of 29 days ago with 55011d7ae9e4c32be19de99fa549ee407534ed00, but I have not seen any response, probably because I did not ask here first.

So, is there anything else I should do, or do you think it can be merged as-is?
Thanks.

**Comment by akrosikam** [comment]
Do you still want us to contribute and pull-request translations? If so, how do we "sign the CLA"? The page you linked in your guidelines (http://www.rainloop.net/contribute/) only says "Contribute" and "Work in progress".

**Comment by RainLoop** [comment]
@akrosikam No, it is just for core developers. No need to worry if you just want to contribute a translation file.

**Comment by akrosikam** [comment]
Alright, thanks.

**Comment by RainLoop** [comment]
Hi, I have moved all translations to Transifex (https://www.transifex.com/rainloop/rainloop-webmail/).
To start translating, you have to become a member of the RainLoop translation team.

**Comment by arturbonnett** [comment]
Right ;)
Requested to join the Rainloop Team :+1:

**Comment by COLORLINK** [comment]
cant find arabic ?

**Comment by COLORLINK** [comment]
nm. just woke up.. found it

**Comment by sloomy** [comment]
Le 15/11/2015 01:29, RainLoop Team a écrit :
>
> Hi, I have moved all translations to Transifex (https://www.transifex.com/rainloop/rainloop-webmail/).
> To start translating, you have to become a member of the RainLoop translation team.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/RainLoop/rainloop-webmail/issues/467#issuecomment-156765025>.
>

Done :)



-- 
Bruno MILLION
WebDevelopeur et Webservices pour particuliers et professionnels.
Infogérance et consulting sur demande.
Site Internet : http://www.timelord.fr
Twitter : https://twitter.com/brunomillion

**Comment by pietroalbini** [comment]
Requested to join the team.

**Comment by DavidVentura** [comment]
Hi. 'BCC' needs translation, as well as "Request delivery receipt" and "Mark as important", all in the mail-composing window, at least in spanish

**Comment by pietroalbini** [comment]
> Edit: Only bcc needs the label/string. The rest weren't translated, I'll make a PR soon with translations

Translations are now managed on [Transifex](https://www.transifex.com/rainloop/rainloop-webmail/).

**Comment by mat-m** [comment]
Can close the issue since Transifex is here, no ?

**Comment by HLFH** [comment]
I think so. cc @RainLoop
