### ISSUE TITLE
date/time translation (i18n)

### ISSUE THREAD

**Issue by insertc0in** [RainLoop/rainloop-webmail#469]
Hi,

I'm not sure if this was already discussed before, I've searched through open/closed issues and could not find it. Anyway, I've noticed that date/time is not translated. I think those strings come from the Modernizr library. This includes months' names, time unit. I'd also like to mention the lack of a 24-hour format.

Nice work btw ;)

**Comment by RainLoop** [comment]
RainLoop uses moment js library for that.
What is your language?

**Comment by insertc0in** [comment]
My language is Portuguese.
Is it possible that it's translated somewhere else outside /langs/pt-pt.ini?

**Comment by insertc0in** [comment]
Found the problem!
The file name mismatches the language.
So, pt.js should be renamed to pt-pt.js.
I'm not sure if the same goes for the ckeditor or not.
Can you change the file name for moment?

**Comment by RainLoop** [comment]
Yes, I'll fix this.

**Comment by insertc0in** [comment]
Thanks.
I should have figure it out before.

**Comment by insertc0in** [comment]
I decided to create a PR for the file.

**Comment by jmce** [comment]
Actually, it should be possible to set the time format independently of the language, at least chossing between 12h & 24h format. If no other way is currently convenient, perhaps via special 'language' alternatives for those languages having 12h format by default?
