### ISSUE TITLE
Allow change of authentication on SMTP server

### ISSUE THREAD

**Issue by sanderhouttekier** [RainLoop/rainloop-webmail#47]
When you are an Admin,
The authentication for the SMTP server is not editable anywhere...
the auth of the SMTP server is not always the same as the auth of the IMAP or POP3 server. thus would be usefull to be able to specify auth details for it.

**Comment by ThomasWorking** [comment]
I have this same problem. The issue is that I want to use a different SMTP provider than my own server. I want to auth to Dovecot with different credentials than to 3rd party SMTP. I can't set the passwords explicitly for both of the servers separately. Is there a workaround for this?
