### ISSUE TITLE
Default Identity option gone

### ISSUE THREAD

**Issue by maddylliieeee** [RainLoop/rainloop-webmail#472]
I am not able to pick a default identity since the update to 1.8.1.
It seems the functionality added with "Ability to pick a "default" identity #157" was lost.

I can of course select the 2nd identity when sending mails, but it is very annoying that the default is the first in the list and is not changeable.

**Comment by RainLoop** [comment]
Drag your 2nd identity on top of the list.

**Comment by maddylliieeee** [comment]
Oh........................... this is.... somehow.... embarrassing....

Sorry! But it was in no way clear to me and I hadn't found this by myself....

**Comment by RainLoop** [comment]
Yes I agree with you, it is not quite obvious :(

**Comment by maddylliieeee** [comment]
From my end this can now be closed. But you may consider adding a small hint so it becomes more obvious.

**Comment by landona** [comment]
NOT obvious. Definitely. NOT. obvious. Although I feel a bit embarressed nevertheless. Maybe I am getting old.
