### ISSUE TITLE
Failed opening handle.php for inclusion.

### ISSUE THREAD

**Issue by benbristow** [RainLoop/rainloop-webmail#478]
Getting this error on my server (Running NGINX and PHP). PHP is working fine as I have a Wordpress blog running on the same Virtualhost.

In the error log:

Failed opening '/home/benbristow/web/benbristow.co.uk/public_html/rainloop/rainloop/v/1.8.1.263/app/handle.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /home/benbristow/web/benbristow.co.uk/public_html/rainloop/rainloop/v/1.8.1.263/include.php on line 228

**Comment by RainLoop** [comment]
Strange error. You get it all the time?

**Comment by benbristow** [comment]
Ooops. I know where the issue was. Filezilla failed to transfer the handle.php file. Always the simplest of things.

I used the installer via cURL and it's working fine now.
