### ISSUE TITLE
Owncloud credentials != Mail Account credentials ?

### ISSUE THREAD

**Issue by deMattin** [RainLoop/rainloop-webmail#481]
The usual way to use Rainloop is to login with a "first" valid mail account and this is then used as the account where you can add more accounts without giving credentials each time.
This works great for me and with auto login and use of "remember" (cookie) I don't have to login everytime on my own PC.
Until now I use Rainoop as a so called "external app" in Owncloud and this integrates fine. But this way the login is separated from the owncloud login 

I tried to use the ownloud app of rainloop, but here I have to set the mailadress with the same credentials for owncloud AND the mailaccount.
I don't want to synchronize these two passwords for different reasons!

The owncloud login should be independent of an existing or successfull mail-login with the mailadress and (owncloud-)password.
But for shure it has to be possible to create an account with the mailadress used in owncloud in the rainloop app.

So, is there already a way to use the owncloud app with autologin (owncloud credentials) and without the need to synchronize the passwords?
And if it's not possible already, do you see a way to realize this?

It's a bit complicated to explain, but I hope, you understand, what I mean.

**Comment by RainLoop** [comment]
> So, is there already a way to use the owncloud app with autologin 
> (owncloud credentials) and without the need to synchronize the passwords?

Yes, 

Admin / RainLoop Webmail/
Disable "Automatically login with ownCloud user credentials"

After that:
Personal / RainLoop Webmail
Setup your custom email/password

**Comment by deMattin** [comment]
GREAT!
I haven't seen the obvious!

Thanks.
