### ISSUE TITLE
Sieve Save button wrap

### ISSUE THREAD

**Issue by ervee** [RainLoop/rainloop-webmail#482]
Hi,

When editing Sieve filters I noticed the Save button wraps to the next line.

![fail](https://cloud.githubusercontent.com/assets/4435930/6315916/36c5b06e-ba12-11e4-8659-9a2829740679.JPG)

This is not an issue when I select English as language.

![ok](https://cloud.githubusercontent.com/assets/4435930/6315917/36e1ecac-ba12-11e4-9d85-856c68e56306.JPG)

Ralf

**Comment by RainLoop** [comment]
Thanks!
