### ISSUE TITLE
admin login failure

### ISSUE THREAD

**Issue by DummesBrot** [RainLoop/rainloop-webmail#488]
Hi!
i use rainloop addon (3.2) for Owncloud (7.0.4) 
* I cannot enter the admin tool. Every time I enter the login data, the login screen returns wihout fault message. (Log file 
![screenshot](https://cloud.githubusercontent.com/assets/11151036/6320635/68db3dea-bae3-11e4-9ee4-9fb344c4e141.jpg)

attached)
* I cannot access email - Fault message: Domain ist not available May not the major issue.

**Comment by FransIk** [comment]
I have the same problem. But I just use the standalone version (1.8.1.266).

**Comment by FransIk** [comment]
After I changed "fast_cache_driver" from memcached to files. I could login again.

**Comment by RainLoop** [comment]
Yes, it can be the cause of this problem.
