### ISSUE TITLE
session timeout

### ISSUE THREAD

**Issue by govindak** [RainLoop/rainloop-webmail#49]
How do I increase the session time for user logged in , so that user donot need to login for certain period of time

**Comment by michael-ts** [comment]
No such thing as session timeout?  Then why after a period of inactivity in the main mail browsing screen does it suddenly kick me to the login window and make me enter my password again?  @govindak  I don't see why you gave up so easily!

**Comment by ervee** [comment]
Did you see this option?

![capture](https://cloud.githubusercontent.com/assets/4435930/16094481/bd642f30-3340-11e6-8bc7-a3aba41b7724.JPG)

**Comment by michael-ts** [comment]
@ervee Yup, that's exactly what I was looking for, but oddly Google sent me to this page and made me think it didn't exist. :-)  Thanks!

**Comment by ervee** [comment]
You're welcome :+1:
