### ISSUE TITLE
PGP does Not work with two private keys of two identities

### ISSUE THREAD

**Issue by programacion-web** [RainLoop/rainloop-webmail#492]
I'm using the latest version, and testing the plugin pgp and I thank you very much the creation of this tool.

I have my e-mail account and an alias identity or extra, but each one has its own pair of keys.

works well with my main account but with the alias always says:"Unverified signature".

it seems to be that it does not recognize the private.key of my second identity,

thanks for all

**Comment by minami-o** [comment]
I confirm this.
On decryption as well, RL does NOT check the email address linked to the private key against the addressee, it seems to consider that the only valid address for a key is the main one.

**Comment by RainLoop** [comment]
Please, check the latest version. There are a lot fixes about your issue.
