### ISSUE TITLE
Message appears strange

### ISSUE THREAD

**Issue by umbertoB67** [RainLoop/rainloop-webmail#495]
I've replied to a mail with a long text.
When I go in Sent Items I see it so:
![image](https://cloud.githubusercontent.com/assets/10993001/6333529/176a44d2-bb8e-11e4-9a29-f28763642988.png)

Best regards.

**Comment by RainLoop** [comment]
This problem persists? Сan you repeat this?

**Comment by umbertoB67** [comment]
Unfortunately I cannot reproduce it, but this is the second time that happens.
In next days I'll try again to reproduce it so I can say you something more.

**Comment by umbertoB67** [comment]
Sorry, I cannot reproduce it.
