### ISSUE TITLE
OwnCloud 8 automatic login does nothing

### ISSUE THREAD

**Issue by nakedhitman** [RainLoop/rainloop-webmail#496]
After installing the RainLoop plugin on OwnCloud 8 and setting the "Automatically login with ownCloud user credentials" option, I am still prompted for credentials when launching the app. I am using LDAP and have identical credentials to get in to OwnCloud and my email server. Please let me know what information would be helpful to figure out where the breakdown is.

**Comment by RainLoop** [comment]
Well, this is a comment from ownCloud forum:
```
If you are using the LDAP app and RainLoop does not log you in
automatically to your e-mail you might have to add go in your
Admin - Settings LDAP Settings - Expert (tab) - under Internal 
Attributes add: sAMAccountName.
```

**Comment by nakedhitman** [comment]
I have set sAMAccountName under the Expert settings, unset and re-enabled automatic login, logged out, logged back in, and am still greeted with a login prompt when I access the RainLoop app. Can you think of anything else I might need to change? Thanks for looking at this.

**Comment by RainLoop** [comment]
What is your domain configuration (IMAP settings)?
Can you show screenshots?

**Comment by nakedhitman** [comment]
https://cloud.awesomegeek.com/index.php/s/3gVtgCCP2L1enHT

If I log in manually, it all works just fine. I see no errors, so I'm not sure what might be breaking down with the automatic login. I just tried various combinations of "use authentication" and "use short name" and that had no effect.

**Comment by RainLoop** [comment]
Do you use email as login in the ownCloud?

**Comment by RainLoop** [comment]
In most cases "Use short login" should be disabled

**Comment by nakedhitman** [comment]
I was logging in using the short name. I changed to log in using my email and disabled the short name setting in the domain, but I'm still having issues.

**Comment by RainLoop** [comment]
Ok, can you send me (support@rainloop.net) RainLoop's logs?

**Comment by nakedhitman** [comment]
I did have to alter my user in AD to add an email address before it would let me do that, and I notice that OwnCloud still thinks that my user has no email. I wonder if my user is cached somewhere...

Where are RainLoops logs stored? I was looking for them before I opened this issue, but was having trouble finding them.

**Comment by RainLoop** [comment]
```
<ownCloud data folder>/rainloop-storage/_data_xxxx/_default_/
```

configs/application.ini

```ini
[logs]
enable = On
```

logs/*

**Comment by nakedhitman** [comment]
Well, that was insightful. It seems to think my email address is f468a775-9446-4ccd-bda4-0149308f790d@awesomegeek.com. I'm betting that's more of an OwnCloud problem than a RainLoop problem. Am I correct in that assumption?

Full logs at: http://pastebin.com/za33Xnw5

**Comment by RainLoop** [comment]
> I'm betting that's more of an OwnCloud problem than a RainLoop problem.
> Am I correct in that assumption?

Yes, RainLoop needs to take email from ownCloud

It logic is:
```php
$user = OCP\User::getUser();
```

As you can see, ownCloud api returns " f468a775-9446-4ccd-bda4-0149308f790d".
Most likely it is the internal name of your LDAP user.

**Comment by nakedhitman** [comment]
OK, I have it all figured out now. It turns out that sAMAccountName was technically the solution, but I had to clear the user mappings in the LDAP config before it would start working. This means I loose all my user data, but I can always re-sync it. This might be good info to document somewhere.

**Comment by RainLoop** [comment]
OK, Thanks!

**Comment by nakedhitman** [comment]
**DANGER WILL ROBINSON**
If you reset your user mappings while your desktop clients are still linked to the system, they will sync down an empty directory and delete all your local files!

Thankfully, this does not delete the files on the server. If you can find your old UUID folder under the OwnCloud data directory, you can move the files into your new user folder. Once the files are moved, you will need to initiate a rescan with:

    sudo -u www-data php $OWNCLOUD/console.php files:scan --all

Just thought this was worth mentioning. Thanks again for your help.

**Comment by apg1980** [comment]
Can u provide an workarround for this problem? I run also into this issue, while my usernames are listed as uuid's and i'm unable to change the display behaviour of my lot of accounts. i tryed to play arround with the plugin custom-login-mapping but no success.
