### ISSUE TITLE
OwnCloud 8 contacts module does not work

### ISSUE THREAD

**Issue by nakedhitman** [RainLoop/rainloop-webmail#497]
When setting up the contacts module in the RainLoop settings, I have checked "Enable contacts", "Allow contacts sync", and have entered my PostgreSQL DB as follows: 

    pgsql:host=::1;port=5432;dbname=rainloop

Credentials are using the same role as OwnCloud, which owns this new DB. However, when I press the "Test" button, I get:

    Personal address book driver is not allowed

Can you explain this error in more detail? Do I have to import a DB schema, or is something configured to disable this integration for the OwnCloud plugin? Please let me know, as this feature is really cool and I would like to use it.

**Comment by RainLoop** [comment]
It does not need to do.

RainLoop ownCloud package takes (Contacts suggestion on compose screen) contacts directly from ownCloud. Contacts popup disabled in RainLoop to avoid user's confusion.

**Comment by nakedhitman** [comment]
Perfect, thank you.
