### ISSUE TITLE
CardDav Sync missing

### ISSUE THREAD

**Issue by mateberlin** [RainLoop/rainloop-webmail#499]
After updating to 1.8.1.271 the carddav-sync feature is missing. I can enable "Allow contacts sync (with external CardDAV server)" in Admin Panel, but loggin as user there is no card-dav sync

**Comment by RainLoop** [comment]
Thanks! You have found the bug.
Try to update your installation.

**Comment by mateberlin** [comment]
Thanks for fixing ... I can't update yet, the admin panel is saying i'm up to date with 1.8.1.271

**Comment by RainLoop** [comment]
Sorry, try again.

**Comment by mateberlin** [comment]
still 1.8.1.271 "RainLoop is up to date" ... deleted browser cache, still up to date.

**Comment by mateberlin** [comment]
working again :) Thanks for fixing
