### ISSUE TITLE
Update Feature in Owncloud App?

### ISSUE THREAD

**Issue by deMattin** [RainLoop/rainloop-webmail#500]
I subscribed the Trigger-Thread for new updates and it's a good idea to get notified about new versions.
Previously I had to log in as admin and in the "About" section there was a nice update button.
I'm not really shure but as I remember, this worked after first installation of the owncloud rainloop app as well.
Now (update from 1.8.1.266 to 1.8.1.271) I get a "Download" button instead of the "Update/Upgrade" Button.

Is this an issue with the owncloud app, that there is no update with one click or with this upgrade step?

And I would suggest to give a short release info in the "Trigger" thread and not only a post with the new version. This way it would be easier to check the new or fixed features.

**Comment by RainLoop** [comment]
This button (Update) is available if the application has enough file permissions.

**Comment by deMattin** [comment]
Ok, thanks.
A simple:
# chown rC www-data:www-data /var/www/owncloud/apps/rainloop
did the thing in Debian with Apache!
I had it with owner "root" as the other apps in owncloud.

But I had in mind, that I used this update button with user "root" before. Maybe I remember wrong ...
