### ISSUE TITLE
Full unicode support?

### ISSUE THREAD

**Issue by skibbipl** [RainLoop/rainloop-webmail#501]
Yesterday I recieved an e-mail with unicode images in subject. This is how it look like in Gmail:
![gmail](https://cloud.githubusercontent.com/assets/4746858/6360921/17278002-bc7e-11e4-9d4d-021d57aeecf2.png)
And this is the same mail in thunderbird:
![tbird](https://cloud.githubusercontent.com/assets/4746858/6360922/1f636b64-bc7e-11e4-8585-efe48ce7aeac.png)
I forwarded the e-mail to rainloop, but unfrotunately RainLoop doesn't display subject correctly.
Here is subject header from the mail:
```Subject: =?UTF-8?B?RndkOiDwn5OIIEJpZyBkYXRhIGNhcmUgcGFja2FnZSDwn5OK?=```
I guess this issue is related to font used in rainloop?

**Comment by RainLoop** [comment]
Thanks I'll see what the cause of the problem.

**Comment by RainLoop** [comment]
OK, I've made some fixes.
Firefox works great, but chrome does not.

Firefox:
![image](https://cloud.githubusercontent.com/assets/5530092/6372401/ff6aee30-bd14-11e4-92a8-baf32c85aac6.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/5530092/6372414/144bae34-bd15-11e4-8e0b-fcba185d6d1d.png)

http://stackoverflow.com/questions/24318787/how-to-get-a-specific-unicode-character-to-display-in-chrome-webkit-browsers

**Comment by skibbipl** [comment]
:+1: I use firefox
