### ISSUE TITLE
OC8, An Error Occurred, please refresh the page and try again.

### ISSUE THREAD

**Issue by millnerd** [RainLoop/rainloop-webmail#503]
I have Rainloop 3.2 installed as an app in my OC8 which is hosted on Windows 8 IIS7 server.  No matter what I do when I try to access the admin page for rainloop I get the error message above.  I've turned on the error log, but after attempting to access the app, nothing is added to the log.  Any ideas?

**Comment by RainLoop** [comment]
Can you tell me your installation URL?

**Comment by millnerd** [comment]
It is installed at www.mmillerandfamily.com/owncloud/ and then in the apps folder.  I've enabled it through the owncloud admin interface, but keep getting the error mentioned.  I've double checked pho version, enabled the logs in the rain loop config file, and I'm getting nothing in the log folder or in the php logs.  Any advice would be appreciated...

Mike

**Comment by RainLoop** [comment]
Ok, can you give me OC access credentials for tests?

**Comment by RainLoop** [comment]
support@rainloop.net
