### ISSUE TITLE
manipulate Exim without cPanel

### ISSUE THREAD

**Issue by TameOfGroans** [RainLoop/rainloop-webmail#504]
for cPanel based Web hosts it would be spiffy to create Exim rules from the web mail client without passing through cPanel. 

Exim rules are "server side" whereas sieve are "client side".

All glory to eximtoad

**Comment by ervee** [comment]
Sieve is definitely also "server side". And you manage them via the manage-sieve protocol from RainLoop. Is there such a management protocol to Exim which could be used by a web mail client?
