### ISSUE TITLE
No more email accounts after upgrading to 1.8.1.272

### ISSUE THREAD

**Issue by bms8197** [RainLoop/rainloop-webmail#507]
I have several other email accounts from my server added to my main email account on rainloop so I can quickly check them all. After I have upgraded to 1.8.1.272, I can only see my main email account. All other accounts have dissapeared. I had to add them manually. I have upgraded from 1.7.x (last version of that branch).

Any clues?

**Comment by arturbonnett** [comment]
Version 1.8.1 it is breaking changes. You need to recreate your accounts and identities.
> 1.8.1 New storage for settings. (You need to recreate your accounts and identities)  (Warning! Breaking changes) - 14.02.2015
#457

**Comment by bms8197** [comment]
Oh, ok. I didn't know that. Thanks for the info.
