### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by mat-mo** [RainLoop/rainloop-webmail#508]
Please add support for RTl languages, e.g Arabic, Hebrew, Urdu, etc.
This support includes:

1. text bidirection - see attached for all 4 modes of mixed RTL
![rtl](https://cloud.githubusercontent.com/assets/4245366/6393309/9dfe7e9c-bdd1-11e4-872e-785d212e6003.png)
2. UI support for RTL

**Comment by hadifarnoud** [comment]
in your online demo, RTL was not working. you don't need to add RTL in the interface, just add it in compose editor
