### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by jashparekh** [RainLoop/rainloop-webmail#509]
I deployed the application on my server. I had couple of queries:
I have a multi domain shared hosting server, so can I access mail accounts of domain names if I deploy it only on the main domain? I tried this but it didn't work.

So now I have deployed the application on each domain and still cannot access the accounts.
It gives me a "Can't connect to server" error.

I went through the guide on your website and did all followed all the mentioned steps.

Can you please guide how to solve this and can I access multiple domain accounts through a single deployment.

**Comment by RainLoop** [comment]
You need to add these domains (domain part of email address) in domain section of admin panel.

**Comment by jashparekh** [comment]
I did that, still it gives the "Can't connect to server" error.

**Comment by RainLoop** [comment]
Ok, can you give me (support@rainloop.net) access to your admin panel and credentials for email account (test)?

**Comment by jashparekh** [comment]
I have sent a mail with all the details you have asked for. Thanks in advance!!

**Comment by jashparekh** [comment]
Thank you for all the assistance.!!

**Comment by koppor** [comment]
Is it posible to comment on the problem and the solution as this page is the first hit for googling for `rainloop log Can't connect to server`.

**Comment by jenki221** [comment]
yes, please respond as I'm having this same issue as well. Error code 104 if that helps. Thanks

**Comment by gathagu354** [comment]
Any solution on these thread on the said issue? Rainloop is giving me some terrible reliability issues.
