### ISSUE TITLE
More information on errors

### ISSUE THREAD

**Issue by yswery** [RainLoop/rainloop-webmail#510]
Trying to send an email I get a long loading sign and then JS alert saying that message could not be sent

Using other mail client (not rainloop) I get 

```
SMTP Error (450): Failed to add recipient "xxxx@gmail.gr" (4.1.2 <xxxx@gmail.gr>: Recipient address rejected: Domain not found).
```

So my proposal would be to add better error alerts :)

**Comment by RainLoop** [comment]
```
./data/...../application.ini
```
```ini
[labs]
smtp_show_server_errors = On
```
