### ISSUE TITLE
Account list cleared after update

### ISSUE THREAD

**Issue by shade511** [RainLoop/rainloop-webmail#513]
Hello,

I recently updated to 1.8.1.276 and on I lost my whole account list I had before update. I tried change parameter mentioned in other issue (https://github.com/RainLoop/rainloop-webmail/issues/505)

[labs]
use_imap_esearch_esort = Off

however it did not change anything at all. 

Is there any way to recover account list? It's super frustrating to lost around dozen of accounts already set. 

Thanks!

**Comment by ervee** [comment]
https://github.com/RainLoop/rainloop-webmail/issues/507#issuecomment-76180395

**Comment by shade511** [comment]
that's... sad. and frustrating.

**Comment by ervee** [comment]
I happens sometimes. If you would take it, I would advise you to read the changelog (http://www.rainloop.net/changelog/) before upgrading. Also, I hope the updater will notify you of breaking changes from now on (https://github.com/RainLoop/rainloop-webmail/issues/457#issuecomment-74514212) but I'm not sure if it's implemented yet.

**Comment by shade511** [comment]
yeah, my bad. I just did not expect to lost some data just by upgrading. :)
