### ISSUE TITLE
Composer loses focus in Internet Explorer 11

### ISSUE THREAD

**Issue by ervee** [RainLoop/rainloop-webmail#515]
Hi,

First of all, I'm not a fan of IE, but some of my users (must) use it. And I suppose you want RainLoop to function with IE too :)

When I login and create a new email message the composer is in HTML mode in my setup. When I set it to plain text and then go about typing an email, the composer loses focus in about 1 to 5 seconds, making us unable to input text.

This also happens when I reply to a plain text email message because the composer will be in plain text mode. I don't see this behavior in Firefox.

I don't expect to see a message in the log about this, but enabled logging in application.ini anyway. But it doesn't show anything useful I think.

Can you (or anybody) reproduce this?

Thanks.

**Comment by RainLoop** [comment]
> Can you (or anybody) reproduce this?

Unfortunately, I can't :(
Have you tested it with last version?
There are some fixes in the mail composer.

**Comment by ervee** [comment]
Of course. I forgot to mention. I updated to the latest version before logging this bug. I'll try to figure out what is going on. Could anyone give me some tips on how to debug this in IE?

**Comment by landona** [comment]
I can confirm the problem. It still happens with current version of rainloop. The editor is not usable in plain text mode with IE 11. (I am on Windows 7 if that matters.)
Unfortunately I cannot investigate further because I am only using Windows at work and they pay me for debugging something else.

**Comment by antondollmaier** [comment]
This issue is still present. When replying to an email using the plain text editor in IE/Edge, the cursor looses focus.

When using HTML editor, everything is working.
