### ISSUE TITLE
SSO

### ISSUE THREAD

**Issue by allertec** [RainLoop/rainloop-webmail#516]
Hi Rainloop Team,

I am trying to enable SSO in plugin for Owncloud, but I am faiiling. Is it actually possible?

I am also tryig to implement it as standalone software. and then embed it into OWncloud and again I am failing. Could you please help?

thank you

**Comment by deMattin** [comment]
What do you want at achieve with rainloop as a "standalone" version?
If you use OC 7 or 8 in last version, rainloop oc app should work simple and fine.
Install it -> set rights of app folder and files to "used by webserver" (www-data on Apache) -> set mail and passwort in personal settings of owncloud -> have fun ...
You should not use login with "Automatically login with ownCloud user credentials" in Admin panel of OC. I have been confused here, too - search here in issues... :wink:)

- If you want to authorize with owncloud, you should use the owncloud "version" of rainloop. It is the same; with some little changes and always has the same version and features as the independent one.

- You can start rainloop (oc app) with a direct link and without oc header but authorized against the oc cookie and login (domain.com/owncloud/index.php/apps/rainloop/)

- If you install a standalone version of rainloop you can simply integrate rainloop as "external app". This has worked for me over month. But here you have a separate cookie with its own livetime and a independend login (the mail-account, you define first, then is the login).

**Comment by megadr01d** [comment]
Is [this](https://github.com/RainLoop/rainloop-webmail/wiki/SSO-example) relevant?
