### ISSUE TITLE
Provide versioned weekly download

### ISSUE THREAD

**Issue by Sp1l** [RainLoop/rainloop-webmail#517]
Hi,

Was just working on an update for the FreeBSD port of Rainloop and found difficulty in locating the latest tarball. There's a 1.8.1 rainloop-latest.zip from http://repository.rainloop.net and there's an 1.8.1 download from sourceforge yet these are not the same (different weekly build I guess).

Can you provide a download (even a GitHub tag like v1.8.1.281 will do just fine) so the port can download a specific version? FreeBSD's ports infrastructure knows 

Thanks! Bernard Spil.

**Comment by RainLoop** [comment]
GitHub is NOT a stable version of RainLoop Webmail.

But, you can find the permalink here:
http://repository.rainloop.net/v2/core.stable.json

**Comment by Sp1l** [comment]
That part I did pick up on. 
The thing is that I'd like to have a versioned download (rainloop-v1.8.1.281.zip 03-03-2015) rather than only a rainloop-latest.zip and a rainloop-1.8.1.tar.gz. The current download we use from sf.net is 1.8.1.276 (26-02-2015). The -latest download is porbably 1.8.1.281 but not a stable download. Since -atest changes every week this will result in sha256 mismatch on the tarball let alone the hash mismatches on all installed files. These sha256 hashes provides proof for the user of the port that he has the correct (not tempered with) tarball.

Thanks, Bernard.

**Comment by RainLoop** [comment]
> The thing is that I'd like to have a versioned download (rainloop-v1.8.1.281.zip 03-03-2015) 
> rather than only a rainloop-latest.zip and a rainloop-1.8.1.tar.gz.

Well, you can get it from:
http://repository.rainloop.net/v2/webmail/1.8.1/rainloop-1.8.1.281-7ef72935d0e81a2a9d5b158f19be0a3a.zip

It is a permalink.

It's not enough?

**Comment by Sp1l** [comment]
That would work just fine! 
I must have missed the location on the website where I can find these links. http://repository.rainloop.net/v2/webmail/1.8.1/rainloop-1.8.1.281.zip I could compose myself but that hash part I can't find anywhere on the site :/

**Comment by RainLoop** [comment]
>  I could compose myself but that hash part I can't find anywhere on the site :/

You can find it here:
http://repository.rainloop.net/v2/core.stable.json

**Comment by Sp1l** [comment]
I feels soooo stupid :-1: Could've found that method in the UI code that tells you dat you need to/can update.
Thanks for the instant support!

**Comment by Sp1l** [comment]
Updated the FreeBSD port to the latest version and added a structure so we can keep up-to-date. https://bugs.freebsd.org/198374
Thanks!

**Comment by RainLoop** [comment]
Thank you, you're doing a great job.
