### ISSUE TITLE
Beta 1.8.2

### ISSUE THREAD

**Issue by RainLoop** [RainLoop/rainloop-webmail#518]
What do you think about new threads?

![thread](https://cloud.githubusercontent.com/assets/5530092/6530072/da74039c-c43e-11e4-887f-41ce9387f0a9.png)

Beta version for testing:
http://repository.rainloop.net/v2/webmail/1.8.2/rainloop-1.8.2.284-8ed02816bec5fd2954a0a65b5ff5fd59.zip

**Comment by arturbonnett** [comment]
Working ok here... the arrows function is cool, but I think I prefere to see all the messages like on stable version...
Would be realy nice, a thread like outlook :stuck_out_tongue_winking_eye: 
![captura de tela 2015-03-06 15 03](https://cloud.githubusercontent.com/assets/7110872/6530722/2081ed86-c412-11e4-982c-ba5364383a9d.png)

**Comment by RainLoop** [comment]
> but I think I prefere to see all the messages like on stable version...

I understand that, but it is not very good as it will work slowly.

**Comment by arturbonnett** [comment]
Okay, it is really much faster!
Should be easy to get used to browse faster :+1:
