### ISSUE TITLE
Signature not avalible in reply

### ISSUE THREAD

**Issue by ProsperDevelopment** [RainLoop/rainloop-webmail#52]
Hi!

First of all I would like to say a-some piece of software. Love the UI!

My only issue right now is that I can not get my signature shown i my message when replying to messages. 

Is it a bug or something i missed?

Best regards
Emmanuel

**Comment by nicholas-itpedia** [comment]
This issue should be re opened. I cannot find the configuration option "Add your signature to all the outgoing messages" in the admin account or a user account. If this is not a bug, please be more descriptive in where the configuration option is. Providing a URL such as:

[domain]/rainloop/#/settings/general

would be helpful. 

Thank you for such fantastic software.

**Comment by nhdnet** [comment]
I see that this functionality was added but then removed. In fact, the labels like "LABEL_ADD_SIGNATURE_TO_ALL" still exist in master branch but functions like signatureToAll() and all code from commit https://github.com/RainLoop/rainloop-webmail/commit/b0593b813e789fafdadb53509efd367fc5a195c5 are totally removed later

**Comment by the-djmaze** [comment]
I have no idea why this should be opened.
It works everywhere as expected in RainLoop and my SnappyMail fork
