### ISSUE TITLE
Customizing and Theming in Owncloud (css)

### ISSUE THREAD

**Issue by deMattin** [RainLoop/rainloop-webmail#520]
Actually I'm on customizing my Owncloud and I use the theming of owncloud for this.

One goal is to colorize the OC header depending on the app that is actually shown in owncloud like this:
![image](https://cloud.githubusercontent.com/assets/5565503/6545934/dc98e79e-c59e-11e4-840e-63c99f74894e.png)

In most oc-apps you can achieve this by overwriting parts of css definitions. OC has a predefined way to do so - also for apps.

To modify header you can i.e. use the "default" css of the app and overwrite some settings with new css definitions in a personal theming folder with a css file named like in the app.
To modify header-color there you can simply define:

#body-user #header {
	background-color: #AAAAAA;
}

to overwirte header color.

Rainlopp uses an iframes and has no global "app-css" included. So OC uses the deafult header color if rainloop is active.
Actually I see no way to force a new header color if rainloop is active.

One easy way, how you could help, would be to integrate in rainloop oc app-definition a default css-file in the app folder (rainloop/css/style.css) like other apps do it.
There has no css definition to be in there. I think, it can be empty.
I have tried hours to give a working patch but I don't know enough to have success to integrate such a css file.

Could you please help?

**Comment by RainLoop** [comment]
This approach does not work well with the theme system.
Why you don't want customize the default theme?

In the premium version you can set Custom Css setting:

![04](https://cloud.githubusercontent.com/assets/5530092/6555270/65c39c4a-c675-11e4-8e5a-596495f3af96.png)

**Comment by deMattin** [comment]
I don't want to customize the rainloop theme!
With rainloop integrated in owncloud via app, there's a menu and a header of oc and rainloop is an iframe. I want to customize the header and menu of OC.

OC has a integrated overwrite system for theming to do so.

But I only am be able to overwrite a css, that alredy exists in the outer OC frame. It has to be a css in the app info of OC.
This css file will be registered in the OC part and not in the rainloop part of the page.

The recommended enhancement has to be in OC app definition of rainloop and not in rainmoop part ("v" oder "data" folder) itself

It's not easy to explain, but I haven'r given up to get a working code.

**Comment by deMattin** [comment]
Following steps are needed:

create following fle style.css there: .../owncloud/apps/rainloop/css/style.css
content of style.css:
>/*
>Empty style sheet!
>Only needed to give you the opportunity to theme the owncloud part
>of the rainloop app with the in ownCoud integrated  theming system.
>*/

patch the file .../owncloud/apps/rainloop/appinfo.app.php:
> _OCP\Util::addScript('rainloop', 'rainloop');_
>
>**// Load the style file we need to allow theming the ownCloud header and navigation **
>**OCP\Util::addStyle('rainloop', 'style');**
>
>_OCP\App::addNavigationEntry(array(_

That's all.
Now you are allowed to theme the owncloud header (headline) and menu depending on wether the rainloop app is active.

Are you able to update this with the rainloop auto updater in a next release or would it be neccessary to install a new rainloop app version for this?

**Comment by RainLoop** [comment]
Thanks! Now, I understand you. You do not need to change styles of the RainLoop.

Ok, I will add your changes/fixes to the code.

> Are you able to update this with the rainloop auto updater in a next release
> or would it be neccessary to install a new rainloop app version for this?

It is an ownCloud package and I can't update it with auto updater.

**Comment by deMattin** [comment]
Thank you.
Could you please give feedback, when you have uploaded the new version?
I don't know, how to automatically upgrade the app itself - maybe it's neccessary to reinstall it to get the updated rainloop owncloud app core part.

**Comment by deMattin** [comment]
Sorry, could you please wait a while with integrating the code?
Maybe I found an issue.
I have to do more testing first ...

**Comment by RainLoop** [comment]
Ok

**Comment by deMattin** [comment]
I integrated the "addStyle" in the wrong place.
The following works the right way:

1. create following file "style.css" there: .../owncloud/apps/rainloop/css/style.css
content of style.css:
>/*
>Empty style sheet!
>Only needed to give you the opportunity to theme the owncloud part
>of the rainloop app with the theming system integrated in ownCoud
>if the rainloop app is activated.
>*/

2. patch the file .../owncloud/apps/rainloop/index.php:
>`* @copyright 2015 RainLoop Team`
>`*` 
>`* https://github.com/RainLoop/rainloop-webmail/tree/master/build/owncloud`
> `*/`
>` `
>**// Load the empty file ../css/style.css, that's needed to allow theming of
>// the ownCloud header and navigation if rainloop is the active app.
>OCP\Util::addStyle('rainloop', 'style');**
>` `
>` OCP\User::checkLoggedIn();`

**Comment by RainLoop** [comment]
Thanks!
