### ISSUE TITLE
Editor bug with ordered and unordered lists

### ISSUE THREAD

**Issue by jbleuzen** [RainLoop/rainloop-webmail#522]
Just a small glitch on editor, with both ordered and unordered lists.

Step to reproduce : 

* Enter a line of text, hit enter
* Click on unordered list bullets (a bullet will appear)
* Enter some text, hit enter

You'll end up with the following capture : 

![screen shot 2015-03-11 at 06 23 27](https://cloud.githubusercontent.com/assets/280681/6590802/31d5dffe-c7b7-11e4-8257-f64ca8351c84.png)

The line is marked as an unordered list line but no bullet is shown. If you click on unorderd list bullet it will remove the bullet from previous line.

There is definitively something strange in this behaviour...

**Comment by RainLoop** [comment]
Thanks! Yes, I know about this bug.
It will be fixed in the next version.
