### ISSUE TITLE
Issue interface in version:1.8.1.281

### ISSUE THREAD

**Issue by umbertoB67** [RainLoop/rainloop-webmail#531]
Today, without doing any update, I see this:
![image](https://cloud.githubusercontent.com/assets/10993001/6662836/685abd58-cbc0-11e4-8ef7-a4b77dd83a5d.png)

Why? Best regards.

**Comment by megadr01d** [comment]
Same issue [here](https://github.com/RainLoop/rainloop-webmail/issues/191). Apparently, `parse_ini_file` was disabled in PHP's main config.

**Comment by RainLoop** [comment]
RainLoop does not use `parse_ini_file` function if it is disabled.

**Comment by RainLoop** [comment]
@umbertoB67 
Any errors in php logs?

**Comment by umbertoB67** [comment]
No errors in php logs, but now it works correctly!

**Comment by megadr01d** [comment]
Just FYI, today I got these variables instead of the actual labels in the login form. <kbd>Ctrl + F5</kbd> fixed it (latest Chrome, Windows).
