### ISSUE TITLE
Forwarding HTML mails

### ISSUE THREAD

**Issue by skibbipl** [RainLoop/rainloop-webmail#532]
It seems RainLoop cannot handle properly HTML mails forwarded from thunderbird. This is original mail displayed in RL:
![original](https://cloud.githubusercontent.com/assets/4746858/6684263/ddc45a02-cc8f-11e4-901e-e0ba761d0f4d.png)
And the same mail forwarded by thunderbird:
![forwarded](https://cloud.githubusercontent.com/assets/4746858/6684276/f6b4f9b8-cc8f-11e4-9e63-5f380f7f57ec.png)

**Comment by RainLoop** [comment]
Can you give me (support@rainloop.net) this message (.eml file)?

**Comment by skibbipl** [comment]
Which one, forwarded or original?

**Comment by RainLoop** [comment]
> Which one, forwarded or original?

forwarded  or both :)

**Comment by skibbipl** [comment]
Mails sent to support mail. Thanks!

**Comment by RainLoop** [comment]
Thanks, It will be fixed in the next version.
