### ISSUE TITLE
Error loading files and other issues (500 Internal Server Error)

### ISSUE THREAD

**Issue by insertc0in** [RainLoop/rainloop-webmail#540]
This is probably not an issue with the Rainloop itself, but I thought of asking for help since I can't really figure out what's wrong. I had installed Rainloop v1.8.1.276 in a server managed by a third-party.
Everything was working great until yesterday when I tried to login and noticed that, beside the long loading times, the theme was not displaying correctly. So I opened the browser's developer tools and checked for anything out of the ordinary, there it was:
`?/Css/0/Admin/-/SquaresDark/-/cf41fa2216d51cfc14cc92052023e13d/Hash/-/`
was throwing a *500 Internal Server Error* every time I loaded any Rainloop page.

I couldn't figure it out so I thought I might try reinstalling Rainloop from scratch and update it at the same time. Not only did the problem persist, I found that the folder where Rainloop is installed was filled with lots of *core.xxxxxx* files ("xxxxx" being random? numbers). Every time I reloaded the page and got a 500 error, one of those *core* files was generated. A single *core* file is 19MB in size and the file header has ELF in it. From a quick Google search I understand that these files are usually dump files generated by the web server whenever it crashes. It becomes apparent that the issue is with the web server itself and not with Rainloop. I tried a few hours later and now nothing will load, giving a 500 error immediately after loading boot.js:
`?/AppData/_B62lkJDrKe_tsAXZNTZNKY2AnlKGuK2DGNoJVLtCbKw3q6HQfzOYMNUAKA1dZ6M_YRcj07lIBOk-1DCyQOcBmfPS-PptktDKZGQipSlhS4E5B_sEhUcp3DQ_ksZDxTR3YtSJvwvPnZYSHy-kBYsZE0YAJqCuH2mowXep3_9STxgzB4jtXRzzGGp4r_2AFo2Z0NS8F8z9mpzWdH5MLgriWtjLABe7kvEU5wendeUD1E_OnBlKDgiudgxHAl5wPCj9mtsqthM5Wdc8qAIaUIoSOS9IFimcmxMohdGgud_ldKwx3qVgdg5RLlP09NOhQHvY1HMZH0_JH-f26QaIQu6rIqF0JkuYVltUaDpWPo0M6PArd_XgibbpDlhwSFQ6WU_BG66x0MSHZl5mZa1podFoAHeSACeQyCkd/7217751489952207/`

Now any Rainloop page displays "An Error occurred, please refresh the page and try again.".
What essential component might be disabled/failing in the web server for this behavior to happen?

**Comment by RainLoop** [comment]
It is difficult to understand what's going on.
You need to understand why your web server falls. 
Check logs for errors.

**Comment by megadr01d** [comment]
> `?/Css/0/Admin/-/SquaresDark/-/cf41fa2216d51cfc14cc92052023e13d/Hash/-/`

My guess is that the issue is caused by the [mod_pagespeed](https://code.google.com/p/modpagespeed/) Apache module. It actually tries to rewrite assets such as stylesheets. I also had trouble with it in my personal website and had to disable it.

Try to create/edit a `.htaccess` file in `/home/user` or `/home/user/public_html` (or whatever your default path is) and include `ModPagespeed Off` at the top, before any other rules.

**Comment by insertc0in** [comment]
@megadr01d Thanks for the reply.
Unfortunately my current hosting doesn't seem to allow the usage of `ModPagespeed Off` in `.htaccess` since it will display an *Internal Server Error* page. I'm trying to have the hosting company to check what is wrong, I may hint at `mod_pagespeed` to see if that helps.

**Comment by megadr01d** [comment]
In the mean time, if they are slow to answer you can also try

~~~ apache
<IfModule pagespeed_module>
        ModPagespeed Off
</IfModule>
~~~

or add `ModPagespeed=off` to the end of the URL as explained [here](http://stackoverflow.com/a/8940154).

**Comment by insertc0in** [comment]
Thanks for the tips, may come in handy, especially the URL one.
Unfortunately neither solved the issue. Maybe `mod_pagespeed` is not really the issue.
I'm not sure if there is anything of relevant in `phpinfo()` for this particular case, but here it is nonetheless: https://jsfiddle.net/5e6mpsuh/embedded/result/

**Comment by RainLoop** [comment]
You have enabled "ionCube", "Zend Guard" and "Suhosin"
Try to disable them.

**Comment by insertc0in** [comment]
@RainLoop Unfortunately I don't control the hosting system, I don't think I can disable those on my own.
I'll have a word about it with the hosting company anyway. Thanks.

**Comment by megadr01d** [comment]
Some paid shared hosting companies allow to enable/disable PHP extensions. Look for **PHP** or **Select PHP Version** in cPanel.

**Comment by insertc0in** [comment]
@megadr01d Yeah, thanks, found it, problem solved!
It was Suhosin that was causing the issue, no more problem after disabling it.
Thanks guys!

**Comment by RainLoop** [comment]
RainLoop should work with Suhosin. 
Usually Suhosin writes logs.

**Comment by insertc0in** [comment]
Not sure why then, but in this case it only works well after disabling Suhosin.
In my case the only thing that gets written are dump files, no logs afaik.
