### ISSUE TITLE
Small UI weirdness on attachment drag and drop.

### ISSUE THREAD

**Issue by jbleuzen** [RainLoop/rainloop-webmail#543]
I think it's a small bug, but when I drag and drop a file onto a composer view, I get the following rendering : 
![screen shot 2015-03-11 at 06 28 13](https://cloud.githubusercontent.com/assets/280681/6702309/e4d6dfbe-cd29-11e4-9da9-185e4d7be73d.png)

Seems a bit strange to me…

**Comment by ervee** [comment]
I think that's by design :) It says "drop files here" to attach them to the email.

![drop](https://cloud.githubusercontent.com/assets/4435930/6704272/8b894826-cd46-11e4-950b-251b4ea81f33.jpg)

**Comment by jbleuzen** [comment]
Yeah I understand the functionnality, I'm just thinking that it should be wider than the compose box.
It's just a design thing in my opinion.

**Comment by megadr01d** [comment]
> It's just a design thing in my opinion.

Agree that it looks out of place. And we love RainLoop not only for its performance but also for its design. A common approach is to make the whole compose window (or just the `textarea`) a drop target and decrease its opacity, when hovered. Other thant that, the default target box should be something like half the compose window's width.

**Comment by RainLoop** [comment]
![image](https://cloud.githubusercontent.com/assets/5530092/6709846/8f5a3b08-cd8d-11e4-9cd0-61c9875f3bef.png)

**Comment by jbleuzen** [comment]
This look better !

**Comment by arturbonnett** [comment]
:+1:

**Comment by ervee** [comment]
Sweet!

**Comment by umbertoB67** [comment]
Yessss

**Comment by megadr01d** [comment]
:+1: Implemented in the latest.

**Comment by megadr01d** [comment]
@jbleuzen Please close when ready. The less open issues we have, the better.

**Comment by jbleuzen** [comment]
Should I wait release or I can close now ?

**Comment by megadr01d** [comment]
> :+1: Implemented in the latest.

It's released already. Update it in the Admin panel to v1.8.2.291.
