### ISSUE TITLE
OpenPGP and Mailvelope

### ISSUE THREAD

**Issue by RainLoop** [RainLoop/rainloop-webmail#544]
I have tested Mailvelope extension with RainLoop and it works fine.
Mailvelope is more functional than the built-in OpenPgp functionality.

What do you think about it? Maybe I should not to do this functionality
when it works perfectly as an extension.

**Comment by ervee** [comment]
I'm not familiar with Mailvelope so just read up on it and it looks pretty good. You install a Browser Plugin (I assume this securely stores your private key...) and use it to encrypt messages into your webmail app.

Doing encryption stuff is usually very hard as you might have experienced. If you can (easily) outsource such stuff to a dedicated plug-in, I'd go for it.

**Comment by megadr01d** [comment]
I don't have much use for OpenPGP but I agree with taking advantage of proved/working solutions instead of re-inventing the wheel. Also, Mailvelope is based on the [OpenPGP.js](http://openpgpjs.org) library so it can be easily picked up by anyone and develop a RainLoop plugin instead of including it in the core code.

**Comment by RainLoop** [comment]
> develop a RainLoop plugin instead of including it in the core code.

Mailvelope already works great. 
I just do not want to spend time developing what has already been done.

**Comment by megadr01d** [comment]
@RainLoop I agree. I meant for edge cases where a user might be locked in a corporate environment where he can't install browser extensions or can't even install another browser other than IE, and someone else decides to do a pull request for a plugin.

**Comment by programacion-web** [comment]
please!
friends using pgp is critical to rainloop.

we are planning to move from roundcubemail rainloop and selection environment to take rainloop allows pgp

AfterLogic tried but only worked the pay version.

rainloop vs AfterLogic

rainloop is opensource even we are willing to support with money and labor programming in php and javascript
Where do I start?


AfterLogic supports 4048-bit keys
supports different keys for different identities

--------

his work has been magnificent, there is only support for 4028-bit keys and possibly the option that public keys are stored together with the address book.
Can we help with anything, where do we start?

thank you

mailvelope sounds good but if you are out of home or vations on a computer without the plugin.

currently use rainloop with owncloud so any user guaradaria your private key in your cloud.

thanks again

**Comment by RainLoop** [comment]
Thanks to all!
