### ISSUE TITLE
username login issue

### ISSUE THREAD

**Issue by phillipwilhelm** [RainLoop/rainloop-webmail#546]
Our mail users login with the following convention: user.domain

so if the email is test@domain.com there username would be test.domain. 

I can't seem to get rainloop to allow me to login with this setup.....any ideas?

**Comment by arturbonnett** [comment]
You can install the "Custom Login Mapping" plugin and set each one

![screenshot-email surta com br-2015-03-18-22-49-23](https://cloud.githubusercontent.com/assets/7110872/6723064/31131ed2-cdc1-11e4-832c-627b438b6899.png)

**Comment by phillipwilhelm** [comment]
Thank you!

On Wed, Mar 18, 2015 at 8:52 PM, Artur <notifications@github.com> wrote:

> You can install the "Custom Login Mapping" plugin and set each one
>
> [image: screenshot-email surta com br-2015-03-18-22-49-23]
> <https://cloud.githubusercontent.com/assets/7110872/6723064/31131ed2-cdc1-11e4-832c-627b438b6899.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RainLoop/rainloop-webmail/issues/546#issuecomment-83260807>
> .
>



-- 
Sincerely,

Phillip Wilhelm

Marketing & Sales
DOV3 Group


*PH:*  949-338-1144

*EM:*  phillip@dov3group.com

*TW:* @phillipwilhelm

*WEB:* DOV3Group.com <http://dov3group.com/>
