### ISSUE TITLE
Store addresses through ownCloud RainLoop module

### ISSUE THREAD

**Issue by jelle-e** [RainLoop/rainloop-webmail#548]
Hi,

First I want to say the new ownCloud RainLoop module is great! Easy install and more or less integrated. Thanks.

My question is about the connection to the ownCloud contacts app. RainLoop uses the contacts database from ownCloud, that works fine. I'd really like to be able to store newly send addresses to that database. Would that be possible?
I know RainLoop has this functionality for it's own database (stand-alone RainLoop install), but is this also possible with the ownCloud module?

**Comment by RainLoop** [comment]
Yes, since 1.9.0 version local contacts allowed in the ownCloud package.
