### ISSUE TITLE
Attachment problem on latest version v1.8.2.291

### ISSUE THREAD

**Issue by glardone** [RainLoop/rainloop-webmail#550]
If I try to send an email with an attachment, the email is not sent:

![schermata 2015-03-24 alle 12 45 56](https://cloud.githubusercontent.com/assets/6884778/6800972/eae5de4c-d223-11e4-8830-67d6b85937f4.png)

**Comment by megadr01d** [comment]
Working fine on my end. Depending on your connection stability, sometimes it can fail the first time and then work, if you insist on it. Other than that, make sure the upload size limit set on the server is enough.

**Comment by glardone** [comment]
My upload size limit is 50Mb, but the file in attach is only 500Kb.
Furthermore, this error occurs only after the last update...

**Comment by megadr01d** [comment]
Try to enable and check the [log file](https://github.com/RainLoop/rainloop-webmail/issues/493#issuecomment-75793042). I just tested sending a ~700KB file to myself and it worked fine.

**Comment by arturbonnett** [comment]
Working fine for me... (17Mb test)
Have you checked on your admin panel <code>http://installation_URL/?admin</code> if the settings is allright?
![screenshot-2015-03-25-15-08-22](https://cloud.githubusercontent.com/assets/7110872/6831738/01bacf64-d301-11e4-8f51-2eb6fcbbd902.png)

**Comment by glardone** [comment]
Yes, in the admin panel the settings is correct.
In the log file is no trace of the attachment operation and if I save the draft message, after in the saved email the attachment is not longer present: I think it does not work  the loading, although it seems to work.

**Comment by RainLoop** [comment]
@glardone 
What is your web server? nginx?

**Comment by glardone** [comment]
My web server is apache.
