### ISSUE TITLE
Cursor flipping back while composing plain text

### ISSUE THREAD

**Issue by jelle-e** [RainLoop/rainloop-webmail#551]
I have problems with the cursor flipping back and forth while composing an email in 'plain text' mode. Using newest Firefox browser for this.
Cursor just flips back a few characters while typing.

**Comment by megadr01d** [comment]
I also noticed some issues on Firefox. To replicate it, press <kbd>Ctrl+F5</kbd> on RainLoop to load an uncached instance, open the compose window and hit <kbd>Tab</kbd> until you're in the `textarea`. You'll notice the cursor shows up after the signature and not in the first line.

~~~
------------------------------------------------------


-- 
name
email|
     ^
-------------------------------------------------------
~~~

Another thing I noticed is that sometimes, when you paste something from the clipboard, the cursor jumps to one character before the pasted line. Pressing <kbd>Enter</kbd> enters a new line correctly, tho, without breaking the pasted line.

~~~
-------------------------------------------------------
http://domain.tl|d
                ^
-- 
name
email

--------------------------------------------------------
~~~

**Comment by heubergen** [comment]
+1

**Comment by RainLoop** [comment]
Try the latest version.

**Comment by heubergen** [comment]
Works now for me, thanks.

**Comment by RainLoop** [comment]
Greate!
