### ISSUE TITLE
Request; attachment icon with a +

### ISSUE THREAD

**Issue by jelle-e** [RainLoop/rainloop-webmail#552]
Just a little request for usability. Could you add something like a "+" to the icon for adding an attachment? Now, the icons for viewing and adding an attachments in a message are the same which is confusing. Thanks.

**Comment by megadr01d** [comment]
I also find it a bit confusing as I keep clicking on the wrong button. I would remove the second icon altogether and include a [+] button on the attachments pane, but that's just me.

Warning: Lame Paint.exe mockup ahead.

![attachments-icon](https://cloud.githubusercontent.com/assets/9649385/6803977/fa611738-d232-11e4-929b-1fbabf891f93.png)

**Comment by arturbonnett** [comment]
I don't believe that turn 2 clicks needed to attach a file is an correctly usability problem resolution.
Maybe giving a highlight and changing the icon as this image may be enough for understanding.
![attachments](https://cloud.githubusercontent.com/assets/7110872/6804650/9eddf3f0-d21d-11e4-9fd9-3ca66739d49c.jpg)

**Comment by ervee** [comment]
Or like the first, but make clear where you are in the composer with some sort of tabs?

![compose-window](https://cloud.githubusercontent.com/assets/4435930/6804924/a56f1ec4-d240-11e4-8d2b-454ee6b6e4d6.jpg)

Although this also makes adding an attachment a two-click action (if you don't use drag-drop). Which is not good IMHO.

So the solution @arturbonnett suggests is looking very good. Perhaps in combination with the tabs instead of two buttons?

**Comment by jelle-e** [comment]
Looks good! Thanks for the 'artwork' ;)
A tab-structure in combination with a single "attach+"-icon would be great although I would be happy with only a "attach+"-icon.

**Comment by megadr01d** [comment]
Either way, when attaching something in the compose tab, your focus should stay there so you can continue with your message while the thing gets uploaded. You shouldn't automatically switch to the attachments tab. That takes an extra click already.

**Comment by megadr01d** [comment]
Another mockup with attachments sidebar and no tabs, to maximize screen real-estate.

![silly-mockup](https://cloud.githubusercontent.com/assets/9649385/6829914/6c81e1fe-d30e-11e4-82e5-d727e4eb2989.png)

**Comment by RainLoop** [comment]
![image](https://cloud.githubusercontent.com/assets/5530092/6834919/31704314-d348-11e4-9395-31342fbb54cf.png)

**Comment by ervee** [comment]
:+1:

**Comment by megadr01d** [comment]
Good choice :+1:
