### ISSUE TITLE
Language problem in plugins on latest version v1.8.2.291 

### ISSUE THREAD

**Issue by bartoszkwiedacz** [RainLoop/rainloop-webmail#556]
In version v1.8.2.291 there is a problem with translations in plugin - custom settings tab. Plugin's template doesn't read files in langs folder. 
![zrzut ekranu 2015-03-25 o 11 08 49](https://cloud.githubusercontent.com/assets/10672854/6822822/de7f5042-d2e2-11e4-9846-055234879365.png)

**Comment by RainLoop** [comment]
Yes, sorry it's my fault.
I changed API (for translation) and did not correct it in plugins.

**Comment by RainLoop** [comment]
before:
```
<span class="i18n" data-i18n-text="SETTINGS_CUSTOM_PLUGIN/LEGEND_CUSTOM"></span>
<input class="i18n" data-i18n-placeholder="SETTINGS_CUSTOM_PLUGIN/LEGEND_CUSTOM" />
```

now:
```
<span data-i18n="SETTINGS_CUSTOM_PLUGIN/LEGEND_CUSTOM"></span>
<input data-i18n="[placeholder]SETTINGS_CUSTOM_PLUGIN/LEGEND_CUSTOM" />
```
