### ISSUE TITLE
Plugin failed to install package

### ISSUE THREAD

**Issue by lordmuffin** [RainLoop/rainloop-webmail#557]
I am having an issue getting rainloop to install plugins.  www-data owns everything, not sure what im missing.

Ubuntu w/Apache and latest version of Rainloop

![image](https://cloud.githubusercontent.com/assets/808023/6834296/1126d858-d301-11e4-9c28-e96ab7687bea.png)

**Comment by RainLoop** [comment]
What plugins do you want to install?

**Comment by lordmuffin** [comment]
Change password (POPPASSD) to start with.  As well as Custom Login Mapping

**Comment by RainLoop** [comment]
Have you read this?
http://www.rainloop.net/docs/permissions/

**Comment by lordmuffin** [comment]
Yes and they are configured as such.

**Comment by RainLoop** [comment]
Errors in php logs?
