### ISSUE TITLE
Contact aren't saved

### ISSUE THREAD

**Issue by mungle** [RainLoop/rainloop-webmail#559]
Hello!
When I receive an email from a new contact his address will not be saved in owncloud contacts... Is there any solution?

Thanks!

**Comment by megadr01d** [comment]
Contacts can only be automatically saved when you send an email to that contact (you really don't want to add contacts for every email received). Just go to **Settings > Contacts** and enable the only option there.

**Comment by megadr01d** [comment]
I just realized you mentioned Owncloud, so not sure if [this](https://github.com/RainLoop/rainloop-webmail/issues/553) is relevant.

**Comment by RainLoop** [comment]
Sorry, but this functionality doesn't work with ownCloud storage.

**Comment by mungle** [comment]
Is there a way to chose the native RL contacts instead OC contacts as before?

**Comment by RainLoop** [comment]
No, but it's an interesting idea, to make a special setting for owncloud.
