### ISSUE TITLE
Reply doesn't add to address

### ISSUE THREAD

**Issue by mungle** [RainLoop/rainloop-webmail#560]
When I press reply in owncloud's rainloop it doesnt add the "TO" email... Is that strange, isn't it?
Thanks

**Comment by megadr01d** [comment]
The button marked in the screenshot below changes according to the last option used (Reply or Forward) so make sure you're not forwarding instead of replying (easily spotted by the "Fwd" prefix in the subject line).

**Comment by RainLoop** [comment]
> When I press reply in owncloud's rainloop it doesnt add the "TO" email... Is that strange, isn't it?

It's possible if you reply your own message ("To" email is same as your account email).

**Comment by RainLoop** [comment]
Fixed in the beta version: https://github.com/RainLoop/rainloop-webmail/issues/571
