### ISSUE TITLE
Attachments with special characters are not uploaded when dropping them to email

### ISSUE THREAD

**Issue by maurermax** [RainLoop/rainloop-webmail#562]
Hello,

I am using Rainloop 1.8.2.291 on my Mac (10.10.2). When having an attachment containing special characters in the file name, like a German Umlaut `ä` for example these are not uploaded to the server. Instead nothing happens at all. Removing all special characters from the file name makes the upload work.

Expected Behavior: The files are also uploaded correctly even if they contain a special character.

Best

Max

**Comment by RainLoop** [comment]
Interesting, but I could not repeat it.
What is your web browser?
Can you give me the file?

**Comment by maurermax** [comment]
Browser: Google Chrome 41.0.2272.89 (64-bit)
It works with any file that contains a special character. I just created a text file with some chars of content and named it "umlautä.txt".

However, I forgot to mentioned that this affects only drag and drop from a finder window to the email preparation window. Choosing the same file using the attachment button works fine. 

I also have no errors popping up on the browser console. The file is just not processed. When I use a bunch of files the ones with correct file names work and all files with special characters are silently omitted.

**Comment by RainLoop** [comment]
Thanks! Fix will be available in the next release

**Comment by maurermax** [comment]
thanks for fixing this so fast.
