### ISSUE TITLE
Previous and Next message buttons do not work across pages

### ISSUE THREAD

**Issue by ervee** [RainLoop/rainloop-webmail#567]
Hi,

When you have more messages than would fit on one page, you can't use the Previous and Next message buttons to move to messages on another page.
Say you open the last message in the message list. Then click the Next message button [>], nothing happens. The CTRL-Up/Down hotkeys behave the same for when you have a preview pane.

Ralf.

**Comment by RainLoop** [comment]
Ok, try beta version (if you want)

New message list navigation works across pages.

https://github.com/RainLoop/rainloop-webmail/issues/571

**Comment by ervee** [comment]
Fixed in Beta. Probably fixed in next release also :+1:
