### ISSUE TITLE
(enhancement) combined accounts

### ISSUE THREAD

**Issue by gadjou** [RainLoop/rainloop-webmail#568]
Hello,
I use Rainloop with multiple accounts. On my android phone, I use boxer as mail client and it has a nice feature: "combined" account. You can (visualy) merge all of you account into a unique "unread" (+trash, archive...) folder. You still have the possibility to filter by account if needed.
See this screen shot for clearer explanation : https://lh4.ggpht.com/qYZrNnxA9ydOVUGtb_-JesWiypcRoslNhTVz4LTRIqABMwUYU2sSTSdG55nUcLBN_g=h900

It would be very nice if Rainloop would offer such a possibility.
Thank you

**Comment by RainLoop** [comment]
I know it is a very popular request.
However, to do this without the database is not possible :(.
