### ISSUE TITLE
Mails are not always grouped in threads

### ISSUE THREAD

**Issue by skibbipl** [RainLoop/rainloop-webmail#569]
Some mails are not always grouped in threads:
![rl](https://cloud.githubusercontent.com/assets/4746858/6937453/5cfbc9e0-d85c-11e4-8278-97bf6fb5f138.png)
The person I'm mailing with is using many different mail clients (thunderbird on MacOS, gmail on Android, default mail client in iPad etc.)
What debbuging information is needed for analysis?

**Comment by RainLoop** [comment]
Can you give me these two messages (from screenshot)?

**Comment by skibbipl** [comment]
Andoid mail client sucks!
https://code.google.com/p/android/issues/detail?id=%2028017

**Comment by ervee** [comment]
Try K-9 Mail. Better in every possible way.

**Comment by skibbipl** [comment]
Yeah, I just didn't realize that default android mail client is so bad :-1:
