### ISSUE TITLE
Beta (1.8.3)

### ISSUE THREAD

**Issue by RainLoop** [RainLoop/rainloop-webmail#571]
http://repository.rainloop.net/v2/webmail/1.8.3/rainloop-1.8.3.292-6f559979a88a1a63de4231ec24c4ae82.zip

**Comment by RainLoop** [comment]
![1](https://cloud.githubusercontent.com/assets/5530092/6960667/6deebbdc-d92d-11e4-9df3-a9c829f3de24.gif)

**Comment by ervee** [comment]
Yes I tested it and it looks like it is working 100% Great!
