### ISSUE TITLE
Custom headers in sieve filters?

### ISSUE THREAD

**Issue by skibbipl** [RainLoop/rainloop-webmail#573]
I would like to configure my server to put potential spam mails in Spam folder. My antispam adds custom X-Spam header to all potential spam messages, but I cannot create sieve filter from RL interface, because there is no custom headers support. Of course I can edit manually my sieve filters, but every filter change in RL will overwrite my custom rules.
Can you add some custom spam headers to RL sieve filters? Or perhaps provide some solution to ignore selected advanced sieve filters in RL interface and not overwrite them on save.

Also sieve filters are saved with windows enters ```\r\n``` instead of unix ```\n```

**Comment by ervee** [comment]
You could use
```sieve_before = /etc/dovecot/sieve/sieve_before```
in you plugin section in dovecot.conf
Add this in /etc/dovecot/sieve/sieve_before
```
require ["fileinto"];

# rule:[SPAM]
if header :contains "X-Spam-Flag" "YES" {
        fileinto "spam-mail";
}
```
Just replace "X-Spam-Flag" "YES" with your header.

Ralf.

**Comment by skibbipl** [comment]
Thanks for the tip. Will do it that way.

**Comment by zeigerpuppy** [comment]
Having the "X-Spam-Level"header avaialble in filter options would be great.
it's easy then for each user to tune their spam level.

**Comment by RainLoop** [comment]
RainLoop supports custom headers:

![image](https://cloud.githubusercontent.com/assets/5530092/17148261/17ded084-536f-11e6-8d9d-239399546d36.png)

**Comment by zeigerpuppy** [comment]
time to self-build I guess, this doesn't seem to have made it to the last release yet.

**Comment by RainLoop** [comment]
Hm, it should be already in the last version.

**Comment by beankylla** [comment]
Hello,

I can't find thiis functionality. Where is it supposed to be located? Has it been removed from rainloop for owncloud?

Kind greetings,

**Comment by plastikschnitzer** [comment]
@beankylla if you look at the rainloop screenshots, you can see that there are a few more sections in the rainloop account settings, which are not existing in the owncloud/nextcloud mail app: [http://www.rainloop.net/screenshots/](http://www.rainloop.net/screenshots/)

**Comment by beankylla** [comment]
who maintains the plugin of rainloop for owncloud/nextcloud ? it would be nice to have that functionality :)
