### ISSUE TITLE
Custom Security

### ISSUE THREAD

**Issue by Marcos030** [RainLoop/rainloop-webmail#576]
Hi,
this is not really an issue, but i'm new here and a i need some help with a problem.
I've  installed the rainloop-webmail on my company server and i need a custom security  functionality. I need to force every user to use 2 step verification, so i need help to make something like this: When a user login i will verify if he has the 2 step verification already turned on and let him to use the email normally, if he does not have this turned on i will redirect him to the security panel and don't let him out without configure the 2 step verification ( hiding all other navigation link, for example ).
Can someone give me a help or show me how can i begin to implement this ?
Thanks in advance.

**Comment by jelle-e** [comment]
Maybe an option like "Allow one step verification" can be implemented?

**Comment by Marcos030** [comment]
Hello @jelle-e,
I didn't understand what you mean. One step verification is the default verification isn't it ? Only login and password ?
What a need is to force every user to use que code generated by the google authenticator for security reasons.

**Comment by jelle-e** [comment]
Yes, that's what I meant.
If you uncheck "Allow one step verification", your users must use two step verification to login. That said, maybe there should be two options to choose from:
1 Force two step verification
2 Allow two step verification

**Comment by Marcos030** [comment]
Yes, that's one solution.
Do you know how can i implement this ?
Can you help me ?

**Comment by jelle-e** [comment]
Ah sorry, could have said this before... I think rainloop is quite dependent on it's developer and not that open source that you can change these aspects. But I might be wrong!
Please wait for a reply of the developer for more info on this. I can't help you further.

**Comment by Marcos030** [comment]
Ok.
I'll wait. I was trying to implement this, but i got lost into the code and has some minified Js that i didn't understand what it does. I really thought( and still think ) that this code here could be altered or the others developers could guide me.
Thank for the attention.

**Comment by RainLoop** [comment]
@Marcos030 

Well, today is your lucky day.

![image](https://cloud.githubusercontent.com/assets/5530092/7027867/ba07a930-dd5a-11e4-8ce9-84ab851fc5e7.png)

Package (beta):
http://repository.rainloop.net/v2/webmail/1.8.3/rainloop-1.8.3.295-289a912c6b0d89f2a96029e44c53a7cc.zip

**Comment by jelle-e** [comment]
Wow, you're the best.
Thanks for all the work!

**Comment by Marcos030** [comment]
Woow ... Very Nice !!!
=D
Saved my job. 
I'd have to implement this anyway. It was a challenge to me.

Thank you.

**Comment by Marcos030** [comment]
Well, 
this is a beta version ? Can i already use it ?

**Comment by RainLoop** [comment]
This is your choice :)
You can start using it now or wait for the release.
Or simply install it for testing.
