### ISSUE TITLE
Very long addresses are not shown correctly

### ISSUE THREAD

**Issue by Corna** [RainLoop/rainloop-webmail#577]
Very long addresses (like the github reply addresses) are not shown correctly on small screen (for example, on my 12" laptop)

![rainloop](https://cloud.githubusercontent.com/assets/6459604/7027741/8726a22c-dd51-11e4-8979-d06e99f2c3c0.png)

**Comment by RainLoop** [comment]
OK, thanks!

**Comment by Corna** [comment]
The bug is still here
![rainloop](https://cloud.githubusercontent.com/assets/6459604/7526880/58f6051e-f516-11e4-852c-32db6ef22430.png)

**Comment by megadr01d** [comment]
> The bug is still here

Out of curiosity, the text is not flowing out of the box anymore... should it have a line break or horizontal scrollbar?

**Comment by Corna** [comment]
An email address that long is probably useless from the user's perspective, i think that a [...] (or even better, a fade) is enough. The user can still see the full address within the tooltip

**Comment by RainLoop** [comment]
What do you think about this?

![image](https://cloud.githubusercontent.com/assets/5530092/7527161/45644c76-f521-11e4-86c7-cc9f37d58dc6.png)

**Comment by RainLoop** [comment]
css:

```css
word-break: break-all;
```

**Comment by Corna** [comment]
I don't think it's a good idea, if the address is very long it will bloat the area
The user is probably not interested in the full address, and keeping it on its line leave the message area clean
It the user is interested in the full address it can still right-click to copy it or leave the mouse on it and wait for the tooltip to appear

**Comment by RainLoop** [comment]
![image](https://cloud.githubusercontent.com/assets/5530092/7527304/8d0bb662-f522-11e4-96d4-8ea787516379.png)

**Comment by Corna** [comment]
Yep, exactly like this

**Comment by RainLoop** [comment]
Ok

**Comment by Corna** [comment]
I didn't noticed that it is not a mailto link; is there a way to copy it in the clipboard?

**Comment by RainLoop** [comment]
I don't think so :(

**Comment by Corna** [comment]
Making the three dots clickable in order to show the full address (with breaklines) is too complex, right? It's just a minor thing, I don't want to make you waste time on it

**Comment by RainLoop** [comment]
In this case `word-break: break-all;` is more effective. 
And I do not think that big an email will be a big problem.

**Comment by Corna** [comment]
Yes, you're right, just break the line
Thanks for your time

**Comment by megadr01d** [comment]
For what it's worth, I agree on the line break. After all that's the mail headers section, it's supposed to have more thorough information and it's collapsed by default, anyway.
