### ISSUE TITLE
Can't Login with Hotmail address

### ISSUE THREAD

**Issue by mubarkan** [RainLoop/rainloop-webmail#578]
Can't login with hotmail email address ... is there any solution for this ????

**Comment by arturbonnett** [comment]
First, you have to add and setup the domain "hotmail.com" in your rainloop admin panel like this:
hotmail.com
IMAP:  imap-mail.outlook.com port 993 SSL;TLS
SMTP: smtp-mail.outlook.com port 587 STARTTLS (use authentication)

So...to login with your hotmail account you have to create an app password on https://account.live.com/proofs/Manage?mkt=en-US -> App passwords

Because is a generated password, i think that the best way to use in rainloop is to add the hotmail account as an additional account..

**Comment by sbrl** [comment]
These settings don't work. Is there any way I can debug it? The 'test connection' doesn't show up any problems.

**Comment by deadport** [comment]
I've got the exact same problem with my Outlook which uses the same servers.
I've checked my config thousands of times - connection goes through, used app-password, but no successfull authentication...

**Comment by cdmlb** [comment]
Yeah it's odd how the same settings work no problem with Office outlook. Same issue with gmail. It's mostly these email services are so tight now making it harder for people to even use their smtp server for an email relay.

I think they just want to cut back on backdoors for spammer but anyone can make free email accounts and use them directly to spam people. Now they want you to turn on and off settings to allow less secure apps to use their services, turn on two step authentication just to generate an app password, and after generate an app password.

Most ISPs also filter smtp to only work with their network's smtp server even tho the ports are not blocked, your server is not registered on their network it just does the same as being port blocked if you can't route. to anyone.

Even when you buy web hosting, sometimes you're not so lucky and get on a server with the hoster that is on a blacklist for know IPs to be blocked by mail services. That's a dam headache to try to get your hosting IP whitelisted cuz of people using hosting services to spam.

Just makes it harder to run your own mail servers or mail services at home.

I remember the good old days of just being able to run a full blown email server at home and have no issues at all.

Sorry for the rant.

**Comment by eduleongh** [comment]
If anyone is still experiencing this issue,  I solved it by deactivate the Two-Step verification on my Outlook account. Then i added the account i Rainloop and then i could reactivate the "Two-Step"  in outlook without issues.
