### ISSUE TITLE
Google Ads

### ISSUE THREAD

**Issue by mubarkan** [RainLoop/rainloop-webmail#579]
I want to add Google Ads on Login page
Ad size: 728 x 90 
Can anyone guide me where to add google ads code ?

**Comment by heubergen** [comment]
Have you already a commercial license?
You will need this and can buy one [here](http://www.rainloop.net/purchase/).

**Comment by RainLoop** [comment]
Now RainLoop Webmail supports `<script>` tag in templates. You may change them and add Google Ads on login page.
