### ISSUE TITLE
User login List in admin area

### ISSUE THREAD

**Issue by mubarkan** [RainLoop/rainloop-webmail#580]
I want to see in admin area how many user login to my website ...
Please contact me with quote khurrams@usa.com if anyone can develop this addon for me

**Comment by AndrewSav** [comment]
Users do not "login" to rainloop, they login to your mail server. the communication protocol that rainloop uses to talk to the mail server (pop, imap, smtp) does not provide for transmitting the number of mail server users. I do not think this addon is possible in principle. What you could develop instead is the number of unique connections in last 10 minutes or something... that would work.

**Comment by mubarkan** [comment]
As i can see user login in FTP: data/_data_1b88/_default_/storage/file 
so i want same in admin area to see daily how many user login
