### ISSUE TITLE
How does one change a password of a user that a user has forgotten ? 

### ISSUE THREAD

**Issue by nashv** [RainLoop/rainloop-webmail#583]
There seems to be no users panel in the Admin settings.

**Comment by jelle-e** [comment]
RainLoop is only the frontend (like Thunderbird). You have to use the backend mailserver to change the password.
There are some plugins available from the RainLoop Admin section though. There might be one that works with your mailserver backend. You can try them out.

**Comment by nashv** [comment]
There is definitely a problem with Rainloop authentication. I tried logging in from a fresh installation of Ubuntu and Rainloop continously gave me 'Authentication Failure' despite having correct credentials.

On another machine, I was already logged into Rainloop with the same credentials and could read my email.This was not therefore not a mailserver issue, nor a domain configuration issue on Rainloop.

I finally workaround the problem by enabling Google Authentication from the  machine I was already logged in from.
Using Google to login from the fresh Ubuntu install then worked and I could access my email.  Thus, Rainloop authentication seems to be broken somwhere. Unfortunately, I cannot pinpoint the problem.

**Comment by jelle-e** [comment]
Might it be a firewall issue? RainLoop directly connects to the mailserver backend en needs to access specific ports as set in the RainLoop domain setup.
This would explain why one server can access the mail backend and the other can't.
Question remains why it does work with Google Auth... I don't know how that works so... But please check your firewall config.
