### ISSUE TITLE
Contacts search (ownCloud RainLoop app) is case sensitive

### ISSUE THREAD

**Issue by jelle-e** [RainLoop/rainloop-webmail#585]
When I have a contact in ownCloud named "John Doe" with email "jdoe@mail.com" then RainLoop can't find the user when typing "john" in the To field while composing an email. When typing "John" it can find the user.
Same is for last name and the email address.

I believe it should search case insensitive. Agree?

**Comment by RainLoop** [comment]
I used ownCloud API method for that. 
Perhaps something wrong with him.

http://api.owncloud.org/classes/OCP.Contacts.html#search

```php
\OCP\Contacts::search
```

Try to search this contact with ownCloud search (contact section).

**Comment by jelle-e** [comment]
Yeah you're right. ownCloud itself has this problem. I'll file the bug to them. Thanks.

**Comment by jelle-e** [comment]
Just an update:
Issue is fixed in the contacts app of ownCloud itself. You can find the fix here.
https://github.com/owncloud/contacts/pull/910/files

**Comment by RainLoop** [comment]
Strange, they use `strtolower` function that does not work correctly with utf 8 strings.

**Comment by jelle-e** [comment]
Thanks, maybe you could participate a bit in conversation https://github.com/owncloud/contacts/pull/910 ?
