### ISSUE TITLE
v1.8.3.302: first call of compose window broken

### ISSUE THREAD

**Issue by megadr01d** [RainLoop/rainloop-webmail#588]
Not sure if anyone can reproduce this but just updated to v1.8.3.302 and the first call of a compose window (click or <kbd>C</kbd>) always default to rich text mode (I have it set to "force plain text") and no sig is loaded. After I close it and call a second compose window, it loads fine.

Can reproduce it constantly by switching between two account, both in Chrome and FF.

**Comment by RainLoop** [comment]
Thanks!

**Comment by megadr01d** [comment]
No, thank **you**, for the continuous improvements and awesome project.

**Comment by megadr01d** [comment]
Just a follow-up, it also happens on replies and forwards, but I guess it's the same issue.

**Comment by RainLoop** [comment]
Fixed
