### ISSUE TITLE
Make a plugin to auto-retrieve domains list from postfixadmin

### ISSUE THREAD

**Issue by spyridonas** [RainLoop/rainloop-webmail#592]
It will be useful (maybe integrate it with the postfixadmin password change ?)

**Comment by RainLoop** [comment]
It is not necessary since RainLoop supports wildcard in domain name.
You may create domain "*" and it will handle all incoming logins.

**Comment by spyridonas** [comment]
Sure but that's not compatible with 'auto figure out the domain name and i dont have to type it as my login name' thingy thing

**Comment by RainLoop** [comment]
> Sure but that's not compatible with 'auto figure out the domain name
> and i dont have to type it as my login name' thingy thing

Ok, it can be fixed.

**Comment by RainLoop** [comment]
Please, try the new version of RainLoop Webmail (1.9.0.322)
