### ISSUE TITLE
Icon Problem

### ISSUE THREAD

**Issue by MrKeiKun** [RainLoop/rainloop-webmail#593]
**Information:**
I'm using Firefox Developer Edition 39.0a2 (2015-04-17).
The icons are like graphically bug. Like whenever you hover on the button, it like disrupts it like a corrupted image.

**Screenshot:**
![image](https://cloud.githubusercontent.com/assets/4362134/7205383/8bb28330-e55b-11e4-8933-828e51047030.png)

**Comment by skibbipl** [comment]
Do you have glitches on other pages? It looks like a firefox / graphics driver bug. Can't reproduce this issue on my firefox developer version.
