### ISSUE TITLE
Release authentication

### ISSUE THREAD

**Issue by yastupin** [RainLoop/rainloop-webmail#595]
Hi,

I haven't found any way to authenticate rainloop release tarballs, since all data and metadata is served over clear HTTP.

Would it be possible that you provide a GPG signature along each release ?
Or maybe have a mirror of either tarballs or the http://repository.rainloop.net/v2/core.stable.json file somewhere trustworthy (github releases ?)

**Comment by RainLoop** [comment]
I have added signatures (GPG) for each release file.
Check the new download page: http://www.rainloop.net/downloads/

**Comment by yastupin** [comment]
Nice, thank you! It is just what I needed to enable automated updates from tarballs.

For other uses, do you plan to add signature checking in installer and updater ?

**Comment by RainLoop** [comment]
Yes, but not right now.

**Comment by yastupin** [comment]
Fine, thanks again.
