### ISSUE TITLE
Feature; add ownCloud to Rainloop Integrations

### ISSUE THREAD

**Issue by jelle-e** [RainLoop/rainloop-webmail#602]
Hi,
How nice it would be to add ownCloud to the list of integrations. Would it be possible to store and/or add attachments from/to ownCloud in Rainloop?

**Comment by RainLoop** [comment]
Work in progress :)

![image](https://cloud.githubusercontent.com/assets/5530092/7299730/4b1a0346-e9e0-11e4-8fee-6e7429a2574c.png)

**Comment by arturbonnett** [comment]
Ow!!! :D

**Comment by jelle-e** [comment]
You just made me buy Rainloop! :)

**Comment by RainLoop** [comment]
Do not hurry, it's not ready yet.

**Comment by jelle-e** [comment]
Haha, no worries, was going to buy it anyway. It's just a thank you for all the work.

**Comment by RainLoop** [comment]
Thanks!

**Comment by RainLoop** [comment]
#606
