### ISSUE TITLE
Relative references using local proxy for external images

### ISSUE THREAD

**Issue by arturbonnett** [RainLoop/rainloop-webmail#603]
Issue with Relative references with URL without protocol scheme (http: or https:) using local proxy for external images

![captura de tela 2015-04-23 11 25 16](https://cloud.githubusercontent.com/assets/7110872/7300128/ad2edb22-e9b0-11e4-9218-4c2c0b7ed04a.png)

But reading the email, these images with relative url doesn't shows...

![captura de tela 2015-04-23 11 28](https://cloud.githubusercontent.com/assets/7110872/7300466/baa88a62-e9b2-11e4-9e45-85226c77f585.png)

**Comment by RainLoop** [comment]
Thanks!

**Comment by RainLoop** [comment]
Fixed
