### ISSUE TITLE
1.8.4 (beta)

### ISSUE THREAD

**Issue by RainLoop** [RainLoop/rainloop-webmail#606]
Attachments actions:

![20](https://cloud.githubusercontent.com/assets/5530092/7333207/bd12f52c-eb6e-11e4-9ddd-896dfecca0b4.gif)

Old / New threads!

![21](https://cloud.githubusercontent.com/assets/5530092/7333208/c108daac-eb6e-11e4-9478-79fadd922c46.gif)

Package:
http://repository.rainloop.net/v2/webmail/1.8.4/rainloop-1.8.4.312-1bdcf8bffce15d35394adb2a04268a34.zip

**Comment by megadr01d** [comment]
![14b96b9ba4dcb5059f1a321d23fbaa5f6a15f8c42e873bf8744255310cbac683](https://cloud.githubusercontent.com/assets/9649385/7359722/b7e013ec-ed39-11e4-8b28-ce84cff19c8a.jpg)
