### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by bytedevil** [RainLoop/rainloop-webmail#613]
Hi all!

After upgrade from Debian 7 Wheezy to Debian 8 Jessie I have this error on the log and I can't acces to read mails:
[crit] 17721#0: *727 SSL_do_handshake() failed (SSL: error:14076102:SSL routines:SSL23_GET_CLIENT_HELLO:unsupported protocol) while SSL handshaking, 

I can acces for other clients regularly, without any problem, from Thunderbird and iPhone native client for example. 

I'm using Debian 8, Nginx, SSL self signed, Postfix and Dovecot. I don't make any change on protcols, i'm still using SSL/TLS.

Anyone can help me? Thank you.

**Comment by bytedevil** [comment]
![pantallazo-6](https://cloud.githubusercontent.com/assets/324570/7367240/4e4819ce-ed9e-11e4-9541-5a5805bfa696.png)

**Comment by RainLoop** [comment]
You can disable SSL verification as well, which will disable all SSL checks.

![image](https://cloud.githubusercontent.com/assets/5530092/7367464/47a06482-eda8-11e4-9326-bd9e59bae380.png)

**Comment by bytedevil** [comment]
Ok, it works. But, have any solution? 

Thanks for support?

**Comment by skibbipl** [comment]
I think Debian dropped support for SSLv3. Perhaps your dovecot/postfix are using old configuration regarding SSLv3 protocol, but PHP has it disabled by default therefore you get unsupported protocol error?

**Comment by RainLoop** [comment]
> But, have any solution?

I can not say for sure. There can be many reasons.
SSL could lose the settings in the system or PHP.
I'm not a great expert in this.
