### ISSUE TITLE
All the Prefixed Domain are not connecting with default settings.

### ISSUE THREAD

**Issue by rvuban** [RainLoop/rainloop-webmail#620]
All the Prefixed Domain are not connecting with default settings. All are now unusable to me. Getting red alert every time I test the connections.

![untitled](https://cloud.githubusercontent.com/assets/12150277/7386925/c62a0bf0-ee7a-11e4-88b4-bc282f514e49.png)

![gmail](https://cloud.githubusercontent.com/assets/12150277/7386910/a12e9424-ee7a-11e4-904e-7b4b4bcdc228.jpg)

**Comment by RainLoop** [comment]
Looks like that your hosting provider or firewall blocks these connections.

**Comment by rvuban** [comment]
So now, what can i do now to solve this ?

**Comment by rvuban** [comment]
I am using a subdomain for using rainloop webmail. How can I configure my cloud firewall ? I am using www.hostinger.co.uk for hosting.

**Comment by RainLoop** [comment]
Well, it's free hosting.
In most cases (99%) these blocks such programs to reduce spam. 
Try to write to them and ask them about this issue.
