### ISSUE TITLE
Sieve bug

### ISSUE THREAD

**Issue by cz-vilda** [RainLoop/rainloop-webmail#621]
When adding more than one filter, only first is processed because both have "stop" command at the end (which means do not process next filter).

**Comment by cz-vilda** [comment]
My solution (quick and dirty):
At file app\libraries\RainLoop\Providers\Filters\SieveStorage.php
LINE 375: //$aResult[] = $sTab.'stop;';
LINE 396: //$aResult[] = $sTab.'stop;';

**Comment by RainLoop** [comment]
It is by design.
"Vacation message" action has this opportunity.

![image](https://cloud.githubusercontent.com/assets/5530092/7397776/6536db1e-eeb3-11e4-9d4c-d44b70aefdea.png)

**Comment by jranma** [comment]
Is it by design ? 
This means that you can only have one filter activated at the same time, which is illogical. 
There are cases where filters should be able to be applied one after the other. 
The function that exists in the "vacation" filter should be available for other script types as well.
