### ISSUE TITLE
[bug] [duplicate] cursor wrong place

### ISSUE THREAD

**Issue by heubergen** [RainLoop/rainloop-webmail#626]
How you can see, are the cursor on the wrong place.

![bildschirmfoto 2015-05-02 um 15 57 06](https://cloud.githubusercontent.com/assets/5529410/7441333/367e2d4e-f0e4-11e4-8657-0d17a668a8fd.png)

The bug happens only when you reply to a exist mail, not by a draft and also not by a new mail.
Behavior goes away when you write on the next line.

(hope you understand what I mean)

**Comment by megadr01d** [comment]
Related issue [here](https://github.com/RainLoop/rainloop-webmail/issues/551).

**Comment by heubergen** [comment]
Thanks, have look some issues back but oversee it obviously. Will close this later.

**Comment by heubergen** [comment]
Will leave the other issue open.
