### ISSUE TITLE
DomainNotAllowed

### ISSUE THREAD

**Issue by furyscript** [RainLoop/rainloop-webmail#629]
Hi all,
I've recently installed rainloop on my Virtual Machine with VirtualBox.
I've set nginx configuration with server name mail.example.com, also in /etc/hosts I set 127.0.0.1 to mail.example.org.
I've added the domain in admin panel of rainloop, with SSL none and SMTP to mail.example.org on port 25.
When I try to login with owner credentials of machine like that:admin@mail.example.org
I see in log and I've got an Exception DomainNotAllowed. 
What is the best way to correct this?? @RainLoop 
I've also installed Postfix in the same machine..

**Comment by RainLoop** [comment]
Can you upload a screen shot with domain configuration to better clarify this issue?

**Comment by furyscript** [comment]
Yes, http://i59.tinypic.com/289za01.jpg

**Comment by RainLoop** [comment]
Ok, you have added "paperland.org", but trying to login with "admin@mail.example.org".
You should login using "admin@paperland.org".

**Comment by furyscript** [comment]
Ok it's correct.
But now the error is: Authentication failed.
I've installed postfix, and I add the user info with useradd. So I will probably login with info@paperland.org / info@mail.paperland.org but not work...

**Comment by RainLoop** [comment]
Try to complete the configuration of the mail server and test it using desktop mail client (Thunderbird for example).
