### ISSUE TITLE
RainLoop creates new folders

### ISSUE THREAD

**Issue by ghost** [RainLoop/rainloop-webmail#631]
After upgrading RainLoop from version 1.8.1.281 to 1.8.2.291 and newer (also 1.8.3.304) some folders ("Archive", "Drafts", "Spam") were created in my mail-account. If I delete this folders, RainLoop  creates they again.

I think the cause are my self-defined Systems-Folders (Sent -> "Sent", Drafts -> "Entwuerfe", Spam -> "Junk", Trash -> "Trash", Archive -> "Do not use").

**Comment by RainLoop** [comment]
Thanks!
It was a bug. It will be fixed in the next release.
