### ISSUE TITLE
Disconnecting Google for Login doesn't disconnect

### ISSUE THREAD

**Issue by drewcsillag** [RainLoop/rainloop-webmail#632]
The file under ...data/_data_NNNNNNNNNNNNNNNNN/_default_/storage/data/__nobody__/HH/HHxxxxxxxxxxxxxxxxxxx is never modified, so logging in with Google doesn't stop working after disconnecting in the settings UI.

**Comment by RainLoop** [comment]
Thanks! I will be fixed in the next release.

**Comment by drewcsillag** [comment]
While not strictly necessary, including the google user id in the contents either of the user config (alongside GoogleSocialName) or in the file above would be helpful for tracking things down when things go wrong.

Thanks again for a great piece of software!
