### ISSUE TITLE
stream_filter_append

### ISSUE THREAD

**Issue by furyscript** [RainLoop/rainloop-webmail#634]
In my error.log files, I had this error:
\nWarning: stream_filter_append(): unable to locate filter "convert.quoted-printable-encode" in /home/****/rainloop/v/1.8.3.304/app/libraries/MailSo/Base/StreamWrappers/Binary.php on line 232

I use HHVM, but filters are supported. Could you repair this bug?

**Comment by RainLoop** [comment]
Can you show me php info / Registered Stream Filters ?

**Comment by RainLoop** [comment]
My, for example:
![image](https://cloud.githubusercontent.com/assets/5530092/7495374/1a9de774-f416-11e4-8f8e-c2d284ed2f50.png)

**Comment by furyscript** [comment]
Yes http://i59.tinypic.com/2wno190.png
But see HHVM documentication. It have all filters...

**Comment by RainLoop** [comment]
It's not look like "Registered Stream Filters"

**Comment by furyscript** [comment]
See this http://docs.hhvm.com/manual/en/ref.stream.php 
HHVM have all libraries. I've tested ^^

**Comment by RainLoop** [comment]
Can you run this code?

```php
var_dump(stream_get_filters());
```

**Comment by furyscript** [comment]
Yes,
result:
array(5) { [0]=> string(12) "zlib.deflate" [1]=> string(12) "zlib.inflate" [2]=> string(12) "string.rot13" [3]=> string(14) "string.toupper" [4]=> string(14) "string.tolower" }

**Comment by RainLoop** [comment]
OK, as you can see your version does not support "convert.*" filters.
RainLoop uses `['convert.base64-decode', 'convert.base64-encode', 'convert.quoted-printable-decode', 'convert.quoted-printable-encode']` filters to work.

**Comment by furyscript** [comment]
Ok now I set php-fpm deamon to PHP and work correctly, thank's!

**Comment by RainLoop** [comment]
You're welcome.
