### ISSUE TITLE
Losing Configurations

### ISSUE THREAD

**Issue by Marcos030** [RainLoop/rainloop-webmail#635]
Hello,
After upgrading RainLoop to newer version i got one strange behavior.
I am losing all my configurations. Losing my contact list, language setting e so on. Losing all. It appears to occur to one day to another. Any ideas for what  is happening ?

**Comment by RainLoop** [comment]
Very strange.
What was your version before upgrading?

**Comment by Marcos030** [comment]
well,
I asked for one modification some days ago, to force 2-step verification, and you send me one beta version. 
This one
http://repository.rainloop.net/v2/webmail/1.8.3/rainloop-1.8.3.295-289a912c6b0d89f2a96029e44c53a7cc.zip

So i upgraded from this version.

**Comment by RainLoop** [comment]
Any errors in logs?
