### ISSUE TITLE
Signup feature

### ISSUE THREAD

**Issue by mubarkan** [RainLoop/rainloop-webmail#636]
I want domain signup feature on login page ... New user can signup domain and access email.
Also I want to see how many users using my website and daily user log in admin area

**Comment by megadr01d** [comment]
Just stop spamming. AndrewSav gave you an [answer](https://github.com/RainLoop/rainloop-webmail/issues/580). Domain sign-ups are not Rainloop's job. Rainloop just connects to existing mail servers.
Could it be done with a plugin? I don't know, maybe. You can ask in the [feature request thread](https://github.com/RainLoop/rainloop-webmail/issues/594) (whistling)...

**Comment by stuff2600** [comment]
Agreed, this would be great +1
