### ISSUE TITLE
WebDAV sync error

### ISSUE THREAD

**Issue by Loki3000** [RainLoop/rainloop-webmail#639]
Trying to sync address book with owncloud and get server error. In log file follow:
`PHP Fatal error:  Call to undefined method Sabre\\VObject\\Parameter::getParts() in /.../owncloud/apps/rainloop/app/rainloop/v/1.9.0.323/app/libraries/RainLoop/Providers/AddressBook/Classes/Contact.php on line 482`

**Comment by RainLoop** [comment]
Thanks! RainLoop and ownCloud use the same ownCloud library but with different versions. This is the reason for the error. I don't know yet what to do, but I will try to solve the problem.

**Comment by RainLoop** [comment]
Check the new version.

**Comment by Loki3000** [comment]
Thanks! Now works fine.

**Comment by RainLoop** [comment]
Thanks!
