### ISSUE TITLE
Check/don't check for new messages default

### ISSUE THREAD

**Issue by jelle-e** [RainLoop/rainloop-webmail#640]
Hi,
Thanks for this new feature. Could you maybe trigger a release with the default check = ON? It would help a lot because I guess a lot of my users will not know this was turned OFF as default and will not understand why no new messages are comming in. If it's not too much trouble I'd be saved :) Thx.

**Comment by Leryan** [comment]
+1.

This option should definitively be on by default. Also, a "check all on/off" would be nice.

Thanks

**Comment by RainLoop** [comment]
Ok, in the 1.9.1 version this functionality will be hidden for 50 < folders.

configuration:

```ini
[labs]
folders_spec_limit = 50
```

**Comment by RainLoop** [comment]
Done (1.9.1 version)
