### ISSUE TITLE
rainloop oc-app 4.0 save attachment (issues and feature request)

### ISSUE THREAD

**Issue by deMattin** [RainLoop/rainloop-webmail#642]
In rainloop owncloud app 4.0 there's the new "save attachment to owncloud" feature.

It works as expected, but looking in the code, I found some
__Spelling errors in source__:
In file: `Actions.php` on line 1360, 1365, 1370
`$aResult['AttahcmentsActions']` should be
`$aResult['AttachmentsActions']`, I think.

__Feature request:__
The folder path for saving attachments is hardcoded in Application.php to "Attachment" in file root of the user files.
If possible, this default folder should be made configurable per oc user in users rainloop settings with "Attachment" as default.
The best solution would be to display a folder browser of oc filespace to select the save path but I think, this woul be much more comlicated to realize.

__Question:__
In Admin login in "About" I don't see this "Rainloop app is up to date" message any more.
Is this an issue or did you remove this?

**Comment by RainLoop** [comment]
> $aResult['AttahcmentsActions'] should be
> $aResult['AttachmentsActions'], I think.

Thanks!

> is hardcoded in Application.php to "Attachment"

application.ini
```ini
[labs]
owncloud_save_folder = "Attachments"
```

> The best solution would be to display a folder browser of oc filespace
> to select the save path but I think, this woul be much more comlicated to realize.

Yes, so far I have implemented a simple way.

> In Admin login in "About" I don't see this "Rainloop app is up to date" message any more.
> Is this an issue or did you remove this?

No, it is no an issue, by default ownCloud package contains RainLoop Community edition (AGPLv3 license). A bit later will be available RainLoop Standard edition (Creative Commons license) for ownCloud with this functionality.

**Comment by deMattin** [comment]
Thanks - next time I should better look at more lines to see, what code does ... ;)
I changed it there and the default folder remains as "save to" place.

BTW: With forcing to overwrite the ini, I destroying my (admin) config  - next time I better close all browser windows befor changin of this ini ...) 

With this different "editions":
Does this mean, that I don't get actual updates as before with simply login as admin and update?
If so, is there a way to stay closer to actual git version?

**Comment by RainLoop** [comment]
Ups :(

line: 2843
```php
$sSaveFolder = $this->Config()->Get('labs', 'owncloud_save_folder', '');
if (!empty($sSaveFolder))
{
    $sSaveFolder = 'Attachments';
```
->
```php
$sSaveFolder = $this->Config()->Get('labs', 'owncloud_save_folder', '');
if (empty($sSaveFolder))
{
    $sSaveFolder = 'Attachments';
```

**Comment by RainLoop** [comment]
> With this different "editions":
> Does this mean, that I don't get actual updates as before with simply login as admin and update?
> If so, is there a way to stay closer to actual git version?

No, you just need to use Standard edition.

**Comment by deMattin** [comment]
With this patch, it works as expected - THANKS! :+1: 

But sorry, I don't undestand this updating and editions thing, please explan it more detailed.

Previously I used a git clone for using the full rainloop.
Updating has been a simple git update or/and the update in admin panel, if I remember right.
Then with this ownloud app, there were the updates from admin panel - which are more often than updates of oC app and I got info about updates from this trigger thread in git!
(The owncloud app isn't updated as often as these updates from admin  panel and further more, I don't get oc app updates automatically or get a notice, if there is an update available.)

And now?
1. How do I get this change to "standard edition"?
2. How do I get information about updates in community edition?
3. How do I install updates in community edition?
(downloading, overwriting all, setting owner and rights isn't much comfortable and is more dangerous than other ways to update)
4. How should I set up my oC app to always get the newest version possible?

I like to be close to actual developing version - also for testing and reporting errors or issues ...

**Comment by RainLoop** [comment]
There are reasons why the Community Edition does not have the update function in the admin panel.

> Previously I used a git clone for using the full rainloop.

It's not a good idea :)

> How do I get this change to "standard edition"?

Check the new download page: http://www.rainloop.net/downloads/

Community edition: ownCloud (AGPL) 
Standard edition: ownCloud (CC) 

> How do I get information about updates in community edition?

From site.

> How do I install updates in community edition?
> (downloading, overwriting all, setting owner and rights 
> isn't much comfortable and is more dangerous than other ways to update)

Yes, you need download and overwrite all files.

> How should I set up my oC app to always get the newest version possible?

Install the standard edition (ownCloud (CC) ).

**Comment by deMattin** [comment]
Now and with the help of http://www.rainloop.net/purchase/ everthing is clear ... Thanks!

1. Maybe you should enhance naming for owncloud download links on [Download page](http://www.rainloop.net/downloads/) a bit, to make it more clear which one is standard or community version:
ownCloud (AGPL) -> ownCloud Community edition (AGPL)
ownCloud (CC) -> ownCloud Standard edition (CC)

2. To see the correlation, it would be good to enhance the naming of the grey Download Buttons for full rainloop app with (APGL) and (CC).

3. In ["feature comparison page (purchase)"](http://www.rainloop.net/purchase/)  you named Standard edition as "basic" - to not get confused, it should be named "Standard edition" there, too.

**Comment by RainLoop** [comment]
Thanks! 
Yes, I will try to describe packages more clearly.

**Comment by deMattin** [comment]
In the admin panel of oC rainloop app (Standard CC) in "Licensing" you also named "Standard Edition" as "Basic".

**Comment by RainLoop** [comment]
You are not quite right.

Package: Community Edition (AGPL)
No Subscriptions.

Package: Standard Edition (CC)
Subscriptions: Basic (Free) or Premium

**Comment by deMattin** [comment]
Ahh, I see ... Standard Edition Basic and Standard Edition Premium ... :)
Why not always name them like this (also in http://www.rainloop.net/purchase/)?

As I see now, there are 3 different Lizenses/Subscriptions:
- Community Edition (free)
- Standard Edition Basic (free)
- Standard Edition Premium (paid once or per year)

If you know this, anything is clear (also in comparison chart).
But in first sight you don't know, that "Standard Edition" contains Subscriptions Basic or Premium or is a collective name of them.

Another thing:
For testing I switched language of Admin panel and License is named "Basis" in German there.
I think, the Edition/License naming (Community, Standard, Basic, Premium) should not be translated in any language because in my opinion it's the name of the edition/subscription like "rainloop" is the name of the app.

**Comment by RainLoop** [comment]
Thanks!

> I think, the Edition/License naming (Community, Standard, Basic, Premium)
> should not be translated in any language

It makes sense.

**Comment by RainLoop** [comment]
I think it is now more intuitive.

http://www.rainloop.net/purchase/

**Comment by deMattin** [comment]
:+1:
