### ISSUE TITLE
Linebreak/paragraph in mail-editor

### ISSUE THREAD

**Issue by deMattin** [RainLoop/rainloop-webmail#644]
In Editor for new mails the useage of `<Return>` and `<Shift>+<Return>` to set a linebreak is used in different way, other editors do it.

Normal useage:
`<Shift>+<Return>` sets a linebreak ("Soft return")
`<Return>` sets a new paragraph  ("Hard return")

Useage in Rainloop editor is vice-versa.

**Comment by RainLoop** [comment]
You may use Enter (Soft) or Shift+Enter (Hard)
Do I understand you correctly?

**Comment by deMattin** [comment]
http://en.wikipedia.org/wiki/Line_wrap_and_word_wrap#Soft_and_hard_returns

In rainloop `<Return>` creates a `<br>` and `<Shift>+<Return>` creates a `<p>` in html code.
But it has to be:
`<Return>` -> `<p>`
`<Shift>+<Return>` -> `<br>`
in html code.

Rainloop mail editor has the functionality to create both types of "Linebreak" but they are set in another way any other word processing app (or desktop suite) does it.

**Comment by RainLoop** [comment]
Hmm, interesting, thanks!

**Comment by ervee** [comment]
If I may say so, I think it is excellent the way it is. I personally hate editors who create a new paragraph.

**Comment by RainLoop** [comment]
> If I may say so, I think it is excellent the way it is.
> I personally hate editors who create a new paragraph on pressing enter.

Agree.

**Comment by deMattin** [comment]
Then you hate all professional editors / word processors? :wink: 
Why do you "hate" this? Do you have any reason for this?
"Normal" user don't use return at all and simply write the whole text / sentence in one - this is most my received mails in job look like.
"Return" is not a visual formatting - it's a logical break.
Actual behaviour is irritating to anybody, who is used to work with office suits!

It's never a good solution to do something different (vice-versa) than established general use.
MS Word, Libre/OpenOffice and any Word Processor I know uses it like described.

It's a great feature, that rainloop allows setting a linebreak or paragraph like this but it should do it the right way.

**Comment by deMattin** [comment]
It's not easy ...
I understand that users, who are not really used to "real" word processors in daily use are irritated and won't understand, why there's 1,5 line spacing if you press "Return".

**Comment by ervee** [comment]
I use Outlook a lot. Which does not create a paragraph on enter. VI does not. Notepad does not. Actually, I can only remember Ms Word doing that default. It's the first thing I change. 

I like computers doing as I say. So when I press enter, I want a CR LF not a new paragraph. For that I'll press enter twice. 
I also dislike the default US international keyboard settings which does all kinds of crazy stuff. I like the standard US keyboard setting which does what I type.

**Comment by deMattin** [comment]
Outlook does create paragraphs on enter - have a look in mailsource of an outlook mail!
And Outlook is doing it the right way.
Format the paragraph in outlook settings when creating a mail and set 6px before pragraph.
Then use return and shift+return and you see the difference..
Another simple test: create a paragraph with auto numbering -> return creates a new line with a new number and shift+return creates a new line without a new number.
(sadly this functionality doesn't work in rainloop numbering, yet)

VI and Notepad aren't editor's with capability to use paragraphs or linebreaks - not even bold or something like that. They have no real formatting options.

But it is as I thought:
Users, who don't care of or know the difference of paragraphs or linebreaks, simple use return without knowing, they use paragraph ... 

I have a simple solution for rainloop that fits to anybody..
Let's do it like Outlook and set paragraph spacing (before and after) to one line as default. Doing so, it looks like a return.and users who don't care on paragraphs see no difference.

So folllowing sould be done in rainloop to fit all needs:
1. switch useage of keyboard for linebreak and paragraph.
2. make pragraph spacing (general css/style) in mail configurable in editor and set it default to 1 line (looks like linebreak)

Outlook allows setting of spacing before and after a paragraph separate for each paragraph.
I don't think, this is neccessary for a webmailer and probably needs much more enhancement in mail editor.

@RainLoop: what do you think?
Handling paragraphs and linebreaks the right way would be a great feature and doing it like outlook won't confuse users who don't care of difference or useage of linebreaks or paragraphs!

**Comment by deMattin** [comment]
Btw.: Rainloop uses ckeditor for mails.
I checked http://ckeditor.com/demo and it also does it the right way (also can use numbered paragraphs correct).

And I found: http://ckeditor.com/demo#enter
> It is still possible to configure the editor to produce `<br>` or `<div>` on ENTER. __This is not a recommendation (let's make the web good!)__

 :wink:

**Comment by ervee** [comment]
I think your paragraph is about the html markup. My paragraph is how it visually looks ;-) I couldn't care less about how the underling code is used or looks. As long as I can press enter for a new line, and two enters for a new paragraph I'm happy :-D

**Comment by deMattin** [comment]
Ah ok ...
So why not do the following in rainloop:
1. change Return (paragraph=hardreturn) and Shift+Return (linebreak=softreturn) to usual and recommended usage
2. define a per user variable in rainloop settings for global paragraph spacing after paragraph (% or px)
3. set this paragraph spacing per default to look like a "return" (1 line or 100% or 0px spacing)
Now a return and a shift+return look equal,

This way users who don't care of paragraphs or linebreak get it as desired (1x spacing).
Users who like to use linebreak and paragraph can set it there in settings to 150% or 6px as spacing after paragraph and can use it like they are used to.

=> Both user groups use the editor in their used way and how they expect it to look like.

**Comment by RainLoop** [comment]
> Now a return and a shift+return look equal,

It is not good decision. Message displaying should be identical after reply.

**Comment by ervee** [comment]
Isn't the set spacing part of the html sent with the email? If it is than I guess it could work.

**Comment by deMattin** [comment]
Yes - and that's the reason why html-Mail is so problematic with clients, that don't work the right way or ignore html- or css-syntax (and also nerdy users don't like them at all).
Rainloop (and some other mailer) does not pharse the whole html-syntax at all (ignores some css styles) and so it doesn't display html-mails like the user generates it. Furthermore Rainloop also ignores color definitions.
That's the reason why some mail replies (also from and with other clients) look weird with big line spacings the initial creator didn't intend.
__This mostly is caused by the wrong use of the enter key!__

Another problem here is, that the mail-replies often do include the full html syntax but some clients don't display it.
It's hard to explan, but if you think of weird formated html-mail replies you've seen in past, that's mostly the reason for this.

This is not only a problem of rainloop - it's a general problem!

But how to do it the right and professional way?
Forget best practise and correct use because many or some users haven't lerned to do it right (yet)?
Force users to use Enter key how it should be used?
Do it wrong, because rainloop isn't capable to read all margin or spacing css of received mails, yet? ;)
I really don't know!

For me, as a user, who is used to work with word processors, big and well formatted documents with stylesheets it is self-evident to use soft and hard returns.
It's so self-evident, that I even use this different types of enter, even if the editor doesn't differ it (like here in git markdown)
But I'm not the center of the word - I know ... ;)

I gave it some thought and also tested some other clients.
Thunderbird doesn't differ between shift+return and return - it always simply does a `<br>`. You have to format a `<p>` another way with stylesheets/templates in UI (don't know, how it's named in english).
Outlook works like a real word processor and you are able generate perfect formatted html-mails with it. But some simple clients don't show it always like it should be and was intended to look (including rainloop).

CKeditor creators tend to train the user to do it right, but know, that there are some, that refuse to do so. And so they gave the opportunity to switch the behaviour of the enter key.
And in rainloop this switch to overwrite the normal useage is set.

All in all I like to have a shortcut for hard AND soft break. So the solution, thunderbird uses, is even worse. And I think, they had the same discussions there in past and did it this way as a compromise for "always-enter-user".

I stick on the opinion, rainloop does it wrong to use enter key like this!
But for me as a user of many different software suits, I'm used to work with software, that does things completely different, than others. And so, if the only possibility would be to loose enter and shift+enter (like thunderbird does), for me it's better to use a vice versa UI than don't have a shortcut at all.

So it will be the decision of the programmer and his philosophy, how to use a word processor.

--------------
Just for information I append some mailsource of mails, generated in Outlook and Thunderbird:

Thunderbird-Mail:
```html
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
  </head>
  <body bgcolor="#FFFFFF" text="#000000">
    Testmail Thunderbird: -Enter-<br>
    line2 -Enter-<br>
    line3 -Shift+Entter-<br>
    line4 -Shift+Enter-<br>
    line5 -Enter-<br>
    last Line<br>
  </body>
</html>
```

Outlook Mail like displayed in Outlook (Paragraph Spacing default = 1 Line):
>Testmail Outlook: -Enter-
line2 -Enter-
line3 -Shift+Entter-
line4 -Shift+Enter-
line5 -Enter-
last Line

Looks like this in Rainloop:
![image](https://cloud.githubusercontent.com/assets/5565503/7556174/af187362-f766-11e4-86c0-1bce44bc02d2.png)

Outlook Source-code:
```html
<style><!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	margin-bottom:.0001pt;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;
	mso-fareast-language:EN-US;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:#0563C1;
	text-decoration:underline;}
a:visited, span.MsoHyperlinkFollowed
	{mso-style-priority:99;
	color:#954F72;
	text-decoration:underline;}
span.E-MailFormatvorlage17
	{mso-style-type:personal-compose;
	font-family:"Calibri",sans-serif;
	color:windowtext;}
.MsoChpDefault
	{mso-style-type:export-only;
	font-family:"Calibri",sans-serif;
	mso-fareast-language:EN-US;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:70.85pt 70.85pt 2.0cm 70.85pt;}
div.WordSection1
	{page:WordSection1;}
--></style><!--[if gte mso 9]><xml>
<o:shapedefaults v:ext=3D"edit" spidmax=3D"1026" />
</xml><![endif]--><!--[if gte mso 9]><xml>
<o:shapelayout v:ext=3D"edit">
<o:idmap v:ext=3D"edit" data=3D"1" />
</o:shapelayout></xml><![endif]-->
</head>
<body lang=3DDE =
link=3D"#0563C1" vlink=3D"#954F72">
<div class=3DWordSection1>
<p class=3DMsoNormal>Testmail Outlook: -Enter-<o:p></o:p></p>
<p class=3DMsoNormal>line2 -Enter-<o:p></o:p></p>
<p class=3DMsoNormal>line3 -Shift+Entter-<br>
line4 -Shift+Enter-<br>
line5 -Enter-<o:p></o:p></p>
<p class=3DMsoNormal>last Line<o:p></o:p></p>
</div>
</body></html>
```

**Comment by RainLoop** [comment]
> Another problem here is, that the mail-replies often do include the full html syntax
> but some clients don't display it.

Well, this is done for security.
Gmail also cuts some styles.

**Comment by RainLoop** [comment]
I decided to leave it as is.

Reasons:

- RainLoop exists for a long time and no one asked to fix this thing (except @deMattin :)).
- RainLoop has some problems with `<p>` when it trying convert HTML to TEXT and back. This is another very large and complex problem.
- I like `<br />` more that `<p>`. If I want `<p>` I usually press Enter two times.

**Comment by deMattin** [comment]
I don't want to check, but I think, it's new, that a shift+return causes a `<p>`. I don't often _write_ mails with rainloop and mostly use it to read mails. I wonder, why I haven't seen this behaviour before. Maybe it hasn't been there and shift+return and return have been both a `<br>` in older rainloop versions?
Rainloop only has very basic formatting options for html-mails (slightly enhanceable but all in all sufficient in my eyes) and I wouldn't have been asked for this shift+return as a feature but the vice-versa usage caught my eyes.

All in all, like it is now, it's better than no possibility to create a `<p>` (2x `<br>` isn't the same as `<p>`).
So leaving as it is, isn't the worst decision... ;)

So thanks for discussing this and keep up the good work!

PS:Offtopic, but one short question:
Is it intended to not display enhanced formatting like (background) colors of div/p ranges?
And does it make sense to discuss this in a separate issue or feature request?

**Comment by RainLoop** [comment]
> Maybe it hasn't been there and shift+return 
> and return have been both a in older rainloop versions?

Yes, in older version `Enter` and `shift+Enter` do same things.

> Is it intended to not display enhanced formatting like (background) colors of div/p ranges?

Well, no one wanted such functionality.

**Comment by deMattin** [comment]
demattin:
> Is it intended to not display enhanced formatting like (background) colors of div/p ranges?
>
> RainLoop:
> > Well, no one wanted such functionality.

Well done! Thanks for implementing this in build 1.9.2.342
You did a good work and now some mails, I get regularly, look much better! :+1:

**Comment by RainLoop** [comment]
You're welcome :)

**Comment by Samonitari** [comment]
I just found this years later.
At least now I know that if I use enter and shift+enter *the other way around* than in any rich-text or Markdown editor, it inserts the tags I want.
Still, I agree with @deMattin, it was a stupid decision to invert the most widespread way, at leasta settings entry should have been made for it.
