### ISSUE TITLE
Structure of download link for AGPLv3 and CC versions

### ISSUE THREAD

**Issue by Sp1l** [RainLoop/rainloop-webmail#648]
Hi, 

I'm having trouble fixing the package on FreeBSD wrt hte community and regular version. Can't seem to construct a tarball url fetching the rainloop-community version from the http://repostiory.rainloop.net/v2/core.stable.json output is there a different repo url to call or what is the structure of the download for the AGPLv3 tarball?

PORTNAME=       rainloop
PORTVERSION=    1.9.0
CATEGORIES?=    mail www
MASTER_SITES=   http://repository.rainloop.net/v2/webmail/${PORTVERSION}/
DISTNAME=       ${PORTNAME}-${PORTVERSION}.${RBUILD}-${RHASH}

# Refresh using info from http://repository.rainloop.net/v2/core.stable.json
RHASH=          0e55c0364faafb6f550fd4b186acfe6e
RBUILD=         325

**Comment by RainLoop** [comment]
http://repository.rainloop.net/v2/core.open.json

**Comment by Sp1l** [comment]
Excellent, many thanks! That wasn't one of the many things I had tried (core.community.json etc)

**Comment by Sp1l** [comment]
curl http://repository.rainloop.net/v2/core.open.json | grep -i license
"license": "CC BY-NC-SA 3.0",

curl http://repository.rainloop.net/v2/core.stable.json | grep -i license
"license": "CC BY-NC-SA 3.0",

The tarballs seem to be OK though

**Comment by RainLoop** [comment]
Thanks! fixed.

**Comment by Sp1l** [comment]
Ever so welcome! My futile attempt at giving back to the project...
