### ISSUE TITLE
Pasting into HTML email does nothing

### ISSUE THREAD

**Issue by justdaj** [RainLoop/rainloop-webmail#649]
Anyone else having problems pasting text into HTML emails?

I've tried it on Chrome and Safari.  When I paste into the message editor nothing happens. If I change the email from HTML to plain text I can paste. 

I'm only seeing this on the Community build (I'm using 1.9.0.325).  I installed the 'Standard' edition and it seems to work ok.

**Comment by RainLoop** [comment]
This problem occurs in all versions. I do not understand The reason, but f5 fixes the problem for a while.

**Comment by justdaj** [comment]
Ok, I've tried the F5 equivalent on a Mac but no luck :-(

Also, occasionally the editor stops accepting some key presses.  Always after an auto save to draft; typically the spacebar is ignored.

**Comment by RainLoop** [comment]
Ok, It seems I have fixed the problem, tomorrow will be a new version with the fix.

**Comment by justdaj** [comment]
excellent :)

**Comment by RainLoop** [comment]
Fixed.
