### ISSUE TITLE
Add avatar user

### ISSUE THREAD

**Issue by furyscript** [RainLoop/rainloop-webmail#650]
Hi, 

How can I add the avatar user???
So the most popular provider can see the avatar mail!

**Comment by megadr01d** [comment]
Avatars are provided by Gravatar. Just enable them in the admin panel. Every gravatar assigned to an email address will show up automatically in Rainloop.

**Comment by furyscript** [comment]
Sorry, but where is the section to set avatar???
Any guide???
I don't see in the admin panel..

**Comment by furyscript** [comment]
Ok understand, I need to set avatar in Gravatar and will show in my user email?

**Comment by megadr01d** [comment]
Yeah. You can set multiple avatars to multiple email addresses in the Gravatar website. Then just send an email to yourself. Be aware that the avatar is not embedded in the email message. People getting an email from you, will need to use Rainloop or another email client which reads Gravatars.

**Comment by furyscript** [comment]
Ok! Thank you! 
Close @RainLoop :)
