### ISSUE TITLE
[Feature-Request] Arbitrary header fields for filters

### ISSUE THREAD

**Issue by amdavidson** [RainLoop/rainloop-webmail#651]
![capture](https://cloud.githubusercontent.com/assets/81012/7595302/3db591a6-f8b4-11e4-82ad-65d0fec9e3a8.PNG)

Filters are drastically more useful if they are able to function on other header fields besides to from / cc / subject. 

Examples:
* X-Spam-Flag is commonly used to filter SPAM into a folder for quarantining.
* List-Id is commonly used to sort email list traffic into different folders to avoid clogging one's inbox.

Please add the ability to use arbitrary headers as it would make this vastly more useful.

**Comment by RainLoop** [comment]
ok

![image](https://cloud.githubusercontent.com/assets/5530092/7599761/908ef986-f90d-11e4-95e8-4d50f0a93f98.png)

**Comment by RainLoop** [comment]
And bonus:

![image](https://cloud.githubusercontent.com/assets/5530092/7600249/382c2368-f912-11e4-8bb9-7d53951d8d8b.png)

**Comment by ervee** [comment]
Cool!

**Comment by RainLoop** [comment]
Done (1.9.1 version)
