### ISSUE TITLE
Text gone while editing or changing sender

### ISSUE THREAD

**Issue by jelle-e** [RainLoop/rainloop-webmail#658]
Using newest version.

While composing an email (html mode) in Firefox I can't select the text. Ctrl-A just doesn't keep the text selected. Mouse select does work as does Shift select.

Also when I composed an email and after that select another sender (identity WITH signature) all text just disappears! Undo doesn't work. Signature overwrites mail. This happens sometimes though. Most of the time the signature is pasted before all text, not at the end of the mail.
I'll try to figure out how to reproduce the 'overwriting of mail'.

**Comment by RainLoop** [comment]
Thanks!
It will be fixed in the next version.

**Comment by RainLoop** [comment]
Fixed (1.9.1 version)
