### ISSUE TITLE
[Feature Request] Smartphone Detection and Optimized Site

### ISSUE THREAD

**Issue by tmcb82** [RainLoop/rainloop-webmail#659]
First off, thank you for this great app. I was wondering if RainLoop would get detection if you are using a smartphone and could load a smartphone optimized version of RainLoop?

**Comment by RainLoop** [comment]
Well, there is no optimized version of RainLoop :)

**Comment by tmcb82** [comment]
Exactly, Is there any plans of making one? :)

**Comment by skibbipl** [comment]
Why not use TypeMail for example? Rainloop is just a web IMAP client - there are plenty of mail apps for Android and other platforms.
