### ISSUE TITLE
Tab key toggles checkboxes

### ISSUE THREAD

**Issue by ervee** [RainLoop/rainloop-webmail#662]
Hi,

When tabbing over checkboxes (search window, options, etc) the checkboxes are toggled. This is not what should happen :)

**Comment by megadr01d** [comment]
Confirmed and also #663.

**Comment by RainLoop** [comment]
Browser, OS ?

**Comment by megadr01d** [comment]
Firefox, Windows here.

**Comment by RainLoop** [comment]
Thanks

**Comment by ervee** [comment]
Firefox on Windows here too :)

**Comment by RainLoop** [comment]
Fixed (1.9.1 version)
