### ISSUE TITLE
RainLoop Software License Agreement

### ISSUE THREAD

**Issue by RainLoop** [RainLoop/rainloop-webmail#664]
What do you think about new license for standard edition (say goodbye to Creative Common).

---

LICENSE AGREEMENT

RainLoop Webmail (Standard edition) is released under RainLoop Software License

By using RainLoop Webmail (Standard edition), you confirm that you have read and agreed to this license agreement.

1. You may use the product on commercial websites by purchasing a commercial license (subscription). 
A commercial website means:
   1. any site which is built, owned or maintained by a profit-making person or organisation, even if the site does not generate revenue;
   2. any site which generates revenue, even if it is otherwise non-commercial;
   3. any government, government-agency or political-party websites.
2. You may use the product on non-commercial websites free of charge subject to the terms of this license. 
A non-commercial website means:
   1. personal or hobby sites which generate no revenue (whether from advertising, commissions, sales or any other source);
   2. websites owned and maintained by charitable or not-for-profit organisations;
3. You must choose the appropriate license (subscription) for your needs:
   * Basic subscription (non-commercial websites).
   * Premium one year subscription (for single web domain).
   * Premium lifetime subscription (for single web domain).
4. The term "website" means a single website of a single person or organisation. (In most cases, that would be a single domain, although there could feasibly be multiple websites on a single domain e.g. through the use of subdomains). The website could be your own or a website you build/maintain for someone else.
5. You may not sell, redistribute or offer for download any of our products in any form or in any medium, whether original or modified or for profit or not.
6. You agree not to alter, remove or decode any of the copyright notices or author attribution without explicit written permission from RainLoop.
7. You can not agree to these terms on behalf of a third-party - if your own interest in the site is in any way commercial (for example, a freelancer being paid to build it) then a commercial license is always required, even if the site is for a non-commercial organisation.
8. You agree not to use the product on illegal sites, or on pages which contain illegal material.
9. You may not use the product at all in jurisdictions where this agreement is itself illegal, or where you are not empowered to enter into such an agreement.
10. You guarantee not to hold RainLoop responsible for any problems you may encounter, whether directly or indirectly caused by your use of any of our products.

**Comment by ervee** [comment]
Disclaimer: I'm not going to interfere in the discussion whether you should switch license and if so, how etc. I'm not into that enough. I'm just giving my opinion on the text above.

I don't understand number 7. If a non-for-profit organization "for and by" elderly people hire a person to help them with installing the RainLoop Webmail system for them, they are not allowed to use it? I don't understand that.

**Comment by megadr01d** [comment]
> 6. You agree not to alter, remove or decode any of the source code without explicit written permission from RainLoop.

The only change I'm interested in, is to change the favicon to match my domain's (Standard Basic, personal use, 1 domain, 1 user, access locked to 2 IPs - home and work). Should I inquire by email or is this change non-negotiable?

**Comment by RainLoop** [comment]
This is not the final version of the license.

@ervee 

It is necessary to remove the misunderstandings about the commercial use of the product.
But ok, probably I need remove this list item.

@megadr01d - fixed
```
You agree not to alter, remove or decode any of the copyright notices or author attribution
without explicit written permission from RainLoop.
```

**Comment by megadr01d** [comment]
:+1: Thanks. I absolutely support the original attributions (copyright, title, author, "powered by" links, etc.) even if I had a commercial interest in it. It's sad when we don't wish to support independent developers but don't mind supporting the big corporations everyday (Gmail, Hotmail, Microsoft, Apple, Adobe...).
