### ISSUE TITLE
Two factor authentication issue?

### ISSUE THREAD

**Issue by skibbipl** [RainLoop/rainloop-webmail#669]
I've enabled two factor authentication in RainLoop . It's working perfectly fine, but I have one concern. On login page there is a check box that states "Do not ask for code for two weeks". But if I don't log off for two weeks RainLoop still keeps my session. Shouldn't RainLoop force automatic log off after two weeks?

**Comment by RainLoop** [comment]
These are different things and they are not related.

**Comment by skibbipl** [comment]
Can you elaborate? For what this check box is used?

**Comment by RainLoop** [comment]
This checkbox used for two factor code only. 
You don't need to enter this code each time you enter the webmail.

**Comment by skibbipl** [comment]
So basically this check box is useful when you login and log off all the time to RL. Checking it will prevent asking for two factor code for two weeks. And if you don't log off then in fact it doesn't matter if you check this box or not?
From security point of view wouldn't be a better to force log off user after some time? Just to make sure that the person using the mail is still the mail owner.

**Comment by RainLoop** [comment]
Do you mean "Remember Me" functionality?

**Comment by skibbipl** [comment]
Yes, I mean if my two factor code is valid for two weeks then "remember me" perhaps should also work only for two weeks?

**Comment by RainLoop** [comment]
Well, signme token has limitation in 1 month.
Of course I can reduce it but I'm not sure it's necessary.

**Comment by skibbipl** [comment]
No need to. I think now I understand how "remember me" and "do not ask for code" are linked.
Thanks for explanation!

**Comment by RainLoop** [comment]
You're welcome.
