### ISSUE TITLE
[Feature] Option to not show deleted emails

### ISSUE THREAD

**Issue by leanderjanssen** [RainLoop/rainloop-webmail#671]
Would it be possible to add a enable/disable option to not show emails that have been marked for deletion but are not yet permanently deleted?

**Comment by RainLoop** [comment]
Yes, this functionality will be available in 1.9.1 version.

**Comment by RainLoop** [comment]
Fixed (1.9.1 version)

**Comment by stenrose** [comment]
What is that option called?

I'm searching for an option to show \Deleted flagged mail that hasn't yet been expunged. Only related option found was use_imap_expunge_all_on_delete, but I haven't found what it does yet.
