### ISSUE TITLE
gpg with multiple addresses in a single key

### ISSUE THREAD

**Issue by xkonni** [RainLoop/rainloop-webmail#672]
i have some gpg keys (including my private key) used for multiple addresses.
unfortunately rainloop shows just one address and can not encrypt for/sign with the others.

**Comment by RainLoop** [comment]
Yes, I understand the problem.
Now, pgp has a basic functionality, but in the future it will be fixed.

**Comment by xkonni** [comment]
sounds good. looking forward to it!

**Comment by tetrakos** [comment]
+1

**Comment by thonixx** [comment]
I have the same issue. I am using a PGP key with private and commercial mail addresses. Currently I am unable to view PGP encrypted mails on my company mail.

Therefore: +1

**Comment by jeekajoo** [comment]
+1 
is this a limitation of openpgpjs?

**Comment by zwarag** [comment]
+1

**Comment by ebal** [comment]
same problem here! I would love to see this being fixed in near future

**Comment by RainLoop** [comment]
Please, try the latest version (1.9.3.363)
![pgp2](https://cloud.githubusercontent.com/assets/5530092/9970316/1cb7287a-5e5d-11e5-84a1-ac6583b6e308.png)

**Comment by jeekajoo** [comment]
wonderful, it works for me
thanks!

**Comment by ebal** [comment]
testing 1.9.3.363
but it doesnt seem to work

I have imported a public key with two mail addresses but I see only the first one

**Comment by RainLoop** [comment]
@ebal Could you give me a similar key for test?

**Comment by ebal** [comment]
https://pgp.mit.edu/pks/lookup?search=0x10B98B4D&op=index

It shows me only the first one

Thank you

**Comment by RainLoop** [comment]
Thanks

**Comment by zwarag** [comment]
Works good!!

**Comment by nnnn20430** [comment]
it still can't decrypt a message for another address that is also covered by the key but is not promary

**Comment by esroyo** [comment]
@RainLoop Just want to tell that I'm working on this issue in esroyo/rainloop-webmail@a34da5de0dbbc72816105d2da6c8399701e06c9c so we don't duplicate efforts.

**Comment by esroyo** [comment]
This should be marked as solved (#999 #1001). Thanks!

**Comment by thonixx** [comment]
I still have an issue with the keys. I get "OpenPGP error: Error: Error signing cleartext message!" when trying to sign a key with multiple identities. And yes it is of course password protected but I entered the correct one in the password field.

**Comment by RainLoop** [comment]
Could you show me a screenshot?

**Comment by thonixx** [comment]
Here you go:
![screenshot50](https://cloud.githubusercontent.com/assets/1019034/14983218/169e4206-113c-11e6-90da-936c248a5b51.png)

**Comment by esroyo** [comment]
Are you using master? If so, I think a multi-address key should show all the addresses as in the attached image:

![rainloop-multiaddress-pgpkey-screenshot-20160503181101](https://cloud.githubusercontent.com/assets/1025694/14989625/0220beae-1159-11e6-8bfd-fd6a99e25b97.png)

**Comment by RainLoop** [comment]
You may try this beta version:

http://repository.rainloop.net/v2/webmail/1.10.0/rainloop-1.10.0.100-79281a744a926ecaffd536d3a55688cf.zip

or wait for stable release.
