### ISSUE TITLE
Missing shortcut for send

### ISSUE THREAD

**Issue by skrat** [RainLoop/rainloop-webmail#680]
Rainloop has generally very good support for keyboard shortcuts. An important one is missing: when in compose UI, there should be a way to send the mail, eg. <kbd>Ctrl+Enter</kbd> or <kbd>Ctrl+Shift+Enter</kbd>

**Comment by RainLoop** [comment]
```ini
[labs]
allow_ctrl_enter_on_compose = On
```
It disabled by default.

**Comment by skrat** [comment]
Nice! Thank you (perhpas make it default to On?)

**Comment by RainLoop** [comment]
No, because this is a dangerous operation (sending message) is best to leave it off.
