### ISSUE TITLE
Second identity is not used when default

### ISSUE THREAD

**Issue by purejava** [RainLoop/rainloop-webmail#688]
I noticed, that on my up-to-date rainloop machine a second identity is not used in the From header.

Steps to reproduce:
* fresh install of rainloop
* add a domain
* add a second identity and make it the default
* compose mail and send it

The From header in the e-mail shows the other / first identity, although the second identity was shown on top of the compose new mail window.

To verify this, I installed rainloop from scratch into a VM with the same result.

Cheers,
Ralph

**Comment by jelle-e** [comment]
Yes, same here. I noticed all my identities aren't used when selecting them in composing.
This is from an up-to-date already running RainLoop installation. I just can't send mails with the chosen identity anymore. Please fix because many users don't use their main identity as their from address. This causes a lot of confusion. Thanks!

**Comment by RainLoop** [comment]
Thanks!
Try the latest version (1.9.1.333).

**Comment by purejava** [comment]
Thank you very much for the new version!
I updated my installation and tested it.

The second identity (default on my system) is used now when sending e-mail - that's fine.

Nevertheless there are some things that do not work:

1. setting the other / first identity as the default and sending an e-mail fills the From header with part of the second identity
2. setting the second identity as default, compose an new e-mail and changing the From header on top of the compose new mail window also leads to an e-mail sent where the From header is filled with part of the second identity

To be precise: my first identity is `name@domain.com`.
My second identity is `First Last (othername@otherdomain.com)`.
_Filled with part of the second identity_ means, that the From header looks like `othername@otherdomain.com` without `First Last`.

Cheers,
Ralph
