### ISSUE TITLE
Feature suggestion: Unified Inbox

### ISSUE THREAD

**Issue by zkvvoob** [RainLoop/rainloop-webmail#690]
Hello,

Have you considered adding an option to consolidate all accounts into one unified Inbox? Switching between accounts as it works now is not very convenient, especially since notifications work only for the currently open account.

Thank you!

**Comment by megadr01d** [comment]
That would require a database which Rainloop [doesn't use](https://github.com/RainLoop/rainloop-webmail/issues/568).

**Comment by d2-d2** [comment]
I also like to ask about this feature. I know it requires DB, but contacts require it too and rainloop seems to support that. Can't you add it as an options, like 'contact' feature? I'm sure most of the users will find it extremely useful.

**Comment by kimusan** [comment]
This is my number one missing feature in Rainloop. would love to see it implemented (and yes I dont care about it using a database)

**Comment by Gymnae** [comment]
+ 1 - please re-open this issue.

**Comment by nomadturk** [comment]
As there is support for databases now,  adding unified inbox as a feature would be perfect.

**Comment by joern45219** [comment]
any updates here?

**Comment by emresaracoglu** [comment]
Year 2021: Any updates?

**Comment by Vincent14** [comment]
Is there a way to retrieve elements in datastructures that tracks from which account a mail come from? I mean, there is a way to mix mails and folders front side at least, what is the limitation without database, I don't understand?

**Comment by mlokaleu** [comment]
November 2021 - is unified mailbox event considered? 
that would make rainloop my go-first e-mail solution

thanks a lot

**Comment by pbanj** [comment]
this is a much needed addition

**Comment by akhiljalagam** [comment]
> November 2021 - is unified mailbox event considered? that would make rainloop my go-first e-mail solution
> 
> thanks a lot

we are getting paid by GMail,Outlook to not add this feature.

**Comment by glli** [comment]
Definitely this is a must-have feature. Currently I am using Cypht which supports unified inbox and new email notification from any account, but its UI is ugly and has issues of html rendering. I really hope Rainloop could have this feature.

**Comment by emresaracoglu** [comment]
Those who believe this feature will come are the same as believing that there is oxygen on Mars.

**Comment by Cyyyyyyyyyyyyyyyy** [comment]
3 years later, this would still be awesome
