### ISSUE TITLE
Bigger Attachments not working 

### ISSUE THREAD

**Issue by vchackos** [RainLoop/rainloop-webmail#694]
Hi,

We love this product , but when we attach a file we are seeing this error " An unknown upload error occured " 

and when i click send, it says the warning that the file was not properly uploaded. 

Any help Please 

Vinod

**Comment by megadr01d** [comment]
Have you checked the upload limit in the admin area's **General > Main**?

**Comment by vchackos** [comment]
yes,, its set to 256 Mb , and the php limits are set to 512.

Vinod

**Comment by megadr01d** [comment]
Try to check the [logs](https://github.com/RainLoop/rainloop-webmail/issues/686#issuecomment-104660418) and post them here. Rainloop's dev will probably take a look at them.

**Comment by tmcb82** [comment]
Just my $.02 but files that large might be better transferred via files sharing services (ie. Dropbox) better, rather than via email.

**Comment by megadr01d** [comment]
@tmcb82 I totally agree. My point is that I always get failed big file uploads in my corporate environment, not just email uploads. Besides, the point of paying for some kind of hosting (shared or dedicated) is to avoid 3rd party sharing services and install something like elFinder or Monsta FTP to transfer files.

**Comment by RainLoop** [comment]
> Just my $.02 but files that large might be better transferred 
> via file sharing services (ie. Dropbox) better, rather than via email.

Yes, and I'll try to do something like that.
But even now you can just add a link to the shared file in your message.

**Comment by beankylla** [comment]
Hello, I have a similar issue: (on ubuntu server 14) 
my settings are:
upload_max_filesize	2G
post_max_size 2G
upload limit: 100 M

I noted that any attachment of 1.00 mega and above does not work.
999 KO works, not 1.0 M..
quite strange i don't see those values anywhere else

On the same server I have an owncloud session where uploading a 1,3 giga file is not a problem

I didn't find anything interesting in the logs they don't seem to log failed email creation...
Should i post them anyways?

**Comment by RainLoop** [comment]
@beankylla What is you web server?

**Comment by beankylla** [comment]
nginx

**Comment by RainLoop** [comment]
Additional configuration for nginx (server section):

```
client_max_body_size 1G;
```
