### ISSUE TITLE
Inbox

### ISSUE THREAD

**Issue by cridet** [RainLoop/rainloop-webmail#695]
I just installed rainloop on my ubuntu server 14
I installed postfix and dovecot then installed rainloop on nginx.
I'm able to send email through rainloop but I can't receive email from the outside, my inbox is always empty.

**Comment by RainLoop** [comment]
Do you test your mail server with other email clients, thunderbird for example?

**Comment by cridet** [comment]
I haven't actually.

**Comment by cridet** [comment]
No, I'm unable to connect to it.

**Comment by cridet** [comment]
The admin config page says IMAP is working, I'm not sure what's going on.

**Comment by ervee** [comment]
If your server is not working correctly (receiving email), then RainLoop won't show any email. Make sure your server and services work as they should. This is not the place to ask for help with installing and configuring your server, this is a place to file bugs you find in RainLoop.

**Comment by cridet** [comment]
Alright, I thought it was an issue with rainloop, I'll go look at my config files and see if I missed anything
