### ISSUE TITLE
Can't login from Owncloud

### ISSUE THREAD

**Issue by davodego** [RainLoop/rainloop-webmail#696]
I cant login from within Owncloud App. 
Log in works with https://myserver/rainloop perfektly, all goes well.
But from inside Owncloud rainloop says "Authentifizierung fehlgeschlagen" auth failure.
What happend?

Owncloud 7.0.4 and Rainloop App 4.3 with rainloop 1.9.1

**Comment by RainLoop** [comment]
In the latest version of RainLoop you should use other urls.

Webmail
`https://owncloudserver/index.php/apps/rainloop/app/`

AdminPanel
`https://owncloudserver/index.php/apps/rainloop/app/?admin`

**Comment by RainLoop** [comment]
Now it is a part of owncloud package.

**Comment by davodego** [comment]
I don't understand. 
In owncloud I click on the rainloop Icon and the login dialog is shown.
Can I give a url anywhere to the app?

**Comment by RainLoop** [comment]
> In owncloud I click on the rainloop Icon and the login dialog is shown.

What do you expect to see?

**Comment by davodego** [comment]
I cant log in, as I say in first post. 
In what way the URLs you give me should solve the Login failure?

**Comment by RainLoop** [comment]
/ ownCloud / Admin / RainLoop Webmail /

![image](https://cloud.githubusercontent.com/assets/5530092/7903372/1ef632b4-07e3-11e5-9758-eb062fb67f41.png)

Use this link to enter RainLoop admin panel.

After that you should to configure you mail domain.
http://www.rainloop.net/docs/configuration/

**Comment by davodego** [comment]
OK, thanks, now I understand. Sorry for my misunderstanding.

**Comment by RainLoop** [comment]
no problem :)

**Comment by R3IDO101** [comment]
Hi, RainLoop

I am unable to authenticate with the admin back panel i am using the shared hosting version of owncloud are you able to help me?

**Comment by vjanuario** [comment]
http://www.rainloop.net/docs/configuration/

Default login is "admin", password is "12345".

**Comment by azawahk** [comment]
i also have the same problem, i can log into my Rainloop admin panel, but get 'authentication failed' every time i want to log into my Rainloop email account through Owncloud

**Comment by pongraczi** [comment]
Try to disable plugins. When I disabled the plugins, I was able to login to all configured accounts.
I used whitelist/blacklist/fullscreen video on logon

**Comment by HLFH** [comment]
@RainLoop You can close the issue. I don't have it on ownCloud 8.2.2 and the last Rainloop package.
