### ISSUE TITLE
How do I log in to the Admin Panel?

### ISSUE THREAD

**Issue by gerroon** [RainLoop/rainloop-webmail#697]
H

I am a bit confused about login in. First of all the admin panel(one in the OC admin page) does not accept my OC user and pass. Is this a different user name? if so where is the default user/pass?

The second issue is that when I try to login with an email it says that the domain not allowed.

I am on OC 8.0.3 Apache and Mysql on Linux

thanks

**Comment by megadr01d** [comment]
Check the default login for the admin panel [here](http://www.rainloop.net/docs/configuration/). After login, you need to configure your domains before you can login in the webmail.

**Comment by gerroon** [comment]
thanks
