### ISSUE TITLE
Add keyboard shortcuts for Compose, Reply, Reply all, Forward, Move, Change account, etc...

### ISSUE THREAD

**Issue by mrmierzejewski** [RainLoop/rainloop-webmail#70]

**Comment by megadr01d** [comment]
What do you think about renaming **Check all messages** to **Select all messages** in the localization text? The wording makes me think about "Check new messages" as in "Retrieve new mail".
And why 2 keys for Read/Unread  message? Wouldn't it be easier for a single key `U` to toggle the state as the `I` for flag?

**Comment by pfesaid** [comment]
how I can change the keyboard shortcuts in my way ? code location?

**Comment by megadr01d** [comment]
I confirm that <kbd>`</kbd>,  <kbd>?</kbd> and  <kbd>/</kbd> don't work in Chrome and <kbd>?</kbd> and  <kbd>/</kbd> don't work in Firefox (both in Windows OS, European keyboard).

@RainLoop Which browser/OS are you using for testing?

**Comment by axos88** [comment]
@RainLoop Can you please change / add backspace as the delete action?
Macbooks do not have a delete button, only a backspace, that is used for that.

**Comment by megadr01d** [comment]
@axos88 On Macbooks, the Backspace key is actually called Delete. 

<kbd>Delete</kbd> - Normal Delete (same as Windows Backspace key)
<kbd>Fn+Delete</kbd> Forward Delete (same as Windows Delete key)

More info [here](https://support.apple.com/en-us/HT202676).

Anyway, If @RainLoop wants to change hotkey behavior depending on the OS, it's fine by me.

**Comment by axos88** [comment]
Yes, I know that, but the backspace key does not delete the selected message

**Comment by axos88** [comment]
No need to change hotkey behaviour depending on OS, just add the backspace with the same behaviour as delete.

**Comment by megadr01d** [comment]
> I confirm that `, ? and / don't work in Chrome and ? and / don't work in Firefox (both in Windows OS, European keyboard).

I just confirmed this is a keyboard layout issue by having a similar problem with some of Ace editor's shortcuts. If I mentally picture my US Mackbook Pro keyboard at home, and I hit the keys where <kbd>` ? and /</kbd> should be, it works.

**Comment by megadr01d** [comment]
A couple more hotkey suggestions...

- reload the message list
- open contacts
- in contacts (which can be browsed with up/down arrows), enter to  compose a message to the selected contact

**Comment by djibux** [comment]
A shortcut for junk would be awesome.

**Comment by hh-lohmann** [comment]
I would like to enforce miebda's suggestion (see above) for an **archive key** - Thunderbird's "A" is something to let me always get back to that locally installed client when facing huge amounts of auto mails (reports, logs, etc.)

**Comment by djibux** [comment]
Z works to archive mail.

**Comment by yforster** [comment]
I'd really appreciate a shortcut to reload the message list - my phone knows about an email roughly 10 seconds before it appears automatically in Rainloop, so I either have to wait (10 seconds!) or click the button all the time.

**Comment by RainLoop** [comment]
`Ctrl+R`

**Comment by yforster** [comment]
Awesome! Is this documented somewhere?

**Comment by RainLoop** [comment]
> Is this documented somewhere?

Yes, but not this shortcut :)

**Comment by 3ruce** [comment]
Is there a way to add cc and bcc options in the compose view?

**Comment by mat-m** [comment]
No shortcut (like Ctrl-Enter) to send message ?

**Comment by RainLoop** [comment]
`./data/.../application.ini`

```ini
[labs]
allow_ctrl_enter_on_compose = On
```

**Comment by 3ruce** [comment]
what are the keyboard shortcuts to access cc and bcc?

**Comment by mat-m** [comment]
@RainLoop : thank you. I knew it, but I forgot it. Thanks for the reminder

**Comment by megadr01d** [comment]
@RainLoop New suggestion: shortcuts to change to previous/next page, when there are a lot of email messages (eg. 50 per page). Current workaround is to press `Home` and `Up` or `End` and `Down`.
