### ISSUE TITLE
Mark spam as readed

### ISSUE THREAD

**Issue by Loki3000** [RainLoop/rainloop-webmail#701]
When "to spam" button is pressed, it's to be good to move messages to spam folder and mark them as readed.

**Comment by skibbipl** [comment]
Not sure if it's a good idea. My antispam generates some false-positives. So I would like to know if something important landed in spam.

**Comment by RainLoop** [comment]
@skibbipl No. He is talking about RainLoop's spam button (user action process).
@Loki3000 Ok

**Comment by megadr01d** [comment]
I also like this idea and I would extend it to the "Delete" button. Currently messages are automatically read when selected but in a thread with more than 1 message, if I select it and delete it, only the first message in the thread gets the read status while other messages in the thread stay as unread.
When I arrive home and check my local mail client, I have a number of unread messages in the trash.

**Comment by skibbipl** [comment]
@RainLoop Aaaah, now I get it. In fact I like the idea :+1:

**Comment by RainLoop** [comment]
Done
