### ISSUE TITLE
OpenPGP.js Update

### ISSUE THREAD

**Issue by capecodrailfan** [RainLoop/rainloop-webmail#706]
RainLoop currently ships with OpenPGP.js version 0.7.2 which was released on  July 30th, 2014. Since then there have been a number of small releases addressing bugs and some new features have been implemented. The latest release version 1.0.1 was made available on April 1st, 2015. Any chance that RainLoop will keep the version of OpenPGP.js used up to date?

**Comment by RainLoop** [comment]
Yes, It will be available in the new version of RainLoop Webmail.
