### ISSUE TITLE
Arabic Language

### ISSUE THREAD

**Issue by mubarkan** [RainLoop/rainloop-webmail#707]
Can you please also add Arabic Language as well or guide me how to add ?

**Comment by pietroalbini** [comment]
Translations are made by community folks.

If you want to translate RainLoop by yourself, you need to add the language name in rainloop/v/0.0.0/app/i18n/langs.ini (maybe ask @RainLoop to do so), and then you need to create the translation file in rainloop/v/0.0.0/langs. The best thing is to copy the en.ini and translate it line by line. If you also want to translate the admin panel, do the same thing in rainloop/v/0.0.0/langs/admin.
Finally, you can send a pull request with the changes.

You might want to subscribe to issue #467, from which you'll be notified when new strings are added.
