### ISSUE TITLE
Invalid Token While Trying to Login to Fresh Installation

### ISSUE THREAD

**Issue by f3yisayo** [RainLoop/rainloop-webmail#708]
I've just installed rainloop on my vps with it installing successfully wit the right file ownership/permissions set. But everytime I try logging in to admin backend with the default rainloop username and password, I just get an "Invalid Token" response. 

Can't seem to find a way around it, as the error doesn't say much.

**Comment by axos88** [comment]
Why was this closed without a response? Encountering the same issue.
