### ISSUE TITLE
Unable to download mp3 attachment while/after playing

### ISSUE THREAD

**Issue by ervee** [RainLoop/rainloop-webmail#709]
Hi,

I have several emails with mp3 attachments. I usually don't play them inside RainLoop, but when I accidentally did I noticed I wasn't able to download that mp3 while or after playing it in RainLoop... The Firefox "loading circle" keeps spinning forever. Even after closing the email. I have to press stop and reload the page to be able to download the particular attachment. Other attachments still download fine while this is happening!

I hope you can reproduce it :) If not, I'll check more logging to see what I can find.

Ralf.

**Comment by RainLoop** [comment]
Thanks!

**Comment by RainLoop** [comment]
It looks like Firefox doesn't download the file until it plays it (I think it's some kind of optimization)

**Comment by alexzeitgeist** [comment]
>  I usually don't play them inside RainLoop, but when I accidentally did I noticed I wasn't able to download that mp3 while or after playing it in RainLoop

Not sure why RainLoop wouldn't allow you to download it after you click on it, but have you considered changing the Content-Disposition header for mp3 files in your web server configuration? With Content-disposition: "attachment; filename=yourmp3song.mp3" a browser is instructed to download yourmp3song.mp3 rather than to open it with a known mime handler (such as the build-in mp3 player in your browser).

**Comment by ervee** [comment]
@RainLoop do you mean FF is not able to download the file until the RainLoop built in player is finished playing the file? That's weird. Is it fixable?

@alexzeitgeist are you asking me to change my webserver config?

**Comment by alexzeitgeist** [comment]
ervee, well, it's up to you of course if you want to change your server config. I was just suggesting that it's possible to instruct browsers to download certain file (mime) types, such as mp3, rather than to autoplay them. How you'd do this depends on your server... apache or nginx come to mind.

**Comment by ervee** [comment]
Hi, thanks for the tip, but the problem is not my browser playing the Mp3 file. RainLoop has incorporated a builtin player:
![75365170-dfe5-11e4-880d-db6796ee023f](https://cloud.githubusercontent.com/assets/4435930/8090063/fa63f80c-0fab-11e5-87a4-debd2cddd68a.gif)
I think the problem is within that code somewhere.

**Comment by alexzeitgeist** [comment]
Oh. Thanks, I didn't know about this feature yet.
