### ISSUE TITLE
Feature: Ability to change the default identity 

### ISSUE THREAD

**Issue by git-endoxa** [RainLoop/rainloop-webmail#710]
Hello,

It would be nice if you can change the default identity under Settings > Accounts because in most cases the login name is not identical to the sender name. If you make a mistake you send a message with your login name which in turn is not present in the alias table.

Thanks in advance.

Karsten

**Comment by jelle-e** [comment]
You can, just slide the Identity of your choosing above the other ones :)

**Comment by git-endoxa** [comment]
Pretty cool. Thank you.

**Comment by zeigerpuppy** [comment]
I agree, this is really cool, though not particularly obvious, I missed this trick too!

**Comment by kousu** [comment]
👍 to this. It's a slick way to implement that, though I had to google to find this thread to know how to do it!

Bumping this so that hopefully more people see this when they also go googling.
