### ISSUE TITLE
This is a nightmare to configure with automatic tools like chef.

### ISSUE THREAD

**Issue by axos88** [RainLoop/rainloop-webmail#713]
Hello,

I do not understand the problem you are trying to solve with obfuscating the data directory, but even if there is a realistic reason other than security by obscurity, please make it more easily reproducible in order to be able to configure rainloop with automated tools such as chef.

I'd love to start contributing to the project, and can help cleaning up the code relating to that.

Akos

**Comment by Leryan** [comment]
+1. Also, truly securing the application is done by disallow access to the "data" folder.

**Comment by axos88** [comment]
For those looking for a TEMPORARY solution:

```
template ::File.join(www_root, 'data', 'DATA.php') do
  action :nothing
  source 'rainloop/salt.php.erb'

  variables(
    iterations: 1
  )
end.run_action(:create_if_missing)

template ::File.join(www_root, 'data', 'SALT.php') do
  action :nothing
  source 'rainloop/salt.php.erb'

  variables(
    iterations: 3
  )
end.run_action(:create_if_missing)

data_dir_hash = ::Digest::MD5.hexdigest(::File.read(::File.join(www_root, 'data', 'DATA.php')))
data_dir = ::File.join(www_root, 'data', "_data_#{data_dir_hash}", '_default_')

template ::File.join(data_dir, 'foo.php') do
  source 'rainloop/salt.php.erb'

  variables(
    iterations: 3
  )
end
```

**Comment by axos88** [comment]
salt.php.erb:
```
<% require 'digest' %><?php //<%= (0...@iterations).map { Digest::MD5.hexdigest(Time.now.to_f.to_s) }.join %>
```

**Comment by RainLoop** [comment]
OK, I will remove md5 suffix in folder name.

Example:
`./data/_data_/_default_/configs/application.ini`

**Comment by axos88** [comment]
The Md5 suffixes are still there. Is this a configuration option?

**Comment by RainLoop** [comment]
@axos88 

Its for backward capability.
There is no suffix for new installations.

Try to remove suffix and delete `DATA.php` file.

**Comment by axos88** [comment]
Ah got it. The website still docuemnts the old way: http://www.rainloop.net/docs/configuration/

**Comment by lucky-sideburn** [comment]
https://github.com/lucky-sideburn/chef-rainloop chef cookbook
