### ISSUE TITLE
Calendar component

### ISSUE THREAD

**Issue by axos88** [RainLoop/rainloop-webmail#716]
Please add a calendar component so that it is possible to select a date on the settings menu

**Comment by tmcb82** [comment]
I know the premise of rainloop is to not require an mysql database. However, I really like this idea and if it could be made to be an optional feature like saving contacts (which does us mysql). Just my opinion.

**Comment by axos88** [comment]
?.. what has this to do with mysql?

To clear things up: I was referring to a datepicker component.

**Comment by alibedog** [comment]
where it ? where calendar man? Now 11 Nov!
