### ISSUE TITLE
Domain is not allowed

### ISSUE THREAD

**Issue by Squeeezeee** [RainLoop/rainloop-webmail#720]
Hello,

I did add domain to my domains and i tested SMTP and IMAP, i even added users in whitelist... But still says domain is no allowed..
.
Please advise...

**Comment by tmcb82** [comment]
Do you have any add=on/extensions enabled?

**Comment by TheLegionStudio** [comment]
Hello, I do not have anything enabled

**Comment by tmcb82** [comment]
Do you have a default domain set under the login tab in the admin interface?
