### ISSUE TITLE
[enhancement] allow admin to select default preferences for new users

### ISSUE THREAD

**Issue by naox** [RainLoop/rainloop-webmail#726]
[enhancement] allow admin to select efault preferences for users. Store per user preferences only those that user has manualny change not to reflect default.

**Comment by RainLoop** [comment]
Already supported in the configuration file.

```ini
[defaults]
view_editor_type = "Html"
view_layout = 1
view_use_checkboxes = On
autologout = 30
show_images = Off
contacts_autosave = On
mail_use_threads = Off
mail_reply_same_folder = Off
```

**Comment by fgiorlando** [comment]
It would also be great if default sieve rules could be set.
This is really useful for setting a SPAM level that the user can then change, or a default vacation message.

Another setting that would be good would be default system folders and a default CardDAV server.  These will all be fairly standard on installs for groups of users.
