### ISSUE TITLE
global search - in multiple folders

### ISSUE THREAD

**Issue by anwfr** [RainLoop/rainloop-webmail#73]
Hi,
Using rainloop connected to an imap server having with multiple mail folders, so far so good...
My only concern is I didn't find a "global search" option, to search mails in all folders.
The search input only searches for mail in current folder.
Did I miss something?

Thx

**Comment by zeigerpuppy** [comment]
I have global search implemented with solr on dovecot, http://wiki2.dovecot.org/Plugins/FTS
It works with roundcube

However, global search does not work in rainloop.  Is there any further info on how to configurethis?

**Comment by zeigerpuppy** [comment]
It's been a long time since the uservoice voting, this feature came up number 3.
Is there plans to implement search in subfolders?
It should be relatively easy to query the IMAP server for FTS support and then use the server-side search results.  This implementation works well with dovecot: http://wiki2.dovecot.org/Plugins/FTS/Solr

Then the heavy lifting is done server-side.
Happy to test if there's a config example for this.

**Comment by zeigerpuppy** [comment]
Bumping this request.  We're wondering if there's any plans to implement search in subfolders?  
There were 825 votes for this feature. https://rainloop.uservoice.com/forums/223477-ideas-for-rainloop-webmail/suggestions/6198273-global-search-in-all-folders

It's really the only feature preventing rainloop being a complete solution for users.

**Comment by madpsy** [comment]
I too would like to use server side full text search.

**Comment by zeigerpuppy** [comment]
Is there any plan to implement search across multiple folders?

**Comment by novadeviator** [comment]
:+1: this would be really necessary. implementation serverside is ok.

**Comment by wbob** [comment]
because it hasn't been mentioned yet: if you run Dovecot, you can use its [virtual](https://wiki2.dovecot.org/Plugins/Virtual) mailbox feature to create a unified folder to be searched in. It's a few config lines and creation of a dovecot-virtual file describing which folders to exclude after a wildcard match. Rainloop has no problem searching this.

**Comment by wbob** [comment]
Dovecots wiki has it explained well, but here it goes
```
/etc/dovecot/conf.d
├── 10-mail.conf
└── 15-mailboxes.conf
```
append after the inbox namespace in `10-mail.conf`:
```
namespace {
  prefix = virtual/
  separator = / 
  location = virtual:/path/to/user/Maildir/virtual
}
```
add within namespace inbox in `15-mailboxes.conf`:
```
  mailbox virtual/All {
    special_use = \All
  }
```
edit `/path/to/user/Maildir/virtual/all/dovecot-virtual` to your needs:
```
*
-Trash
-Trash/*
-Junk
-Junk/*
-Drafts
-Drafts/*
  all
```
restart dovecot, go to rainloops `/#/settings/folders` and subscribe to the special IMAP folder,
select it and have at best dovecot-solr/-elasticsearch as its search backend
![subscribe-all](https://user-images.githubusercontent.com/8349171/44174705-37906e00-a0e4-11e8-9d44-534ce2e3fb50.png)

**Comment by novadeviator** [comment]
I'm using virtual mailboxes, so I added to `10-mail.conf`:

```
mail_plugins = $mail_plugins virtual

namespace {
  prefix = virtual/
  separator = /
  location = virtual:/var/mail/vmail/%%d/%%u/mail/virtual
}
```
uncommented in `15-mailboxes.conf` inside `namespace inbox {`:
```
namespace inbox {
  # [......]
  # If you have a virtual "All messages" mailbox:                                                                                                                                                                                                                         
  mailbox virtual/All {
    special_use = \All
    comment = All my messages
  }
}
```

I the created a folder in /var/mail/vmail/domain.com/user/mail/ called `virtual` and within it a folder called `All`. I put a `dovecot-virtual` in there with above foldernames to exclude. The important part was the foldername with capital A. After I renamed virtual/all to virtual/All, I was able to subscribe to it and then seen all my messages in it and tried full-text search in it and it worked (it took about 20seconds to text-search in 10.000 messages - it's a small 1CPU 5$ droplet on digital ocean)

However I'm not sure if I'm using elastic search. Probably not. There's a dovecot-solr package in ubuntu, does this enables it? (Apologies for the noob question)

Also, (and I know, I'm hijacking the thread for dovecot configuration questions, sorry!), how can I enable virtual/All folder for everyone on the system? There's probably conf file for newly created mailbox where it can be included, but for already existing users? Manualy creating that folder?

**Comment by wbob** [comment]
thread hijack for documentation purposes might be tolerable? I forgot mentioning the mail_plugin and edited it in, thanks. Check out the dovecot [wiki](https://wiki.dovecot.org/Plugins/FTS/Solr) for dovecot-solr, it has dependencies on java (openjdk-8-jre-headless) and solr itself (solr-common): there must be guides online. It's either solr or elastic. Once indexed in any of these, it's a subsecond search over 10k+ messages.

Dovecot has a `subscriptions` file in the users Maildir, you can append the virtual folder there. For your specific case-sensitive example it is `echo "virtual/All" >> /var/mail/vmail/domain.com/user/mail/subscriptions`. With variables a `for user in $(); do ..; done` could handle this for many.
