### ISSUE TITLE
generating GPG keylength

### ISSUE THREAD

**Issue by punkkeks** [RainLoop/rainloop-webmail#736]
There is a dropdown menu, where you can select the keylength of your key to generate.
    
    1024 is "insecure" in terms of, that new keys should have 2048 or more bits 
    ^--- this option should be remove
    2048 is fine
    ^--- leave this
    4096 bits is missed
    ^--- this should be added to the drop down

**Comment by RainLoop** [comment]
Ok, it will be available in the next version.
