### ISSUE TITLE
Compose HTML Emails

### ISSUE THREAD

**Issue by spongemon** [RainLoop/rainloop-webmail#74]
Hi,

Is it possible to send HTML emails from Rainloop? If not, do you guys plan to make this feature available?

Thanks.

**Comment by Vladimirtishenko** [comment]
When I pushed the button nothing happened. How can I send HTML template?? 
<img width="998" alt="Screenshot 2020-10-29 at 12 22 24" src="https://user-images.githubusercontent.com/12623368/97555951-75d28900-19e1-11eb-9002-169751a62e3a.png">
<img width="1003" alt="Screenshot 2020-10-29 at 12 22 34" src="https://user-images.githubusercontent.com/12623368/97555960-7834e300-19e1-11eb-912e-7ecd2d024c22.png">
