### ISSUE TITLE
json link to versioned owncloud packages ?

### ISSUE THREAD

**Issue by shiznix** [RainLoop/rainloop-webmail#753]
Hi,

The following are URLs to community and standard edition files containing versioned tarball links:
http://repository.rainloop.net/v2/core.open.json
http://repository.rainloop.net/v2/core.stable.json

Are there json URLs containing the tarball versions to the owncloud packages?

Thanks.

**Comment by RainLoop** [comment]
http://repository.rainloop.net/v2/owncloud.open.json
http://repository.rainloop.net/v2/owncloud.stable.json
