### ISSUE TITLE
No preview for JPEG attachment

### ISSUE THREAD

**Issue by ervee** [RainLoop/rainloop-webmail#754]
Hi,

I have an email with a JPEG attachment which does not show a preview. GIF attachments do and JPEG did work in the past as far as I can remember.

I'll send you an EML of such email.

**Comment by RainLoop** [comment]
Interesting, but i don't understand why it does not work :(

**Comment by ervee** [comment]
Did the Eml work with preview on your test setup?

**Comment by RainLoop** [comment]
Yes, everything's fine, except preview.

**Comment by RainLoop** [comment]
I see the problem, but I do not understand how it can be solved.

**Comment by RainLoop** [comment]
https://github.com/RainLoop/rainloop-webmail/blob/master/rainloop/v/0.0.0/app/libraries/RainLoop/Actions.php#L8337

`$oThumb =@ new \PHPThumb\GD($sFileName);` require file $sFileName.

I save imap stream to the memory (\MailSo\Base\StreamWrappers\TempFile) and give file name to lib.

Something wrong with my temporary file stream. 
Everything works correctly if I save email attachment in real file.
