### ISSUE TITLE
[Feature] Keybase.io integration

### ISSUE THREAD

**Issue by jelle-e** [RainLoop/rainloop-webmail#760]
Hi,
You know https://keybase.io? It's a public server for people to use their pubkeys with. You can use their API to encrypt/decrypt/sign you messages with. Also you can easily search for others and their pubkeys.
How great would it be to integrate that behaviour in RainLoop to be able to just typ someone's name and find his/her pubkey and encrypt your message. Userfriendly and easy! :)

Well, I just thought I'd let you know about it. Just take a look at it and maybe you find some way to integrate in RainLoop someday. Thanks.

**Comment by jelle-e** [comment]
Just to add:
https://keybase.io/blog/2015-07-15/keybase-raises-series-a

**Comment by RainLoop** [comment]
Maybe later, now it still in private beta.
