### ISSUE TITLE
Autologin does not work on owncloud 8.1

### ISSUE THREAD

**Issue by farson2003** [RainLoop/rainloop-webmail#763]
Hello.
Nice.
But:
Everytime I log out of owncloud I have to reenter my email credentials to Rainloop.

Why is he not saving my credentials? ( I am using a custom server, not google or yahoo...)
Thx

**Comment by jelle-e** [comment]
Probably because your credentials of ownCloud are not the same as your email.
Set both email and owncloud accounts with the same loginname AND password and it will work.

**Comment by farson2003** [comment]
@jelle-e  Thank you.

Well that is a problem, as most users need to login to Rainloop with different credentials than owncloud.
Is there no workaround?

**Comment by jelle-e** [comment]
Well, as stated here: https://github.com/RainLoop/rainloop-webmail/issues/481
Admin / RainLoop Webmail/
Disable "Automatically login with ownCloud user credentials"

Maybe that solves your problem?

You can also load the RainLoop module full screen (so outside owncloud) by creating a symlink to the module in the root webdir of owncloud.
You get something like:
https://myowncloud.com/webmail
(when having the RainLoop module symlinked to 'webmail' in the root webfolder)

**Comment by ERamseth** [comment]
Another option may be to setup IMAP login backend for owncloud.

**Comment by farson2003** [comment]
@jelle-e 
That solved the problem, thank you: Well, as stated here: #481
WOuld be good to have that in the documentation though, as more users seem to struggle here...
