### ISSUE TITLE
[suggestion] Hide menu (or parts of menu) and username when integrated with owncloud

### ISSUE THREAD

**Issue by ERamseth** [RainLoop/rainloop-webmail#768]
Not sure how hard this could be, but (optionally) hiding the top right menu (or at least the logout button) and the username when integrated with owncloud would make the overall experience more cohesive. With these items showing, it feels a lot more like rainloop inside a frame. Also, with auto-login from owncloud, I'm not sure how logging out would work. 

In the attached image, I'm suggesting an option to hide the items I've highlighted in green boxes.

![untitled](https://cloud.githubusercontent.com/assets/2932353/8860364/5826fa72-3151-11e5-9762-19e044b56869.png)

**Comment by ERamseth** [comment]
In order to hardcode some changes, I tried to edit files in [owncloud]apps/rainloop/app/rainloop/v/1.9.2.343/app/templates/Views/User but the changes didn't seem to be reflected in production.

**Comment by RainLoop** [comment]
Try to clear RainLoop cache folder.

`./data/_data_/_default_/cache`

**Comment by ERamseth** [comment]
Clearing ./data/_data_/_default_/cache broke logins completely. tried a full reinstall and it's completely broken now.

**Comment by RainLoop** [comment]
Did you delete `cache` folder?

**Comment by ERamseth** [comment]
No. Just the contents.

**Comment by ERamseth** [comment]
So I reinstalled then made changes before activating and it worked ok. Tried to roll back my changes by editing files and clearing the cache. Same thing happened. Can no longer login. It's not failing at login saying my password is bad or anything. It's just bringing me back to the login screen after taking me to the loading screen.

**Comment by ERamseth** [comment]
Been playing with this all morning. More often than not when I make any changes to the files in [owncloud]apps/rainloop/app/rainloop/v/1.9.2.343/app/templates/Views/User and delete the cache I end up breaking something and can't login. A for effort? F for outcome.

Feel free to delete all this rambling and consider this an enhancement request.

**Comment by RainLoop** [comment]
I'm sorry for the delay.

You are using ownCloud and rainloop data folder stored in the ownCloud data storage.

RainLoop's cache folder
`./data/rainloop-storage/_data_/_default_/cache`
