### ISSUE TITLE
Desktop notifications are not shown with Firefox on linux

### ISSUE THREAD

**Issue by purejava** [RainLoop/rainloop-webmail#770]
The setting to show desktop notifications (dn) in the preferences of rainloop is set.
dn are also allowed for the site rainloop is installed on.

When I receive a new mail, it plays the sound but no dn is shown. The system is an Arch linux 64bit machine with Gnome 3 and Firefox 39.0. rainloop is v1.9.2.343 (05.07.2015).

dn itself is working with the same browser on the same system, as the test button on this page shows the dn: https://developer.mozilla.org/de/docs/Web/API/notification

I made a cross test and dn do work on Firefox for Windows. To verify, that this is no issue with my system, I installed Kubuntu 15.04 into a VM and tested there with the same result: dn work, but not with rainloop. Firefox there is 37.x.

I wonder why nobody else seems to have this problem.
Could somebody please confirm this?

Cheers,
Ralph

**Comment by megadr01d** [comment]
I can confirm that they're not show in Firefox, Windows 7, either. The button on your link is also glitchy. I have to click on it a number of times in succession for it to work, but then multiple notifications appear in a jerky motion and the browser gets slow as hell.

**Comment by purejava** [comment]
With the new notifications that came with FF 44 new mail is notified again.
So I am closing this issue.
