### ISSUE TITLE
arabic support - ar.ini

### ISSUE THREAD

**Issue by COLORLINK** [RainLoop/rainloop-webmail#771]
rtl... how can i make the whole website right to left... like which files to edit ?
also i got arabic language translated and ready to use.. in case you want to add it in. 
ar.ini

https://drive.google.com/file/d/0BzmWSIfjTdc1SG9YOUhGb29iX3M/view?usp=sharing

**Comment by COLORLINK** [comment]
add to that .. there should be a way to make the website returns back to ltr in case of choosing en...
i think this wouldnt take much of work using direction:rtl;; can you help me out plz... tyvm

**Comment by RainLoop** [comment]
Thanks for a language file.

Unfortunately, RTL interface does not work correctly right now.
I can accept you file, but it is not a great idea.

**Comment by COLORLINK** [comment]
okay. can you add the flag plz. and thanks
