### ISSUE TITLE
reCaptcha not showing on login page

### ISSUE THREAD

**Issue by quatroweb** [RainLoop/rainloop-webmail#772]
I tried to install the reCaptcha package into Rainloop and it installed perfectly. But when trying to login to the webmail it says: Incorrect CAPTCHA verification.

There is no Captcha shown in at the login page, even though it's already enabled in the admin panel.

Have made 3 installation tests to see if it was a problem with the installation, but doesn't seem like that's the problem.

Any ideas?

**Comment by megadr01d** [comment]
Just a wild guess but are you using an ad blocker (although a good rule set shouldn't block captchas)?

**Comment by COLORLINK** [comment]
change browser and test it again

**Comment by RainLoop** [comment]
I have tested it on a demo installation:

![rec](https://cloud.githubusercontent.com/assets/5530092/8914093/e525f8ea-34a5-11e5-9fd2-c5c8fbf3932c.png)

You may try, just enter your email with incorrect password.

**Comment by hadifarnoud** [comment]
I have the same issue @RainLoop. you can test it on https://email.kamva.ir

**Comment by RainLoop** [comment]
@hadifarnoud Have you entered reCaptcha's site code?

**Comment by hadifarnoud** [comment]
I did not see any reCaptcha config to set. Can I do it manually now?

**Comment by RainLoop** [comment]
![image](https://cloud.githubusercontent.com/assets/5530092/22182642/6287dbec-e0bb-11e6-89d4-088cbfd8723d.png)

**Comment by hadifarnoud** [comment]
oops how did I miss that. now, can I do it manually? or I have to remove (or rename?) the plugin to disable it?

**Comment by hadifarnoud** [comment]
I removed this plugin by doing:
```
mv _data_/_default_/plugins/recaptcha/ ~
mv _data_/_default_/configs/plugin-recaptcha.ini ~
```
and I removed recaptcha plugin from application.ini 

but now, it says authentication failed. I'm quite sure I did not change the password for `admin` account. I can't login as regular user either

**Comment by hadifarnoud** [comment]
disregard my comments. It turns out I have to use `http://webmail.domain.com/?admin ` for admin logins

**Comment by ESVDESIGNER** [comment]
you can change the ?admin by editing the application.ini,

change admin_panel_key to any name you like and change "admin" to the new value in the url
