### ISSUE TITLE
PHP Mailer does not create a correct header

### ISSUE THREAD

**Issue by enricocanino** [RainLoop/rainloop-webmail#774]
Hi all,

I am using Rainloop webmail for Owncloud and It is great. Version 1.9.1.333

Unfortunately a lot of sent email are marked as spam.

In my opinion it is because Rainloop creates the header using a system user instead of the effective sender.

Following an header example:Return-Path: <xyz@mydomain.mytld> <----- this is a SYSTEM USER NOT THE SENDER
Delivered-To: info@recipient.tld <---- this is the correct rcpt to
To: info@recipient.tld <---- this is the correct rcpt to
Subject: Test1
X-PHP-Originating-Script: 10000:Actions.php
Mime-Version: 1.0
Date: Mon, 27 Jul 2015 16:03:30 +0000
Content-Type: multipart/alternative;
 boundary="----=_Part_203_468685435.1438013010"
Message-ID: <1a1992348552493bbf75b08a1231777d@cloud.copiearchivi.it>
X-Mailer: RainLoop/1.9.1.333
From: "Enrico Canino - Multisoft Srl" <foo@foo.com> <--- this is the correct sender

Best regards and thanks in advance for any suggestion.

**Comment by RainLoop** [comment]
Hi Enrico Canino,

RainLoop doesn't add `Return-Path` header in messages at all.

Do you use php mail function?
If yes, you may need to configure it in `php.in` configuration file.

**Comment by enricocanino** [comment]
Yes I use php mail function...

What I have to configure in php.ini?

Thanks in advance.

**Comment by RainLoop** [comment]
Unfortunately I cann't help you here. It depends on many factors.

You may also try next:
`./data/rainloop-storage/.../configs/application.ini`

```ini
[labs]
mail_func_additional_parameters = On
```

Using mail function is not a great idea for outgoing messages.

**Comment by enricocanino** [comment]
I would like to use smtpinstead of php mail, but many of my domains uses a specofic user to access auth smtp and not the same email user. This may be a suggestion for future implementation.

Best regards.
