### ISSUE TITLE
error host imap

### ISSUE THREAD

**Issue by incorpore** [RainLoop/rainloop-webmail#775]
![rainloop](https://cloud.githubusercontent.com/assets/10521792/8915676/c80ec490-347c-11e5-8413-6e7fa12bafc4.png)
Hello, I am having difficulty connecting imap, always of an error.
Can anyone help me?
thanks

**Comment by incorpore** [comment]
Recalling that the hosting is shared Hostinger

**Comment by davbaumgartner** [comment]
It doesn't seem to be related to Rainloop but to your server's configuration.

-> are your SSL certificates up-to-date ?
-> could you run `nmap -p 993 mx1.hostinger.com.br` to check you have access to this server ?
