### ISSUE TITLE
[enhancement] replying to a msg in sent folder

### ISSUE THREAD

**Issue by naox** [RainLoop/rainloop-webmail#780]
When replying to a msg in set folder To: adres should be set to same as message you are replying, not your own adress. Its pretty sure that you don't want to reply to yourselt but actualy add to add something to a thread (send to recipients). Its done so in gmail for example.

**Comment by modir** [comment]
In the mail clients I know you would have to press "reply all" and then you get what you want. The correct thing happens then because my own email address is then taken out automatically. Maybe this solution works as well for you?

**Comment by megadr01d** [comment]
Also discussed in https://github.com/RainLoop/rainloop-webmail/issues/828 and @modir has the right answer. You should reply all or always reply to the original message, not your own reply.

**Comment by naox** [comment]
"reply all" also puts my own email in To field which requires me to manualy remove it. Also it requires additional click do get to this option and especialy it is counter inutitive so nobody will guess to use it for that.

```
You should reply all or always reply to the original message, not your own reply.
```
How about situation when there is no original message. Example: you just sent message to someone but 5 minutes later you want to send another one that will be in the same thread on receiver end and will contain original message.

All comercial email services now allow replying to your own message to send message to original recipient (including gmail of course).
