### ISSUE TITLE
Google doc viewer as offline

### ISSUE THREAD

**Issue by COLORLINK** [RainLoop/rainloop-webmail#781]
hi.. i installed rainloop on local machine with local network . the only pc can get internet is the local server which have rainloop on it. 
. 
enabled google viewer integration . 
but the docs wouldn't get previewed what ever i try .. 
any solution for that?
waiting your replay . ty 
as a local server.. it cant have a public domain. so it doesnt have .com or ,net or or or...
and by that.. i cant do integration with google.
how ever i got an online server .. diff from this one. 
any one can help plz?
ty

if all that not possible.. is there an alternative for google docs viewer that i can host localy and integrate it with rainloop?

**Comment by RainLoop** [comment]
Unfortunately, it is Google viewer limitation.
it works only with external web sites. 

I didn't hear about solutions that work locally.

**Comment by COLORLINK** [comment]
U might use google extention in google chrom..
https://chrome.google.com/webstore/detail/office-editing-for-docs-s/gbkeegbaiigmenfmjfclcdgdpimamgkj?hl=en
It works offline.. u need to open file using google chrom.. but how to tell the view to auto open it there ?.
