### ISSUE TITLE
reconfigure two authent

### ISSUE THREAD

**Issue by ouafnico** [RainLoop/rainloop-webmail#782]
Hello

anyway to start again the wizard to configure two authent mode?
After a reset of the google auth app, I need to rescan the clearcode, but I can't ask rainloop to reconfigure it.

Any way to do it ?
Thanks

**Comment by RainLoop** [comment]
You may reconfigure it after pressing clear button.

![clearga](https://cloud.githubusercontent.com/assets/5530092/9121610/118e1532-3c8c-11e5-8567-69ae00bfc2fb.png)

**Comment by ouafnico** [comment]
where is this window on admin panel? I didn't find it. thanks

**Comment by RainLoop** [comment]
This is a configuration section of user.
Why are you looking for it in the admin panel?

**Comment by ouafnico** [comment]
because I can't find it in the user section ;s I guess when I disable the two authent in admin section, the panel disapear on user configuration? If yes i'm stuck my google authenticator is reset, so I can't login in user section with two authent

**Comment by RainLoop** [comment]
Ok, I understood you.

You should do it manualy.
Just delete `two_factor` file in the data folder.

Example for `test@rainloop.de` email: 
`./data/_data_/_default_/storage/cfg/te/test@rainloop.de/two_factor`

**Comment by ouafnico** [comment]
Nice this is good :-) thanks ;)

**Comment by DjDOESIT** [comment]
Hello,

I have the same problem, but the removal of two_factor file does not allow me to re-scan the QR to use 2-step auth.
He always asks me the code of google auth.

I reinstall google auth so I have not the generated code.

Thank you in advance.

**Comment by DjDOESIT** [comment]
I solved my problem by connecting me with my account with at off 2-step advance and leaving a window in my active account, I go to the admin account and I reactivated "2-step" and I reloaded the page of my normal account, and the security parameters I could "clear" and reconfiguring my Google auth ...


Thx
