### ISSUE TITLE
rainloop in owncloud: can I use the postfixadmin Plugin?

### ISSUE THREAD

**Issue by stefkey** [RainLoop/rainloop-webmail#785]
Hi,

can i use the postfixadmin plugin in a owncloud rainloop app?
https://github.com/RainLoop/rainloop-webmail/search?utf8=%E2%9C%93&q=postfixadmin

How can I install it?

thanks al lot, stefkey

**Comment by RainLoop** [comment]
You should copy this plugin to RainLoop data folder.

`https://github.com/RainLoop/rainloop-webmail/tree/master/plugins/postfixadmin-change-password`
->
`./data/rainloop-storage/_data_/_default_/plugins`

Then you need to config it in the admin panel.

**Comment by stefkey** [comment]
Oh thanks a lot. It works. Many thanks!
But I have save the passwords as md5, not md5crypt. Is there another script for md5?

**Comment by RainLoop** [comment]
> Is there another script for md5?

What did you mean? I do not understand your question.

![postfix](https://cloud.githubusercontent.com/assets/5530092/9123383/d101b792-3c97-11e5-95dc-b81b1da1af5d.png)

**Comment by stefkey** [comment]
Oh sorry. I did not see the pull down menu. There are already md5. Sorry and thanks for the fast support. I love RainLoop!
