### ISSUE TITLE
UTF-8 encoded searching

### ISSUE THREAD

**Issue by davelima** [RainLoop/rainloop-webmail#793]
Hi!

When using the search box with any accented letter (like á, é, ã õ, etc.), I get a `Can't get message list` error message.

Example:
Searching `from: joão` return a error, but searching by `from: joao`, everything is ok.

PHP 5.6 on Debian 8.1 Jessie

Also, this is my first time contributing here, so, if this issue is confirmed, I'll like to pull a fix to it :)

**Comment by RainLoop** [comment]
Hi @davelima, 
What is your mail server?

**Comment by davelima** [comment]
@RainLoop I'm using Gmail and Outlook.com servers (two separated accounts)

**Comment by RainLoop** [comment]
Thanks, fix will be available in the next release.
