### ISSUE TITLE
Are there any limitations to the 'unread message' indicators on folders?

### ISSUE THREAD

**Issue by greg-1-anderson** [RainLoop/rainloop-webmail#794]
I have installed RainLoop on a server where there are two email users: myself and my wife.

When my wife logs in to RainLoop, each of her folders has an indicator of how many unread messages each one contains.  In contrast, when I log in to RainLoop, I get a message count on my "Drafts" folders, but the rest of the folders are missing this item. After I click on a folder, the unread message indicator for that folder shows up.

Are there any limitations on the generation of this display? Does it perhaps time out if the counting operation takes too long?  I marked all of the messages in every folder as "read", but it didn't help; maybe the total size of my folders is too high?

Any advice on how I might tune things so that this feature works?

**Comment by RainLoop** [comment]
Yes, RainLoop has some optimizations for your case.

Check this link: https://github.com/RainLoop/rainloop-webmail/issues/611

**Comment by greg-1-anderson** [comment]
OMG that is fantastic. I turned a bunch on, and now it is working as expected. I love that I can leave junk folders that I don't care about unchecked.  Not sure why these all started as disabled for me, but were enabled for my wife, but it works great for me now.

I just need to figure out how to fix #693 (which seems to work for most people), and I'll be able to switch to Rainloop for my primary mail client.  Thanks!

**Comment by RainLoop** [comment]
You're welcome :)
