### ISSUE TITLE
Contributing documentation

### ISSUE THREAD

**Issue by greg-1-anderson** [RainLoop/rainloop-webmail#795]
c.f. #692.

**Getting started**
1. Install node.js - `https://nodejs.org/download/`
2. Install gulp - `npm install gulp -g`
3. Fork rainloop - https://github.com/RainLoop/rainloop-webmail/issues/new#fork-destination-box
4. Clone rainloop - git clone git@github.com:USERNAME/rainloop-webmail.git rainloop
5. `cd rainloop`
6. Install gulp into project directory - `npm install gulp --save-dev`
7. Add gulp plugins - `npm install`
8. Run all gulp tasks - `gulp build`

This is pretty close, but I get an error:
`Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 51.0`

Maybe I am missing a build step, to set an appropriate version number for the build I am making?

**Comment by RainLoop** [comment]
Thanks!

> This is pretty close, but I get an error:
> `Exception in thread "main" java.lang.UnsupportedClassVersionError: `
> `com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 51.0`

Something wrong with `google closure compiler`. You may comment it in `gulpfile.js`:

```js
gulp.task('js:lint', function() {

	var
//		closureCompiler = require('gulp-closure-compiler'),
		jshint = require('gulp-jshint')
	;

	return gulp.src(cfg.paths.globjs)
		.pipe(jshint('.jshintrc'))
		.pipe(jshint.reporter('jshint-summary', cfg.summary))
		.pipe(jshint.reporter('fail'))
		// google compiler
//		.pipe(closureCompiler({
//			compilerPath: './build/compiler.jar',
//			fileName: 'gc.js',
//			compilerFlags: {
//				output_wrapper: '(function(){%output%}());'
//			}
//		}))
	;
});
```

**Comment by greg-1-anderson** [comment]
Thanks for the workaround; I'll try it out tonight, and see if I can make more forward progress.  Is there a separate issue or PR for this defect?

I was going to offer to make a PR for CONTRIBUTING.md, but I see you already put this in. Thanks!

**Comment by greg-1-anderson** [comment]
Thanks for the above; I now have a working local dev environment.  <3
