### ISSUE TITLE
[Urgent] Newest version 1.9.2.351; can't login anymore!

### ISSUE THREAD

**Issue by jelle-e** [RainLoop/rainloop-webmail#796]
Hi,
Just upgraded the owncloud-rainloop module through webinterface. No problems there.
Now, loading the webmail from owncloud, I can't login anymore!
First question; how can I roll back to previous release? (so my users can login again)

I looked in logfiles, but nothing special there. Tests on connecting to mailbackend and mysql database are fine. Any idea what might be happening?

**Comment by jochen35** [comment]
Hi,
I have the same problem Rainloop 1.9.2.351 and ownCloud 8.1.1. According Rainloop log there are no problems, but the login is not working. It is no error message and almost seems that the frontend will simply not load.

greeting
Jochen

**Comment by RainLoop** [comment]
What is your previous version?

**Comment by jelle-e** [comment]
previous: 1.9.2.343
(I have another (stand-alone) instance of rainloop running at 1.9.2.343 that still works.

**Comment by RainLoop** [comment]
1.9.2.343 - 
Stand-alone standard: http://repository.rainloop.net/v2/webmail/1.9.2/rainloop-1.9.2.343-b21276cc22a92698f5813079b046334c.zip
Stand-alone community: http://repository.rainloop.net/v2/webmail/1.9.2/rainloop-community-1.9.2.343-1579e1f742ef7a4fa87e55c201416e30.zip

**Comment by RainLoop** [comment]
Owncloud packages 4.4 - 
Stand-alone standard: http://repository.rainloop.net/v2/other/owncloud/4.x/rainloop-owncloud-app-standard-4.4-f2dcd69f18ed220ef0818e545fbcbb3a.zip
Stand-alone community: http://repository.rainloop.net/v2/other/owncloud/4.x/rainloop-owncloud-app-4.4-45039d76e0770b24f356f5c6f7ab2cc8.zip

**Comment by jelle-e** [comment]
okay, replacing owncloud package with 4.4 standard fixed the issue for now. Thx. I'll wait for a fix. :+1:

**Comment by RainLoop** [comment]
You may try 4.5 version: 
http://repository.rainloop.net/v2/other/owncloud/4.x/rainloop-owncloud-app-standard-4.5-a2871360dc8588715c37693c10edcec5.zip

**Comment by jelle-e** [comment]
so, what's this versioning about? I don't really understand the difference between 4.5 and 1.9.2.351 releases. Does the 4.5 package release contain rainloop 1.9.2.351 or is it something else?

**Comment by RainLoop** [comment]
Owncloud package 4.5 = owncloud app plugin 4.5 + rainloop 1.9.2.351 (complete package, you don't need install RainLoop separately)

It isn't the same as stand-alone version of RainLoop Webmail.

**Comment by jelle-e** [comment]
okay, I understand thx.
So the package 4.5 is something different then my rainloop owncloud-app installation that I upgraded every time to newest version through webinterface? That's where this might have gone wrong? Using an old version (<4.5) of the owncloud app in combination with newest Rainloop?

**Comment by RainLoop** [comment]
Yes, from 4+ version owncloud package has different logic for work.
It contains RainLoop Webmail, so you no need to configure paths to standalone RainLoop.

**Comment by jochen35** [comment]
@RainLoop 
"You may try 4.5 version:
http://repository.rainloop.net/v2/other/owncloud/4.x/rainloop-owncloud-app-standard-4.5-a2871360dc8588715c37693c10edcec5.zip"

Is that the official or a customized version?

**Comment by RainLoop** [comment]
Today I fixed a few bugs. Please, try to update and check the issue.

http://www.rainloop.net/downloads/
versions:
OwnCloud - 4,6
RainLoop - 1.9.2.353

**Comment by jelle-e** [comment]
Works great! Thanks. I can login again with 4.6 (1.9.2.353)

**Comment by RainLoop** [comment]
good, thanks for an issue :)

**Comment by prilly** [comment]
Are there any reasons why rainloop owncloud app is not creating an ocsid in database as the rest of the apps? 

It seems if you install the app from your rainloop.net page for owncloud directly, it does not create the ocsid in oc_appconfig (mysql), this can couse problems if you use the app menu inside owncloud to update it later.
