### ISSUE TITLE
What is the URL for the rain video on http://demo.rainloop.net?

### ISSUE THREAD

**Issue by greg-1-anderson** [RainLoop/rainloop-webmail#802]
Is the background video used in the demo page available for use in other Rainloop installations?  If so, what is its URL?

**Comment by 0xACE** [comment]
http://static.rainloop.net/videos/backgrounds/raindrops/raindrops.mp4

**Comment by greg-1-anderson** [comment]
Thanks!

**Comment by szewczyk-it** [comment]
Hi,
why in Rainloop demo now is not video background? And on above URLs I can see ':(' instead of video.
What happened?

**Comment by RainLoop** [comment]
:)

> why in Rainloop demo now is not video background? What happened?

RainLoop goes HTTPS and I have disabled video background.

New URLs:
http://static.rainloop.net/videos/backgrounds/raindrops/v.mp4
http://static.rainloop.net/videos/backgrounds/raindrops/v.webm
http://static.rainloop.net/videos/backgrounds/raindrops/v.ogv

**Comment by szewczyk-it** [comment]
Ooo, many thanks! :)

**Comment by nook24** [comment]
@RainLoop can you please add license informations for the videos ? :)

**Comment by fernandokosh** [comment]
+1 Would like to use this for my RainLoop login as well :)

**Comment by RainLoop** [comment]
> +1 Would like to use this for my RainLoop login as well :)

@fernandokosh Use it with "Snowfall on login screen" plugin:

https://static.rainloop.net/videos/backgrounds/raindrops/v.mp4
https://static.rainloop.net/videos/backgrounds/raindrops/v.webm
https://static.rainloop.net/videos/backgrounds/raindrops/v.ogv

> @RainLoop can you please add license informations for the videos ?

@nook24 Sorry, but it was 2 years ago. So, If you will see the source of this video, please tell me.

**Comment by plett** [comment]
@nook24 @RainLoop It looks like this is the original source of the video: http://www.beachfrontbroll.com/2014/10/FreeStockFootageofRaindrops.html

The bottom of that page says it's licensed under CC:BY 3.0

**Comment by diederikbemmel** [comment]
How can i add any mp4?

**Comment by djdill** [comment]
@diederikbemmel 

https://yourserver/rainloop/?admin

Find packages
Fullscreen background video on login screen.

Find plugins, enable the plugin for video
Then configure and add your own mp4 url

**Comment by nook24** [comment]
@plett thanks buddy
