### ISSUE TITLE
How is the "Packages" config panel populated?

### ISSUE THREAD

**Issue by greg-1-anderson** [RainLoop/rainloop-webmail#806]
Have you considered adding a mechanism for third-party plugins?  Or should they be submitted a pull requests and added to the rainloop-webmail/plugins folder?

c.f. https://github.com/greg-1-anderson/rainloop-count-down-the-days

**Comment by greg-1-anderson** [comment]
I have started another third-party plugin:

https://github.com/greg-1-anderson/rainloop-gallifreyan

Both of these plugins are still 'beta' quality at the moment, but putting this here for reference.

**Comment by RainLoop** [comment]
Fast answer is:
```
http://repository.rainloop.net/v1/repository.json
```

If you consider that your plugin should be in the main repository, you may create a pull request.

But this does not mean that I'll merge it in :).

**Comment by greg-1-anderson** [comment]
I'll submit a PR for count-down-the-days after it supports multiple dates.  You probably do not need a Gallifreyan quiz in the core plugin repository, though!

In any event, thank you for the answer.
