### ISSUE TITLE
Keeps downloading Index.php file

### ISSUE THREAD

**Issue by luckyrajiv** [RainLoop/rainloop-webmail#808]
Installed Rainloop from using Ajenti and Ajenti V Control Panel.

I keep getting a downloading file when i enter mail.mydomain.com/?admin

**Comment by punkkeks** [comment]
Sounds like a problem with your webserver. This is not an issue with rainloop itself. Just google your problem and you should be able to fix it.

**Comment by luckyrajiv** [comment]
okay. it is working now.  Thanks

**Comment by arcreative** [comment]
@luckyrajiv Usually helpful to tell people how you fixed it :wink:

**Comment by luckyrajiv** [comment]
I am not sure, i was trying so many online forums and tips, to make it work. finally it worked.

ALso, i was adding lots of code in PHP Advanced settings to make it work. but cleared it all , and in Under content>advanced> i have just this inside the WEBSITES section in AJENTI PANEL.

location ^~ /data {
  deny all;
}

and to ReInstall Rainloop i followed DIGITAL OCEAN TUTORIAL.

I hope this helps.

This file downloading problem was occurring for all php based index.php files. i believe it has to do with php settings. I had actually reinstalled the whole server few times to make it work.
