### ISSUE TITLE
Support for Mailadresses with username != address

### ISSUE THREAD

**Issue by pattimaus** [RainLoop/rainloop-webmail#810]
We only have to fields to login: username@domain.tld and password.

But not for every mailservice the username@domain.tld is the username that is beeing used to sign in. 
My university e.g. gives every student ids like abcxyz984 which is used to login, without @domain.tld and without beeing part of the mailaddress.

So in addition to the mailaddress an optional setup is needed where you can specify the username to login, if it differs from the mailaddress.

**Comment by ervee** [comment]
You can. Well, only admin can, but it is possible.

Use the Custom Login Mapping plugin:
![custom-login-mapping](https://cloud.githubusercontent.com/assets/4435930/9378301/995ccdb6-4720-11e5-8da9-c91cb5575ccc.JPG)

And set "Use short login" in the domain configuration.

**Comment by pattimaus** [comment]
I see. That works for me, 
thank you.
