### ISSUE TITLE
Email content is lost in every message

### ISSUE THREAD

**Issue by paulocoghi** [RainLoop/rainloop-webmail#811]
```
Ubuntu 14.04 64bits, HHVM 3.7.3, Postfix 2.11.0, Nginx 1.4.6
MySQL Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.3
```

First, congratulations for all RainLoop creators and community.

In my Rainloop install with 1.9.2.343 and 1.9.2.353 (latest), the body content of e-mail becomes empty.

If I send an email, it is sent but received empty. Or if I save in draft, the saved message also becomes empty. The message content is not saved, it is lost.

1. First I created a new email, insert a content to it and saved in draft or send it.
![compose-screen](https://cloud.githubusercontent.com/assets/378397/9413644/8176717c-4809-11e5-862a-94eef6ca61ae.png)

2. Both the received or draft message lost its content.
![draft-screen](https://cloud.githubusercontent.com/assets/378397/9413647/857fb72e-4809-11e5-856b-2dea571ea30b.png)

3. Opening the original email data, no body content is found:

```
Mime-Version: 1.0
Date: Fri, 21 Aug 2015 16:31:18 +0000
Content-Type: multipart/alternative;
 boundary="--=_RainLoop_248_549824324.1440174678"
Message-ID: <0a78257ba0e45cb9677bf5683d34a8c9@webmail.muraldocoach.com.br>
X-Mailer: RainLoop/1.9.2.353
From: mail@muraldocoach.com.br
Subject: Just a subject
To: "Paulo Coghi" <paulocoghi@gmail.com>


----=_RainLoop_248_549824324.1440174678
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable



----=_RainLoop_248_549824324.1440174678
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: quoted-printable



----=_RainLoop_248_549824324.1440174678--
```

**Comment by RainLoop** [comment]
```
HHVM 3.7.3
```
Try to use the standard PHP, HHVM does not work well in some places.

**Comment by paulocoghi** [comment]
The standard PHP works well. Closing.
