### ISSUE TITLE
Multiple Domain Support using one installation

### ISSUE THREAD

**Issue by luckyrajiv** [RainLoop/rainloop-webmail#812]
Hi,

I have installed Ajenti and Ajenti V as Web Hosting Panel. I have multiple domains added into one single VPS.

Currently i access rainloop via first domain at mail.abc.com, and for email accounts of other domains also i am currently logging in via mail.abc.com

How can i use single installation of rainloop, to serve for each domain separately at their own mail.xyz.com, instead of going to mail.abc.com

**Comment by RainLoop** [comment]
You should create an empty "MULTIPLY" file in the root directory.
It creates configuration directory for each domain separately.

**Comment by luckyrajiv** [comment]
Okay do i have to create this MULTIPLY file in the root directory of rainloop installation.

**Comment by luckyrajiv** [comment]
Under Rainloop Folder, i have data(folder), rainloop(folder) and index.php (3 files), should i add the MULTIPLY Here.

**Comment by ervee** [comment]
RainLoop says: You should create an empty "MULTIPLY" file in the root directory.

**Comment by luckyrajiv** [comment]
where should i put this MULTIPLY file, under root directory of Rainloop or under root directory of each domains under such as mail.123.com, mail.xyz.com etc

If i have to put under Rainloop only. then how do i access mail for other domains, is it under mail.123.com or 123.com/webmail or other.

**Comment by Centaman** [comment]
Insert the file into the root where the file index.php is located.
Inside the "/date/_data_..." folder, duplicate the "_default_" folder by naming it with the domain name

**Comment by Centaman** [comment]
I have a problem, after multi-domain activation if I try to access the admin panel I deny access.
