### ISSUE TITLE
Email addresses are always lower case

### ISSUE THREAD

**Issue by techxplorer** [RainLoop/rainloop-webmail#814]
Hi,

I'm not sure if this is a bug or expected behaviour. I have a web application, based on Moodle, that parses emails that are sent to it. These addresses are case sensitive. 

For example the address in the 'Reply-To:' field in the email sent by the application is as follows:

`Reply-To: moodleadmin+AAAAAAAAAAIAAAAAAAAAaAAAAAAAAAACVAqOB2WW3Mz0ckPf@webmail.dev`

When I go to reply to this email, the email address used by RainLoop is as follows:

`To: moodleadmin+aaaaaaaaaaiaaaaaaaaaaaaaaaaaaaacvaqob2ww3mz0ckpf@webmail.dev`

Is RainLoop enforcing a rule that all email addresses should be lower case? If so, is this controlled by a setting that I can turn off? 

With thanks. 

-Corey

**Comment by RainLoop** [comment]
> Is RainLoop enforcing a rule that all email addresses should be lower case? 
> If so, is this controlled by a setting that I can turn off?

Yes, RainLoop does it. 

This causes problems? 
Moodle does not work with these email addresses?

**Comment by ervee** [comment]
Apparently so if I understand Corey correctly. Why does RL change anything to lowercase? IMHO it should always leave the upper/lower case as is where possible.

**Comment by techxplorer** [comment]
@RainLoop Yes, changing the email address to all lower case causes problems.

These email addresses are designed to allow users to email replies to a forum post in a Moodle course. As such the text between the + and the @ sign is actually a base64 encoded identifier. As such it is case sensitive. 

By changing the address to all lower case, the base64 decoding doesn't work and Moodle will throw an error. According to the Moodle developer [RFC-5321][https://tools.ietf.org/html/rfc5321] specifies that the mailbox portion of an email address is case sensitive. I have not read the RFC myself. 

Is there any way to stop RainLoop from changing the case of email addresses?

**Comment by RainLoop** [comment]
OK, I will fix it.

**Comment by urban-thinking** [comment]
Hi.

Has this been fixed? It's also causing problems, when you use the option "Use short login  (user@domain.com → user)" and the remote system (i.e. imap server) is case sensitiv in login (user) names ... :-(

Kind regards.

**Comment by RainLoop** [comment]
Yes, it was fixed. But this issue is about email address, not about the login.

For you I have added login.login_lowercase setting into application.ini (enabled by default)
But I do not advise change this setting, since TEST@domain.com and test@domain.com will be interpreted as different users.

New settings will be available in the next release.

**Comment by urban-thinking** [comment]
Very cool ... we will give it a try and see, if we run into any problems concerning the user thingy :-D

Thank you very much.
