### ISSUE TITLE
How to use GPG ?

### ISSUE THREAD

**Issue by Angristan** [RainLoop/rainloop-webmail#815]
Hi,
I have imported my public and private key into RainLoop.
When I receive an encrypted mail, it appears like this :  https://lut.im/LXnEz6aZ/DLzcIlu9

It doesn't ask me for my passphrase... How to decrypt the message ? (it's woking on other clients)

**Comment by RainLoop** [comment]
Hi, try to click a lock icon.

![pgp1](https://cloud.githubusercontent.com/assets/5530092/9500265/18f509ce-4c2d-11e5-9c03-511a7a5863f4.png)

**Comment by Angristan** [comment]
Then the message become red... What does it mean ?

**Comment by RainLoop** [comment]
It means that something went wrong :)

**Comment by Angristan** [comment]
Oh thank you that is helping me a lot ^^

**Comment by RainLoop** [comment]
You may check an error description, just hover your mouse on a lock icon.

**Comment by Angristan** [comment]
Yep it' says it can't decrypt the message. But I have the public key of my contact and my private key. I do not see where is the problem

**Comment by flo-4** [comment]
Hello,

I have the same problem.

My configuration :
PHP Version 5.4.41-0+deb7u1
ownCloud 7.0.4
Apache/2.2.22 
Debian 7

Thanxs

**Comment by acarna** [comment]
Same problem here. It was working fine before 1.9.2.353.
I have been trying to reload my keys but decryption is failing. Encryption is working fine.
Also, to import keys, only option is Copy & Paste. Could be handy to have an "Upload Key" button.

**Comment by RainLoop** [comment]
Check the latest version (1.9.3.363)

**Comment by Angristan** [comment]
It's working ! :D

**Comment by acarna** [comment]
Yes, it's working!
Thank you!!!
