### ISSUE TITLE
Empty contacts list in owncloud integration

### ISSUE THREAD

**Issue by lakano** [RainLoop/rainloop-webmail#816]
Hello,

I love RainLoop, with OwnCloud integration this add a new dimension to mails / contacts management synced with the mobile.

But, I have a problem, the contacts list is empty. 
Strangely, if I start typing the name of my contact in the "To" field, I see the list of matching email from my OwnCloud contacts list.

So, may be it's just a little bug because RainLoop can access them... but not show them in the popup window.

Regards,

**Comment by RainLoop** [comment]
Yes, RainLoop shows only local contacts in a popup window.
In "To" field RainLoop gets contacts from local address book (RainLoop) and external (directly from OwnCloud)

**Comment by lakano** [comment]
Ok, thanks for the precision! :)
