### ISSUE TITLE
Baikal and sync with rainloop

### ISSUE THREAD

**Issue by COLORLINK** [RainLoop/rainloop-webmail#822]
Baikal and sync with rainloop.. would that work!? or not really

**Comment by ebal** [comment]
I have that setup for over a year now. No complaints at all. 

If you have a more specific question, don't hesitate

**Comment by COLORLINK** [comment]
please can you provide me a way to communicate with you. or do you have a tutorial that explains how to do that?... i got baikal running. and i have rainloop running. but i dont know how to make the 2 meet each other to sync.. 
i'm using localhost.

**Comment by ebal** [comment]
It's really easy: 

Rainloop --> settings/contacts

Addressbook URL: https://mybaikalurl.mydomain.tld:443/card.php/addressbooks/USERNAME/default
User: USERNAME
Password: ********

so if you have baikal on a localhost, try replacing the url with localhost
