### ISSUE TITLE
[Standard Edition] Soft-wrap on viewing plain text emails

### ISSUE THREAD

**Issue by megadr01d** [RainLoop/rainloop-webmail#824]
I'm using the latest version and I really can't remember about the previous ones but, plain text emails composed in Rainloop are viewed with no CSS applied to the viewing window resulting in long lines, horizontal scrollbar and line breaks just where Enter was pressed.

While this means that Rainloop presents text accurately, the way it was written, with no added line breaks (copying and pasting to a text editor, will paste the message correctly, as it is), shouldn't CSS [soft-wrapping](http://stackoverflow.com/questions/1795109/what-is-the-difference-between-word-break-break-all-versus-word-wrap-break) be applied to plain text to fit the view port, the same way big images are resized or HTML emails, just for viewing comfort?

**Comment by RainLoop** [comment]
Yes, it was a bug and it will be fixed in the next version.

**Comment by megadr01d** [comment]
:+1:

**Comment by RainLoop** [comment]
Fixed

**Comment by megadr01d** [comment]
Actually, the `word-break: break-all` property is undesirable because it **always** breaks words.

With `break-all` enabled:

![break-all-enabled](https://cloud.githubusercontent.com/assets/9649385/9976840/3230d72e-5ee8-11e5-857b-544c4b0ee548.jpg)

With `break-all` disabled:

![break-all-disabled](https://cloud.githubusercontent.com/assets/9649385/9976841/3855486a-5ee8-11e5-8e50-ea89cf5bded7.jpg)

**Comment by RainLoop** [comment]
Thanks

**Comment by megadr01d** [comment]
This seems fixed in the latest 1.9.3.365. :+1:
