### ISSUE TITLE
opmsg support | gpg alternative

### ISSUE THREAD

**Issue by HLFH** [RainLoop/rainloop-webmail#825]
Hi,

We need opmsg support, the best gpg alternative.

https://github.com/stealth/opmsg

Thanks in advance,

**Comment by HLFH** [comment]
@RainLoop Any explanation?

**Comment by RainLoop** [comment]
Unfortunately, I did not get other requests for this functionality from other users.

also:

- I do not see much activity around the project.
- I do not see the library to work with opmsg in the browser (like OpenPGP.js).

**Comment by HLFH** [comment]
For the time being, you're entirely right.
