### ISSUE TITLE
rain loop architecture

### ISSUE THREAD

**Issue by manirathinam** [RainLoop/rainloop-webmail#83]
Hi 

i need rain loop architecture diagram. with explanation.

Thanks.

**Comment by axos88** [comment]
@RainLoop If you'd provide a little bit help on the architecture, and how it's built together, a lot of keen opensource developers would pitch in, including myself.

We don't have time for documentation is going to bite you in the ass sooner or later. Hard.

**Comment by greg-1-anderson** [comment]
I could live without architecture documents if there were at least build/deploy documentation. Then I could do small experiments and contributions with just a little spare time. 

Suggestions:
1. Add build and deploy instructions to GitHub
2. Update http://www.rainloop.net/contribute/ with a link to the build instructions
3. Tag all of your releases in GitHub, so contributors can work off of dev/master or the latest stable release

The Affero GPL v3 says: 
```
The "Corresponding Source" for a work in object code form means all the source code needed to generate, install, and (for an executable work) run the object code and to modify the work, including scripts to control those activities.
```
So, how about you give us a clue how to use those scripts? We just want to be able to help out.

**Comment by greg-1-anderson** [comment]
Started some *Contributing* documentation at #795.
