### ISSUE TITLE
different subject endoding that body encoding

### ISSUE THREAD

**Issue by ebal** [RainLoop/rainloop-webmail#830]
It seems that some mail client are using different encoding for subject and body. 
a friend 's mail client encodes subject with iso-8859-7 but body with utf8 !

That seem to create a problem to rainloop when rendering/decoding such mails. 
gmail/thunderbird seems to work this out 

Subject: Re:  =?iso8859-7?b?1OX99+/yIDMyIHJldmlldw==?=

Content-Type: text/plain; charset=utf-8; format=flowed

![subject_body](https://cloud.githubusercontent.com/assets/3049624/9722238/0dabcdee-55b2-11e5-889e-6b87f0f16308.jpg)

**Comment by RainLoop** [comment]
Hi @ebal,

Could you give me example eml message?
Thanks.

**Comment by ebal** [comment]
Thanks for your immediate response. 

I guess you request a full header/body example  right ? 
cause I cant get you an eml message - no available windows machine for 15years now!

I'll ask my friend to sent me a test email.

**Comment by RainLoop** [comment]
OK, I have repeated the problem.

Thanks, it will be fixed in the next version.
