### ISSUE TITLE
Support for email aliases

### ISSUE THREAD

**Issue by gravypod** [RainLoop/rainloop-webmail#833]
There does not seem to be any support for email aliases. 

This feature is fairly important for companies using google apps: https://support.google.com/a/answer/33327?hl=en

Do you know if you will be supporting this?

**Comment by megadr01d** [comment]
Once you login in Rainloop webmail, go to **Settings > Accounts** and you can add identities (aliases) for the current account.

**Comment by gravypod** [comment]
That does not work for a alias email from google apps. You will get an error telling you that RainLoop was unable to verify.

**Comment by ebal** [comment]
To use an email alias for receiving emails from a different account is something you create on your mail server and not on your webmail. 

Identities is the way to go for sending emails for such a different account.

That's actually my setup!

**Comment by gravypod** [comment]
From a gmail alias, you can send from the alias. I had the same setup on my Thunderbird install. This is how you would go about setting this up on Thunderbird: https://support.mozilla.org/en-US/kb/configuring-email-aliases

It is already configured on my email server as I had it working fine on Thunder bird. This is a separate thing from email forwarding or having two accounts on an email server.

**Comment by gravypod** [comment]
Sorry, I figured it out. I must have misread something on my first look around. Thanks for the help.

**Comment by AbuAhmedSuman** [comment]
I want to add Image in Auto replay system in my rainloop mail server. Any one can suggest me how can I do it.
