### ISSUE TITLE
Empty drafts folder, but number of unread messages in sidebar

### ISSUE THREAD

**Issue by 29hertz** [RainLoop/rainloop-webmail#838]
Hi,

I have an empty drafts folder. None of my clients (Thunderbird 38, K-9 Mail and Rainloop, of course!) lists an e-mail in this folder. Nevertheless Rainloop shows a number of seemingly unread messages in the sidebar beside the label of this folder. 

I'm sorry about the screenshot in German language, but the problem should be clear:
![bildschirmfoto 2015-09-24 um 11 15 26](https://cloud.githubusercontent.com/assets/14818707/10069616/97d6ae00-62ad-11e5-8647-7941978b02a4.png)

I'm using the Communiy edition v1.9.2.343. Thank you…

**Comment by megadr01d** [comment]
Same issue as https://github.com/RainLoop/rainloop-webmail/issues/698. Try to clear the browser/Rainloop's cache folder and while you're at it, latest version is [1.9.3.363](https://github.com/RainLoop/rainloop-webmail/issues/698).

**Comment by 29hertz** [comment]
Thank you very much. I will try your solution and do an update soon.
