### ISSUE TITLE
[Standard Edition v1.9.3.363] [Bug] Leading blank space in message preview

### ISSUE THREAD

**Issue by megadr01d** [RainLoop/rainloop-webmail#840]
I just noticed that the latest version introduced some unwanted blank lines in some emails.
In this test case, I'm using [IFTTT](https://ifttt.com) to deliver RSS  to Email Digests to my inbox, more specifically, commits of a GitHub project.

In the screenshot below, Rainloop inserts a huge amount of `<br style="max-width: 100% !important">` lines before the content:

![leading-blank-space](https://cloud.githubusercontent.com/assets/9649385/10161496/79a498f0-669c-11e5-9814-911498938a70.png)

This only happens in email digests, which contain more than one IFTTT header (highlighted in blue):

![header-first](https://cloud.githubusercontent.com/assets/9649385/10161649/8391ec2c-669d-11e5-9b25-5c9ae3e053c4.png)

Also, the rest of the IFTTT headers also have extra blank lines added to them:

![header-next](https://cloud.githubusercontent.com/assets/9649385/10161761/3775f454-669e-11e5-8d43-529e0c2377e3.png)

Things to consider:

- This didn't happen in previous Rainloop versions
- I can reproduce this bug in both Chrome and Firefox

**Comment by RainLoop** [comment]
Hi @megadr01d , could you give me (support@rainloop.net) these messages (eml files) for tests.

**Comment by megadr01d** [comment]
Hi @RainLoop 

Just sent you an email with some test `eml` files.
I also noticed that the bug doesn't happen on all digest emails, just on the ones from GitHub commits.

**Comment by RainLoop** [comment]
Thanks, it'll be fixed in the next release.

Fast fix:
`./rainloop/v/x.x.x/app/libraries/RainLoop/Actions.php ~9595`
```php
$sHtml = \preg_replace_callback('/(<pre[^>]*>)([\s\S\r\n\t]*?)(<\/pre>)/mi', function ($aMatches) {
    return \preg_replace('/[\r\n]+/', '<br />', $aMatches[1].\trim($aMatches[2]).$aMatches[3]);
}, $sHtml);
```

**Comment by megadr01d** [comment]
Cool, thanks for the quick fix.
