### ISSUE TITLE
Add package versions in downloads

### ISSUE THREAD

**Issue by simonsmiley** [RainLoop/rainloop-webmail#842]
It would be nice to have different versions hosted, where the names contain the version numbers.  
The minimum would be to have version numbers, so that anything relating to a version of the software including the link to download doesn't get obsolete when a new version is pushed.  
Even if you choose to not host all versions, at least people would realize that a new version has been published

**Comment by RainLoop** [comment]
https://github.com/RainLoop/rainloop-webmail/releases
https://github.com/RainLoop/rainloop-webmail/issues/479
