### ISSUE TITLE
Make SMPT-Timeout configurable

### ISSUE THREAD

**Issue by Nebukadneza** [RainLoop/rainloop-webmail#843]
Hello,

in some installations, especially on slower machines, SpamAssassin checking can take a while, up to 40seconds. Since the SMTP-timeout of rainloop is hardcoded to 10seconds (… i think), some emails that take longer to be checked cannot be sent. This seems to work when manually changing these 10s in the source.

I think that it would be great if SMTP timeouts could be configured. The domain-wise configuration file is there anyways, and iConnectionTimeout is variable in Actions.php already, so it shouldn’t be too hard …

Thanks for you great software, best regards
-Dario Ernst

*EDIT: I forgot to add — Actually i had to increase iSocketTimeOut in NetClient.php also…

**Comment by RainLoop** [comment]
Thanks, additional configurations will be available in the next release.

**Comment by Nebukadneza** [comment]
Thank you a lot!
