### ISSUE TITLE
UI gone ugly 

### ISSUE THREAD

**Issue by jenalgit** [RainLoop/rainloop-webmail#847]
after I am enable plugin web UI gone ugly. i use standart edition v.1.9.2.353
![screenshot 2015-10-08 09 37 41](https://cloud.githubusercontent.com/assets/3593036/10356347/6e660342-6da0-11e5-9af9-be0387e346cb.png)

**Comment by megadr01d** [comment]
Known issue https://github.com/RainLoop/rainloop-webmail/issues/191 and https://github.com/RainLoop/rainloop-webmail/issues/531.

Press <kbd>Ctrl+F5</kbd> to force refresh the browser and the problem should be gone.

**Comment by jenalgit** [comment]
still ugly..... 
![Uploading Screenshot 2015-10-10 14.01.21.png…]()

**Comment by RainLoop** [comment]
Interesting, what plugins have you installed?
Are there any errors in php/apache/rainloop logs?
