### ISSUE TITLE
Invalid email addresses remain in the address bar

### ISSUE THREAD

**Issue by axos88** [RainLoop/rainloop-webmail#848]
Version: 1.9.1.335

Repro:

Click create a new mail
Type "blah" into the To field, and press space. The text disappears.
Type a valid email address (example@example.com) into the field, and complete your message, click on send.

Expected:

The email be sent to example@example.com address only

Actual:

The email has "blah, example@example.com" in the To field.
This causes a send error (on my mail config at least), and the email is NOT sent.

``` Oct  8 10:08:54 mail postfix/submission/smtpd[12725]: warning: Illegal address syntax from localhost[::1] in RCPT command: <blah,example@example.com> ```

**Comment by megadr01d** [comment]
It works correctly for me in the latest version is [1.9.3.363](http://www.rainloop.net/downloads).

**Comment by axos88** [comment]
I will give it a try when I have some time to do the upgrade.

**Comment by axos88** [comment]
Is the versioning semantic?

**Comment by megadr01d** [comment]
> Is the versioning semantic?

I dunno.

**Comment by axos88** [comment]
Confirmed fixed.
