### ISSUE TITLE
Filters not visible after update

### ISSUE THREAD

**Issue by nbittmann** [RainLoop/rainloop-webmail#849]
HI,

Trying to use the sieve filtering with round cube and updated to latest community version however the filtering is not available in settings?

How can I activate it?

Running on OS X Server 10.11 
Rain loop version 1.9.3.363

**Comment by ervee** [comment]
Do you have Sieve configured on your IMAP server? And a Manage Sieve also?

**Comment by nbittmann** [comment]
Yes sieve and manage Sieve are both available

**Comment by nbittmann** [comment]
Epic fail now sorted

**Comment by julemarts29** [comment]
how did you manage to install managesieve and sieve on the latest version of rainloop?
