### ISSUE TITLE
rlBlockquoteSwitcher formats email when clicked

### ISSUE THREAD

**Issue by dodedodo** [RainLoop/rainloop-webmail#853]
Hi,

Something I noticed today: When I press the rlBlockquoteSwitcher to display previous messages it formats my tekst and sometimes removes parts of the email. For example:

>Hi bob,
>
>This is just regular tekst (10/10/'15) some more regular tekst to replace sensitive information?
>
>cheers,
>bob2
>
>"name of sender" <xxx@xxx.xx> schreef op 10 oktober 2015 07:34:
>[ &#x26AB;&#x26AB;&#x26AB;  ]

becomes this when I click the button twice (unfold, fold again):

>Hi bob,
>
>**This is just regular text** (&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;) some more regular text to replace sensitive information?
>
>cheers,
>bob2
>
>**"name of sender"** <&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;> schreef op 10 oktober 2015 07:34:
>[ &#x26AB;&#x26AB;&#x26AB; ]

Note that the bold tekst is actually bold in rainloop, and that everything between () and <> seems to be replaced my spaces.   [ &#x26AB;&#x26AB;&#x26AB;  ] represents the unfolding button. I tried to stay as close as possible to the original message without showing any personal information.

It's not really a breaking bug, but it makes me curious. Any idea what causes this?

**Comment by dodedodo** [comment]
I also noticed this bug is absent when I resize my browser to the point that the last sentence flows on a new line.

Also i'm on google chrome 45.0.2454.101 m , and it does not seem to affect firefox. I can't test IE since it has never worked on my laptop.

**Comment by RainLoop** [comment]
is this issue still relevant?
