### ISSUE TITLE
Domain variable option when setting up SMTP/IMAP servers

### ISSUE THREAD

**Issue by jas8522** [RainLoop/rainloop-webmail#857]
Loving Rainloop so far! 

I've set up a wildcard domain via "*", however I wish to allow the one install of Rainloop to be usable by a number of domains across multiple servers. To make this work I would like to be able to enter a variable that represents the domain. Example configuration:

SMTP Server: mail.$domain with port 587 and STARTTLS

This way if I'm logging in with jordan@xyz.com it will connect to the right server, and if I'm logging in with jordan@abc.com, it will connect to the right server.

Since we're adding domains regularly in Plesk, it would be cumbersome to also manually enter them in Rainloop.

Is this possible?

**Comment by RainLoop** [comment]
> Is this possible?

No, but you may create a plugin.

For example:
https://github.com/RainLoop/rainloop-webmail/tree/master/plugins/override-smtp-credentials

**Comment by jas8522** [comment]
Thanks! That should do the trick :)

**Comment by aaronstuder** [comment]
@jas8522 Did you get it working? Could you share how?

**Comment by jas8522** [comment]
> @jas8522 Did you get it working? Could you share how?

I had duped the smtp credentials plugin as described above, then modified it to work with IMAP logins as well. It was then modified a bit by the rainloop devs (likely for code consistency and compatibility) and turned into this plugin: https://github.com/RainLoop/rainloop-webmail/tree/master/plugins/auto-domain-grab

That plugin should do it, though I'm technically still using my original code.

**Comment by aaronstuder** [comment]
How do I install it? I am new to this.

**Comment by jas8522** [comment]
> How do I install it? I am new to this.

Described here: https://github.com/RainLoop/rainloop-webmail/issues/1362

**Comment by aaronstuder** [comment]
Works Great!!!
