### ISSUE TITLE
Parameter continuations not supported?

### ISSUE THREAD

**Issue by ozanhazer** [RainLoop/rainloop-webmail#858]
According to RFC2184/2231 (https://tools.ietf.org/html/rfc2184#section-3) long mime headers could be split up into smaller units. It looks like long attachment filenames cannot be read in rainloop. Eg:

    Content-Type: application/xml; 
        name*0="RelayToREMMDFailure<62a98a667b7824a0070691260feda5f3@dersera"; 
        name*1=".com>.xml"
    Content-Transfer-Encoding: quoted-printable
    X-REM-Section-Type: rem_message/evidence
    Content-Disposition: attachment; 
        filename*0="RelayToREMMDFailure<62a98a667b7824a0070691260feda5f3@dersera"; 
        filename*1=".com>.xml"

**Comment by RainLoop** [comment]
This should work.
Could you send me the example message?
