### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by GaneshKandu** [RainLoop/rainloop-webmail#871]
Hi My Name is Ganesh Kandu
I an Trying to installed RainLoop in my PC
But Getting error 
<q><b>An Error occurred,<br/>please refresh the page and try again. </b></q>
having php 5.5 and data directory is writable recursively
![screenshot-192 168 58 130 2015-10-28 11-34-49](https://cloud.githubusercontent.com/assets/12833130/10780844/eca2babc-7d67-11e5-806d-3b0a084271a9.png)

**Comment by megadr01d** [comment]
Try the following:

- force refresh the browser <kbd>Ctrl+F5</kbd>
- close and restart the browser
- try another bwoser
- empty Rainloop's cache folder `./data/_data_7d6917231519a4cf64ff358ceb666d55/_default_/cache`

**Comment by DigiAngel** [comment]
Exact same issue here... Tried all the above steps with no differing results.  Apache logs show nothing amiss.

**Comment by RainLoop** [comment]
Hi, did you install RainLoop from GitHub zip archive?

**Comment by DigiAngel** [comment]
Negative...git cloned :)

**Comment by RainLoop** [comment]
It's almost the same thing.

Github version requires additional compilation, so it cannot work by itself.

Work package should be taken here:
http://www.rainloop.net/downloads/

**Comment by DigiAngel** [comment]
Ah...ok I will give that a go thank you.

**Comment by DigiAngel** [comment]
Ya that totally worked...thanks so much...continuing on my journey :)

**Comment by GaneshKandu** [comment]
Hi am Getting same error in firefox with v1.9.3.365
<b><q>An Error occurred,
please refresh the page and try again.</q></b> 
but working in chrome without error

**Comment by Luskan777** [comment]
Hello guys,

I had the same problem, and the problem was due to a plugin I had installed, the fix was the removal of this plugin, hope it helps
