### ISSUE TITLE
EXIF information ignored, leads to incorrect image orientation

### ISSUE THREAD

**Issue by alexzeitgeist** [RainLoop/rainloop-webmail#872]
RainLoop doesn't respect EXIF information embedded in images. For example, images taken with iOS devices aren't rotated properly in the right orientation. Not sure if RainLoop uses the GD library to preprocess images before displaying them; if it does, it also requires extra handling beforehand since GD strips any embedded EXIF information (for example for thumbnail generation).

If the EXIF PHP extension is loaded, the exif_read_data() function could be used along with the imagerotate() function provided by GD. 

http://php.net/manual/en/function.exif-read-data.php

**Comment by alexzeitgeist** [comment]
RainLoop currently uses the 3rd party PhpThumb library, which hasn't been updated in a very long time. Perhaps, also to include proper EXIF handling, it would make sense to replace the library with one that is more capable and actively maintained. One example: 

https://github.com/avalanche123/Imagine

Supports rotating based on EXIF information., and also alternative image extensions (GD, Imagick and Gmagick).

**Comment by RainLoop** [comment]
Hi, thanks for the link.
Could you give me some examples (photos with wrong orientation)?

**Comment by RainLoop** [comment]
email: support@rainloop.net

**Comment by alexzeitgeist** [comment]
Sent.

**Comment by RainLoop** [comment]
Done

**Comment by zeigerpuppy** [comment]
I am having trouble with iphone image rotation, the orientation is incorrect, attached sample image
![photo](https://cloud.githubusercontent.com/assets/415981/17648701/5c199100-620e-11e6-9817-5184ab0ba646.JPG)
