### ISSUE TITLE
Use Dev JS in development environment

### ISSUE THREAD

**Issue by uynil** [RainLoop/rainloop-webmail#885]
Hi, How can I include and use javascripts in dev folder instead of using compressed app.js?
It takes quite a lot time to compile the scripts every time.

**Comment by RainLoop** [comment]
`./data/.../application.ini`

```ini
[labs]
use_app_debug_js = On
use_app_debug_css = On
```

**Comment by uynil** [comment]
Thanks.
How to develop plugins on real time? It seems there is a cache in data folder.

**Comment by RainLoop** [comment]
```ini
[labs]
cache_system_data = Off
```

**Comment by uynil** [comment]
Thanks
