### ISSUE TITLE
Google 2-step authentification

### ISSUE THREAD

**Issue by zwarag** [RainLoop/rainloop-webmail#886]
When adding 2step authentication to your Google Account, it is not possible to add this account to rainloop as it looks like rainloop does not work with the "App Password" yet.

[Screenshot](http://imgur.com/9EGb9Q6)

See: 
 - [App Password BY GOOGLE](https://support.google.com/accounts/troubleshooter/3141849#ts=3202254%2C3202318)
 - [Using sign-in Apps BY GOOGLE](https://support.google.com/accounts/answer/185833)

**Comment by RainLoop** [comment]
I have tested it right now and it works correctly for my gmail account with "App Password".

**Comment by zwarag** [comment]
Interesting. 
I did add an "app" manually to the app-password list, but i never get asked about the App Password when I try to add my gmail account to rainloop
.
