### ISSUE TITLE
Multiple identities

### ISSUE THREAD

**Issue by Mageti** [RainLoop/rainloop-webmail#9]
Hello,
Is there a possibility to use several identities as a sender, in RainLoop ?
On my server, I use one account, but it has aliases. Aliases as both receiver and sender. The receiver aliases are well computed by my postfix server, but for the sender part, I didnot see anything like that in RainLoop. Roundcube and Hastymail (my 2 previous webmails) were able to do that.
ex : main e-mail : Mageti < mageti_AT_domain1.com >
alias e-mail : Realname < mageti_AT_domain2.net >
alias e-mail : Me and my wife < mageti_and_his_wife_AT_domain1.com >
Did I miss something in RainLoop ? Or will you add such a feature ?

**Comment by viperdriver2000** [comment]
was this option removed? i cant found them in v1.11.3.
