### ISSUE TITLE
Outlook.com: unable to connect (timed out)

### ISSUE THREAD

**Issue by mikerockett** [RainLoop/rainloop-webmail#916]
Using RL 1.9.1.335, and not able to connect to Outlook.com for my personal email account. The following errors are thrown:

![rl-outlook](https://cloud.githubusercontent.com/assets/4586280/11949907/b9c079cc-a88c-11e5-8053-7c8057d3e4cf.png)

**Comment by tunermason** [comment]
Try 
imap: outlook.office365.com   port:993 tls/ssl
smtp: smtp.office365.com port:587 tls/ssl

**Comment by mikerockett** [comment]
@tunermason I had already tried those, also didn't work.

But my bad, I forgot to come back here and state the problem was solved. For some reason, the host I was using prevented me from connecting to an external service provider for pop/imap/smtp. So I move it over to another host with a larger package, and all works well now.

:+1:
