### ISSUE TITLE
Dragging emails to folders

### ISSUE THREAD

**Issue by fearworksmedia** [RainLoop/rainloop-webmail#92]
I think this is a bug, but only have my own setup and mail servers to test it on so some others might need to confirm it as a bug.

RainLoop version: 1.6.3.712

When I drag emails from my inbox to a folder I have created, the emails I have dragged are not shown in that folder in date order, but rather in the order I have dragged them in. So if I drag an email that is 6 minutes old to a folder called "work", and then drag an email that is 2 days old to the "work folder", the 2 day old message appears in the list above the 6 minute old one.

Like I say, this may be something to do with my setup but if others can check if this happens and either confirm or reject this as a bug!

**Comment by fearworksmedia** [comment]
I've a feeling this bug has come back to haunt us... I've started to get emails in the order they were copied to another IMAP folder again, even though use_imap_sort = On is set in application.ini.

**Comment by RainLoop** [comment]
Try to disable "Use threads" and check again

**Comment by fearworksmedia** [comment]
Hi and thanks for the quick reply!

My mail server doesn't support threads (hmailserver), I don't see the "Use threads" option in the admin config system anymore (although I used to in earlier versions) and in application.ini I already have use_imap_thread = Off. Any other suggestions?

Thanks!

**Comment by fearworksmedia** [comment]
I should say that I'm using version 1.7.2.220.

**Comment by fearworksmedia** [comment]
Also, I don't know if date_from_headers has anything to do with this but in my application.ini file it is currently set to date_from_headers = On. I tried with it set to Off too but it doesn't seem to affect this issue...?

**Comment by RainLoop** [comment]
Weel, can you give me email account for tests (access credentianals)?

**Comment by RainLoop** [comment]
IMAP host/port, imap account login/password

**Comment by fearworksmedia** [comment]
Yes sure. How should I send you the info?

**Comment by RainLoop** [comment]
Ops, sorry.
support@rainloop.net

**Comment by fearworksmedia** [comment]
Ok great, sent.

**Comment by RainLoop** [comment]
Thanks!
Ok, I see the problem. It will be fixed in the next version.

Fast fix:

file: ./rainloop/v/x.x.x/app/libraries/MailSo/Mail/MailClient.php
line: 1917

```php
if ($bMessageListOptimization || 0 === \MailSo\Config::$MessageListDateFilter)
{
```
change to
```php
if (0 === \MailSo\Config::$MessageListDateFilter &&
	($bMessageListOptimization || !$bUseSortIfSupported))
{
```

**Comment by fearworksmedia** [comment]
That's great - thanks very much!
