### ISSUE TITLE
GPG encryption with multiple keys

### ISSUE THREAD

**Issue by corna** [RainLoop/rainloop-webmail#927]
I'm getting a generic "OpenPGP decryption error" when I try to decrypt my own message encrypted with two keys, the recipient's one and mine. The recipient can decrypt it, but the sender (me) can't.
The message is correctly encrypted with both keys, as I can decrypt it with the gpg tools.

**Comment by thonixx** [comment]
Same problem at my place. I have multiple IDs but I can not decrypt a message I have received.

**Comment by RainLoop** [comment]
Check the last version, please.
