### ISSUE TITLE
Incorrect timezone used

### ISSUE THREAD

**Issue by Ulrar** [RainLoop/rainloop-webmail#931]
Hi,

I just installed rainloop, and it seems to work great, except for a little detail : in the mail list, the time is off. For example I just sent myself an email, and it says I received it an hour ago instead of just now. When I click on the message, the date displayed on top is off by one hour on every mails.

My server is using the correct timezone (Europe/Paris), the date command in a shell does return the correct time, and in php.ini (and indeed in a phpinfo(); call) the timezone is set to Europe/Paris. Any idea ? I tried sending a mail with rainloop to myself, the Date header seems to be in UTC, and with mutt the Date header is in UTC +1, in both case it's the correct time (relative to the timezone) but rainloop displays it "one hour ago".

Thanks

**Comment by RainLoop** [comment]
Well, RainLoop does not use php timezone configuration.
It gets date from email message, converts to UTC and displays it in your client's (web-browser) time zone.

**Comment by Ulrar** [comment]
That seems weird, the date in the message is correct, and I'm pretty sure
my browser timezone is correct too. At least my system timezone is.
I tried from multiple browsers on multiple computers, always the same
problem.

2016-01-20 11:00 GMT+01:00 RainLoop Team <notifications@github.com>:

> Well, RainLoop does not use php timezone configuration.
> It gets date from email message, converts to UTC and displays it in your
> client's (web-browser) time zone.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RainLoop/rainloop-webmail/issues/931#issuecomment-173151464>
> .
>



-- 
Kévin Lemonnier

**Comment by gfontaniere** [comment]
I try to configure fail2ban, but timezone is incorrect in log file : 
`[2016-03-17 23:38:11] Auth failed: ip=77.247.181.162 user=test@domain.fr host=192.168.0.6 port=993`
In fact it's **00:38:11** (UTC+1)
PHP timezone is good.
SYSTEM timezone is good (ntp).
Any idea ?
Thank you.

**Comment by RainLoop** [comment]
@gfontaniere 

RainLoop uses UTC timezone in log files.
It can be change in the configuration file.

`./data/../application.ini`

```ini
[logs]
time_offset = 2 // 2h => UTC+2
```

**Comment by gfontaniere** [comment]
Indeed...
Thnk you.

**Comment by pc-maniac** [comment]
I have the same issue. My timezone is EEST (GMT+3) and in mail list date/time is incorrect. I tried sending mail to myself, my local mail client shows time of this message correct, but in RainLoop list this time shows 3 hours less. Server time and timezone set correctly, local time and timezone too. I checked this from more than 10 desktops with different OSes and Browsers. I think RainLoop web interface displays time in UTC, but this is very unuseful for users. It will be great if RainLoop web interface shows date/time in browser timezone.

**Comment by pc-maniac** [comment]
After changing the settings to:
date_from_headers = On
use_imap_sort = On
dates in web interface displayed correctly and converted to browser timezone.

**Comment by RainLoop** [comment]
RainLoop always uses browser timezone to display dates in the message list.  This means that most likely, something is wrong with your mail server.

**Comment by pc-maniac** [comment]
What field used for date detecting?
I checked headers and find three date field:

```
Received: on behalf of honored client by ... with ESMTPS id ...
        for <...> on Fri, 22 Sep 2017 16:31:06 +0300 (EEST)
Date: Fri, 22 Sep 2017 16:30:58 +0300
X-Envelope-Date: Fri Sep 22 13:31:39 2017
```

With "date_from_headers = On" in config RainLoop shows me 16:31 but with "date_from_headers = Off" - 13:31. The same client/server/browser.

**Comment by RainLoop** [comment]
With "date_from_headers = Off" RainLoop uses IMAP INTERNALDATE response value (by default). This value provided by your IMAP server. But some servers do it incorrect, so "date_from_headers = On" can fix this problem.

**Comment by Ulrar** [comment]
I'm using dovecot, which seems pretty standard to me. The timezone is
correct everywhere but in rain loop so something weird is definitely
happening

**Comment by pc-maniac** [comment]
Checked our IMAP server:
```
03 FETCH 110:110 INTERNALDATE
* 109 FETCH (INTERNALDATE "27-Sep-2017 11:50:19 +0000")
03 OK FETCH Completed
```
So server provides date in UTC and many different desktop and mobile mail clients shows this date in client local timezone. But RainLoop shows in UTC.

**Comment by RainLoop** [comment]
@pc-maniac RainLoop gets this date in UTC and shows it in local browser timezone.
Most of desktop and mobile mail clients get date from headers, so RainLoop can do it too with date_from_headers = On
