### ISSUE TITLE
Missing "send"-shortcut

### ISSUE THREAD

**Issue by sabsab88** [RainLoop/rainloop-webmail#938]
Dear all,

as I am used to the extraordinarily useful shortcut "ctrl+enter" in order to send a message in a very smooth way you can imagine that I was rather shocked when I realised rainloop lacks this function. Would you please integrate it to bring it to perfection? 
Thanks.

**Comment by ervee** [comment]
You can enable it in the application.ini. If it's not there by default, search for bugs I filed I think you can find the exact option you need in one of them.

**Comment by RainLoop** [comment]
`./data/.../application.ini`

```ini
[labs]
allow_ctrl_enter_on_compose = On
```
