### ISSUE TITLE
PGP/MIME works - but rendering problems

### ISSUE THREAD

**Issue by beccon4** [RainLoop/rainloop-webmail#942]
Recieving an encrypted message works now.(which is great) 

But the result displayed looks line that:

Content-Type: multipart/signed;
	boundary="Apple-Mail=_DF0B0FB2-D8BB-1680-A26C-5C33B888C3E3";
	protocol="application/pgp-signature";
	micalg=pgp-sha256

--Apple-Mail=_DF0B0FB2-D8BB-1680-A26C-5C33B888C3E3
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain;
	charset=windows-1252

danke f=FCr die sehr interessante Mail...  

where =FC is the Umlaut ü of course. 

As the browser is certainly capable of displaying html it would be nice to configure it like that.

**Comment by RainLoop** [comment]
Could you send me (support@rainloop.net) this message (encrypted version) ?
