### ISSUE TITLE
Attachment upload fail

### ISSUE THREAD

**Issue by digititus** [RainLoop/rainloop-webmail#944]
Rainloop 1.9.4.394

It's no longer possible to upload attachments.Here are the logs:
`[error] 5504#0: *234219 client intended to send too large body: 5421601 bytes, client: 
Attachment size limit is 50MB, and PHP: upload_max_filesize = 50M; post_max_size = 50M`

Ideas?

**Comment by davelima** [comment]
Can you edit your php.ini file? If you update the `upload_max_filesize` and `post_max_size` on your php.ini, then probably this problem will be solved.

**Comment by digititus** [comment]
@davelima 
php.ini already set to 50MB. Attachment is only 5MB

**Comment by digititus** [comment]
More info:
nginx version: nginx/1.4.6 (Ubuntu) PHP Version 5.5.9-1

**Comment by RainLoop** [comment]
You will need to set the client_max_body_size value (nginx configuration)
http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

**Comment by digititus** [comment]
@RainLoop 
Thanks. That worked. This is something that wasn't required before under my setup.
