### ISSUE TITLE
Raw variable seen

### ISSUE THREAD

**Issue by ervee** [RainLoop/rainloop-webmail#947]
Hi,

This raw variable is seen when creating a new imap folder:
![capture](https://cloud.githubusercontent.com/assets/4435930/12687081/f51aa704-c6cd-11e5-8744-007a5a29962c.JPG)
It's also there in English :)

**Comment by RainLoop** [comment]
Thanks! Yes, I know.

It's already fixed in the repository.
Fix will be available in the next release version.
