### ISSUE TITLE
Dynamic domain/server association

### ISSUE THREAD

**Issue by gallart** [RainLoop/rainloop-webmail#958]
Hello RainLoop,

What if we want to user RainLoop within a multi-domains/multi-servers configuration ?

Is there a way of dynamically choosing the right MailServer/SMTP based on the domain MX for example ? 
My idea is to skip allowing a new domain everytime someone wants to use it. For example, Roundcube automatically tries to connect to "domain.com" as IMAP Server.

Could we allow this kind of configuration ?

![image](https://cloud.githubusercontent.com/assets/2728195/13170919/0b7e75f2-d6f0-11e5-9088-57313c71627b.png)

Gaëtan

**Comment by RainLoop** [comment]
@gallart 
Yes, it's possible to do by using [this ](https://github.com/RainLoop/rainloop-webmail/tree/master/plugins/auto-domain-grab) plugin.

**Comment by RainLoop** [comment]
It's not exactly what you ask, but you can simply change the code for your needs.

**Comment by gallart** [comment]
That's exactly what I need ! Thanks !
