### ISSUE TITLE
[Feature request] select a folder via URL

### ISSUE THREAD

**Issue by llimz** [RainLoop/rainloop-webmail#959]
We have an application which generate an email and put it under the draft folder. Then I would like to open Rainloop and select the draft folder by default. I did not find a way to do that. Could it be an idea to add this feature to select the draft folder via the rainloop URL like e.g.:

http://rainloop.mydomain.com/?folder=draft

Thank you.

**Comment by RainLoop** [comment]
Try this:

http://rainloop.mydomain.com/#/mailbox/Drafts

**Comment by llimz** [comment]
Many thanks for your fast reply and I'm sorry that I did not find this way of working before.

**Comment by llimz** [comment]
In the same way, is there an option to create a new email via the url like e.g. http://rainloop.mydomain.com/#/new? It will open Rainloop in the inbox folder and open a new email. 

I checked in the code where the mailbox/Drafts function is handled but did not find the same to create new email

**Comment by llimz** [comment]
Any chance to compose a new message by using an url? I still did not find a way. Any advice will be appreciate. Thank you.
