### ISSUE TITLE
Better option for mobile screens?

### ISSUE THREAD

**Issue by wngroves** [RainLoop/rainloop-webmail#961]
Rainloop is incredible. So far i've only got one issue and that is with mobile display on smaller viewports. Everything works fine, its just that its too small to navigate.

(keep in mind the actual screen size is 3")
![screenshot_2016-02-19-15-46-48](https://cloud.githubusercontent.com/assets/8558548/13190074/b0ef05a8-d720-11e5-84eb-8350de3aad5a.png)

Here with preview mode turned off, its still too small to read:
![screenshot_2016-02-19-15-47-52](https://cloud.githubusercontent.com/assets/8558548/13190085/bcf3139e-d720-11e5-89c7-2aee30bc99d8.png)

Is there a way to scale up the views so they are more legible on smaller screens? 

I have the most recent version (installed yesterday).

**Comment by BloodMotion** [comment]
Same issue, rainloop is totaly incredible, but a responsive desing could be great and make it perfect !

**Comment by nioc** [comment]
+1 :smiley:

**Comment by RainLoop** [comment]
Last version (1.10) supports mobile view layout.
Not everything looks great, but it more useful on mobile devices now.

![aa50f3de-0fae-11e6-93ab-d720c29995e5](https://cloud.githubusercontent.com/assets/5530092/15336102/93a28a9a-1c7d-11e6-940d-424ccdc87ad2.gif)

**Comment by esroyo** [comment]
Looking great on Xperia, thanks soo much @Rainloop

**Comment by nioc** [comment]
Very good work! It is exactly what we needed. Thanks you.
Need some adaptations on the new message (formatting option are on two lines) and it will be perfect :smile:
