### ISSUE TITLE
Log-in page hangs in IE9

### ISSUE THREAD

**Issue by stevedowe** [RainLoop/rainloop-webmail#967]
Using Rainloop version 1.9.4.398 and currently assessing for a corporate client who is restricted to an IE9 environment  - but as per requirements, this should be ok.

Unfortunately, the log-in page doesn't finish loading.  The progress bar gets about 2/3 of the way along but I do not get the travelling dots or the login form.

Using Windows Vista sp2 & IE 9.0.8112.

I've attached response header and body.
[rainloop-response-body.txt](https://github.com/RainLoop/rainloop-webmail/files/144369/rainloop-response-body.txt)
[rainloop-response-headers.txt](https://github.com/RainLoop/rainloop-webmail/files/144370/rainloop-response-headers.txt)

**Comment by extremeshok** [comment]
Would Chrome frame for Ie work ?

Ie 9 has major issues with most JavaScript functions

**Comment by RainLoop** [comment]
@stevedowe 
Thanks for the issue. I will try to fix it as soon as possible.

**Comment by stevedowe** [comment]
Thanks for the superbly fast update!  Will this fix be part of the next version release?

**Comment by RainLoop** [comment]
Yes, of course.

**Comment by stevedowe** [comment]
Great!  Do you have a date in mind for the next release?

Thanks.

**Comment by RainLoop** [comment]
This week.
