### ISSUE TITLE
Problem with char "ś"

### ISSUE THREAD

**Issue by james4321** [RainLoop/rainloop-webmail#97]
The problem with char "ś". When you want to write a word containing the letter then made ​​a record mail. conventionally adopted it using CTRL + S, while the combination of ALT + S is used to enter a trade ś.
Please check and correct this problem.

**Comment by Ciangi** [comment]
Hello,
I use Rainloop 1.11.3 version.
Still problem with polish signs. Could you add possibility to on/off shortcuts?

Regards.

**Comment by Ciangi** [comment]
I would like to add that problem with polish signs exist only in Chrome Web Browser. When i write an e-mail and click on HTML <---> Normal text then i can write polish signs, but in HTML mode i can't.
