### ISSUE TITLE
owncloud 9 upgrade

### ISSUE THREAD

**Issue by Loki3000** [RainLoop/rainloop-webmail#975]
Hi!
After upgrading to OC9 rainloop lost datadir. The reason is class OC_Config is no longer exists.
 I have changed
```php
if (class_exists('OC_Config'))
{
    $sData = rtrim(trim(OC_Config::getValue('datadirectory', '')), '\\/').'/';
}
```
to

```php
$sData = rtrim(trim(OC::$server->getSystemConfig()->getValue('datadirectory', '')), '\\/').'/';
```
in RainLoopHelper.php, and now it's work well. So its need to upgrade app version.

**Comment by RainLoop** [comment]
Thanks!

**Comment by ezraholm50** [comment]
Thanks for the great ownCloud app, any update on when it gets shipped to OC 9?

**Comment by Schengawegga** [comment]
Thanks Loki for this very quick solution. My girlfriend was terrorising me, becaus the rainloop app was not working after upgrading owncloud. You saved my life ;-)

**Comment by pierre-alain-b** [comment]
Thanks, it works very well within oC 9 with your patch!

**Comment by Loki3000** [comment]
>Thanks, it works very well within oC 9 with your patch!
It's not patch. It's just a dirty hack to wait for an update:)

**Comment by Schengawegga** [comment]
today i want to send an email with an attachment. but its not possible to upload a file since OC9. did you´ve got another quick solution for this problem too?

**Comment by Loki3000** [comment]
I just try to send email with attachment and get no problem.
Seems that your trouble are not connected with the new version of OC.

**Comment by Loki3000** [comment]
Try to check permissions to

``` data/rainloop-storage/_data_XXX/_default_/storage/files/... ```

It's place for store uploaded files.

**Comment by Schengawegga** [comment]
After the OC Upgrade, the permissions to this folder are set to 777:www-data. i´ve done a chown with www-data:www-data and it workes. Thanks a lot for this clue Loki.

**Comment by ezraholm50** [comment]
`After the OC Upgrade, the permissions to this folder are set to 777:www-data. i´ve done a chown with www-data:www-data and it workes. Thanks a lot for this clue Loki.`

The ownership you mean by that right? I cant find the folder @Loki3000, and why is it set to 777, there must have been a typo somewhere but 777 on files?

**Comment by Schengawegga** [comment]
`The ownership you mean by that right? I cant find the folder @Loki3000, and why is it set to 777, there must have been a typo somewhere but 777 on files?`
yes, it´s the ownership. You can find the the folder in your `owncloud/data/rainloop-storage/...` folder.

**Comment by ezraholm50** [comment]
No folder like that anywhere on my data directory... strage

**Comment by RainLoop** [comment]
Last version should work with ownCloud 9.
