### ISSUE TITLE
admin panel security

### ISSUE THREAD

**Issue by suyashjain** [RainLoop/rainloop-webmail#976]
hi,

how can i secure admin section. I am using nginx and would like to have additional web user/pass to be added to this but i am not getting the correct url for that.

**Comment by RainLoop** [comment]
`http://domain.com/rainloop-path/?admin`

**Comment by suyashjain** [comment]
That is my question, how can i secure it or change it. this ?admin is known to everyone.

**Comment by ET-Bent** [comment]
@suyashjain I recommend this tutorial. https://www.digitalocean.com/community/tutorials/how-to-set-up-password-authentication-with-nginx-on-ubuntu-14-04 

The solution is called 'htpasswd'. Make sure to install the `apache2-utils` packet before going through the tutorial. Also it's debatable if this really increases security.

**Comment by suyashjain** [comment]
Hi,

I would like to know if I could change the default admin URL so that others
could not guess the correct one.

Thanks

**Comment by ET-Bent** [comment]
@suyashjain You could use some simple rewrite rules for this (either NGINX or Apache).

**Comment by RainLoop** [comment]
I have added a configuration parameter (54c3e07).
It will allow you to change admin url as you need.

Fix will be allowed in the next release version.

**Comment by RainLoop** [comment]
```
[security]
admin_panel_key = "admin"
```
