### ISSUE TITLE
Where to set limit for "You have too many folders!" option

### ISSUE THREAD

**Issue by richard-scott** [RainLoop/rainloop-webmail#978]
I wanted to convert from Roundcube but have got this problem where I can't see 95% of my folders anymore. I have lots of folders (and no issue with performance in Roundcube) but get this error:

"You have too many folders!"

Where can I change this limit? or remove it?

**Comment by RainLoop** [comment]
`./data/.../application.ini`

```ini
[labs]
imap_folder_list_limit = 200 // 0 is off
```

**Comment by richard-scott** [comment]
fab

**Comment by zeigerpuppy** [comment]
beware that long folder lists really slow down any folder operations, see  #1125
