### ISSUE TITLE
Custom Data Path

### ISSUE THREAD

**Issue by ghost** [RainLoop/rainloop-webmail#983]
Hi. Can I ask, what is the correct way to use a custom data path?

I'm trying to install RainLoop on the OpenShift Online platform, which needs a specific directory for persistent data. This can be referred to by the $OPENSHIFT_DATA_DIR environment variable.

I don't really know PHP but I've created an include.php file in the root directory that contains the following:

```
<?php
	define('DATA_DIR',getenv('OPENSHIFT_DATA_DIR'));
	$sCustomDataPath = DATA_DIR;
```

However the data directory is still being created in the default location.

Is this simply bad coding on my part or am I going about this the wrong way? Many thanks.

**Comment by RainLoop** [comment]
Try to check https://github.com/RainLoop/rainloop-webmail/blob/master/_include.php file.

**Comment by CarrotCruncher** [comment]
Dear RainLoop Team,

The email sent to mail@carrotcruncher.tk with subject
"Re: [RainLoop/rainloop-webmail] Custom Data Path (#983)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to mail@carrotcruncher.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by CarrotCruncher** [comment]
Working perfectly. Many thanks.

On a similar subject. I'm trying to use environment variables in the application.ini file. Eg.:

```
[contacts]
; Enable contacts
enable = On
allow_sharing = On
allow_sync = On
sync_interval = 20
type = "mysql"
pdo_dsn = "mysql:host=$OPENSHIFT_MYSQL_DB_HOST;port=$OPENSHIFT_MYSQL_DB_PORT;dbname=$OPENSHIFT_APP_NAME"
pdo_user = "$OPENSHIFT_MYSQL_DB_USERNAME"
pdo_password = "$OPENSHIFT_MYSQL_DB_PASSWORD"
suggestions_limit = 30
```

What I've coded doesn't work so it's obviously incorrect. Is there a way I can reference the environment variables in the config file? Thanks again.

**Comment by RainLoop** [comment]
Available in the last version.
