### ISSUE TITLE
Rainloop can't send with photo 1MB

### ISSUE THREAD

**Issue by Guideman** [RainLoop/rainloop-webmail#992]
I put a photo of 1mb in the email and I can't send. I have made all the variable for uploads as big as possable. It is driving me nuts! I don't want to go back to gmail I want to use rainloop I don't know what to do.

**Comment by extremeshok** [comment]
Check your php post limits and smtp limits

We routinely send emails via rainloop of larger than 100mb

**Comment by Guideman** [comment]
THanks for that. Are these in the rainloop configuration or cpanel? Many thanks.

**Comment by Guideman** [comment]
I can't find a php.ini. But I have a user.ini and these are it's settings:
upload_max_filesize=513M
post_max_size=513M
memory_limit=512M
mbstring.func_overload=0
always_populate_raw_post_data=-1
default_charset='UTF-8'
output_buffering=0

**Comment by Guideman** [comment]
In the Rain loop admin panel I have set attatchment size to 100MB and it says this below it:

PHP: upload_max_filesize = 128M; post_max_size = 128M

**Comment by Guideman** [comment]
Tried to send an email with photos total size 1.8MB I get this:
It tries to send and after a few seconds it says cant send. 
![screen shot 2016-04-14 at 10 20 00 am](https://cloud.githubusercontent.com/assets/16567912/14513383/9a510d3e-022a-11e6-99c5-844a24a506a6.png)

**Comment by Guideman** [comment]
My latest update is that it can send files over 1MB if they are attatched. But when I put photos in the body of the email that are over 1MB it can't save and it wont send.

**Comment by Guideman** [comment]
Can anyone help?

**Comment by hlx98007** [comment]
Same here. Any attachments larger than 1M will fail. The attachment will be red.

**Comment by hlx98007** [comment]
Same here. Any attachments larger than 1M will fail. The attachment will be red.

**Comment by RainLoop** [comment]
In 99% of cases  it's a web server configuration issue.

- PHP:
post_max_size, upload_max_filesize 

- Nginx
client_max_body_size;

Each web server has its own configurations.

**Comment by hlx98007** [comment]
You were right, client_max_body_size was not set, and nginx is default to 1M.
