### ISSUE TITLE
User filters

### ISSUE THREAD

**Issue by fjllacer** [RainLoop/rainloop-webmail#994]
In the demo rainloop website I can see user filters are available.
I have rainloop 1.9.1.330 community version installed on my system and user filters are not available.

What must I do to have user filters ?
Upgrade to latest version ? community or standard version ?

Regards

**Comment by fjllacer** [comment]
No one has an answer for such a simple question ?

**Comment by ervee** [comment]
Did you enable and configure the "Sieve configuration" (in admin panel > Domains > Edit your Domain).

**Comment by fjllacer** [comment]
No. I haven´t configured SIEVE in my domain.
Is that the only way to for users to be able to create custom filters ?

**Comment by ervee** [comment]
Yes

**Comment by pascalBokBok** [comment]
Somebody please tell me if I misunderstood this. 
Filters running in the Rainloop software are disabled if I don't also have filters running on the server?

**Comment by ervee** [comment]
RainLoop doesn't actually have filters. You can use RainLoop to manage SIEVE filtering on the mailserver of you have that correctly configured.

**Comment by cypriotxx** [comment]
what is the correct approach to create a filter for a word in the body of the email if exist delete the email auto ? thnx

**Comment by kmmrtnz** [comment]
What is the main reason of email sending repeatedly in rainloop?
