### ISSUE TITLE
Cannot send emails to Bcc Users without To 

### ISSUE THREAD

**Issue by heyou93** [RainLoop/rainloop-webmail#995]
Hi,

We have an issue with rainloop email client that we're using, we would like to send emails to all BCC users only and we want to leave the To Field emails blank. As of now we cannot do it because every time we send it to all BCC users without the To, it says that "Please specify atleast one recipient"

![image](https://cloud.githubusercontent.com/assets/8090574/14481525/4f6cb940-0166-11e6-989b-c75ca92662c4.png)

Hope you can make it send to all bcc users even though the To field is blank thanks

Version: 1.9.4.398

![image](https://cloud.githubusercontent.com/assets/8090574/14481583/f9be0fc0-0166-11e6-9039-9fc4bc82f4b5.png)

**Comment by RainLoop** [comment]
Fixed
